### ISSUE TITLE
[terminal] verbose error logging after reload

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1077]
When I reload the browser with an open terminal session I see the output below on every keystroke:

```
Error: not opened

    at WebSocket.send (/Users/efftinge/Documents/theia-dev/theia/node_modules/ws/lib/WebSocket.js:360:18)
    at MultiRingBufferReadableStream.<anonymous> (/Users/efftinge/Documents/theia-dev/theia/packages/terminal/lib/node/terminal-backend-contribution.js:50:24)
    at emitOne (events.js:115:13)
    at MultiRingBufferReadableStream.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)
    at readableAddChunk (_stream_readable.js:253:11)
    at MultiRingBufferReadableStream.Readable.push (_stream_readable.js:211:10)
    at MultiRingBufferReadableStream.deq (/Users/efftinge/Documents/theia-dev/theia/packages/process/lib/node/multi-ring-buffer.js:92:34)
    at MultiRingBufferReadableStream.onData (/Users/efftinge/Documents/theia-dev/theia/packages/process/lib/node/multi-ring-buffer.js:84:18)
    at MultiRingBuffer.onData (/Users/efftinge/Documents/theia-dev/theia/packages/process/lib/node/multi-ring-buffer.js:190:25)
```

**Comment by hexa00** [comment]
Your websocket connection is failing ? 
Do you get this consistently?

**Comment by svenefftinge** [comment]
Yes, I get this when I
1) open a workspace without terminals
2) start one
3) reload the browser
4) type in the reopened terminal

It works, but it seems like it is still also trying to interact with the old closed Websocket.

**Comment by hexa00** [comment]
OK humm I'll check it out

**Comment by hexa00** [comment]
I tried this multiple times on master but I can't reproduce...

Also the code clearly closes the reader on the websocket being closed...

Could you retry?... not sure what to do...

**Comment by hexa00** [comment]
Actually I think I have an idea output could leak after being disposed...
I'll do a PR that you can test.

**Comment by hexa00** [comment]
@svenefftinge could you please test with #1088

It should take care of it, the only thing i'm not sure of is if the set to undefined is necessary.. if you could test with/without that it would be nice.
