### ISSUE TITLE
[git] Stash changes before switching branch not available within Theia

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1143]
Client side:
When trying to switch git branch, a popup dialog says to "Commit" or "stash" my changes. I don't want to commit this changes, so I look for the stash command and this is not available within Theia.

NODE side:
The command `git checkout 75129/20/jacques --` exited with an unexpected code: 1. The caller should either handle this error, or expect that exit code.
error: Your local changes to the following files would be overwritten by checkout:
	org.eclipse.egerrit.feature/feature.xml
Please commit your changes or stash them before you switch branches.
Aborting

Error reported :+1:  Exception has occurred: Error
Error: error: Your local changes to the following files would be overwritten by checkout:
	org.eclipse.egerrit.feature/feature.xml
Please commit your changes or stash them before you switch branches.
Aborting

    at new GitError (/home/lmcbout/theia/theia/node_modules/dugite-extra/src/core/git.ts:67:9)
    at Object.<anonymous> (/home/lmcbout/theia/theia/node_modules/dugite-extra/src/core/git.ts:142:11)
    at step (/home/lmcbout/theia/theia/node_modules/dugite-extra/lib/core/git.js:50:23)
    at Object.next (/home/lmcbout/theia/theia/node_modules/dugite-extra/lib/core/git.js:31:53)
    at fulfilled (/home/lmcbout/theia/theia/node_modules/dugite-extra/lib/core/git.js:22:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by kittaakos** [comment]
> command and this is not available within Theia.

#4397.
