### ISSUE TITLE
Errors in the backend console when no preference files found

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#1194]
i.e
```
Request resolveContent failed with error: Cannot find file under the given URI. URI: file:///home/epatpol/Projects/Github/eclipse-two/.theia/settings.json. Error: Cannot find file under the given URI. URI: file:///home/epatpol/test/workspace/.theia/settings.json.
    at FileSystemNode.<anonymous> (/home/epatpol/Projects/Github/theia/packages/filesystem/lib/node/node-filesystem.js:140:35)
    at step (/home/epatpol/Projects/Github/theia/packages/filesystem/lib/node/node-filesystem.js:50:23)
    at Object.next (/home/epatpol/Projects/Github/theia/packages/filesystem/lib/node/node-filesystem.js:31:53)
    at fulfilled (/home/epatpol/Projects/Github/theia/packages/filesystem/lib/node/node-filesystem.js:22:58)
    at <anonymous>
```

I believe the same thing happens if you don't have a preference file under $HOME/.theia

**Comment by akosyakov** [comment]
It will be fixed by https://github.com/theia-ide/theia/pull/1188
