### ISSUE TITLE
Exceptions when no settings.json exist

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#1211]
```
Request getFileStat failed with error: Cannot find file under the given URI. URI: file:///home/epatpol/.theia/settings.json. Error: Cannot find file under the given URI. URI: file:///home/epatpol/.theia/settings.json.
    at FileSystemNode.<anonymous> (/home/epatpol/Projects/Github/theia/packages/filesystem/lib/node/node-filesystem.js:115:35)
    at step (/home/epatpol/Projects/Github/theia/packages/filesystem/lib/node/node-filesystem.js:50:23)
    at Object.next (/home/epatpol/Projects/Github/theia/packages/filesystem/lib/node/node-filesystem.js:31:53)
    at fulfilled (/home/epatpol/Projects/Github/theia/packages/filesystem/lib/node/node-filesystem.js:22:58)
    at <anonymous>

Request resolveContent failed with error: Cannot find file under the given URI. URI: file:///home/epatpol/.theia/settings.json. Error: Cannot find file under the given URI. URI: file:///home/epatpol/.theia/settings.json.
 at FileSystemNode.<anonymous> (/home/epatpol/Projects/Github/theia/packages/filesystem/lib/node/node-filesystem.js:140:35)
    at step (/home/epatpol/Projects/Github/theia/packages/filesystem/lib/node/node-filesystem.js:50:23)
    at Object.next (/home/epatpol/Projects/Github/theia/packages/filesystem/lib/node/node-filesystem.js:31:53)
    at fulfilled (/home/epatpol/Projects/Github/theia/packages/filesystem/lib/node/node-filesystem.js:22:58)
    at <anonymous>

```

**Comment by epatpol** [comment]
Duplicate of #1194
