### ISSUE TITLE
Docker image complains about fs.pathExists

### ISSUE THREAD

**Issue by rcjsuen** [theia-ide/theia#1248]
```
    TypeError: fs.pathExists is not a function
        at DefaultWorkspaceServer.<anonymous> (/home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:150:49)
        at step (/home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:50:23)
        at Object.next (/home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:31:53)
        at /home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:25:71
        at new Promise (<anonymous>)
        at __awaiter (/home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:21:12)
        at DefaultWorkspaceServer.writeToUserHome (/home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:144:16)
        at DefaultWorkspaceServer.setRoot (/home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:121:14)
        at /home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:167:59
        at new Promise (<anonymous>) []
```
I used [PWD](https://labs.play-with-docker.com/) to try Theia out with the `typefox/theia` image. When I opened Theia, it told me that no workspace folder was selected so I asked it to open up `/root/`. After the progress spinner did its thing, I realized that I had an error in my PWD console.
```
$ docker pull typefox/theia:next

next: Pulling from typefox/theia
85b1f47fba49: Pull complete
ba6bd283713a: Pull complete
817c8cd48a09: Pull complete
47cc0ed96dc3: Pull complete
8888adcbd08b: Pull complete
6f2de60646b9: Pull complete
51fa8867e10f: Pull complete
3de546fb9d8f: Pull complete
f83e7cf6dc0b: Pull complete
0763fde0994d: Pull complete
dd82ccd078db: Pull complete
f17536cf5599: Pull complete
Digest: sha256:a2c09af4cb7c791717650e3ff82f777631e9366377f1c929ef160f5738b1e493
Status: Downloaded newer image for typefox/theia:next
```
```
$ docker run -it -p 3000:3000 -v "/root/" typefox/theia:next

Starting server worker...

Server worker has been started. [ID: 1 | PID: 35]

Server worker is ready to accept messages. [ID: 1 | PID: 35]

[2018-02-11T08:33:11.254Z]  INFO: Theia/35 on d1f98c0d2903: Theia app listening on http://0.0.0.0:3000. []

[2018-02-11T08:33:32.209Z] ERROR: Theia/35 on d1f98c0d2903: Uncaught Exception:  [ 'TypeError: fs.pathExists is not a function' ]

[2018-02-11T08:33:32.210Z] ERROR: Theia/35 on d1f98c0d2903:
    TypeError: fs.pathExists is not a function
        at DefaultWorkspaceServer.<anonymous> (/home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:150:49)
        at step (/home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:50:23)
        at Object.next (/home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:31:53)
        at /home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:25:71
        at new Promise (<anonymous>)
        at __awaiter (/home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:21:12)
        at DefaultWorkspaceServer.writeToUserHome (/home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:144:16)
        at DefaultWorkspaceServer.setRoot (/home/theia/node_modules/@theia/workspace/lib/node/default-workspace-server.js:121:14)
        at /home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:167:59
        at new Promise (<anonymous>) []


[2018-02-11T08:33:41.246Z]  INFO: Theia/35 on d1f98c0d2903:
    [nsfw-watcher: 63] Started watching: /root
     []
```

**Comment by akosyakov** [comment]
`typefox/theia` - is outdated and not maintained image, you should use images from theiaide: https://hub.docker.com/u/theiaide/

**Comment by akosyakov** [comment]
Please open if you have the same issue with latest images.

**Comment by rcjsuen** [comment]
Now the image won't even give me a 3000 link in PWD to click on.
```
$ docker run -it -p 3000:3000 -v "/root/" theiaide/theia
yarn run v1.3.2
$ /home/theia/node_modules/.bin/theia start /home/project --hostname=0.0.0.0
Starting server worker...

Server worker has been started. [ID: 1 | PID: 45]

[2018-02-12T00:12:23.184Z] ERROR: Theia/45 on e7a4665466f9: ReferenceError: window is not defined []

Server worker is ready to accept messages. [ID: 1 | PID: 45]

[2018-02-12T00:12:23.207Z]  INFO: Theia/45 on e7a4665466f9: Theia app listening on http://0.0.0.0:3000. []
```
