### ISSUE TITLE
npm watch breaks webpack ?

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#125]
With the following steps:

git clone https://github.com/theia-ide/theia \\
  && cd theia \\
  && npm install \\
  && npm run build \\
  && cd examples/browser \\
  && npm install \\
  && npm run build  

Then 
  cd examples/browser
  npm start

Then:
   cd theia 
   npm run watch

I get:
```
webpack-server] webpack: Compiling...
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/types.js.map'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/types.js'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/types.d.ts'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/event.js.map'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/event.js'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/event.d.ts'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/disposable.js.map'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/disposable.js'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/disposable.d.ts'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/contribution-provider.js.map'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/contribution-provider.js'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/contribution-provider.d.ts'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/command.js.map'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/command.js'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/command.d.ts'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/menu.js.map'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/menu.js'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/application/common/menu.d.ts'.
...
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/terminal/browser/terminal-frontend-module.js.map'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/terminal/browser/terminal-frontend-module.js'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/terminal/browser/terminal-frontend-module.d.ts'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/terminal/node/terminal-backend-module.js.map'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/terminal/node/terminal-backend-module.js'.
[watch-deps] Updated file under '/home/eantotr/work/theia/examples/browser/node_modules/theia/lib/terminal/node/terminal-backend-module.d.ts'.
[webpack-server] undefined:1
[webpack-server] 
[webpack-server] 
[webpack-server] 
[webpack-server] SyntaxError: Unexpected end of JSON input
[webpack-server]     at JSON.parse (<anonymous>)
[webpack-server]     at /home/eantotr/work/theia/examples/browser/node_modules/source-map-loader/index.js:44:22
[webpack-server]     at tryToString (fs.js:449:3)
[webpack-server]     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
[backend] [ Error: Reader recevied error. Reason: Error during socket reconnect: code = 1006, reason = 
[backend]       at WebSocketMessageReader.AbstractMessageReader.asError (/home/eantotr/work/theia/examples/browser/node_modules/vscode-jsonrpc/lib/messageReader.js:133:20)
[backend]       at WebSocketMessageReader.AbstractMessageReader.fireError (/home/eantotr/work/theia/examples/browser/node_modules/vscode-jsonrpc/lib/messageReader.js:106:37)
[backend]       at WebSocketMessageReader.fireError (/home/eantotr/work/theia/examples/browser/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:70:40)
[backend]       at WebSocket.<anonymous> (/home/eantotr/work/theia/examples/browser/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:33:23)
[backend]       at emitTwo (events.js:111:20)
[backend]       at WebSocket.emit (events.js:194:7)
[backend]       at WebSocket.emitClose (/home/eantotr/work/theia/examples/browser/node_modules/ws/lib/WebSocket.js:227:10)
[backend]       at _receiver.cleanup (/home/eantotr/work/theia/examples/browser/node_modules/ws/lib/WebSocket.js:213:41)
[backend]       at Receiver.cleanup (/home/eantotr/work/theia/examples/browser/node_modules/ws/lib/Receiver.js:522:15)
[backend]       at WebSocket.finalize (/home/eantotr/work/theia/examples/browser/node_modules/ws/lib/WebSocket.js:213:22),
[backend]   undefined,
[backend]   undefined ]
[backend] [ Error: Reader recevied error. Reason: Error during socket reconnect: code = 1006, reason = 
[backend]       at WebSocketMessageReader.AbstractMessageReader.asError (/home/eantotr/work/theia/examples/browser/node_modules/vscode-jsonrpc/lib/messageReader.js:133:20)
[backend]       at WebSocketMessageReader.AbstractMessageReader.fireError (/home/eantotr/work/theia/examples/browser/node_modules/vscode-jsonrpc/lib/messageReader.js:106:37)
[backend]       at WebSocketMessageReader.fireError (/home/eantotr/work/theia/examples/browser/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:70:40)
[backend]       at WebSocket.<anonymous> (/home/eantotr/work/theia/examples/browser/node_modules/vscode-ws-jsonrpc/lib/socket/reader.js:33:23)
[backend]       at emitTwo (events.js:111:20)
[backend]       at WebSocket.emit (events.js:194:7)
[backend]       at WebSocket.emitClose (/home/eantotr/work/theia/examples/browser/node_modules/ws/lib/WebSocket.js:227:10)
[backend]       at _receiver.cleanup (/home/eantotr/work/theia/examples/browser/node_modules/ws/lib/WebSocket.js:213:41)
[backend]       at Receiver.cleanup (/home/eantotr/work/theia/examples/browser/node_modules/ws/lib/Receiver.js:522:15)
[backend]       at WebSocket.finalize (/home/eantotr/work/theia/examples/browser/node_modules/ws/lib/WebSocket.js:213:22),
[backend]   undefined,
[backend]   undefined ]
[webpack-server] 
[webpack-server] npm
[webpack-server]  
[webpack-server] ERR!
[webpack-server]  Linux 4.4.0-77-generic
[webpack-server] npm
[webpack-server]  ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "start:frontend"
[webpack-server] npm ERR! node v7.10.0
[webpack-server] npm ERR! npm  v4.2.0
[webpack-server] npm ERR! code ELIFECYCLE
[webpack-server] npm ERR! errno 1
[webpack-server] npm ERR! browser-example@0.0.1-alpha.1 start:frontend: `webpack-dev-server --open`
[webpack-server] npm ERR! Exit status 1
[webpack-server] npm ERR! 
[webpack-server] npm ERR! Failed at the browser-example@0.0.1-alpha.1 start:frontend script 'webpack-dev-server --open'.
[webpack-server] npm ERR! Make sure you have the latest version of node.js and npm installed.
[webpack-server] npm ERR! If you do, this is most likely a problem with the browser-example package,
[webpack-server] npm ERR! not with npm itself.
[webpack-server] npm ERR! Tell the author that this fails on your system:
[webpack-server] npm ERR!     webpack-dev-server --open
[webpack-server] npm ERR! You can get information on how to open an issue for this project with:
[webpack-server] npm ERR!     npm bugs browser-example
[webpack-server] npm ERR! Or if that isn't available, you can get their info via:
[webpack-server] npm ERR!     npm owner ls browser-example
[webpack-server] npm ERR! There is likely additional logging output above.
[webpack-server] 
[webpack-server] npm
[webpack-server]  
[webpack-server] ERR!
[webpack-server]  Please include the following file with any support request:
[webpack-server] npm ERR!     /home/eantotr/.npm/_logs/2017-05-16T12_53_07_845Z-debug.log
[webpack-server] npm run start:frontend exited with code 1
```

**Comment by kittaakos** [comment]
Could you reproduce it if you start the `npm run watch` first, then you strat the example?

**Comment by hexa00** [comment]
No if I do npm watch before it work...

Note that I tested more and:

npm watch before npm start : Works
npm watch after  npm start but no code changes: Works but copies a lot of files
kill npm watch, modify a file , run npm watch then run npm start -> Problem appears

**Comment by kittaakos** [comment]
> npm watch before npm start : Works

So I could add this to the documentation, and mention, that this is the proper way to watch and update changes from the core Theia code in a downstream project. This watcher makes sense only with the file-based npm dependencies anyway.

What do you think @svenefftinge, @akosyakov, @hexa00

**Comment by hexa00** [comment]
Unfortuantely we can't rely on doing npm watch before since part of the workflow is to stop npm start to to able to reload changes to the backend for example.

So if I C-c npm start and do it again I get back into the situation where I have a watch after a start.

I think we should investigate the source of the issue.

**Comment by simark** [comment]
I also get this error.  Here's what i found.  If I start these two at the same time:

- `tsc --watch` on `theia-core`
- `node ../../config/file-dependency-updater/index.js` on `browser-example`

The first command regenerates all the output files at startup, so the second command outputs a long list of:

```
...
Updated file under '/home/simark/src/theia/examples/browser/node_modules/theia-core/lib/terminal/browser/terminal-frontend-module.js.map'.
Updated file under '/home/simark/src/theia/examples/browser/node_modules/theia-core/lib/terminal/browser/terminal-frontend-module.js'.
Updated file under '/home/simark/src/theia/examples/browser/node_modules/theia-core/lib/terminal/browser/terminal-frontend-module.d.ts'.
...
```

Once it has stabilized I just run "webpack" in the browser example directory to try to build bundle.js, and I get the error mentioned by @hexa00.  I added some logging to `source-map-loader/index.js`, and indeed found that `./theia/examples/browser/node_modules/theia-core/lib/application/common/keys.js.map` is empty.  It's not always this particular file, it varies between runs.

So I think there is some race condition between the `tsc --watch` on `theia:core` and the file dependency updater script.  `tsc -watch` probably creates some empty files first and then writes to them.  If the file dependency updater script happens to copy the file after the file creation but before it was written, then it will copy an empty file.

I added a console.log in the file dependency updater to know what events we receive.  For a problematic file, I got:

    Event change for application/common/uri.js.map size 0

So at the time we receive the event, the file is empty.  If I look at uri.js.map in `theia-core`, it does have content, meaning it has been written after we received the event and after we copied it.  What I find strange, is that we don't receive another event later for when the file is written.

**Comment by simark** [comment]
It seems to be related to this:

https://github.com/paulmillr/chokidar/issues/365

Perhaps using the `awaitWriteFinish` option would help, like it did for babel.  I still find it strange that we do not get a new change event when the file gets written to.  We would just trigger a copy again, it would be much cleaner.

**Comment by simark** [comment]
For a particular file, tsc does this;

```
13373 open("/home/simark/src/theia/lib/application/common/keys.js.map", O_WRONLY|O_CREAT|O_TRUNC|O_CLOEXEC, 0666) = 9
13374 write(9, "{\"version\":3,\"file\":\"keys.js\",\"s"..., 10304) = 10304
13375 close(9)                                = 0
```

So it opens the file in writing mode with the O_TRUNC flag, which truncates the file.  It then writes the content in id.  It couldn't be simpler.  Using inotifywait to understand to see what events are generated at the inotify level, we get this:

```
$ inotifywait -m /home/simark/src/theia/lib/application/common/keys.js.map
Setting up watches.
Watches established.
/home/simark/src/theia/lib/application/common/keys.js.map MODIFY 
/home/simark/src/theia/lib/application/common/keys.js.map OPEN 
/home/simark/src/theia/lib/application/common/keys.js.map MODIFY 
/home/simark/src/theia/lib/application/common/keys.js.map CLOSE_WRITE,CLOSE 
```

So we do get two MODIFY events there, which makes sense: one for the truncate and one for the write. Why don't we get two events at the chokidar level?

**Comment by simark** [comment]
@hexa00 and @kittaakos, can you take a look and try #138 ?

**Comment by simark** [comment]
I think we only see one event coming out of chokidar because it's throttling the change events:

https://github.com/paulmillr/chokidar/blob/c716ffd3d01ceab2622c5d916e227afca3231d5a/index.js#L221

I didn't find anything related to this in the doc.  I also found that we could use the `raw` event to get all the events from inotify/fsevents.  But awaitWriteFinish seems good enough.  I'll reduce the delay to maybe 100ms though.  If I understand correctly the link above, chokidar will throttle the change events to one per 50ms.  So we should be safe with an awaitWriteFinish delay of 100ms: if for some reason there is more than 100ms between the open and the write, we'll get two distinct events, because they'll be more than 50ms apart.

**Comment by hexa00** [comment]
#138 Works like a charm!! Thanks!!

**Comment by hexa00** [comment]
Note for reference about hot-reloading

It works for the frontend code but not the backend which kinda makes sense anyway but we should document a workflow for backend and frontend in the doc
