### ISSUE TITLE
[git history] multiple repos: exception in backend : <x> is outside repository

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#1364]
(I am not sure if the "Git History" command is meant to be shown in the command palette: it doesn't seem to be there always. e.g. to get to the state below, I first had to open the view though the menu item, close it, and then I could see the command in the palette)

note: This only happens in workspaces with multiple git repositories. 

It works fine when I trigger the git history command using the menu "View -> Git History" but not when I do it through the command palette - the widget remains empty and there is this backend exception:
```
[2018-02-23T14:09:25.546Z] ERROR: Theia/12447 on elxa610sxy1:
    GitError: fatal: ..: '..' is outside repository
    
        at new GitError (/opt/ericsson-dev/theia/node_modules/dugite-extra/lib/core/git.js:79:28)
        at Object.<anonymous> (/opt/ericsson-dev/theia/node_modules/dugite-extra/lib/core/git.js:155:27)
        at step (/opt/ericsson-dev/theia/node_modules/dugite-extra/lib/core/git.js:50:23)
        at Object.next (/opt/ericsson-dev/theia/node_modules/dugite-extra/lib/core/git.js:31:53)
        at fulfilled (/opt/ericsson-dev/theia/node_modules/dugite-extra/lib/core/git.js:22:58)
        at <anonymous> []
```

There is a similar exception if I trigger the git history command using the context menu, on a file that is not in the currently selected git repo: 

```
[2018-02-23T14:25:44.565Z] ERROR: Theia/12447 on elxa610sxy1:
    GitError: fatal: ../binutils-gdb/.gitignore: '../binutils-gdb/.gitignore' is outside repository
    
        at new GitError (/opt/ericsson-dev/theia/node_modules/dugite-extra/lib/core/git.js:79:28)
        at Object.<anonymous> (/opt/ericsson-dev/theia/node_modules/dugite-extra/lib/core/git.js:155:27)
        at step (/opt/ericsson-dev/theia/node_modules/dugite-extra/lib/core/git.js:50:23)
        at Object.next (/opt/ericsson-dev/theia/node_modules/dugite-extra/lib/core/git.js:31:53)
        at fulfilled (/opt/ericsson-dev/theia/node_modules/dugite-extra/lib/core/git.js:22:58)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:169:7) []
```

**Comment by kittaakos** [comment]
> file that is not in the currently selected git repo:

Or not yet under version control.

**Comment by jbicker** [comment]
The problem is, that the git-history and the git-diff currently work with the selected repository. Which causes also other problems. See https://github.com/theia-ide/theia/issues/1404.
