### ISSUE TITLE
Uninstalling @theia/output with the extension-manager runs a `yarn install` loop in the backend

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#1379]
When trying to implement #1356, I happened to test the extension-manager to make sure I didn't break anything. When I tried to install `@theia/output`, it failed and tried to revert but it seems to be stuck in a loop of some sort. Going back to master I still see the same problem. The frontend then gets spammed with failure messages like so:

![screenshot from 2018-02-26 11-14-12](https://user-images.githubusercontent.com/2881761/36681431-a12ff4b8-1ae6-11e8-885a-460ccb87282e.png)

Note that closing the frontend client doesn't make the backend stop trying to reinstall (which makes sense as it's trying to get to a stable state). Here's what the logs look like:

```
[2018-02-26T16:18:36.116Z]  INFO: Theia/22917 on elxag2w8q32:
    [1/5] Validating package.json...
     []

[2018-02-26T16:18:36.118Z]  INFO: Theia/22917 on elxag2w8q32:
    [2/5] Resolving packages...
     []

[2018-02-26T16:18:36.706Z]  INFO: Theia/22917 on elxag2w8q32:
    success Already up-to-date.
     []

[2018-02-26T16:18:36.707Z]  INFO: Theia/22917 on elxag2w8q32:
    $ yarn run clean && yarn build
     []

[2018-02-26T16:18:37.062Z]  INFO: Theia/22917 on elxag2w8q32:
    $ theia clean && rimraf errorShots
     []

[2018-02-26T16:18:37.294Z] ERROR: Theia/22917 on elxag2w8q32:
    /bin/sh: 1: rimraf: not found
     []

[2018-02-26T16:18:37.295Z] ERROR: Theia/22917 on elxag2w8q32:
    error Command failed with exit code 127.
     []

[2018-02-26T16:18:37.295Z]  INFO: Theia/22917 on elxag2w8q32:
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     []

[2018-02-26T16:18:37.301Z] ERROR: Theia/22917 on elxag2w8q32:
    error Command failed with exit code 1.
     []

[2018-02-26T16:18:37.301Z]  INFO: Theia/22917 on elxag2w8q32:
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
     []

[2018-02-26T16:18:37.311Z] ERROR: Theia/22917 on elxag2w8q32:
    The app installation is failed
     [ Error: Failed install , code: 1, signal: null
          at ChildProcess.<anonymous> (/home/epatpol/Projects/Github/theia/packages/extension-manager/lib/node/npm-client.js:76:28)
          at emitTwo (events.js:125:13)
          at ChildProcess.emit (events.js:213:7)
          at maybeClose (internal/child_process.js:897:16)
          at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5) ]

[2018-02-26T16:18:37.311Z]  INFO: Theia/22917 on elxag2w8q32: Reverting the app installation ... []

[2018-02-26T16:18:37.638Z]  INFO: Theia/22917 on elxag2w8q32: Intalling the app... []
[2018-02-26T16:18:37.638Z]  INFO: Theia/22917 on elxag2w8q32: Installing extensions... []
[2018-02-26T16:18:37.638Z]  INFO: Theia/22917 on elxag2w8q32: /home/epatpol/Projects/Github/theia/examples/browser [ 'yarn', 'install' ]

[2018-02-26T16:18:38.113Z]  INFO: Theia/22917 on elxag2w8q32:
    [1/5] Validating package.json...
     []

[2018-02-26T16:18:38.115Z]  INFO: Theia/22917 on elxag2w8q32:
    [2/5] Resolving packages...
     []

[2018-02-26T16:18:38.691Z]  INFO: Theia/22917 on elxag2w8q32:
    success Already up-to-date.
     []

[2018-02-26T16:18:38.694Z]  INFO: Theia/22917 on elxag2w8q32:
    $ yarn run clean && yarn build
     []

[2018-02-26T16:18:39.048Z]  INFO: Theia/22917 on elxag2w8q32:
    $ theia clean && rimraf errorShots
     []

[2018-02-26T16:18:39.282Z] ERROR: Theia/22917 on elxag2w8q32:
    /bin/sh: 1: rimraf: not found
     []

[2018-02-26T16:18:39.284Z] ERROR: Theia/22917 on elxag2w8q32:
    error Command failed with exit code 127.
     []

[2018-02-26T16:18:39.284Z]  INFO: Theia/22917 on elxag2w8q32:
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     []

[2018-02-26T16:18:39.290Z] ERROR: Theia/22917 on elxag2w8q32:
    error Command failed with exit code 1.
     []

[2018-02-26T16:18:39.291Z]  INFO: Theia/22917 on elxag2w8q32:
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
     []

[2018-02-26T16:18:39.300Z] ERROR: Theia/22917 on elxag2w8q32:
    The app installation is failed
     [ Error: Failed install , code: 1, signal: null
          at ChildProcess.<anonymous> (/home/epatpol/Projects/Github/theia/packages/extension-manager/lib/node/npm-client.js:76:28)
          at emitTwo (events.js:125:13)
          at ChildProcess.emit (events.js:213:7)
          at maybeClose (internal/child_process.js:897:16)
          at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5) ]
[2018-02-26T16:18:39.300Z]  INFO: Theia/22917 on elxag2w8q32: Reverting the app installation ... []

[2018-02-26T16:18:39.640Z]  INFO: Theia/22917 on elxag2w8q32: Intalling the app... []

[2018-02-26T16:18:39.641Z]  INFO: Theia/22917 on elxag2w8q32: Installing extensions... []

[2018-02-26T16:18:39.641Z]  INFO: Theia/22917 on elxag2w8q32: /home/epatpol/Projects/Github/theia/examples/browser [ 'yarn', 'install' ]

[2018-02-26T16:18:40.116Z]  INFO: Theia/22917 on elxag2w8q32:
    [1/5] Validating package.json...
     []

[2018-02-26T16:18:40.118Z]  INFO: Theia/22917 on elxag2w8q32:
    [2/5] Resolving packages...
     []

[2018-02-26T16:18:40.678Z]  INFO: Theia/22917 on elxag2w8q32:
    success Already up-to-date.
     []

[2018-02-26T16:18:40.681Z]  INFO: Theia/22917 on elxag2w8q32:
    $ yarn run clean && yarn build
     []

[2018-02-26T16:18:41.057Z]  INFO: Theia/22917 on elxag2w8q32:
    $ theia clean && rimraf errorShots
     []

[2018-02-26T16:18:41.337Z] ERROR: Theia/22917 on elxag2w8q32:
    /bin/sh: 1: rimraf: not found
     []

[2018-02-26T16:18:41.339Z] ERROR: Theia/22917 on elxag2w8q32:
    error Command failed with exit code 127.
     []

[2018-02-26T16:18:41.339Z]  INFO: Theia/22917 on elxag2w8q32:
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
     []

[2018-02-26T16:18:41.348Z] ERROR: Theia/22917 on elxag2w8q32:
    error Command failed with exit code 1.
     []

```

There seems to be an issue with `rimraf` ?

**Comment by epatpol** [comment]
Note that I'm specifically launching theia backhand from `examples/browser` with `yarn run start` and not from vscode with cluster disabled.

**Comment by vince-fugnitto** [comment]
closing since the `@theia/extension-manager` is deprecated
