### ISSUE TITLE
[windows] Workspace search is broken

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1584]
<kbd>Ctrl</kbd>+<kbd>P</kbd> does not return anything in Theia.

```
[2018-03-27T06:52:27.814Z] ERROR: Theia/4568 on DESKTOP-VJRAMKC: Request find failed with error: spawn C:\Users\kittaako
s\dev\theia\node_modules\vscode-ripgrep\bin\rg ENOENT [ 'Error: spawn C:\\Users\\kittaakos\\dev\\theia\\node_modules\\vs
code-ripgrep\\bin\\rg ENOENT\n    at exports._errnoException (util.js:1024:11)\n    at Process.ChildProcess._handle.onex
it (internal/child_process.js:192:19)\n    at onErrorNT (internal/child_process.js:374:16)\n    at _combinedTickCallback
 (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)' ]

[2018-03-27T06:52:27.914Z] ERROR: Theia/4568 on DESKTOP-VJRAMKC: Error: spawn C:\Users\kittaakos\dev\theia\node_modules\
vscode-ripgrep\bin\rg ENOENT [] (module=process)

[2018-03-27T06:52:27.914Z] ERROR: Theia/4568 on DESKTOP-VJRAMKC: Request find failed with error: spawn C:\Users\kittaako
s\dev\theia\node_modules\vscode-ripgrep\bin\rg ENOENT [ 'Error: spawn C:\\Users\\kittaakos\\dev\\theia\\node_modules\\vs
code-ripgrep\\bin\\rg ENOENT\n    at exports._errnoException (util.js:1024:11)\n    at Process.ChildProcess._handle.onex
it (internal/child_process.js:192:19)\n    at onErrorNT (internal/child_process.js:374:16)\n    at _combinedTickCallback
 (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)' ]

[2018-03-27T06:52:29.644Z] ERROR: Theia/4568 on DESKTOP-VJRAMKC: Error: spawn C:\Users\kittaakos\dev\theia\node_modules\
vscode-ripgrep\bin\rg ENOENT [] (module=process)

[2018-03-27T06:52:29.644Z] ERROR: Theia/4568 on DESKTOP-VJRAMKC: Request find failed with error: spawn C:\Users\kittaako
s\dev\theia\node_modules\vscode-ripgrep\bin\rg ENOENT [ 'Error: spawn C:\\Users\\kittaakos\\dev\\theia\\node_modules\\vs
code-ripgrep\\bin\\rg ENOENT\n    at exports._errnoException (util.js:1024:11)\n    at Process.ChildProcess._handle.onex
it (internal/child_process.js:192:19)\n    at onErrorNT (internal/child_process.js:374:16)\n    at _combinedTickCallback
 (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)' ]

[2018-03-27T06:52:29.789Z] ERROR: Theia/4568 on DESKTOP-VJRAMKC: Error: spawn C:\Users\kittaakos\dev\theia\node_modules\
vscode-ripgrep\bin\rg ENOENT [] (module=process)

[2018-03-27T06:52:29.789Z] ERROR: Theia/4568 on DESKTOP-VJRAMKC: Request find failed with error: spawn C:\Users\kittaako
s\dev\theia\node_modules\vscode-ripgrep\bin\rg ENOENT [ 'Error: spawn C:\\Users\\kittaakos\\dev\\theia\\node_modules\\vs
code-ripgrep\\bin\\rg ENOENT\n    at exports._errnoException (util.js:1024:11)\n    at Process.ChildProcess._handle.onex
it (internal/child_process.js:192:19)\n    at onErrorNT (internal/child_process.js:374:16)\n    at _combinedTickCallback
 (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)' ]

[2018-03-27T06:52:29.939Z] ERROR: Theia/4568 on DESKTOP-VJRAMKC: Error: spawn C:\Users\kittaakos\dev\theia\node_modules\
vscode-ripgrep\bin\rg ENOENT [] (module=process)

[2018-03-27T06:52:29.940Z] ERROR: Theia/4568 on DESKTOP-VJRAMKC: Request find failed with error: spawn C:\Users\kittaako
s\dev\theia\node_modules\vscode-ripgrep\bin\rg ENOENT [ 'Error: spawn C:\\Users\\kittaakos\\dev\\theia\\node_modules\\vs
code-ripgrep\\bin\\rg ENOENT\n    at exports._errnoException (util.js:1024:11)\n    at Process.ChildProcess._handle.onex
it (internal/child_process.js:192:19)\n    at onErrorNT (internal/child_process.js:374:16)\n    at _combinedTickCallback
 (internal/process/next_tick.js:138:11)\n    at process._tickCallback (internal/process/next_tick.js:180:9)' ]

```

**Comment by kittaakos** [comment]
It should be `rg.exe` on Windows.

<img width="282" alt="screen shot 2018-03-27 at 09 04 53" src="https://user-images.githubusercontent.com/1405703/37951805-0391f296-319e-11e8-8d64-416f9c8fea92.png">

**Comment by kittaakos** [comment]
I have looked into it, changed the command path to `.exe` on Windows. If I execute the following, the suffixed command path exists.
```
require('fs').existsSync(command)
true
```

But when spawning the process it fails because cannot locate the executable. Could it be related to the `rootPath`?
Currently, the `rootPath` is `"/c:/Users/kittaakos/dev/theia"` on my image and look at this:

```
require('fs').existsSync(opts.rootPath)
false
```

Do you have any hints on the `path`, @akosyakov?

**Comment by kittaakos** [comment]
These are the two places where we have to change the path
 - https://github.com/theia-ide/theia/blob/e41a77e57de7f5948e3c61cfe5f5f724b6e2fac1/packages/search-in-workspace/src/node/ripgrep-search-in-workspace-server.ts#L55
 - https://github.com/theia-ide/theia/blob/e41a77e57de7f5948e3c61cfe5f5f724b6e2fac1/packages/file-search/src/node/file-search-service-impl.ts#L40

And it should be fixed here: https://github.com/theia-ide/theia/blob/e41a77e57de7f5948e3c61cfe5f5f724b6e2fac1/packages/file-search/src/browser/quick-file-open.ts#L57

My problem is rather, is it safe at all to use our path? It cannot be just substituted with the desired FS path on Windows. Please advise.

**Comment by kittaakos** [comment]
I think it would be much better to change the `rootPath` to `rootUri` and pass the URI as a string to the backend and the backend can resolve it with `FsUri.fsPath(rootUri)` just as we do in other places: FS, Git.
