### ISSUE TITLE
file-dependency-updater is not working properly

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#163]
I get errors like:

````
watch-frontend] SyntaxError: Unexpected end of JSON input
[watch-frontend]     at JSON.parse (<anonymous>)
[watch-frontend]     at /home/eantotr/ownCloud/work/theia/examples/browser/node_modules/source-map-loader/index.js:44:22
[watch-frontend]     at tryToString (fs.js:449:3)
[watch-frontend]     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
[watch-frontend] 
ch-backend] node_modules/theia-core/lib/application/browser/application.d.ts(3,33): error TS2306: File '/home/eantotr/ownCloud/work/theia/examples/browser/node_modules/theia-core/lib/application/common/command.d.ts' is not a module.
[watch-backend] node_modules/theia-core/lib/application/browser/application.d.ts(4,36): error TS2306: File '/home/eantotr/ownCloud/work/theia/examples/browser/node_modules/theia-core/lib/application/common/keybinding.d.ts' is not a module.
[watch-backend] node_modules/theia-core/lib/application/browser/menu/menu-plugin.d.ts(3,33): error TS2306: File '/home/eantotr/ownCloud/work/theia/examples/browser/node_modules/theia-core/lib/application/common/command.d.ts' is not a module.
[watch-backend] node_modules/theia-core/lib/application/browser/menu/menu-plugin.d.ts(4,36): error TS2306: File '/home/eantotr/ownCloud/work/theia/examples/browser/node_modules/theia-core/lib/application/common/keybinding.d.ts' is not a module.
````
Looks like it's coping half written files.

Also just running the updater with no changes between runs makes a lot of copy etc...

Things needs to be improved there...

**Comment by akosyakov** [comment]
> Also just running the updater with no changes between runs makes a lot of copy etc...
I've added `cleanSync` on the purpose to be sure that the state at the beginning in sync.

**Comment by hexa00** [comment]
See #156 about this

**Comment by hexa00** [comment]
Closing that, created new issue for the new issues with ldm see #172
