### ISSUE TITLE
[release 0.3.9] issue publishing extension @theia/java

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#1822]
Everything went well until ```@theia/java```. The error messages hint at a network issue, but every other package seemed to publish correctly. I re-tried a few times, with the same result. Finally I removed the java extension and published everything else. 

So ATM we have all extensions published as ```0.3.9```, except ```@theia/java```, that's still at ```0.3.8```. Once we figure-out what's the issue, we can publish a ```0.3.10```, that includes java. 

log: 
``` npm
$ lerna publish --registry=https://registry.npmjs.org/ --skip-git
lerna info version 2.11.0
lerna info current version 0.3.8
lerna info Checking for updated packages...
lerna info Comparing with v0.3.8.
lerna info Checking for prereleased packages...
? Select a new version (currently 0.3.8) Patch (0.3.9)

Changes:
 - @theia/application-manager: 0.3.8 => 0.3.9
 - @theia/application-package: 0.3.8 => 0.3.9
 - @theia/cli: 0.3.8 => 0.3.9
 - @theia/ext-scripts: 0.3.8 => 0.3.9 (private)
 - @theia/callhierarchy: 0.3.8 => 0.3.9
 - @theia/core: 0.3.8 => 0.3.9
 - @theia/cpp: 0.3.8 => 0.3.9
 - @theia/editor: 0.3.8 => 0.3.9
 - @theia/editorconfig: 0.3.8 => 0.3.9
 - @theia/extension-manager: 0.3.8 => 0.3.9
 - @theia/file-search: 0.3.8 => 0.3.9
 - @theia/filesystem: 0.3.8 => 0.3.9
 - @theia/git: 0.3.8 => 0.3.9
 - @theia/java: 0.3.8 => 0.3.9
 - @theia/keymaps: 0.3.8 => 0.3.9
 - @theia/languages: 0.3.8 => 0.3.9
 - @theia/markers: 0.3.8 => 0.3.9
 - @theia/merge-conflicts: 0.3.8 => 0.3.9
 - @theia/messages: 0.3.8 => 0.3.9
 - @theia/metrics: 0.3.8 => 0.3.9
 - @theia/mini-browser: 0.3.8 => 0.3.9
 - @theia/monaco: 0.3.8 => 0.3.9
 - @theia/navigator: 0.3.8 => 0.3.9
 - @theia/outline-view: 0.3.8 => 0.3.9
 - @theia/output: 0.3.8 => 0.3.9
 - @theia/preferences: 0.3.8 => 0.3.9
 - @theia/preview: 0.3.8 => 0.3.9
 - @theia/process: 0.3.8 => 0.3.9
 - @theia/python: 0.3.8 => 0.3.9
 - @theia/search-in-workspace: 0.3.8 => 0.3.9
 - @theia/task: 0.3.8 => 0.3.9
 - @theia/terminal: 0.3.8 => 0.3.9
 - @theia/typescript: 0.3.8 => 0.3.9
 - @theia/userstorage: 0.3.8 => 0.3.9
 - @theia/variable-resolver: 0.3.8 => 0.3.9
 - @theia/workspace: 0.3.8 => 0.3.9
 - @theia/example-browser: 0.3.8 => 0.3.9 (private)
 - @theia/example-electron: 0.3.8 => 0.3.9 (private)

? Are you sure you want to publish the above changes? Yes
lerna info publish Publishing packages to npm...
lerna info published @theia/application-package
lerna info published @theia/application-manager
lerna info published @theia/core
lerna info published @theia/cli
lerna info published @theia/messages
lerna info published @theia/metrics
lerna info published @theia/filesystem
lerna info published @theia/outline-view
lerna info published @theia/output
lerna info published @theia/process
lerna info published @theia/variable-resolver
lerna info published @theia/mini-browser
lerna info published @theia/userstorage
lerna info published @theia/extension-manager
lerna info published @theia/languages
lerna info published @theia/workspace
lerna info published @theia/file-search
lerna info published @theia/keymaps
lerna info published @theia/navigator
lerna info published @theia/editor
lerna info published @theia/preferences
lerna info published @theia/python
lerna info published @theia/terminal
lerna info published @theia/preview
lerna info published @theia/merge-conflicts
lerna info published @theia/markers
lerna info published @theia/git
lerna info published @theia/search-in-workspace
lerna info published @theia/task
lerna info published @theia/monaco
lerna info published @theia/editorconfig
lerna info published @theia/callhierarchy
lerna info published @theia/cpp
[                 .] / npmPublish: info published @theia/cpp
lerna ERR! publish Retrying failed publish: @theia/java
lerna ERR! publish Retrying failed publish: @theia/java
lerna ERR! publish Retrying failed publish: @theia/java
lerna ERR! publish Retrying failed publish: @theia/java
lerna ERR! publish Ran out of retries while publishing @theia/java Error: Command failed: yarn publish --tag latest --new-version 0.3.9
lerna ERR! publish warning There appears to be trouble with your network connection. Retrying...
lerna ERR! publish warning There appears to be trouble with your network connection. Retrying...
lerna ERR! publish warning There appears to be trouble with your network connection. Retrying...
lerna ERR! publish warning There appears to be trouble with your network connection. Retrying...
lerna ERR! publish error An unexpected error occurred: "https://registry.npmjs.org/@theia%2fjava: ESOCKETTIMEDOUT".
lerna ERR! publish yarn publish v1.0.2
lerna ERR! publish [1/4] Bumping version...
lerna ERR! publish info Current version: 0.3.9
lerna ERR! publish [2/4] Logging in...
lerna ERR! publish [3/4] Publishing...
lerna ERR! publish $ yarn run clean && yarn run build
lerna ERR! publish yarn run v1.0.2
lerna ERR! publish $ theiaext clean
lerna ERR! publish Done in 0.48s.
lerna ERR! publish yarn run v1.0.2
lerna ERR! publish $ concurrently -n download,build -c red,blue "gulp download_java_server" "theiaext build"
lerna ERR! publish [download] [20:16:28] Using gulpfile /opt/ericsson-dev/theia/packages/java/gulpfile.js
lerna ERR! publish [download] [20:16:28] Starting 'download_java_server'...
lerna ERR! publish [download] [20:16:28] Finished 'download_java_server' after 13 ms
lerna ERR! publish [download] gulp download_java_server exited with code 0
lerna ERR! publish [build] [lint] theiaext lint exited with code 0
lerna ERR! publish [build] [compile] theiaext compile exited with code 0
lerna ERR! publish [build] theiaext build exited with code 0
lerna ERR! publish Done in 2.69s.
lerna ERR! publish info If you think this is a bug, please open a bug report with the information provided in "/opt/ericsson-dev/theia/packages/java/yarn-error.log".
lerna ERR! publish info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
lerna ERR! publish
lerna ERR! publish     at Promise.all.then.arr (/opt/ericsson-dev/theia/node_modules/execa/index.js:236:11)
lerna ERR! publish     at <anonymous>
lerna ERR! publish     at process._tickCallback (internal/process/next_tick.js:169:7)
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn publish --tag latest --new-version 0.3.9
lerna ERR! warning There appears to be trouble with your network connection. Retrying...
lerna ERR! warning There appears to be trouble with your network connection. Retrying...
lerna ERR! warning There appears to be trouble with your network connection. Retrying...
lerna ERR! warning There appears to be trouble with your network connection. Retrying...
lerna ERR! error An unexpected error occurred: "https://registry.npmjs.org/@theia%2fjava: ESOCKETTIMEDOUT".
lerna ERR! yarn publish v1.0.2
lerna ERR! [1/4] Bumping version...
lerna ERR! info Current version: 0.3.9
lerna ERR! [2/4] Logging in...
lerna ERR! [3/4] Publishing...
lerna ERR! $ yarn run clean && yarn run build
lerna ERR! yarn run v1.0.2
lerna ERR! $ theiaext clean
lerna ERR! Done in 0.48s.
lerna ERR! yarn run v1.0.2
lerna ERR! $ concurrently -n download,build -c red,blue "gulp download_java_server" "theiaext build"
lerna ERR! [download] [20:16:28] Using gulpfile /opt/ericsson-dev/theia/packages/java/gulpfile.js
lerna ERR! [download] [20:16:28] Starting 'download_java_server'...
lerna ERR! [download] [20:16:28] Finished 'download_java_server' after 13 ms
lerna ERR! [download] gulp download_java_server exited with code 0
lerna ERR! [build] [lint] theiaext lint exited with code 0
lerna ERR! [build] [compile] theiaext compile exited with code 0
lerna ERR! [build] theiaext build exited with code 0
lerna ERR! Done in 2.69s.
lerna ERR! info If you think this is a bug, please open a bug report with the information provided in "/opt/ericsson-dev/theia/packages/java/yarn-error.log".
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (/opt/ericsson-dev/theia/node_modules/execa/index.js:236:11)
lerna ERR!     at <anonymous>
{ stack: 'Error: Command failed: yarn publish --tag latest --new-version 0.3.9\nwarning There appears to be trouble with your network connection. Retrying...\nwarning There appears to be trouble with your network connection. Retrying...\nwarning There appears to be trouble with your network connection. Retrying...\nwarning There appears to be trouble with your network connection. Retrying...\nerror An unexpected error occurred: "https://registry.npmjs.org/@theia%2fjava: ESOCKETTIMEDOUT".\nyarn publish v1.0.2\n[1/4] Bumping version...\ninfo Current version: 0.3.9\n[2/4] Logging in...\n[3/4] Publishing...\n$ yarn run clean && yarn run build\nyarn run v1.0.2\n$ theiaext clean\nDone in 0.48s.\nyarn run v1.0.2\n$ concurrently -n download,build -c red,blue "gulp download_java_server" "theiaext build"\n[download] [20:16:28] Using gulpfile /opt/ericsson-dev/theia/packages/java/gulpfile.js\n[download] [20:16:28] Starting \'download_java_server\'...\n[download] [20:16:28] Finished \'download_java_server\' after 13 ms\n[download] gulp download_java_server exited with code 0\n[build] [lint] theiaext lint exited with code 0\n[build] [compile] theiaext compile exited with code 0\n[build] theiaext build exited with code 0\nDone in 2.69s.\ninfo If you think this is a bug, please open a bug report with the information provided in "/opt/ericsson-dev/theia/packages/java/yarn-error.log".\ninfo Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.\n\n    at Promise.all.then.arr (/opt/ericsson-dev/theia/node_modules/execa/index.js:236:11)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:169:7)',
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lmcmcds@elxa610sxy1:/opt/ericsson-dev/theia$
lmcmcds@elxa610sxy1:/opt/ericsson-dev/theia$
```

**Comment by marcdumais-work** [comment]
One thing that's a bit puzzling to me: when we commit to master, the ```next``` version of ```@theia/java``` seems to publish without issue: https://travis-ci.org/theia-ide/theia/jobs/373049323#L1252

**Comment by marcdumais-work** [comment]
BTW, not sure if I'm the only one, but I can't access gitter. It was already the case late yesterday, and persists so far today...

**Comment by marcdumais-work** [comment]
Re: gitter issues: apparently not just me (https://twitter.com/gitchat/status/991268870483795968):

![image](https://user-images.githubusercontent.com/25749063/39472062-e8ec83c4-4d14-11e8-8d3b-931cf41e6a1b.png)
