### ISSUE TITLE
[quality] As an extension developer I would like to see the cause of the problem if an error occurs

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1837]
Currently, this is what an extension developer can see in the browser's console:

```
getApplicationInfo failed with message: ENOENT: no such file or directory, open '/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/package.json'
    at new t (messages.js:46)
    at main.js:430
    at main.js:258
    at main.js:242
    at setImmediate.js:40
    at _ (setImmediate.js:69)
    at s (setImmediate.js:109)
```

The backend log is not that useful either; it complains about a missing `package.json` file that I can confirm, but no one knows why it does try to open that file. Thanks!

```
"name":"Theia","hostname":"Akoss-MacBook-Pro.local","pid":39326,"level":50,"msg":"Request getApplicationInfo failed with error: ENOENT: no such file or directory, open '/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/package.json' [ 'Error: ENOENT: no such file or directory, open \\'/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/package.json\\'\\n    at Object.fs.openSync (fs.js:648:18)\\n    at Object.fs.readFileSync (fs.js:553:33)\\n    at Object.readJsonFile (/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/application-package/lib/json-file.js:13:26)\\n    at ApplicationPackage.get [as pck] (/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/application-package/lib/application-package.js:154:44)\\n    at ApplicationServerImpl.getApplicationInfo (/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/core/lib/node/application-server.js:30:43)\\n    at JsonRpcProxyFactory.<anonymous> (/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:206:73)\\n    at step (/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:38:23)\\n    at Object.next (/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:19:53)\\n    at /Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:13:71\\n    at new Promise (<anonymous>)' ]","time":"2018-05-02T11:52:43.319Z","v":0}
```

Perhaps, @epatpol knows why it does try to read the above-mentioned missing `package.json` file.

**Comment by akosyakov** [comment]
The real issue: https://github.com/theia-ide/theia/issues/1699

The idea was to avoid exposing backend errors to an end user and log them on the backend for further investigations.

We should look why the ouput is not prettified. If one uses `theia start` it should be.

In this case the formatted output looks like:
```
"name":"Theia","hostname":"Akoss-MacBook-Pro.local","pid":39326,"level":50,"msg":"Request getApplicationInfo failed with error: ENOENT: no such file or directory, open '/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/package.json' [ 'Error: ENOENT: no such file or directory, open \\'/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/package.json\\'
    at Object.fs.openSync (fs.js:648:18)
    at Object.fs.readFileSync (fs.js:553:33)
    at Object.readJsonFile (/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/application-package/lib/json-file.js:13:26)
    at ApplicationPackage.get [as pck] (/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/application-package/lib/application-package.js:154:44)
    at ApplicationServerImpl.getApplicationInfo (/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/core/lib/node/application-server.js:30:43)
    at JsonRpcProxyFactory.<anonymous> (/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:206:73)
    at step (/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:38:23)
    at Object.next (/Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:19:53)
    at /Users/akos.kitta/dev/wss/sadl_master/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:13:71
    at new Promise (<anonymous>)' ]","time":"2018-05-02T11:52:43.319Z","v":0}
```

**Comment by akosyakov** [comment]
Sorry, overlooked it. Did you start the server from the app directory? `cwd` is used by default as an app dir. maybe it is: https://github.com/theia-ide/theia/issues/1529

**Comment by kittaakos** [comment]
Yes, it does not happen if I start the application from the app folder with `yarn run start` but occurs when I start it from the generated launch configuration.

**Comment by kittaakos** [comment]
The code was minified in the browser due to https://github.com/theia-ide/generator-theia-extension/issues/17.

**Comment by sgraband** [comment]
Reporter identified root causes in comments (wrong working directory + minified code). Underlying tooling substantially rewritten.
