### ISSUE TITLE
[question][quality] The backend should terminate when the address is already in use

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1883]
Currently, we just log the error and that's all. It would be better to terminate the process, wouldn't it?

```
{"name":"Theia","hostname":"Akoss-MacBook-Pro.local","pid":16249,"level":50,"msg":"Uncaught Exception:  [ 'Error: bind EADDRINUSE 127.0.0.1:3000' ]","time":"2018-05-10T14:11:12.849Z","v":0}
{"name":"Theia","hostname":"Akoss-MacBook-Pro.local","pid":16249,"level":50,"msg":"Error: bind EADDRINUSE 127.0.0.1:3000\n    at Object._errnoException (util.js:1024:11)\n    at _exceptionWithHostPort (util.js:1046:20)\n    at listenOnMasterHandle (net.js:1414:16)\n    at rr (internal/cluster/child.js:111:12)\n    at Worker.send (internal/cluster/child.js:78:7)\n    at process.onInternalMessage (internal/cluster/utils.js:42:8)\n    at emitTwo (events.js:130:20)\n    at process.emit (events.js:213:7)\n    at emit (internal/child_process.js:774:12)\n    at _combinedTickCallback (internal/process/next_tick.js:141:11) []","time":"2018-05-10T14:11:12.850Z","v":0}
```

CC: @akosyakov, @svenefftinge

**Comment by akosyakov** [comment]
Yes, terminating is fine.
