### ISSUE TITLE
Theia backend does not run without at least one explicit LS contribution

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#189]
```
--root-dir= was not present. Falling back to current working directory: '/Users/akos.kitta/Desktop/xtext-lsp-workshop/theia-calc-extension.'
Error: No matching bindings found for serviceIdentifier: Symbol(LanguageServerContribution)
    at _createSubRequests (/Users/akos.kitta/Desktop/xtext-lsp-workshop/theia-calc-extension/node_modules/inversify/lib/planning/planner.js:107:19)
    at Object.plan (/Users/akos.kitta/Desktop/xtext-lsp-workshop/theia-calc-extension/node_modules/inversify/lib/planning/planner.js:126:5)
    at /Users/akos.kitta/Desktop/xtext-lsp-workshop/theia-calc-extension/node_modules/inversify/lib/container/container.js:228:37
    at Container._get (/Users/akos.kitta/Desktop/xtext-lsp-workshop/theia-calc-extension/node_modules/inversify/lib/container/container.js:221:44)
    at Container.getAll (/Users/akos.kitta/Desktop/xtext-lsp-workshop/theia-calc-extension/node_modules/inversify/lib/container/container.js:189:21)
    at ContainerBasedContributionProvider.getContributions (/Users/akos.kitta/Desktop/xtext-lsp-workshop/theia-calc-extension/node_modules/theia-core/lib/application/common/contribution-provider.js:24:48)
    at LanguagesBackendContribution.onStart (/Users/akos.kitta/Desktop/xtext-lsp-workshop/theia-calc-extension/node_modules/theia-core/lib/languages/node/languages-backend-contribution.js:55:54)
    at /Users/akos.kitta/Desktop/xtext-lsp-workshop/theia-calc-extension/node_modules/theia-core/lib/application/node/application.js:71:33
    at BackendApplication.start (/Users/akos.kitta/Desktop/xtext-lsp-workshop/theia-calc-extension/node_modules/theia-core/lib/application/node/application.js:62:16)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/xtext-lsp-workshop/theia-calc-extension/lib/main.js:46:13)
Theia app listening on port 3000.
```

**Comment by akosyakov** [comment]
It should be fixed already.
