### ISSUE TITLE
workspace/didChangeWatchedFiles is not sent to Clangd

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#1916]
If I edit a .cpp file, workspace/didChangeWatchedFiles is not sent to Clangd, even though BaseLanguageClientContribution.globPatterns is set. It used to work. It also currently works in VS Code so I assume it's not a problem on the Clangd side.

**Comment by simark** [comment]
I don't quite understand.

Are you saying that previously, Theia would send some `workspace/didChangeWatchedFiles` for .cpp/.h files to the server, without the server asking for it?  Was it only for files not currently open in the editor?

According to the current LSP spec document, the server must ask the client to receive change notifications for certain files.  So clangd will need to ask the client to watch `compile_commands.json` on its behalf.  It also says that previous client implementations (I guess before support for dynamic registration was added) pushed change notifications to the server, without the server asking for them.  So perhaps that's what you saw?

Are you able to pinpoint a specific revision that exhibits the old behavior?

**Comment by simark** [comment]
Theia sends this in its capabilities:

```
                "didChangeWatchedFiles": {
                    "dynamicRegistration": false
                },
```

what does this means, that it may send the `didChangeWatchedFiles` notification, but the server can't specify which files it needs to have watched?  So it's at the client's (Theia's) discretion what to watch and what change notifications to send?

**Comment by MarkZ3** [comment]
> Are you saying that previously, Theia would send some workspace/didChangeWatchedFiles for .cpp/.h files to the server, without the server asking for it? Was it only for files not currently open in the editor?

Yes. It was sending events without the server having any say (AFAIK). Basically, we would specify a pattern in the client then it would send the events for any files matching the pattern, whether or not they were open in the editor. This is how it still happens in VS Code. In fact, it's easy to try in VS Code since there is now an "official" clangd extension published :) But I do notice in VS Code we do create a file watcher by hand and in Theia the equivalent looks like should be handled automatically in BaseLanguageClientContribution.createOptions, which calls createFileEvents and should set everything up. Anyway, I'll debug this code tomorrow when my Ubuntu session is not all broken with the missing text bug...

> It also says that previous client implementations (I guess before support for dynamic registration was added) pushed change notifications to the server, without the server asking for them. So perhaps that's what you saw?

Yes. That server registration mechanism is new to me (but makes a lot of sense!) So probably it would be better for the server to ask for what to watch, but at the same time, maybe this change of behavior is breaking some other servers.

**Comment by MarkZ3** [comment]
Uhh, here's something interesting:

```
bundle.js:95444 Uncaught (in promise) Error: Request watchFileChanges failed with message: NSFW was unable to start watching that directory.
    at new ResponseError (file:///home/emalape/git/theia/examples/electron/lib/bundle.js:95444:28)
    at handleResponse (file:///home/emalape/git/theia/examples/electron/lib/bundle.js:94428:48)
    at processMessageQueue (file:///home/emalape/git/theia/examples/electron/lib/bundle.js:94256:17)
    at Immediate._onImmediate (file:///home/emalape/git/theia/examples/electron/lib/bundle.js:94240:13)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by marcdumais-work** [comment]
It would be interesting to find out what was the problem, watching that directory, in the backend.

**Comment by dihlorfos** [comment]
I faced the same issue while using emf.cloud. I updated .ecore model and couldn't save workspace due to the same error.

**Comment by sgraband** [comment]
Old `@theia/languages` package completely removed. Theia now uses plugin system for language server integration.
