### ISSUE TITLE
[navigator] Useless command on a folder generates error

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#1958]
On a folder or the workspace folder, in the Theia navigator view, the option:
   "Open"  -> do nothing Why this option is presented?
   "Open with" -> "Code editor"  why this option is presented, do nothing? 
   "Open with" -> "Mini Browser"
generates an error:
[2018-05-25T14:33:07.904Z] ERROR: Theia/13600 on elxa36mbq32: Uncaught Exception:  [ 'Error: Cannot resolve the content of a directory. URI: file:///home/lmcbout/theia/theia/examples.' ] (logger=root)

[2018-05-25T14:33:07.904Z] ERROR: Theia/13600 on elxa36mbq32: (logger=root)
    Error: Cannot resolve the content of a directory. URI: file:///home/lmcbout/theia/theia/examples.
        at FileSystemNode.<anonymous> (/home/lmcbout/theia/theia/packages/filesystem/lib/node/node-filesystem.js:151:35)
        at step (/home/lmcbout/theia/theia/packages/filesystem/lib/node/node-filesystem.js:50:23)
        at Object.next (/home/lmcbout/theia/theia/packages/filesystem/lib/node/node-filesystem.js:31:53)
        at fulfilled (/home/lmcbout/theia/theia/packages/filesystem/lib/node/node-filesystem.js:22:58)
        at <anonymous> []

**Comment by marcdumais-work** [comment]
Yes, seems like commands and corresponding menu items, that are not applicable, e.g. for a folder selection in the navigator, should be grayed-out. 

Not sure about the wording of this issue, however. "useless" may be a bit strong, as the commands / menu-items in question definitely have a use, in the proper context.

**Comment by akosyakov** [comment]
@kittaakos it is true. Is there a way to have a synchronous check, for example based on the file extension?

**Comment by kittaakos** [comment]
> Is there a way to have a synchronous check, for example based on the file extension

👍 This is exactly what I was planning to do on the frontend.
