### ISSUE TITLE
[java][LSP] Should JAVA LSP automatically try to restart and continue reporting errors 

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2103]
After receiving the following message: 

`Failed to start Java language server, connection got disposed`

it seems the JAVA LSP does not try to restart automatically, so it does not report any errors in the code ever after.

```
[2018-06-12T13:03:52.737Z] ERROR: Theia/10101 on elxa36mbq32: (logger=root)
    Error: Language client is not ready yet
        at BaseLanguageClient.sendNotification (http://localhost:3000/bundle.js:97215:19)
        at DidOpenTextDocumentFeature.callback (http://localhost:3000/bundle.js:96853:26)
        at CallbackList.../../node_modules/vscode-jsonrpc/lib/events.js.CallbackList.invoke (http://localhost:3000/bundle.js:98998:39)
        at Emitter.../../node_modules/vscode-jsonrpc/lib/events.js.Emitter.fire (http://localhost:3000/bundle.js:99062:36)
        at MonacoWorkspace.../../packages/monaco/lib/browser/monaco-workspace.js.MonacoWorkspace.fireDidOpen
```

**Comment by vince-fugnitto** [comment]
@lmcbout is this still an issue? 
We have commands for each language server so users can `restart` language servers if required.
Do you have any way to consistently reproduce the error?

**Comment by lmcbout** [comment]
@vince-fugnitto with the current code, being able to restart the JAVA LSP, this issue is not relevant anymore.
I cannot reproduce the error either., JAVA LSP is running and when resetting the browser, JAVA LSP restart.
