### ISSUE TITLE
[git][context-menu] Context menu should be sensitive to the selected items

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2115]
Context menu should only be available on proper selection items, otherwise it creates error.
Either we remove the context menu options or at least, we make it non-selectable.

scenario:
1- Create a folder
2- Clone a project into that folder: i.e. Theia 
3- In the browser, you see the following:
  folder1
     |- theia
4- Select folder1 and open the context menu + select "Diff: Compare with"
---> In the dialog, select "master"
==> On the console log, you get the error:
[2018-06-15T13:33:24.752Z] ERROR: Theia/503 on elxa36mbq32: Uncaught Exception:  [ 'GitError: fatal: ..: \'..\' is outside repository\n' ] (logger=root)

[2018-06-15T13:33:24.753Z] ERROR: Theia/503 on elxa36mbq32: (logger=root)
    GitError: fatal: ..: '..' is outside repository

        at new GitError (/home/lmcbout/theia/theia/node_modules/dugite-extra/lib/core/git.js:79:28)
        at Object.<anonymous> (/home/lmcbout/theia/theia/node_modules/dugite-extra/lib/core/git.js:155:27)
        at step (/home/lmcbout/theia/theia/node_modules/dugite-extra/lib/core/git.js:50:23)
        at Object.next (/home/lmcbout/theia/theia/node_modules/dugite-extra/lib/core/git.js:31:53)
        at fulfilled (/home/lmcbout/theia/theia/node_modules/dugite-extra/lib/core/git.js:22:58)
        at <anonymous> []

**Comment by vince-fugnitto** [comment]
fixed thanks to #3668

**Comment by vince-fugnitto** [comment]
Fixed thanks to #3668
