### ISSUE TITLE
Error when deleting a file opened

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2166]
Deleting/Renaming a file form the navigator view while the same file is opened in the editor generates an error:

[2018-06-22T13:41:56.707Z] ERROR: Theia/1461 on elxa36mbq32: (logger=root)
    Error: Request resolveContent failed with message: Cannot find file under the given URI. URI: file:///home/lmcbout/theia/workspace/multi-6/f2.
        at new ResponseError (http://localhost:3000/bundle.js:122583:28)
        at handleResponse (http://localhost:3000/bundle.js:121564:48)
        at processMessageQueue (http://localhost:3000/bundle.js:121392:17)
        at http://localhost:3000/bundle.js:121376:13
        at run (http://localhost:3000/bundle.js:115253:13)
        at runIfPresent (http://localhost:3000/bundle.js:115282:21)
        at onGlobalMessage (http://localhost:3000/bundle.js:115322:17) []

**Comment by AlexTugarev** [comment]
@lmcbout isn't this the same as #230?

**Comment by akosyakov** [comment]
yes, it is a dup
