### ISSUE TITLE
[electron] Error: Possible Emitter memory leak detected

### ISSUE THREAD

**Issue by MarkZ3** [theia-ide/theia#2208]
Theia master as of (603fe22), Electron example.

[2018-06-27T13:43:31.978Z]  WARN: Theia/10545 on elxajvlvvz1: (logger=root)
    Error: Possible Emitter memory leak detected. 30 exit listeners added. Use event.maxListeners to increase limit
        at Emitter.../../packages/core/lib/common/event.js.Emitter.checkMaxListeners (file:///home/user/git/stable-dev/theia/examples/electron/lib/bundle.js:148920:26)
        at PreferenceServiceImpl._event.Object.assign.maxListeners [as onPreferenceChanged] (file:///home/user/git/stable-dev/theia/examples/electron/lib/bundle.js:148887:27)
        at ElectronMainMenuFactory.../../packages/core/lib/electron-browser/menu/electron-main-menu-factory.js.ElectronMainMenuFactory.fillMenuTemplate (file:///home/user/git/stable-dev/theia/examples/electron/lib/bundle.js:152110:33)
        at _loop_1 (file:///home/user/git/stable-dev/theia/examples/electron/lib/bundle.js:152064:28)
        at ElectronMainMenuFactory.../../packages/core/lib/electron-browser/menu/electron-main-menu-factory.js.ElectronMainMenuFactory.fillMenuTemplate (file:///home/user/git/stable-dev/theia/examples/electron/lib/bundle.js:152100:17)
        at ElectronMainMenuFactory.../../packages/core/lib/electron-browser/menu/electron-main-menu-factory.js.ElectronMainMenuFactory.createContextMenu (file:///home/user/git/stable-dev/theia/examples/electron/lib/bundle.js:152043:29)
        at ElectronContextMenuRenderer.../../packages/core/lib/electron-browser/menu/electron-context-menu-renderer.js.ElectronContextMenuRenderer.render (file:///home/user/git/stable-dev/theia/examples/electron/lib/bundle.js:151955:37)
        at MonacoContextMenuService.../../packages/monaco/lib/browser/monaco-context-menu.js.MonacoContextMenuService.showContextMenu (file:///home/user/git/stable-dev/theia/examples/electron/lib/bundle.js:177484:38)
        at ContextMenuController._doShowContextMenu (file:///home/user/git/stable-dev/theia/examples/electron/lib/vs/editor/editor.main.js:78999:38)

**Comment by MarkZ3** [comment]
Please note that you have to use a different command now to see the logging, see https://github.com/theia-ide/theia/issues/2344
