### ISSUE TITLE
Running yo theia-extension errors

### ISSUE THREAD

**Issue by adamretter** [theia-ide/theia#2368]
Following the instructions here: http://www.theia-ide.org/doc/authoring_extensions

```
$ yo theia-extension hello-world
?==========================================================================
We're constantly looking for ways to make yo better! 
May we anonymously report usage statistics to improve the tool over time? 
More info: https://github.com/yeoman/insight & http://yeoman.io
========================================================================== No
HelloWorld
   create package.json
   create lerna.json
   create .gitignore
   create README.md
   create .vscode/launch.json
   create hello-world-extension/package.json
   create hello-world-extension/tsconfig.json
   create hello-world-extension/src/browser/hello-world-frontend-module.ts
   create hello-world-extension/src/browser/hello-world-contribution.ts
   create browser-app/package.json
   create electron-app/package.json
events.js:112
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at _errnoException (util.js:1003:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:201:19)
    at onErrorNT (internal/child_process.js:379:16)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by akosyakov** [comment]
You should make sure that `yarn` is installed.

**Comment by adamretter** [comment]
Doh!

thanks @akosyakov
