### ISSUE TITLE
The widget manager caches the rejected widget promises

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2421]
The widget manager caches rejected promises, so if I try to open a widget that fails (due to missing resource in a given time) I will not be able to open it unless I reset the `localStorage`. Rejected promises should not be cached.

```
logger.ts:107 
{exception: null, error: Error: Request resolveContent failed with message: Cannot find file under the given URI. URI: file:/…, promise: _…e.C…s.d…e._creator, handler: undefined, id: 4, …}
error
:
Error: Request resolveContent failed with message: Cannot find file under the given URI. URI: file:///Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/sadl-extension/example-projects/query/ImplicitModel/SadlImplicitModel.sadl. at new ResponseError (http://localhost:3000/bundle.js:99609:28) at handleResponse (http://localhost:3000/bundle.js:98590:48) at processMessageQueue (http://localhost:3000/bundle.js:98418:17) at http://localhost:3000/bundle.js:98402:13 at run (http://localhost:3000/bundle.js:96285:13) at runIfPresent (http://localhost:3000/bundle.js:96314:21) at onGlobalMessage (http://localhost:3000/bundle.js:96354:17)
code
:
-32603
data
:
undefined
message
:
"Request resolveContent failed with message: Cannot find file under the given URI. URI: file:///Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/sadl-extension/example-projects/query/ImplicitModel/SadlImplicitModel.sadl."
stack
:
"Error: Request resolveContent failed with message: Cannot find file under the given URI. URI: file:///Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/sadl-extension/example-projects/query/ImplicitModel/SadlImplicitModel.sadl.↵    at new ResponseError (http://localhost:3000/bundle.js:99609:28)↵    at handleResponse (http://localhost:3000/bundle.js:98590:48)↵    at processMessageQueue (http://localhost:3000/bundle.js:98418:17)↵    at http://localhost:3000/bundle.js:98402:13↵    at run (http://localhost:3000/bundle.js:96285:13)↵    at runIfPresent (http://localhost:3000/bundle.js:96314:21)↵    at onGlobalMessage (http://localhost:3000/bundle.js:96354:17)"
__proto__
:
Error
exception
:
null
handler
:
undefined
id
:
4
parent
:
undefined
promise
:
_Base.Class.derive._creator
done
:
ƒ ErrorPromise_done(unused, onError)
then
:
ƒ ErrorPromise_then(unused, onError)
_creator
:
null
_errorId
:
4
_isException
:
false
_listeners
:
null
_nextState
:
null
_state
:
{name: "error", enter: ƒ, cancel: ƒ, done: null, then: null, …}
_value
:
Error: Request resolveContent failed with message: Cannot find file under the given URI. URI: file:///Users/akos.kitta/git/sadlos2/sadl3/com.ge.research.sadl.parent/theia-sadl-extension/sadl-extension/example-projects/query/ImplicitModel/SadlImplicitModel.sadl. at new ResponseError (http://localhost:3000/bundle.js:99609:28) at handleResponse (http://localhost:3000/bundle.js:98590:48) at processMessageQueue (http://localhost:3000/bundle.js:98418:17) at http://localhost:3000/bundle.js:98402:13 at run (http://localhost:3000/bundle.js:96285:13) at runIfPresent (http://localhost:3000/bundle.js:96314:21) at onGlobalMessage (http://localhost:3000/bundle.js:96354:17)
__proto__
:
constructor
__proto__
:
Object
```

**Comment by kittaakos** [comment]
Something like this should fix the problem. What's your take on this @akosyakov?
```diff
diff --git a/packages/core/src/browser/widget-manager.ts b/packages/core/src/browser/widget-manager.ts
index 37731d4a..4c964288 100644
--- a/packages/core/src/browser/widget-manager.ts
+++ b/packages/core/src/browser/widget-manager.ts
@@ -106,8 +106,11 @@ export class WidgetManager {
     protected async doGetWidget<T extends Widget>(key: string): Promise<T | undefined> {
         const existingWidgetPromise = this.widgetPromises.get(key);
         if (existingWidgetPromise) {
-            const existingWidget = await existingWidgetPromise;
-            return existingWidget as T;
+            try {
+                return await existingWidgetPromise as T;
+            } catch {
+                this.widgetPromises.delete(key);
+            }
         }
         return undefined;
     }
```
