### ISSUE TITLE
DSL (xtext) language server integration with Theia

### ISSUE THREAD

**Issue by amirsaad2015** [theia-ide/theia#2438]
I am having trouble integrating my DSL to the Theia application. I have followed the following steps:

I cloned the github repository labeled theia-xtext
I used eclipse to generate my own DSL following this tutorial: https://www.eclipse.org/community/eclipse_newsletter/2017/may/article5.php

I then removed the .ide and .example file from the cloned repository and pasted my directories created from the tutorial. I also modified the build.gradle files respectively.

Afterwards, I run the command as stated in the github repo:

Build the language server

  cd xtext-dsl-language-server &&
  ./gradlew shadowJar &&
  cd ..
Build and start Theia

   yarn install &&
   cd app &&
   yarn start

After visiting "localhost:3000", the the application cannot find my DSL and in the command line I receive the following error:

[2018-07-25T23:27:18.683Z] ERROR: Theia/58281 on MT-110778: Request getFileStat failed with error: Cannot find file under the given URI. URI: file:///Users/asaad/Desktop/theia-xtext/xtext-dsl-language-server/io.typefox.xtext.langserver.example/src/main/java/io/typefox/xtext/langserver/example/MyDsl.xtext. [ 'Error: Cannot find file under the given URI. URI: file:///Users/asaad/Desktop/theia-xtext/xtext-dsl-language-server/io.typefox.xtext.langserver.example/src/main/java/io/typefox/xtext/langserver/example/MyDsl.xtext.\n    at FileSystemNode.<anonymous> (/Users/asaad/Desktop/theia-xtext/node_modules/@theia/filesystem/lib/node/node-filesystem.js:115:35)\n    at step (/Users/asaad/Desktop/theia-xtext/node_modules/@theia/filesystem/lib/node/node-filesystem.js:50:23)\n    at Object.next (/Users/asaad/Desktop/theia-xtext/node_modules/@theia/filesystem/lib/node/node-filesystem.js:31:53)\n    at fulfilled (/Users/asaad/Desktop/theia-xtext/node_modules/@theia/filesystem/lib/node/node-filesystem.js:22:58)\n    at <anonymous>' ]

**Comment by kittaakos** [comment]
@amirsaad2015, can you share the current state of your code? (Preferably as a public GH repository.)

**Comment by amirsaad2015** [comment]
Yes, I have uploaded the code in the following repository: https://github.com/amirsaad2015/dsl

**Comment by amirsaad2015** [comment]
Yes, I have uploaded the code in the following repository: https://github.com/amirsaad2015/dsl

**Comment by kittaakos** [comment]
Thanks for the link, @amirsaad2015. Can you please get rid of the generated stuff and `node_modules` content? Once you are done, I am happy to try out and see what's wrong with the setup.

**Comment by kittaakos** [comment]
Your repository content is out of sync, isn't it?

 - Your Xtext grammar is for files with [`.mydsl`](https://github.com/amirsaad2015/dsl/blob/a18cfc94124792ff5015c45eb5ce12c46d1f8564/xtext-dsl-language-server/org.xtext.example.mydsl/src/main/java/org/xtext/example/mydsl/GenerateMyDsl.mwe2#L31) extension.
 - But your Theia extension is waiting for [`.dsl`](https://github.com/amirsaad2015/dsl/blob/a18cfc94124792ff5015c45eb5ce12c46d1f8564/xtext-dsl-extension/src/browser/language-contribution.ts#L20) resources.

If you update, I'll take a look.

**Comment by amirsaad2015** [comment]
I updated the code per your advice and was able to resolve the issue. Thank you for the help.
