### ISSUE TITLE
Max number of watches reached (ENOSPC), no root access to increase max_user_watches

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#257]
My terminal is flooded with these messages:
```
[backend]     Watching error: [ [ { Error: watch /repo/emaisin/src/theia/examples/browser/node_modules/express/node_modules/debug/component.json ENOSPC
[backend]             at exports._errnoException (util.js:1050:11)
[backend]             at FSWatcher.start (fs.js:1398:19)
[backend]             at Object.fs.watch (fs.js:1424:11)
[backend]             at createFsWatchInstance (/repo/emaisin/src/theia/examples/browser/node_modules/chokidar/lib/nodefs-handler.js:37:15)
[backend]             at setFsWatchListener (/repo/emaisin/src/theia/examples/browser/node_modules/chokidar/lib/nodefs-handler.js:80:15)
[backend]             at FSWatcher.NodeFsHandler._watchWithNodeFs (/repo/emaisin/src/theia/examples/browser/node_modules/chokidar/lib/nodefs-handler.js:228:14)
[backend]             at FSWatcher.NodeFsHandler._handleFile (/repo/emaisin/src/theia/examples/browser/node_modules/chokidar/lib/nodefs-handler.js:255:21)
[backend]             at FSWatcher.<anonymous> (/repo/emaisin/src/theia/examples/browser/node_modules/chokidar/lib/nodefs-handler.js:473:21)
[backend]             at FSReqWrap.oncomplete (fs.js:114:15)
[backend]           code: 'ENOSPC',
[backend]           errno: 'ENOSPC',
[backend]           syscall: 'watch /repo/emaisin/src/theia/examples/browser/node_modules/express/node_modules/debug/component.json',
[backend]           filename: '/repo/emaisin/src/theia/examples/browser/node_modules/express/node_modules/debug/component.json' } ] ]
```

I don't have root access on that machine so I can't modify max_user_watches.  I think in an enterprise context this may be a quite common scenario, so I think it should be gracefully handled.

- It seems like we are watching all files in the root directory. Why is it necessary?
- After the first error, is it possible to stop so that the terminal is not flooded with these messages?
- A message could be presented to the user saying that some file watching functionality may not be working, and some link to how to fix it.  It could also say if there's an alternative way of doing a "manual refresh" of a directory, as an immediate workaround.

**Comment by akosyakov** [comment]
a dup of https://github.com/theia-ide/theia/issues/239?

**Comment by simark** [comment]
Right, it's close enough.  I'll comment there instead.
