### ISSUE TITLE
Electron Example App won't start on Windows

### ISSUE THREAD

**Issue by adamretter** [theia-ide/theia#2613]
After fixing the Windows build process - https://github.com/theia-ide/theia/pull/2612

I can now run the Theia example Browser App.
However, when I try and run the Theia example Electron App, I get this error:

```ps
C:\Users\aretter\code\theia\examples\electron>yarn run start
yarn run v1.7.0
$ theia start

Starting server worker...
Server worker has been started. [ID: 1 | PID: 7000]
Server worker failed to start.
C:\Users\aretter\code\theia\packages\core\lib\node\cluster\main.js:58
    throw reason;
    ^

Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\aretter\code\theia\node_modules\vscode-nsfw\lib\src\index.js:3:16)
    at Object.<anonymous> (C:\Users\aretter\code\theia\node_modules\vscode-nsfw\lib\src\index.js:130:3)
Server worker has been disconnected. [ID: 1 | PID: 7000]
Server worker has been stopped. [ID: 1 | PID: 7000]
Error: Module did not self-register.
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\aretter\code\theia\node_modules\vscode-nsfw\lib\src\index.js:3:16)
    at Object.<anonymous> (C:\Users\aretter\code\theia\node_modules\vscode-nsfw\lib\src\index.js:130:3)
Done in 17.75s.
```

**Comment by marcdumais-work** [comment]
Did you rebuild the native Node.js packages for electron? If not run the following from the Theia root and try starting Theia again:
```yarn run rebuild:electron```

**Comment by oquistador** [comment]
That seemed to work @marcdumais-work. Thanks. What does `theia rebuild:electron` do?

**Comment by marcdumais-work** [comment]
@oquistador Theia has some npm dependencies that need to be built natively for a given machine. Those dependencies are built against the Node.js version being used. Since most of the time the node version used for the Theia browser version will not exactly match the version being used internally by Electron, a recompilation step is generally necessary, when switching between browser and Electron version of Theia. 

One such dependency is the ```vscode-nsfw``` file watcher, that I noticed at the bottom of the stack trace above.

**Comment by marcdumais-work** [comment]
@adamretter Please re-open if this does not fix the issue for you

**Comment by adamretter** [comment]
@marcdumais-work Thanks, that previously seemed to work. However now I get a slightly different problem:

```
C:\Users\aretter\code\theia>yarn run rebuild:electron
yarn run v1.7.0
$ theia rebuild:electron
Processing node-pty
Processing vscode-nsfw
Processing find-git-repositories
Done in 76.16s.

C:\Users\aretter\code\theia>cd examples\electron

C:\Users\aretter\code\theia\examples\electron>yarn run start
yarn run v1.7.0
$ theia start

Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 3500]
Server worker is ready to accept messages. [ID: 1 | PID: 3500]
Server worker has been disconnected. [ID: 1 | PID: 3500]
Server worker failed to start within 5000 milliseconds.
Pass a greater value as '--startup-timeout' option to increase the timeout or a negative to disable.
root INFO Theia app listening on http://localhost:50442.
root ERROR Error: Object has been destroyed
    at BrowserWindow.loadURL (C:\Users\aretter\code\theia\node_modules\electron\dist\resources\electron.asar\browser\api\browser-window.js:167:16)
    at loadMainWindow (C:\Users\aretter\code\theia\examples\electron\src-gen\frontend\electron-main.js:63:24)
    at require.then.address (C:\Users\aretter\code\theia\examples\electron\src-gen\frontend\electron-main.js:70:17)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
root INFO Started watching: c:\Users\aretter\code\theia\examples\electron\package.json
Done in 51.85s.
```

@marcdumais-work p.s. I don't seem to have permission to re-open an issue.

**Comment by kittaakos** [comment]
@adamretter, try to increase the timeout: https://github.com/theia-ide/theia/pull/3074#issue-220298500
