### ISSUE TITLE
Our placeholder electron spec test throws exception on execution but reported as a green one

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#271]
Execute the build script locally as described at #270. Got this:

```
theia-core -> electron-example: installed original sources in 198 sourcemaps

> electron-example@0.0.1-alpha.1 test /Users/akos.kitta/Desktop/foo/theia/examples/electron
> electron-mocha --timeout 60000 --require ts-node/register test/**/*.espec.ts



  basic-example-spec
    01 #start example app
Error: The module '/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/dtrace-provider/build/Release/DTraceProviderBindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/dtrace-provider/dtrace-provider.js:42:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/bunyan/lib/bunyan.js:79:18)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/bunyan/lib/bunyan.js:1629:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/src/application/node/bunyan-logger-server.ts:8:1)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/theia-core/lib/application/node/bunyan-logger-server.js:149:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/src/application/node/logger-backend-module.ts:11:1)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/theia-core/lib/application/node/logger-backend-module.js:39:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/src/application/node/index.ts:12:1)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/theia-core/lib/application/node/index.js:20:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/src-gen/backend/main.js:13:79)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/src-gen/backend/main.js:44:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Context.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/test/basic-example.espec.ts:32:17)
    at callFnAsync (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runnable.js:371:21)
    at Test.Runnable.run (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runnable.js:318:7)
    at Runner.runTest (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:443:10)
    at /Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:361:14)
    at /Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:295:14)
    at Immediate.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/dtrace-provider/dtrace-provider.js:42:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/bunyan/lib/bunyan.js:79:18)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/bunyan/lib/bunyan.js:1629:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/src/application/node/bunyan-logger-server.ts:8:1)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/theia-core/lib/application/node/bunyan-logger-server.js:149:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/src/application/node/logger-backend-module.ts:11:1)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/theia-core/lib/application/node/logger-backend-module.js:39:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/src/application/node/index.ts:12:1)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/theia-core/lib/application/node/index.js:20:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/src-gen/backend/main.js:13:79)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/src-gen/backend/main.js:44:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Context.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/test/basic-example.espec.ts:32:17)
    at callFnAsync (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runnable.js:371:21)
    at Test.Runnable.run (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runnable.js:318:7)
    at Runner.runTest (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:443:10)
    at /Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:361:14)
    at /Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:295:14)
    at Immediate.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/dtrace-provider/dtrace-provider.js:42:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/bunyan/lib/bunyan.js:79:18)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/bunyan/lib/bunyan.js:1629:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/src/application/node/bunyan-logger-server.ts:8:1)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/theia-core/lib/application/node/bunyan-logger-server.js:149:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/src/application/node/logger-backend-module.ts:11:1)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/theia-core/lib/application/node/logger-backend-module.js:39:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/src/application/node/index.ts:12:1)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/theia-core/lib/application/node/index.js:20:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/src-gen/backend/main.js:13:79)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/src-gen/backend/main.js:44:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Context.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/test/basic-example.espec.ts:32:17)
    at callFnAsync (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runnable.js:371:21)
    at Test.Runnable.run (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runnable.js:318:7)
    at Runner.runTest (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:443:10)
    at /Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:549:12
    at next (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:361:14)
    at /Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:371:7
    at next (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:295:14)
    at Immediate.<anonymous> (/Users/akos.kitta/Desktop/foo/theia/examples/electron/node_modules/mocha/lib/runner.js:339:5)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5) code: 'MODULE_NOT_FOUND' }
      ✓ should start the electron example app (382ms)
{"name":"Theia","hostname":"Akoss-MBP.fritz.box","pid":5741,"level":30,"msg":"Theia app listening on port 3000. [ [] ]","time":"2017-07-03T20:05:03.618Z","v":0}


  1 passing (828ms)

```

**Comment by kittaakos** [comment]
I have not seen this for a long time now. The electron test also passes without any problem on the CIs. I am closing this issue.
