### ISSUE TITLE
[bundled-electron] The `event.maxListeners` exceeded right after starting the application

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2725]
No editors, no previous workspaces, nothing. Got this right after starting the application:
```
root WARN Error: Possible Emitter memory leak detected. 30 exit listeners added. Use event.maxListeners to increase limit
    at e.checkMaxListeners (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:1:68630)
    at e._event._event.Object.assign.maxListeners [as onPreferenceChanged] (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:1:68183)
    at e.fillMenuTemplate (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:514907)
    at c (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:514087)
    at e.fillMenuTemplate (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:514767)
    at e.createMenuBar (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:513656)
    at e.onStart (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:54:397515)
    at e.<anonymous> (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:334069)
    at file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:329332
    at Object.next (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:329437)
root WARN Error: Possible Emitter memory leak detected. 30 exit listeners added. Use event.maxListeners to increase limit
    at e.checkMaxListeners (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:1:68630)
    at e._event._event.Object.assign.maxListeners [as onPreferenceChanged] (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:1:68183)
    at e.fillMenuTemplate (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:514907)
    at c (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:514142)
    at e.fillMenuTemplate (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:514767)
    at c (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:514087)
    at e.fillMenuTemplate (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:514767)
    at e.createMenuBar (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:513656)
    at e.onStart (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:54:397515)
    at e.<anonymous> (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:334069)
root WARN Error: Possible Emitter memory leak detected. 30 exit listeners added. Use event.maxListeners to increase limit
    at e.checkMaxListeners (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:1:68630)
    at e._event._event.Object.assign.maxListeners [as onPreferenceChanged] (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:1:68183)
    at e.fillMenuTemplate (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:514907)
    at c (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:514087)
    at e.fillMenuTemplate (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:514767)
    at e.createMenuBar (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:513656)
    at e.onStart (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:54:397515)
    at e.<anonymous> (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:334069)
    at file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:329332
    at Object.next (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:329437)
root WARN Error: Possible Emitter memory leak detected. 30 exit listeners added. Use event.maxListeners to increase limit
    at e.checkMaxListeners (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:1:68630)
    at e._event._event.Object.assign.maxListeners [as onPreferenceChanged] (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:1:68183)
    at e.fillMenuTemplate (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:514907)
    at e.createMenuBar (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:513656)
    at e.onStart (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:54:397515)
    at e.<anonymous> (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:334069)
    at file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:329332
    at Object.next (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:329437)
    at a (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:328183)
    at <anonymous>
root WARN Error: Possible Emitter memory leak detected. 30 exit listeners added. Use event.maxListeners to increase limit
    at e.checkMaxListeners (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:1:68630)
    at e._event._event.Object.assign.maxListeners [as onPreferenceChanged] (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:1:68183)
    at Object.t.createPreferenceProxy (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:54:44272)
    at i (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:23:101673)
    at e.dynamicValue (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:23:102059)
    at file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:38:24798
    at c (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:38:23843)
    at file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:38:24739
    at Array.map (native)
    at Object.t.resolveInstance (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:38:26142)
root WARN Error: Possible Emitter memory leak detected. 30 exit listeners added. Use event.maxListeners to increase limit
    at e.checkMaxListeners (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:1:68630)
    at e._event._event.Object.assign.maxListeners [as onPreferenceChanged] (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:1:68183)
    at Object.t.createPreferenceProxy (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:54:44272)
    at i (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:611440)
    at e.dynamicValue (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:12:612163)
    at file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:38:24798
    at c (file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:38:23843)
    at file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:38:24739
    at Array.map (native)
    at file:///Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/app/lib/bundle.js:38:25885
Server worker has been disconnected. [ID: 1 | PID: 12559]
```

**Comment by kittaakos** [comment]
This is the same as https://github.com/theia-ide/theia/issues/2208 and was fixed. It is available from `0.3.14` as `latest`. I am closing this.
