### ISSUE TITLE
[bundled-electron] Cannot select a workspace

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2726]
This is a follow-up of #2725. Application crashed when I started to set the workspace after the very first start.
```
Server worker has been disconnected. [ID: 1 | PID: 12559]
Server worker has been stopped. [ID: 1 | PID: 12559]
module.js:487
    throw err;
    ^

Error: Cannot find module '../dialog'
    at Module._resolveFilename (module.js:485:15)
    at Function.Module._resolveFilename (/Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:437:25)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.get [as dialog] (/Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:11:16)
    at process.<anonymous> (/Users/akos.kitta/Desktop/theia-apps/theia-electron/dist/mac/Theia.app/Contents/Resources/electron.asar/browser/init.js:54:31)
    at emitOne (events.js:115:13)
    at process.emit (events.js:210:7)
    at process._fatalException (bootstrap_node.js:338:26)
```

I had to force quit the application.

**Comment by kittaakos** [comment]
I cannot reproduce it with `0.3.14` anymore.
