### ISSUE TITLE
[Electron][Git] Selecting the Git History view from an existing workspace generates an error

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2855]
Testing with Electron
Scenario:
- Start Electron
- theia workspace already in it
- Select the "Git History" view  ==> generates the following error

task INFO Config file tasks.json does not exist under file:///home/lmcbout/theia/theia
root ERROR The above error occurred in the <Grid> component:
    in Grid (created by List)
    in List (created by AutoSizer)
    in div (created by AutoSizer)
    in AutoSizer (created by InfiniteLoader)
    in InfiniteLoader (created by GitHistoryList)
    in GitHistoryList
    in div
    in div

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
root ERROR TypeError: this.node.scrollTo is not a function
    at GitHistoryWidget.push.../../packages/git/lib/browser/history/git-history-widget.js.GitHistoryWidget.doHandleScroll (file:///home/lmcbout/theia/theia/examples/electron/lib/48.bundle.js:7874:19)
    at GitHistoryWidget._this.handleScroll (file:///home/lmcbout/theia/theia/examples/electron/lib/48.bundle.js:7582:61)
    at List._this._onScroll (file:///home/lmcbout/theia/theia/examples/electron/lib/bundle.js:64981:7)
    at callback (file:///home/lmcbout/theia/theia/examples/electron/lib/bundle.js:62704:11)
    at Grid._onScrollMemoizer (file:///home/lmcbout/theia/theia/examples/electron/lib/bundle.js:69372:7)
    at Grid._invokeOnScrollMemoizer (file:///home/lmcbout/theia/theia/examples/electron/lib/bundle.js:62694:12)
    at Grid.componentDidMount (file:///home/lmcbout/theia/theia/examples/electron/lib/bundle.js:62252:12)
    at commitLifeCycles (file:///home/lmcbout/theia/theia/examples/electron/lib/bundle.js:55987:22)
    at commitAllLifeCycles (file:///home/lmcbout/theia/theia/examples/electron/lib/bundle.js:57088:7)
    at HTMLUnknownElement.callCallback (file:///home/lmcbout/theia/theia/examples/electron/lib/bundle.js:41725:14

**Comment by westbury** [comment]
doHandleScroll fails.  this.node is div#git-history.p-Widget.theia-git.p-DockPanel-widget which I would not expect to contain the scrollTo function.  It seems to me that scrolling is not necessary here.  I'm not sure what it is trying to achieve, as this view scrolls without this scrollTo call.
