### ISSUE TITLE
[tests] GitError: fatal: unknown date format unix

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#2920]
Since the beginning of the week, I am unable to run the tests, it always fails with:

```
  79 passing (30s)
  1 failing

  1) log should not fail with local git when executed from the repository root:
     GitError: fatal: unknown date format unix

      at new GitError (/home/emaapur/projects/theia.chocolat/node_modules/dugite-extra/src/core/git.ts:89:9)
      at Object.<anonymous> (/home/emaapur/projects/theia.chocolat/node_modules/dugite-extra/src/core/git.ts:275:15)
      at step (/home/emaapur/projects/theia.chocolat/node_modules/dugite-extra/lib/core/git.js:50:23)
      at Object.next (/home/emaapur/projects/theia.chocolat/node_modules/dugite-extra/lib/core/git.js:31:53)
      at fulfilled (/home/emaapur/projects/theia.chocolat/node_modules/dugite-extra/lib/core/git.js:22:58)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by marechal-p** [comment]
Not sure if the bug was from my installation or from the repo, but the problem seems to be gone... I will reopen if it happens again.

**Comment by anymost** [comment]
The same issue I encountered, Does somebody has any ideas?
