### ISSUE TITLE
Error when opening a workspace

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2929]
- Start the Theia example browser app.
 - Open Theia in the workspace.
 - Open the root of the [Eclipse JDT](https://github.com/eclipse/eclipse.jdt.ls) project as a workspace with `Open Recent Workspace...`.

Got this:
```
root INFO [nsfw-watcher: 19447] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/CompletionResolveHandler.java
root ERROR Uncaught Exception:  Error: not opened
root ERROR Error: not opened
    at WebSocket.send (/Users/akos.kitta/git/theia/packages/core/node_modules/ws/lib/WebSocket.js:359:18)
    at WebSocketChannel.doSend (/Users/akos.kitta/git/theia/packages/core/lib/node/messaging/messaging-contribution.js:224:97)
    at WebSocketChannel.close (/Users/akos.kitta/git/theia/packages/core/lib/common/messaging/web-socket-channel.js:92:14)
    at WebSocket.<anonymous> (/Users/akos.kitta/git/theia/packages/core/lib/node/messaging/messaging-contribution.js:210:29)
    at emitTwo (events.js:131:20)
    at WebSocket.emit (events.js:214:7)
    at WebSocket.emitClose (/Users/akos.kitta/git/theia/packages/core/node_modules/ws/lib/WebSocket.js:211:10)
    at _receiver.cleanup (/Users/akos.kitta/git/theia/packages/core/node_modules/ws/lib/WebSocket.js:199:39)
    at Receiver.cleanup (/Users/akos.kitta/git/theia/packages/core/node_modules/ws/lib/Receiver.js:520:15)
    at WebSocket.finalize (/Users/akos.kitta/git/theia/packages/core/node_modules/ws/lib/WebSocket.js:199:20)
root INFO Registering scopes for language: java.
root INFO The scopes have been successfully registered for java.
root WARN A command java.edit.organizeImports is already registered.
```

**Comment by marcdumais-work** [comment]
I am able to reproduce. It seems the error appears whenever I open a workspace. Doesn't matter if one is previously opened or not, or if the new workspace is opened through "open recent workspace" or "open workspace".
