### ISSUE TITLE
Language client restart does not work

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#2987]
I rebased #2907 on current master, and I can't get my language server to be restarted.

The first time the `BaseLanguageClientContribution.restart()` method is called, the value of `this.toRestart` is not undefined, so something seems to happen.  But in the subsequent calls, `this.toRestart` is always undefined, which makes the call to `.restart()` a no-op.

**Comment by AlexTugarev** [comment]
Confirmed with `Restart TS` command.

Getting this error and no TS support afterwards:

```
root INFO Error: Connection is disposed.
    at new ConnectionError (http://localhost:3000/bundle.js:79948:28)
    at throwIfClosedOrDisposed (http://localhost:3000/bundle.js:80426:19)
    at Object.sendRequest (http://localhost:3000/bundle.js:80525:13)
    at Object.sendRequest (http://localhost:3000/9.bundle.js:171:43)
    at MonacoLanguageClient.push.../../node_modules/vscode-base-languageclient/lib/client.js.BaseLanguageClient.sendRequest (http://localhost:3000/9.bundle.js:4934:64)
    at provideFoldingRanges (http://localhost:3000/9.bundle.js:6290:27)
    at Object.provideFoldingRanges (http://localhost:3000/9.bundle.js:6300:23)
    at Object.provideFoldingRanges (http://localhost:3000/9.bundle.js:2895:37)
    at Object.provideFoldingRanges (http://localhost:3000/9.bundle.js:1997:33)
    at http://localhost:3000/vs/editor/editor.main.js:42336:48
root INFO connect...
root WARN Error: Connection is disposed.
    at new ConnectionError (http://localhost:3000/bundle.js:79948:28)
    at throwIfClosedOrDisposed (http://localhost:3000/bundle.js:80426:19)
    at Object.sendRequest (http://localhost:3000/bundle.js:80525:13)
    at Object.sendRequest (http://localhost:3000/9.bundle.js:171:43)
    at MonacoLanguageClient.push.../../node_modules/vscode-base-languageclient/lib/client.js.BaseLanguageClient.sendRequest (http://localhost:3000/9.bundle.js:4934:64)
    at provideCompletionItems (http://localhost:3000/9.bundle.js:3966:27)
    at Object.provideCompletionItems (http://localhost:3000/9.bundle.js:3982:27)
    at Object.provideCompletionItems (http://localhost:3000/9.bundle.js:2600:41)
    at Object.provideCompletionItems (http://localhost:3000/9.bundle.js:1542:33)
    at SuggestAdapter.provideCompletionItems (http://localhost:3000/vs/editor/editor.main.js:112313:41)
```

**Comment by simark** [comment]
I would suggest writing a UI test for this when this is fixed :)
