### ISSUE TITLE
[electron][Windows] Error on app startup in a bundled electron application

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#2992]
It happens on Windows, I do not know if it affects other platforms or not.

```
Error: @postConstruct error in class TypeScriptContribution: EPERM: operation not permitted, open 'c:\Program Files\typefox2\.application-module-loader.js'
    at _postConstruct (c:\Program Files\typefox2\resources\app\node_modules\inversify\lib\resolution\instantiation.js:30:19)
    at Object.resolveInstance (c:\Program Files\typefox2\resources\app\node_modules\inversify\lib\resolution\instantiation.js:47:5)
    at c:\Program Files\typefox2\resources\app\node_modules\inversify\lib\resolution\resolver.js:72:42
    at c:\Program Files\typefox2\resources\app\node_modules\inversify\lib\resolution\resolver.js:34:24
    at Array.map (native)
    at c:\Program Files\typefox2\resources\app\node_modules\inversify\lib\resolution\resolver.js:32:34
    at Object.resolve (c:\Program Files\typefox2\resources\app\node_modules\inversify\lib\resolution\resolver.js:96:12)
    at c:\Program Files\typefox2\resources\app\node_modules\inversify\lib\container\container.js:320:37
    at Container._get (c:\Program Files\typefox2\resources\app\node_modules\inversify\lib\container\container.js:311:44)
    at Container.getAll (c:\Program Files\typefox2\resources\app\node_modules\inversify\lib\container\container.js:239:21)
```

~Update:~
 - ~It worth to mention, it happened on Windows in the `@theia/typescript` extension.~
 - ~This could be related: https://github.com/theia-ide/typescript-language-server/issues/72~

Update2:
  - The problem is described here:  https://github.com/theia-ide/theia/issues/2624#issuecomment-425106180. In a nutshell: we incorrectly assume the position of the `package.json` in case of a bundled electron application. Same reason the `About Dialog` fails in electron.

Related code:
https://github.com/theia-ide/theia/blob/1e747c97ec092ad0cdb73f718cee8c353c0cf240/packages/typescript/src/node/typescript-contribution.ts#L33-L49

**Comment by marechal-p** [comment]
On my end, it crashes with the following error:

> root ERROR [nsfw-watcher: 27103] /meh/projects/electron-bundle/node_modules/electron/dist/electron: symbol lookup error: /meh/projects/electron-bundle/node_modules/vscode-nsfw/build/Release/nsfw.node: undefined symbol: _ZN4node19GetCurrentEventLoopEPN2v87IsolateE

(Ubuntu 16.04)

**Comment by kittaakos** [comment]
> On my end, it crashes with the following error:

@marechal-p, please file a separate issue. We can close it as a duplicate later.

**Comment by kittaakos** [comment]
https://github.com/theia-ide/theia/blob/e0ccd3ac7b182251aa5321004ab2f4387de0385f/dev-packages/application-package/src/application-package.ts#L248-L251

On Windows, we cannot create modules on the fly, the application is sitting in the `Program Files` which cannot be modified by the user. It ends in an `EPERM`.

**Comment by kittaakos** [comment]
This is an issue for the binary Theia (#4541)

**Comment by msujew** [comment]
Since we now offer the Theia IDE for download and we haven't heard anyone experience this issue, I'm closing this. It's probably quite outdated after mutliple Electron uplifts.
