### ISSUE TITLE
Reconnecting issues

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3224]
Steps to reproduce with **TS** (Java is below):

 - Close your browser.
 - Delete previous Theia settings: `rm -rf ~/.theia`. (I am not sure this is mandatory.)
 - Clone, build and start Theia's backend for the browser. (e619393d)
 - Set `theia` as your workspace root.
 - Open `os.ts` in Theia. Make sure your LS has started. You can verify with the CA.
 - Stop the backend.
 - Restart the backend.
 - You can see that something is already odd with the command registration.

```
yarn run start
yarn run v1.10.1
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 87960]
Server worker is ready to accept messages. [ID: 1 | PID: 87960]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"
root INFO [nsfw-watcher: 87961] Started watching: /Users/akos.kitta/git/theia/examples/browser/package.json
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.next","keybinding":"f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}
Error: "f7" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.prev","keybinding":"shift+f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}
Error: "shift+f7" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"pluginsView:toggle","keybinding":"ctrlcmd+shift+y"}  collided with  {"command":"debug:console:toggle","keybinding":"ctrlcmd+shift+y"}
root WARN Could not register keybinding:
  {"command":"pluginsView:toggle","keybinding":"ctrlcmd+shift+y"}
Error: "ctrlcmd+shift+y" is in collision with something else [scope:0]
root INFO [nsfw-watcher: 87974] Started watching: /Users/akos.kitta/Desktop/-1539695154767.log
root INFO [nsfw-watcher: 87974] Stopped watching: /Users/akos.kitta/Desktop/-1539695154767.log
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.next","keybinding":"f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}
Error: "f7" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.prev","keybinding":"shift+f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}
Error: "shift+f7" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"pluginsView:toggle","keybinding":"ctrlcmd+shift+y"}  collided with  {"command":"debug:console:toggle","keybinding":"ctrlcmd+shift+y"}
root WARN Could not register keybinding:
  {"command":"pluginsView:toggle","keybinding":"ctrlcmd+shift+y"}
Error: "ctrlcmd+shift+y" is in collision with something else [scope:0]
root INFO [nsfw-watcher: 87986] Started watching: /Users/akos.kitta/.theia
root INFO [nsfw-watcher: 87986] Started watching: /Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 87986] Started watching: /Users/akos.kitta/git/theia
task INFO Config file tasks.json does not exist under file:///Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 87986] Started watching: /Users/akos.kitta/git/theia/packages/core/src/browser/status-bar/index.ts
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
^C
Akoss-MacBook-Pro:browser akos.kitta$ yarn run start
yarn run v1.10.1
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 88028]
Server worker is ready to accept messages. [ID: 1 | PID: 88028]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"
root INFO [nsfw-watcher: 88030] Started watching: /Users/akos.kitta/git/theia/examples/browser/package.json
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO [nsfw-watcher: 88031] Started watching: /Users/akos.kitta/.theia
Started watching: /Users/akos.kitta/git/theia
Started watching: /Users/akos.kitta/git/theia
Started watching: /Users/akos.kitta/git/theia/packages/core/src/browser/status-bar/index.ts
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/theia
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 88058] Started watching: /Users/akos.kitta/.theia
Started watching: /Users/akos.kitta/git/theia
Started watching: /Users/akos.kitta/git/theia
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root INFO [nsfw-watcher: 88058] Started watching: /Users/akos.kitta/git/theia/packages/core/src/browser/status-bar/index.ts
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/theia
root INFO Started watching the git repository: file:///Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 88104] Started watching: /Users/akos.kitta/.theia
Started watching: /Users/akos.kitta/git/theia
root INFO [nsfw-watcher: 88104] Started watching: /Users/akos.kitta/git/theia
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root INFO [nsfw-watcher: 88104] Started watching: /Users/akos.kitta/git/theia/packages/core/src/browser/status-bar/index.ts
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
root WARN A command _typescript.applyWorkspaceEdit is already registered.
root WARN A command _typescript.applyCodeAction is already registered.
root WARN A command _typescript.applyRefactoring is already registered.
root WARN A command _typescript.organizeImports is already registered.
root WARN A command _typescript.applyRenameFile is already registered.
^C
```

----

Steps to reproduce with **Java** (TS is above):

 - Close your browser.
 - Delete previous Theia settings: `rm -rf ~/.theia`. (I am not sure this is mandatory.)
 - Clone, build and start Theia's backend for the browser. (e619393d)
 - Set [`eclipse.jdt.ls`](https://github.com/eclipse/eclipse.jdt.ls) as your workspace root.
 - Open `AbstractProjectImporter.java` in Theia. Make sure your LS has started. You can verify with the CA.
 - Stop the backend.
 - Restart the backend.
 - You can see how many times the Java LS has started after the backend restart.

```
yarn run start
yarn run v1.10.1
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 88629]
Server worker is ready to accept messages. [ID: 1 | PID: 88629]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"
root INFO [nsfw-watcher: 88630] Started watching: /Users/akos.kitta/git/theia/examples/browser/package.json
root INFO Started watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936536884/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936536928/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936536952/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936536967/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936536981/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936536998/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537012/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537025/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537039/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537052/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537065/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537078/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537090/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537102/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537114/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936537126/.metadata/.log
root INFO [nsfw-watcher: 88638] Started watching: /Users/akos.kitta/.theia
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 88638] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936548770/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936549200/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936549226/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936549640/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936549990/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936550342/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936550626/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936550979/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936551202/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936551524/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936551604/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936551818/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936551848/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936552194/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936552448/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936552715/.metadata/.log
root INFO Started watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 88706] Started watching: /Users/akos.kitta/.theia
root INFO [nsfw-watcher: 88706] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 88706] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 88706] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/AbstractProjectImporter.java
^C
Akoss-MacBook-Pro:browser akos.kitta$ yarn run start
yarn run v1.10.1
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 88880]
Server worker is ready to accept messages. [ID: 1 | PID: 88880]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"
root INFO [nsfw-watcher: 88881] Started watching: /Users/akos.kitta/git/theia/examples/browser/package.json
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682261/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682279/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682293/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682308/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682331/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682349/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682367/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682384/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682401/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682423/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682445/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682457/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682470/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682482/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682493/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682505/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682516/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682528/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682539/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682551/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682562/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682575/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682586/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682597/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682609/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682620/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682632/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682643/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682654/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682665/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682677/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936682689/.metadata/.log
root INFO Started watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO [nsfw-watcher: 88889] Started watching: /Users/akos.kitta/.theia
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO [nsfw-watcher: 88889] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO [nsfw-watcher: 88889] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
root INFO [nsfw-watcher: 88889] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/AbstractProjectImporter.java
^C
Akoss-MacBook-Pro:browser akos.kitta$
Akoss-MacBook-Pro:browser akos.kitta$
```

Finally, it ends up with the following error:
```
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936500478/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936500506/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936500617/.metadata/.log
root INFO Java: logs at /var/folders/k3/d2fkvv1j16v3_rz93k7f74180000gn/T/_ws_1539936500661/.metadata/.log
root INFO Started watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 88555] Started watching: /Users/akos.kitta/.theia
Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
Started watching: /Users/akos.kitta/git/eclipse.jdt.ls
root INFO [nsfw-watcher: 88555] Started watching: /Users/akos.kitta/git/eclipse.jdt.ls/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/AbstractProjectImporter.java
root INFO Stopped watching the git repository: file:///Users/akos.kitta/git/eclipse.jdt.ls
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: false == true
    at RoundRobinHandle.add (internal/cluster/round_robin_handle.js:34:3)
    at queryServer (internal/cluster/master.js:316:10)
    at Worker.onmessage (internal/cluster/master.js:248:5)
    at ChildProcess.onInternalMessage (internal/cluster/utils.js:42:8)
    at emitTwo (events.js:131:20)
    at ChildProcess.emit (events.js:214:7)
    at emit (internal/child_process.js:772:12)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
✨  Done in 19.78s.
```

Related issues: https://github.com/theia-ide/theia/issues/3150, https://github.com/theia-ide/theia/issues/3145, https://github.com/theia-ide/theia/pull/3148#issuecomment-428980689

**Comment by kittaakos** [comment]
I was unable to verify if the same happens when only the connection is lost between the client and the server. So no backend stop. I set `Offline` in Chrome > `Network`, but it is smart enough not to report offline in Theia. Any ideas how we can check this?

**Comment by akosyakov** [comment]
`Chrome` does not apply connection profiles to ws connections. One needs to use the system-level proxy to emulate connection issues, something lik https://www.charlesproxy.com/

**Comment by kittaakos** [comment]
Thanks, @akosyakov. I will try this and update the thread.

**Comment by kittaakos** [comment]
I will try with https://mitmproxy.org. It is open source.

**Comment by marcdumais-work** [comment]
> I was unable to verify if the same happens when only the connection is lost between the client and the server.

+1 on testing this properly. 

However from my experience with using a backend from the other side of the ocean, in a setup where the network is sometimes flaky, I do relatively often experience the client disconnecting, and it seems to reconnect without causing visible issues.
