### ISSUE TITLE
[electron][linux] The application crashes when setting a new workspace root

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3242]
Happens with ac580dd from the `master`.

Steps:
 - Clone and build the electron the application (`yarn --force && yarn run rebuild:electron`).
 - Make sure you do not have a workspace (`rm -rf ~/.theia/`).
 - Start the application and select a workspace.
 - Crash.

![screencast 2018-10-22 11-16-24](https://user-images.githubusercontent.com/1405703/47285788-84b12480-d5ec-11e8-8efc-63c076a2de7a.gif)

Full console log:
```
kittaakos@ubuntu:~/dev/theia/examples/electron$ rm -rf ~/.theia && git rev-parse --short HEAD && yarn run start
ac580dd
yarn run v1.9.4
$ theia start
ATTENTION: default value of option force_s3tc_enable overridden by environment.
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 66524]
Server worker is ready to accept messages. [ID: 1 | PID: 66524]
root INFO Theia app listening on http://localhost:38195.
Received message which is neither a response nor a notification message:
"38195"
root INFO [nsfw-watcher: 66538] Started watching: /home/kittaakos/dev/theia/examples/electron/package.json
root ERROR Cannot find a service for the path: /services/plugin-ext
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.next","keybinding":"f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.next","keybinding":"f7","context":"editorTextFocus"}
Error: "f7" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}  collided with  {"command":"monaco.editor.action.diffReview.prev","keybinding":"shift+f7","context":"editorTextFocus"}
root WARN Could not register keybinding:
  {"command":"monaco.editor.action.wordHighlight.prev","keybinding":"shift+f7","context":"editorTextFocus"}
Error: "shift+f7" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"pluginsView:toggle","keybinding":"ctrlcmd+shift+y"}  collided with  {"command":"debug:console:toggle","keybinding":"ctrlcmd+shift+y"}
root WARN Could not register keybinding:
  {"command":"pluginsView:toggle","keybinding":"ctrlcmd+shift+y"}
Error: "ctrlcmd+shift+y" is in collision with something else [scope:0]
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
root ERROR Request getDrives failed with error: Unexpected end of JSON input SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at parse (/home/kittaakos/dev/theia/node_modules/drivelist/lib/lsblk/json.js:106:25)
    at exec (/home/kittaakos/dev/theia/node_modules/drivelist/lib/lsblk/index.js:84:33)
    at ChildProcess.childProcess.spawn.on.on (/home/kittaakos/dev/theia/node_modules/drivelist/lib/exec.js:38:7)
    at emitTwo (events.js:125:13)
    at ChildProcess.emit (events.js:213:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
root ERROR Error when loading drives. Error: Request 'getDrives' failed
    at Proxy.<anonymous> (file:///home/kittaakos/dev/theia/examples/electron/lib/bundle.js:96185:33)
    at FileDialogModel.<anonymous> (file:///home/kittaakos/dev/theia/examples/electron/lib/2.bundle.js:1563:62)
    at step (file:///home/kittaakos/dev/theia/examples/electron/lib/2.bundle.js:1485:23)
    at Object.next (file:///home/kittaakos/dev/theia/examples/electron/lib/2.bundle.js:1466:53)
    at file:///home/kittaakos/dev/theia/examples/electron/lib/2.bundle.js:1460:71
    at Promise (<anonymous>)
    at push.../../packages/filesystem/lib/browser/file-tree/file-tree-model.js.__awaiter (file:///home/kittaakos/dev/theia/examples/electron/lib/2.bundle.js:1456:12)
    at FileDialogModel.push.../../packages/filesystem/lib/browser/file-tree/file-tree-model.js.FileTreeModel.drives (file:///home/kittaakos/dev/theia/examples/electron/lib/2.bundle.js:1557:16)
    at LocationListRenderer.push.../../packages/filesystem/lib/browser/location/location-renderer.js.LocationListRenderer.doLoadDrives (file:///home/kittaakos/dev/theia/examples/electron/lib/2.bundle.js:2479:26)
    at LocationListRenderer.push.../../packages/filesystem/lib/browser/location/location-renderer.js.LocationListRenderer.collectLocations (file:///home/kittaakos/dev/theia/examples/electron/lib/2.bundle.js:2470:14)
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
context mismatch in svga_sampler_view_destroy
Server worker has been disconnected. [ID: 1 | PID: 66524]
Server worker has been stopped. [ID: 1 | PID: 66524]
Done in 21.41s.
kittaakos@ubuntu:~/dev/theia/examples/electron$
```

From time to time, I can see the following error. This happens very rarely, and I am not sure if the error is related to the application crash.

```
root ERROR [nsfw-watcher: 53896] /home/kittaakos/dev/theia/node_modules/vscode-nsfw/lib/src/index.js:62
      throw nsfwError;
      ^
Service shutdown unexpectedly
root ERROR Request watchFileChanges failed with error: Connection is closed. Error: Connection is closed.
    at new ConnectionError (/home/kittaakos/dev/theia/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/home/kittaakos/dev/theia/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendRequest (/home/kittaakos/dev/theia/node_modules/vscode-jsonrpc/lib/main.js:715:13)
    at /home/kittaakos/dev/theia/packages/core/lib/common/messaging/proxy-factory.js:309:72
    at new Promise (<anonymous>)
    at /home/kittaakos/dev/theia/packages/core/lib/common/messaging/proxy-factory.js:302:24
    at <anonymous>
task INFO Config file tasks.json does not exist under file:///home/kittaakos/dev/theia/examples/electron
root ERROR Error: Request 'watchFileChanges' failed
    at Proxy.<anonymous> (file:///home/kittaakos/dev/theia/examples/electron/lib/bundle.js:96251:33)
    at ReconnectingFileSystemWatcherServer.push.../../packages/filesystem/lib/common/filesystem-watcher-protocol.js.ReconnectingFileSystemWatcherServer.doWatchFileChanges (file:///home/kittaakos/dev/theia/examples/electron/lib/0.bundle.js:384:27)
    at ReconnectingFileSystemWatcherServer.push.../../packages/filesystem/lib/common/filesystem-watcher-protocol.js.ReconnectingFileSystemWatcherServer.watchFileChanges (file:///home/kittaakos/dev/theia/examples/electron/lib/0.bundle.js:380:21)
    at file:///home/kittaakos/dev/theia/examples/electron/lib/0.bundle.js:207:33
    at <anonymous>
```

**Comment by marechal-p** [comment]
Maybe unrelated, but my Electron backend used to fail silently as well, that since at least May 2018.

I don't see the same error as you do, on my side it just says the following:

```
Server worker has been disconnected. [ID: 1 | PID: 26343]
Server worker has been stopped. [ID: 1 | PID: 26343]
Done in 20.40s.
```

I wonder how related these issues are.

**Comment by beeman** [comment]
We've been seeing this error frequently when running a customized version of Theia in a Docker container. The issue seems to have been fixed by increasing the number of `fs.inotify.max_user_watches` on the host that runs the containers.

Something like this:

```
echo fs.inotify.max_user_watches=65536 | sudo tee -a /etc/sysctl.conf
sudo sysctl -p
```

**Comment by vince-fugnitto** [comment]
@thegecko @kittaakos I tested it again with the recent updates and it seems to be working correctly now most likely thanks to both the electron version bump and the removal of the cluster mode. It might be good to re-test and confirm if it's still an issue.

Tested with b0aaeca and Ubuntu 16.04.

**Comment by vince-fugnitto** [comment]
Closing since it is no longer seems to be an issue.
The issue can be re-opened if the problem ever returns.
