### ISSUE TITLE
not all mocha tests are running in some situations

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#329]
If I take PR #278  and run from theia's root directory: 

```
yarn run test
```

I get:
```
@theia/gdb:   GDBProbe
@theia/gdb: Undefined command: "new-ui".  Try "help".
@theia/gdb:     ✓ test for GDB new-ui support (129ms)
@theia/gdb:   1 passing (139ms)
```

However if I run:
```
cd packages/gdb
../../node_modules/.bin/mocha --opts ../mocha.opts src/**/*.spec.ts
```
I get:

```
....
  36 passing (430ms)
```

Note that in the same directory doing
```
yarn run tset
```

I get only 1 test also...  This wasn't the case in my previous testing but for some reason it is now... strange

Note for this to work properly you need to  install GDB on your path, (apt-get install gdb)

@kittaakos  ts-node could be to blame?

**Comment by kittaakos** [comment]
@hexa00, I have tried it out on the `master` branch and works as expected. Please note, I was running test in `theia/core`. I have attached the [console output](https://github.com/theia-ide/theia/files/1176447/GH_329_mocha_test_console_output.txt) which I got when I executed the tests from VSCode. Could you please check your test setup on your branch? It might have the problem, or I messed up something while I was verifying the issue. Either way, I will re-assign the ticket to you. If the defect still present, let us know, otherwise, please close this ticket. Thanks!

Relevant parts from the console output is here:
```
Akoss-MBP:theia akos.kitta$ pwd
/Users/akos.kitta/git/theia
Akoss-MBP:theia akos.kitta$ yarn run test
yarn run v0.27.5
$ yarn run test:theia && yarn run test:electron && yarn run test:browser
lerna info version 2.0.0

...

@theia/core:     ✓ from c:
@theia/core:     ✓ from /c:
@theia/core:     ✓ from /c:/
@theia/core:   42 passing (60ms)

...

Akoss-MBP:theia akos.kitta$ cd  packages/core/
Akoss-MBP:core akos.kitta$ ls
compile.tsconfig.json   coverage                extension.package.json  lib                     node_modules            package.json            src
Akoss-MBP:core akos.kitta$ ../../node_modules/.bin/mocha --opts ../mocha.opts src/**/*.spec.ts

...

   ✓ from /c:/


  42 passing (65ms)

...

Akoss-MBP:core akos.kitta$ yarn run test
yarn run v0.27.5
$ nyc mocha --opts ../mocha.opts src/**/*.spec.ts

...

  42 passing (76ms)

Done in 2.70s.
Akoss-MBP:core akos.kitta$
```

**Comment by hexa00** [comment]
@kittaakos yes master is ok, the problem has something to do with where the tests are placed in the directory structure and on master somehow it's ok...

You need ot test with my branch to reproduce it

**Comment by kittaakos** [comment]
@hexa00, all right, I give it a try on your branch.

**Comment by kittaakos** [comment]
I did the followings but it failed:
```
git clone https://github.com/hexa00/theia.git \
&& cd theia \
&& git checkout origin/gdb-console -b gdb-console \
&& npm install --unsafe-perm \
&& cd examples/browser \
&& npm run start
```

I had the below error:
```
npm ERR! missing script: start
```

Did I mess up something or your branch is not up to date. If the latter one, please update, ping me, and I try it out once more. Thanks!

**Comment by akosyakov** [comment]
Should be `yarn`?

**Comment by kittaakos** [comment]
Good point, but if it is yarn, that would mean your documentation related changes are already in that branch too, right? Let's wait for the update from @hexa00.

**Comment by hexa00** [comment]
The branch was rebased on the 21 of July so yarn is there... not sure about all the doc

**Comment by hexa00** [comment]
@kittaakos I just noticed you cloned but did not switch branch...
You need to use branch: gdb-console

**Comment by kittaakos** [comment]
> && git checkout origin/gdb-console -b gdb-console \

@hexa00, could you double check [here](https://github.com/theia-ide/theia/issues/329#issuecomment-318284529)? I must be blind.

**Comment by hexa00** [comment]
@kittaakos use yarn

**Comment by kittaakos** [comment]
I have tried it out again, but the tests are failing:
```
@theia/gdb:   GDBProbe
@theia/gdb:     1) test for GDB new-ui support
@theia/gdb:   0 passing (25ms)
@theia/gdb:   1 failing
@theia/gdb:   1) GDBProbe test for GDB new-ui support:
@theia/gdb:      Uncaught Error: spawn gdb ENOENT
@theia/gdb:       at exports._errnoException (util.js:1018:11)
@theia/gdb:       at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
@theia/gdb:       at onErrorNT (internal/child_process.js:367:16)
@theia/gdb:       at _combinedTickCallback (internal/process/next_tick.js:80:11)
@theia/gdb:       at process._tickCallback (internal/process/next_tick.js:104:9)
@theia/gdb: npm ERR! Darwin 16.6.0
@theia/gdb: npm ERR! argv "/Users/akos.kitta/.nvm/versions/node/v6.10.3/bin/node" "/Users/akos.kitta/.nvm/versions/node/v6.10.3/bin/npm" "run" "test"
@theia/gdb: npm ERR! node v6.10.3
@theia/gdb: npm ERR! npm  v3.10.10
@theia/gdb: npm ERR! code ELIFECYCLE
@theia/gdb: npm ERR! @theia/gdb@0.0.1-alpha.1 test: `nyc mocha --opts ../mocha.opts src/**/*.spec.ts`
@theia/gdb: npm ERR! Exit status 1
@theia/gdb: npm ERR! 
@theia/gdb: npm ERR! Failed at the @theia/gdb@0.0.1-alpha.1 test script 'nyc mocha --opts ../mocha.opts src/**/*.spec.ts'.
@theia/gdb: npm ERR! Make sure you have the latest version of node.js and npm installed.
@theia/gdb: npm ERR! If you do, this is most likely a problem with the @theia/gdb package,
@theia/gdb: npm ERR! not with npm itself.
@theia/gdb: npm ERR! Tell the author that this fails on your system:
@theia/gdb: npm ERR!     nyc mocha --opts ../mocha.opts src/**/*.spec.ts
@theia/gdb: npm ERR! You can get information on how to open an issue for this project with:
@theia/gdb: npm ERR!     npm bugs @theia/gdb
@theia/gdb: npm ERR! Or if that isn't available, you can get their info via:
@theia/gdb: npm ERR!     npm owner ls @theia/gdb
@theia/gdb: npm ERR! There is likely additional logging output above.
@theia/gdb: npm ERR! Please include the following file with any support request:
@theia/gdb: npm ERR!     /Users/akos.kitta/Desktop/baz/theia/packages/gdb/npm-debug.log
lerna ERR! execute Error: Command failed: npm run test
lerna ERR! execute 
lerna ERR! execute npm ERR! Darwin 16.6.0
lerna ERR! execute npm ERR! argv "/Users/akos.kitta/.nvm/versions/node/v6.10.3/bin/node" "/Users/akos.kitta/.nvm/versions/node/v6.10.3/bin/npm" "run" "test"
lerna ERR! execute npm ERR! node v6.10.3
lerna ERR! execute npm ERR! npm  v3.10.10
lerna ERR! execute npm ERR! code ELIFECYCLE
lerna ERR! execute npm ERR! @theia/gdb@0.0.1-alpha.1 test: `nyc mocha --opts ../mocha.opts src/**/*.spec.ts`
lerna ERR! execute npm ERR! Exit status 1
lerna ERR! execute npm ERR! 
lerna ERR! execute npm ERR! Failed at the @theia/gdb@0.0.1-alpha.1 test script 'nyc mocha --opts ../mocha.opts src/**/*.spec.ts'.
lerna ERR! execute npm ERR! Make sure you have the latest version of node.js and npm installed.
lerna ERR! execute npm ERR! If you do, this is most likely a problem with the @theia/gdb package,
lerna ERR! execute npm ERR! not with npm itself.
lerna ERR! execute npm ERR! Tell the author that this fails on your system:
lerna ERR! execute npm ERR!     nyc mocha --opts ../mocha.opts src/**/*.spec.ts
lerna ERR! execute npm ERR! You can get information on how to open an issue for this project with:
lerna ERR! execute npm ERR!     npm bugs @theia/gdb
lerna ERR! execute npm ERR! Or if that isn't available, you can get their info via:
lerna ERR! execute npm ERR!     npm owner ls @theia/gdb
lerna ERR! execute npm ERR! There is likely additional logging output above.
lerna ERR! execute 
lerna ERR! execute npm ERR! Please include the following file with any support request:
lerna ERR! execute npm ERR!     /Users/akos.kitta/Desktop/baz/theia/packages/gdb/npm-debug.log
lerna ERR! execute 
lerna ERR! execute > @theia/gdb@0.0.1-alpha.1 test /Users/akos.kitta/Desktop/baz/theia/packages/gdb
lerna ERR! execute > nyc mocha --opts ../mocha.opts src/**/*.spec.ts
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute   GDBProbe
lerna ERR! execute     1) test for GDB new-ui support
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute   0 passing (25ms)
lerna ERR! execute   1 failing
lerna ERR! execute 
lerna ERR! execute   1) GDBProbe test for GDB new-ui support:
lerna ERR! execute      Uncaught Error: spawn gdb ENOENT
lerna ERR! execute       at exports._errnoException (util.js:1018:11)
lerna ERR! execute       at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
lerna ERR! execute       at onErrorNT (internal/child_process.js:367:16)
lerna ERR! execute       at _combinedTickCallback (internal/process/next_tick.js:80:11)
lerna ERR! execute       at process._tickCallback (internal/process/next_tick.js:104:9)
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute     at Promise.all.then.arr (/Users/akos.kitta/Desktop/baz/theia/node_modules/lerna/node_modules/execa/index.js:210:11)
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:109:7)
lerna ERR! execute  callback with error
lerna ERR! execute  { Error: Command failed: npm run test
lerna ERR! execute 
lerna ERR! execute npm ERR! Darwin 16.6.0
lerna ERR! execute npm ERR! argv "/Users/akos.kitta/.nvm/versions/node/v6.10.3/bin/node" "/Users/akos.kitta/.nvm/versions/node/v6.10.3/bin/npm" "run" "test"
lerna ERR! execute npm ERR! node v6.10.3
lerna ERR! execute npm ERR! npm  v3.10.10
lerna ERR! execute npm ERR! code ELIFECYCLE
lerna ERR! execute npm ERR! @theia/gdb@0.0.1-alpha.1 test: `nyc mocha --opts ../mocha.opts src/**/*.spec.ts`
lerna ERR! execute npm ERR! Exit status 1
lerna ERR! execute npm ERR! 
lerna ERR! execute npm ERR! Failed at the @theia/gdb@0.0.1-alpha.1 test script 'nyc mocha --opts ../mocha.opts src/**/*.spec.ts'.
lerna ERR! execute npm ERR! Make sure you have the latest version of node.js and npm installed.
lerna ERR! execute npm ERR! If you do, this is most likely a problem with the @theia/gdb package,
lerna ERR! execute npm ERR! not with npm itself.
lerna ERR! execute npm ERR! Tell the author that this fails on your system:
lerna ERR! execute npm ERR!     nyc mocha --opts ../mocha.opts src/**/*.spec.ts
lerna ERR! execute npm ERR! You can get information on how to open an issue for this project with:
lerna ERR! execute npm ERR!     npm bugs @theia/gdb
lerna ERR! execute npm ERR! Or if that isn't available, you can get their info via:
lerna ERR! execute npm ERR!     npm owner ls @theia/gdb
lerna ERR! execute npm ERR! There is likely additional logging output above.
lerna ERR! execute 
lerna ERR! execute npm ERR! Please include the following file with any support request:
lerna ERR! execute npm ERR!     /Users/akos.kitta/Desktop/baz/theia/packages/gdb/npm-debug.log
lerna ERR! execute 
lerna ERR! execute > @theia/gdb@0.0.1-alpha.1 test /Users/akos.kitta/Desktop/baz/theia/packages/gdb
lerna ERR! execute > nyc mocha --opts ../mocha.opts src/**/*.spec.ts
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute   GDBProbe
lerna ERR! execute     1) test for GDB new-ui support
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute   0 passing (25ms)
lerna ERR! execute   1 failing
lerna ERR! execute 
lerna ERR! execute   1) GDBProbe test for GDB new-ui support:
lerna ERR! execute      Uncaught Error: spawn gdb ENOENT
lerna ERR! execute       at exports._errnoException (util.js:1018:11)
lerna ERR! execute       at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
lerna ERR! execute       at onErrorNT (internal/child_process.js:367:16)
lerna ERR! execute       at _combinedTickCallback (internal/process/next_tick.js:80:11)
lerna ERR! execute       at process._tickCallback (internal/process/next_tick.js:104:9)
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute     at Promise.all.then.arr (/Users/akos.kitta/Desktop/baz/theia/node_modules/lerna/node_modules/execa/index.js:210:11)
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:109:7)
lerna ERR! execute   stack: 'Error: Command failed: npm run test\n\nnpm ERR! Darwin 16.6.0\nnpm ERR! argv "/Users/akos.kitta/.nvm/versions/node/v6.10.3/bin/node" "/Users/akos.kitta/.nvm/versions/node/v6.10.3/bin/npm" "run" "test"\nnpm ERR! node v6.10.3\nnpm ERR! npm  v3.10.10\nnpm ERR! code ELIFECYCLE\nnpm ERR! @theia/gdb@0.0.1-alpha.1 test: `nyc mocha --opts ../mocha.opts src/**/*.spec.ts`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @theia/gdb@0.0.1-alpha.1 test script \'nyc mocha --opts ../mocha.opts src/**/*.spec.ts\'.\nnpm ERR! Make sure you have the latest version of node.js and npm installed.\nnpm ERR! If you do, this is most likely a problem with the @theia/gdb package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     nyc mocha --opts ../mocha.opts src/**/*.spec.ts\nnpm ERR! You can get information on how to open an issue for this project with:\nnpm ERR!     npm bugs @theia/gdb\nnpm ERR! Or if that isn\'t available, you can get their info via:\nnpm ERR!     npm owner ls @theia/gdb\nnpm ERR! There is likely additional logging output above.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /Users/akos.kitta/Desktop/baz/theia/packages/gdb/npm-debug.log\n\n> @theia/gdb@0.0.1-alpha.1 test /Users/akos.kitta/Desktop/baz/theia/packages/gdb\n> nyc mocha --opts ../mocha.opts src/**/*.spec.ts\n\n\n\n  GDBProbe\n    1) test for GDB new-ui support\n\n\n  0 passing (25ms)\n  1 failing\n\n  1) GDBProbe test for GDB new-ui support:\n     Uncaught Error: spawn gdb ENOENT\n      at exports._errnoException (util.js:1018:11)\n      at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)\n      at onErrorNT (internal/child_process.js:367:16)\n      at _combinedTickCallback (internal/process/next_tick.js:80:11)\n      at process._tickCallback (internal/process/next_tick.js:104:9)\n\n\n\n\n    at Promise.all.then.arr (/Users/akos.kitta/Desktop/baz/theia/node_modules/lerna/node_modules/execa/index.js:210:11)\n    at process._tickCallback (internal/process/next_tick.js:109:7)',
lerna ERR! execute   code: 1,
lerna ERR! execute   killed: false,
lerna ERR! execute   stdout: '\n> @theia/gdb@0.0.1-alpha.1 test /Users/akos.kitta/Desktop/baz/theia/packages/gdb\n> nyc mocha --opts ../mocha.opts src/**/*.spec.ts\n\n\n\n  GDBProbe\n    1) test for GDB new-ui support\n\n\n  0 passing (25ms)\n  1 failing\n\n  1) GDBProbe test for GDB new-ui support:\n     Uncaught Error: spawn gdb ENOENT\n      at exports._errnoException (util.js:1018:11)\n      at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)\n      at onErrorNT (internal/child_process.js:367:16)\n      at _combinedTickCallback (internal/process/next_tick.js:80:11)\n      at process._tickCallback (internal/process/next_tick.js:104:9)\n\n\n\n',
lerna ERR! execute   stderr: '\nnpm ERR! Darwin 16.6.0\nnpm ERR! argv "/Users/akos.kitta/.nvm/versions/node/v6.10.3/bin/node" "/Users/akos.kitta/.nvm/versions/node/v6.10.3/bin/npm" "run" "test"\nnpm ERR! node v6.10.3\nnpm ERR! npm  v3.10.10\nnpm ERR! code ELIFECYCLE\nnpm ERR! @theia/gdb@0.0.1-alpha.1 test: `nyc mocha --opts ../mocha.opts src/**/*.spec.ts`\nnpm ERR! Exit status 1\nnpm ERR! \nnpm ERR! Failed at the @theia/gdb@0.0.1-alpha.1 test script \'nyc mocha --opts ../mocha.opts src/**/*.spec.ts\'.\nnpm ERR! Make sure you have the latest version of node.js and npm installed.\nnpm ERR! If you do, this is most likely a problem with the @theia/gdb package,\nnpm ERR! not with npm itself.\nnpm ERR! Tell the author that this fails on your system:\nnpm ERR!     nyc mocha --opts ../mocha.opts src/**/*.spec.ts\nnpm ERR! You can get information on how to open an issue for this project with:\nnpm ERR!     npm bugs @theia/gdb\nnpm ERR! Or if that isn\'t available, you can get their info via:\nnpm ERR!     npm owner ls @theia/gdb\nnpm ERR! There is likely additional logging output above.\n\nnpm ERR! Please include the following file with any support request:\nnpm ERR!     /Users/akos.kitta/Desktop/baz/theia/packages/gdb/npm-debug.log\n',
lerna ERR! execute   failed: true,
lerna ERR! execute   signal: null,
lerna ERR! execute   cmd: 'npm run test',
lerna ERR! execute   timedOut: false }
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
(node:92542) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Command failed: npm run test

npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/akos.kitta/.nvm/versions/node/v6.10.3/bin/node" "/Users/akos.kitta/.nvm/versions/node/v6.10.3/bin/npm" "run" "test"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! @theia/gdb@0.0.1-alpha.1 test: `nyc mocha --opts ../mocha.opts src/**/*.spec.ts`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @theia/gdb@0.0.1-alpha.1 test script 'nyc mocha --opts ../mocha.opts src/**/*.spec.ts'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @theia/gdb package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nyc mocha --opts ../mocha.opts src/**/*.spec.ts
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @theia/gdb
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @theia/gdb
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/akos.kitta/Desktop/baz/theia/packages/gdb/npm-debug.log

> @theia/gdb@0.0.1-alpha.1 test /Users/akos.kitta/Desktop/baz/theia/packages/gdb
> nyc mocha --opts ../mocha.opts src/**/*.spec.ts



  GDBProbe
    1) test for GDB new-ui support


  0 passing (25ms)
  1 failing

  1) GDBProbe test for GDB new-ui support:
     Uncaught Error: spawn gdb ENOENT
      at exports._errnoException (util.js:1018:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
      at onErrorNT (internal/child_process.js:367:16)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)

```

**Comment by kittaakos** [comment]
I have installed it with `yarn`, it worked fine. Then I called `yarn run test` in the root.

**Comment by kittaakos** [comment]
Although that single test is failing, for me only one single test is being executed:
```
Akoss-MBP:theia akos.kitta$ cd packages/gdb/
Akoss-MBP:gdb akos.kitta$ ../../node_modules/.bin/mocha --opts ../mocha.opts src/**/*.spec.ts


  GDBProbe
    1) test for GDB new-ui support


  0 passing (23ms)
  1 failing

  1) GDBProbe test for GDB new-ui support:
     Uncaught Error: spawn gdb ENOENT
      at exports._errnoException (util.js:1018:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
      at onErrorNT (internal/child_process.js:367:16)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)



Akoss-MBP:gdb akos.kitta$ yarn run test
yarn run v0.27.5
$ nyc mocha --opts ../mocha.opts src/**/*.spec.ts


  GDBProbe
    1) test for GDB new-ui support


  0 passing (25ms)
  1 failing

  1) GDBProbe test for GDB new-ui support:
     Uncaught Error: spawn gdb ENOENT
      at exports._errnoException (util.js:1018:11)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
      at onErrorNT (internal/child_process.js:367:16)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)



error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Akoss-MBP:gdb akos.kitta$
```

**Comment by hexa00** [comment]
Yes that is the problem you will see there's other *spec.ts in the gdb directory...

These tests should run but do not.
```
find . -iname "*spec.ts"
./src/node/mi/mi-interpreter.spec.ts
./src/node/mi/mi-parser.spec.ts
./src/node/mi/mi-output-parser.spec.ts
./src/node/mi/mi-debugger.spec.ts
./src/node/gdb-probe.spec.ts
```

**Comment by kittaakos** [comment]
OK, got it finally. Let me check.

**Comment by kittaakos** [comment]
It's a bug. I will take care of it.

**Comment by kittaakos** [comment]
PR: #383.
