### ISSUE TITLE
Error: Request 'resolveContent' failed when `launch.json` does not exist in the workspace

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3367]
```
application-error.ts:61 Uncaught (in promise) Error: Request 'resolveContent' failed
    at Proxy.<anonymous> (http://localhost:3000/bundle.js:96159:33)
    at FileResource.<anonymous> (http://localhost:3000/3.bundle.js:143:62)
    at step (http://localhost:3000/3.bundle.js:77:23)
    at Object.next (http://localhost:3000/3.bundle.js:58:53)
    at http://localhost:3000/3.bundle.js:52:71
    at new Promise (<anonymous>)
    at push.../../packages/filesystem/lib/browser/file-resource.js.__awaiter (http://localhost:3000/3.bundle.js:48:12)
    at FileResource.push.../../packages/filesystem/lib/browser/file-resource.js.FileResource.readContents (http://localhost:3000/3.bundle.js:137:16)
    at new MonacoEditorModel (http://localhost:3000/19.bundle.js:127:38)
    at MonacoTextModelService.<anonymous> (http://localhost:3000/19.bundle.js:582:47)
Caused by: Error: 'file:///Users/akos.kitta/git/eclipse.jdt.ls/.theia/launch.json' has not been found.
    at FileSystemNode.<anonymous> (/Users/akos.kitta/git/theia/packages/filesystem/lib/node/node-filesystem.js:159:64)
    at step (/Users/akos.kitta/git/theia/packages/filesystem/lib/node/node-filesystem.js:59:23)
    at Object.next (/Users/akos.kitta/git/theia/packages/filesystem/lib/node/node-filesystem.js:40:53)
    at fulfilled (/Users/akos.kitta/git/theia/packages/filesystem/lib/node/node-filesystem.js:31:58)
    at <anonymous>
```

**Comment by akosyakov** [comment]
Can you reproduce it with https://github.com/theia-ide/theia/pull/3366?

**Comment by kittaakos** [comment]
Checking...

**Comment by kittaakos** [comment]
No, it works nicely. I will update the PR, so this issue will be closed automatically when the PR is merged.
