### ISSUE TITLE
[UI tests] browser tests fail

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#337]
```javascript
lerna info version 2.0.0
lerna info versioning independent
lerna info scope @theia/example-browser
lerna ERR! test Errored while running script in '@theia/example-browser'
lerna ERR! execute Error: Command failed: npm run test
lerna ERR! execute A service failed in the 'onPrepare' hook
lerna ERR! execute Error: Could not download https://github.com/mozilla/geckodriver/releases/download/v0.16.1/geckodriver-v0.16.1-linux64.tar.gz: Error: read ECONNRESET
lerna ERR! execute     at Request.<anonymous> (/opt/ericsson-dev/theia/node_modules/selenium-standalone/lib/install.js:378:12)
lerna ERR! execute     at Object.onceWrapper (events.js:293:19)
lerna ERR! execute     at emitOne (events.js:96:13)
lerna ERR! execute     at Request.emit (events.js:191:7)
lerna ERR! execute     at Request.onRequestError (/opt/ericsson-dev/theia/node_modules/selenium-standalone/node_modules/request/request.js:845:8)
lerna ERR! execute     at emitOne (events.js:96:13)
lerna ERR! execute     at ClientRequest.emit (events.js:191:7)
lerna ERR! execute     at TLSSocket.socketErrorListener (_http_client.js:358:9)
lerna ERR! execute     at emitOne (events.js:96:13)
lerna ERR! execute     at TLSSocket.emit (events.js:191:7)
lerna ERR! execute 
lerna ERR! execute Continue...
```

It looks-like it's attempting to download version 0.16.1 of geckodriver. When I try the URL in chrome, it triggers a security warning, about the site being potentially used for phishing: 

![image](https://user-images.githubusercontent.com/25749063/28569216-fa15acce-7106-11e7-9a34-56e255a4a6de.png)

**Comment by marcdumais-work** [comment]
Already reported for selenium-standalone: https://github.com/vvo/selenium-standalone/issues/291

**Comment by marcdumais-work** [comment]
This seems to work now.
