### ISSUE TITLE
[electron][menu] Missing `File` menu

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3429]
From the `master` with a9cf7d8d19d3218a85373adbc2e0c1d1dbddef1c.

```
$ rm -rf ~/.theia/ && git rev-parse HEAD && yarn --cwd ./examples/electron/ start
a9cf7d8d19d3218a85373adbc2e0c1d1dbddef1c
yarn run v1.10.1
$ theia start
Starting the master backend process with 5000 (ms) timeout.
```

```
root ERROR Could not start contribution Error: Unknown command with ID: workspace:openRecent.
    at _loop_1 (file:///Users/akos.kitta/git/theia/examples/electron/lib/39.bundle.js:220:27)
    at ElectronMainMenuFactory.push.../../packages/core/lib/electron-browser/menu/electron-main-menu-factory.js.ElectronMainMenuFactory.fillMenuTemplate (file:///Users/akos.kitta/git/theia/examples/electron/lib/39.bundle.js:248:17)
    at _loop_1 (file:///Users/akos.kitta/git/theia/examples/electron/lib/39.bundle.js:213:28)
    at ElectronMainMenuFactory.push.../../packages/core/lib/electron-browser/menu/electron-main-menu-factory.js.ElectronMainMenuFactory.fillMenuTemplate (file:///Users/akos.kitta/git/theia/examples/electron/lib/39.bundle.js:248:17)
    at _loop_1 (file:///Users/akos.kitta/git/theia/examples/electron/lib/39.bundle.js:201:41)
    at ElectronMainMenuFactory.push.../../packages/core/lib/electron-browser/menu/electron-main-menu-factory.js.ElectronMainMenuFactory.fillMenuTemplate (file:///Users/akos.kitta/git/theia/examples/electron/lib/39.bundle.js:248:17)
    at ElectronMainMenuFactory.push.../../packages/core/lib/electron-browser/menu/electron-main-menu-factory.js.ElectronMainMenuFactory.createMenuBar (file:///Users/akos.kitta/git/theia/examples/electron/lib/39.bundle.js:179:29)
    at ElectronMenuContribution.push.../../packages/core/lib/electron-browser/menu/electron-menu-contribution.js.ElectronMenuContribution.onStart (file:///Users/akos.kitta/git/theia/examples/electron/lib/39.bundle.js:500:43)
    at file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:75234:155
    at FrontendApplication.<anonymous> (file:///Users/akos.kitta/git/theia/examples/electron/lib/bundle.js:75313:46)
```

**Comment by kittaakos** [comment]
Duplicate of #3428.
