### ISSUE TITLE
[theia] JavaScript heap out of memory

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#3477]
**JavaScript heap out of memory**

**scenario:**
1- start the server + open a workspace in the web browser. Ex my workspace has the following:
   ├── node_modules
   └── package.json
2- refresh the browser , wait the workspace is available in the browser
3- Do it ~ 10-12 times
==> You will get the following crash on the server side:

Security context: 0x3470a11a5879 <JSObject>
    1: fromString(aka fromString) [buffer.js:314] [bytecode=0x235c4be3ce29 offset=164](this=0xf49792822d1 <undefined>,string=0x3a28f5506561 <Very long string[677034716]>,encoding=0x3470a11b4dc1 <String[4]: utf8>)
    2: from [buffer.js:177] [bytecode=0x235c4be3c931 offset=11](this=0x645b13ae749 <JSFunction Buffer (sfi = 0x3470a11fd4e1)>,value=0x3a28f5506561 <Very long string[677034716]>,encoding...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
 2: 0x8cbf4c [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
 5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
 7: v8::internal::String::Flatten(v8::internal::Handle<v8::internal::String>, v8::internal::PretenureFlag) [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
 8: v8::String::WriteUtf8(char*, int, int*, int) const [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
 9: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
10: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
11: 0x8e8404 [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
12: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
13: 0xb0bbec [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
14: v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [/home/lmcbout/.nvm/versions/node/v8.12.0/bin/node]
15: 0x38be269842fd
Server worker has been disconnected. [ID: 1 | PID: 20004]
Server worker has been stopped. [ID: 1 | PID: 20004]
Done in 490.40s.

**Comment by lmcbout** [comment]
I found two links about it:
see: https://stackoverflow.com/questions/38558989/node-js-heap-out-of-memory
see: https://github.com/nodejs/node/issues/14402

If I repeat the scenario above,~10-12 times to refresh the browser but having the following options when starting the server node:

**node --max-old-space-size=8192 --max_old_space_size=8192 src-gen/backend/main.js**

Theia server is not reporting "Java Heap out of memory", but I get some error like "Connection got disposed" and after ~5-10 minutes", the client on the browser comes back .

root ERROR Error: Connection got disposed.
    at Object.dispose (http://localhost:3000/bundle.js:74741:25)
    at http://localhost:3000/bundle.js:76517:56
    at CallbackList.../../node_modules/vscode-jsonrpc/lib/events.js.CallbackList.invoke (http://localhost:3000/bundle.js:73484:39)
    at Emitter.../../node_modules/vscode-jsonrpc/lib/events.js.Emitter.fire (http://localhost:3000/bundle.js:73548:36)
    at closeHandler (http://localhost:3000/bundle.js:74137:26)
    at CallbackList.../../node_modules/vscode-jsonrpc/lib/events.js.CallbackList.invoke (http://localhost:3000/bundle.js:73484:39)
    at Emitter.../../node_modules/vscode-jsonrpc/lib/events.js.Emitter.fire (http://localhost:3000/bundle.js:73548:36)
    at WebSocketMessageReader.../../node_modules/vscode-jsonrpc/lib/messageReader.js.AbstractMessageReader.fireClose (http://localhost:3000/bundle.js:74936:27)
    at WebSocketMessageReader.../../node_modules/vscode-ws-jsonrpc/lib/socket/reader.js.WebSocketMessageReader.fireClose (http://localhost:3000/bundle.js:76635:40)
    at http://localhost:3000/bundle.js:76591:19

**Comment by lmcbout** [comment]
@vitaliy-guliy I just watch your video and this is the same issue

**Comment by vitaliy-guliy** [comment]
@lmcbout I was afraid I broke Theia when developing back-end plugin. The plugin become not working after refreshing the browser 3-4 times but part of Theia was still alive.

**Comment by marcdumais-work** [comment]
A couple of things I noticed: I was able to reproduce easily, without even setting a workspace. Just start a B-E, connect with a client, and restart the client 5-10 times.

**Comment by akosyakov** [comment]
It would be nice if one can dive into it, profile and measure there CPU get lost, how busy GC, what is leaking and so on.

**Comment by lmcbout** [comment]
@akosyakov 
I trace back when the problem occurs. The commit when we starts seeing this issue:

commit badbe15f3146f54b208123bb96aaebbb739062d1
Author: Anton Kosyakov <anton.kosyakov@typefox.io>
Date:   Mon Nov 5 16:17:58 2018 +0000

    use both node & node2 debug types
    
    Signed-off-by: Anton Kosyakov <anton.kosyakov@typefox.io>

**Comment by daisuke-yoshimoto** [comment]
@akosyakov 
This issue seems to be reproduced in the latest version (v0.5.0). In v0.4.0, it does not reproduce.

**Comment by akosyakov** [comment]
@daisuke-yoshimoto Could you give a hint how to reproduce on master?

**Comment by daisuke-yoshimoto** [comment]
@akosyakov I'm sorry that I didn't have enough information. I will provide a project to reproduce.

**Comment by daisuke-yoshimoto** [comment]
@akosyakov 
Sorry. It does not seem to be a problem with memory leaks. I could avoid it by setting the heap size below.
`ENV NODE_OPTIONS=$NODE_OPTIONS--max-old-space-size=2098`

**Comment by akosyakov** [comment]
@daisuke-yoshimoto avoid or postpone? You can start the backend in inspect mode and use chrome to measure heap growth. Just don't forget to collect garbage before taking the snapshot. If something is leaking you will see that more memory is accumulating after you do the same action and collect garbage over and over.
