### ISSUE TITLE
[cli] Cannot start browser application after starting the electron

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3521]
Steps to reproduce:
  1. `yarn && yarn run rebuild:electron`
  2. `yarn --cwd ./examples/electron start`
  3. `yarn run rebuild:browser`
  4. `yarn --cwd ./examples/browser start`

----

 1: `yarn && yarn run rebuild:electron`:
```
kittaakos@DESKTOP-VJRAMKC MINGW64 ~/dev/theia (mp/startup-window-title)
$ yarn && yarn run rebuild:electron
yarn install v1.10.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...

[...]

lerna success - @theia/example-electron
Done in 506.04s.
Done in 535.30s.
yarn run v1.10.1
$ theia rebuild:electron
Processing node-pty
Processing vscode-nsfw
Processing find-git-repositories
Done in 6.64s.
```

 2: `yarn --cwd ./examples/electron/ start`:
```
kittaakos@DESKTOP-VJRAMKC MINGW64 ~/dev/theia (mp/startup-window-title)
$ yarn --cwd ./examples/electron/ start
yarn run v1.10.1
$ theia start

Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 6520]
Server worker is ready to accept messages. [ID: 1 | PID: 6520]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"

[...]

root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1.windows.2'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1.windows.2'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1.windows.2'.
root INFO Stopped watching the git repository: file:///c%3A/Users/kittaakos/dev/theia
Done in 23.06s.
```

 3: `yarn run rebuild:browser`:
```
kittaakos@DESKTOP-VJRAMKC MINGW64 ~/dev/theia (mp/startup-window-title)
$ yarn run rebuild:browser
yarn run v1.10.1
$ theia rebuild:browser
Reverting find-git-repositories
Reverting node-pty
Reverting vscode-nsfw
Done in 1.38s.
```

 4: `yarn --cwd ./examples/browser/ start`:
```
kittaakos@DESKTOP-VJRAMKC MINGW64 ~/dev/theia (mp/startup-window-title)
$ yarn --cwd ./examples/browser/ start
yarn run v1.10.1
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 4484]
C:\Users\kittaakos\dev\theia\packages\core\lib\node\cluster\main.js:59
    throw reason;
    ^

Error: The specified module could not be found.
\\?\C:\Users\kittaakos\dev\theia\node_modules\vscode-nsfw\build\Release\nsfw.node
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\kittaakos\dev\theia\node_modules\vscode-nsfw\lib\src\index.js:3:16)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
Server worker has been disconnected. [ID: 1 | PID: 4484]
Server worker failed to start within 5000 milliseconds.
Pass a greater value as '--startup-timeout' option to increase the timeout or a negative to disable.
Done in 1.49s.

kittaakos@DESKTOP-VJRAMKC MINGW64 ~/dev/theia (mp/startup-window-title)
$
```

**Comment by Suzamax** [comment]
Can confirm.

After using the Electron example, rebuilding in browser version fails.

Steps to reproduce are the same but the `--cwd` part, not needed in UNIX OSes.

```
carlos@MacBook-Pro-de-Carlos browser % yarn run start           
yarn run v1.19.1
$ theia start --plugins=local-dir:../../plugins
internal/modules/cjs/loader.js:807
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: The module '/Users/carlos/theia/node_modules/nsfw/build/Release/nsfw.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 69. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/carlos/theia/node_modules/nsfw/lib/src/index.js:3:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
✨  Done in 1.09s.
```

**Node v10, macOS Catalina 10.15.1**

**Comment by akosyakov** [comment]
@Suzamax and you have run `yarn run rebuild:browser` before running browser app again too?

**Comment by Suzamax** [comment]
@akosyakov yes, but it was useless, "currently using browser" according to the output.

**Comment by kittaakos** [comment]
I had this issue several times; somehow there is an inconsistent state in the CLI. Can you try `git clean -ffxqd` (will delete all untracked files) and run `yarn && yarn rebuild:electron`. Does it help?

**Comment by a1994846931931** [comment]
> I had this issue several times; somehow there is an inconsistent state in the CLI. Can you try `git clean -ffxqd` (will delete all untracked files) and run `yarn && yarn rebuild:electron`. Does it help?

I somehow cannot rebuild theia, even if I checkout all the changes in my workspace. `git clean -ffxqd` fixed the issue.

**Comment by kittaakos** [comment]
> rebuild theia

@a1994846931931, can you give me a commit hash. Let me try to reproduce it.

**Comment by a1994846931931** [comment]
The commit ID is: c80f3fecb632150243aa3044dda50ec2cda2d9fc

But I really don't how to reproduce it. It may due to that I do some cleaning every time I build theia:

```
compile_production() {
    export NODE_TLS_REJECT_UNAUTHORIZED=0
    export NODE_OPTIONS="--max-old-space-size=4096"
    export THEIA_ELECTRON_SKIP_REPLACE_FFMPEG=1
    export PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1
    yarn --ignore-engines --link-duplicates && \
    yarn --ignore-engines --link-duplicates --production && \
    yarn autoclean --force && \
    modclean -r && \
    rm -rf node_modules/typescript && \
    rm -rf node_modules/listr && \
    rm -rf node_modules/rxjs && \
    rm -rf node_modules/@types && \
    rm -rf node_modules/prettier
}
```

**Comment by kittaakos** [comment]
> The commit ID is: [c80f3fe](https://github.com/eclipse-theia/theia/commit/c80f3fecb632150243aa3044dda50ec2cda2d9fc)

I have tried the following, it worked:
```
git clone https://github.com/eclipse-theia/theia.git \
&& cd theia \
&& git checkout -b c80f3fecb632150243aa3044dda50ec2cda2d9fc c80f3fecb632150243aa3044dda50ec2cda2d9fc \
&& git status \
&& yarn \
&& yarn rebuild:electron \
&& yarn rebuild:browser \
&& yarn --cwd ./examples/browser start
```

**Comment by sgraband** [comment]
NSFW completely replaced by `@parcel/watcher`.
