### ISSUE TITLE
Creating a Xtext DSL for Theia

### ISSUE THREAD

**Issue by SharkJ** [theia-ide/theia#3564]
Hi,
I need to add a language extension to Theia by implementing a DSL I created using Xtext. I found [this repo](https://github.com/theia-ide/theia-xtext) but I get so many errors when trying to build it (probably because it is outdated). Could you please tell me the steps to follow in order to implement my DSL to Theia?
Thanks!

**Comment by kittaakos** [comment]
> I found [this repo](https://github.com/theia-ide/theia-xtext) but I get so many errors when trying to build it (probably because it is outdated)

I have just tried it in Gitpod and it works as expected.

![screen shot 2018-11-21 at 08 18 59](https://user-images.githubusercontent.com/1405703/48824991-47b08d00-ed66-11e8-9e29-1414a4356ff6.jpg)

The only difference I made is, instead of running
```
yarn start
```

I did
```
yarn start --hostname 0.0.0.0 --port 3000
```

> so many errors when trying to build it

What kind of errors do you have?

**Comment by SharkJ** [comment]
I tried it out in Gitpod and it works as you have mentioned. I've been trying to do this locally, and wasn't successful.
I have mentioned the problem in [this issue](https://github.com/theia-ide/theia-xtext/issues/8#issue-382965858).

**Comment by kittaakos** [comment]
I see. The problem is in the example but you can work around it.

The error says:
```
lerna ERR! 'rm' is not recognized as an internal or external command,
```

You're on Windows and you do not have `rm`. Try it in [Git Bash](https://gitforwindows.org) or install [Cygwin](https://www.cygwin.com) and add the Cygwin `bin` folder to your path.

**Comment by SharkJ** [comment]
I tried Git Bash. Still I get this error: -

```

$ yarn install
yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
$ lerna run prepare
lerna info version 2.4.0
@theia/xtext-dsl-extension: > @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\
theia-xtext\xtext-dsl-extension
@theia/xtext-dsl-extension: > yarn run clean && yarn run build
@theia/xtext-dsl-extension: yarn run v1.12.3
@theia/xtext-dsl-extension: warning package.json: No license field
@theia/xtext-dsl-extension: $ rimraf lib
@theia/xtext-dsl-extension: Done in 0.28s.
@theia/xtext-dsl-extension: yarn run v1.12.3
@theia/xtext-dsl-extension: warning package.json: No license field
@theia/xtext-dsl-extension: $ tsc && yarn run copy-ls
@theia/xtext-dsl-extension: src/browser/language-contribution.ts(30,5): error TS
2304: Cannot find name 'monaco'.
@theia/xtext-dsl-extension: src/browser/language-contribution.ts(36,5): error TS
2304: Cannot find name 'monaco'.
@theia/xtext-dsl-extension: src/browser/language-contribution.ts(52,5): error TS
2304: Cannot find name 'monaco'.
@theia/xtext-dsl-extension: info Visit https://yarnpkg.com/en/docs/cli/run for d
ocumentation about this command.
@theia/xtext-dsl-extension: error Command failed with exit code 2.
@theia/xtext-dsl-extension: npm ERR! code ELIFECYCLE
@theia/xtext-dsl-extension: npm ERR! errno 1
@theia/xtext-dsl-extension: npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `
yarn run clean && yarn run build`
@theia/xtext-dsl-extension: npm ERR! Exit status 1
@theia/xtext-dsl-extension: npm ERR!
@theia/xtext-dsl-extension: npm ERR! Failed at the @theia/xtext-dsl-extension@0.
1.0 prepare script.
@theia/xtext-dsl-extension: npm ERR! This is probably not a problem with npm. Th
ere is likely additional logging output above.
@theia/xtext-dsl-extension: npm ERR! A complete log of this run can be found in:
@theia/xtext-dsl-extension: npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cac
he\_logs\2018-11-21T08_47_01_969Z-debug.log
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run prepare
lerna ERR! warning package.json: No license field
lerna ERR! warning package.json: No license field
lerna ERR! error Command failed with exit code 2.
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean &&
 yarn run build`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare scrip
t.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely add
itional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cache\_logs\2018-11-
21T08_47_01_969Z-debug.log
lerna ERR!
lerna ERR!
lerna ERR! > @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\theia-xtext\xtext
-dsl-extension
lerna ERR! > yarn run clean && yarn run build
lerna ERR!
lerna ERR! yarn run v1.12.3
lerna ERR! $ rimraf lib
lerna ERR! Done in 0.28s.
lerna ERR! yarn run v1.12.3
lerna ERR! $ tsc && yarn run copy-ls
lerna ERR! src/browser/language-contribution.ts(30,5): error TS2304: Cannot find
 name 'monaco'.
lerna ERR! src/browser/language-contribution.ts(36,5): error TS2304: Cannot find
 name 'monaco'.
lerna ERR! src/browser/language-contribution.ts(52,5): error TS2304: Cannot find
 name 'monaco'.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation abou
t this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (D:\THEIA\theia-xtext\node_modules\execa\
index.js:236:11)
lerna ERR!     at <anonymous>
(node:10300) UnhandledPromiseRejectionWarning: Error: Command failed: npm run pr
epare
warning package.json: No license field
warning package.json: No license field
error Command failed with exit code 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean && yarn run b
uild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cache\_logs\2018-11-21T08_47_01
_969Z-debug.log


> @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\theia-xtext\xtext-dsl-extens
ion
> yarn run clean && yarn run build

yarn run v1.12.3
$ rimraf lib
Done in 0.28s.
yarn run v1.12.3
$ tsc && yarn run copy-ls
src/browser/language-contribution.ts(30,5): error TS2304: Cannot find name 'mona
co'.
src/browser/language-contribution.ts(36,5): error TS2304: Cannot find name 'mona
co'.
src/browser/language-contribution.ts(52,5): error TS2304: Cannot find name 'mona
co'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

    at Promise.all.then.arr (D:\THEIA\theia-xtext\node_modules\execa\index.js:23
6:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:10300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
 error originated either by throwing inside of an async function without a catch
 block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 4)
(node:10300) [DEP0018] DeprecationWarning: Unhandled promise rejections are depr
ecated. In the future, promise rejections that are not handled will terminate th
e Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.

```

**Comment by kittaakos** [comment]
Try to add the following to the `tsconfig.json`.

```bash
Akoss-MacBook-Pro:theia-xtext akos.kitta$ git diff ./xtext-dsl-extension/tsconfig.json
```

```diff
diff --git a/xtext-dsl-extension/tsconfig.json b/xtext-dsl-extension/tsconfig.json
index bdecca0..cc897e1 100644
--- a/xtext-dsl-extension/tsconfig.json
+++ b/xtext-dsl-extension/tsconfig.json
@@ -19,5 +19,8 @@
     },
     "include": [
         "src"
+    ],
+    "files": [
+        "../node_modules/@theia/monaco/src/typings/monaco/index.d.ts"
     ]
 }
\ No newline at end of file
```

**Comment by SharkJ** [comment]
The errors have definitely reduced, but I  get this now: -

```

$ yarn install
yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
$ lerna run prepare
lerna info version 2.4.0
@theia/xtext-dsl-extension: > @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\
theia-xtext\xtext-dsl-extension
@theia/xtext-dsl-extension: > yarn run clean && yarn run build
@theia/xtext-dsl-extension: yarn run v1.12.3
@theia/xtext-dsl-extension: warning package.json: No license field
@theia/xtext-dsl-extension: $ rimraf lib
@theia/xtext-dsl-extension: Done in 0.28s.
@theia/xtext-dsl-extension: yarn run v1.12.3
@theia/xtext-dsl-extension: warning package.json: No license field
@theia/xtext-dsl-extension: $ tsc && yarn run copy-ls
@theia/xtext-dsl-extension: error TS6053: File 'D:/THEIA/theia-xtext/node_module
s/@theia/monaco/src/typings/monaco/index.d.ts' not found.
@theia/xtext-dsl-extension: info Visit https://yarnpkg.com/en/docs/cli/run for d
ocumentation about this command.
@theia/xtext-dsl-extension: error Command failed with exit code 2.
@theia/xtext-dsl-extension: npm ERR! code ELIFECYCLE
@theia/xtext-dsl-extension: npm ERR! errno 1
@theia/xtext-dsl-extension: npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `
yarn run clean && yarn run build`
@theia/xtext-dsl-extension: npm ERR! Exit status 1
@theia/xtext-dsl-extension: npm ERR!
@theia/xtext-dsl-extension: npm ERR! Failed at the @theia/xtext-dsl-extension@0.
1.0 prepare script.
@theia/xtext-dsl-extension: npm ERR! This is probably not a problem with npm. Th
ere is likely additional logging output above.
@theia/xtext-dsl-extension: npm ERR! A complete log of this run can be found in:
@theia/xtext-dsl-extension: npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cac
he\_logs\2018-11-21T09_00_56_316Z-debug.log
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run prepare
lerna ERR! warning package.json: No license field
lerna ERR! warning package.json: No license field
lerna ERR! error Command failed with exit code 2.
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean &&
 yarn run build`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare scrip
t.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely add
itional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cache\_logs\2018-11-
21T09_00_56_316Z-debug.log
lerna ERR!
lerna ERR!
lerna ERR! > @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\theia-xtext\xtext
-dsl-extension
lerna ERR! > yarn run clean && yarn run build
lerna ERR!
lerna ERR! yarn run v1.12.3
lerna ERR! $ rimraf lib
lerna ERR! Done in 0.28s.
lerna ERR! yarn run v1.12.3
lerna ERR! $ tsc && yarn run copy-ls
lerna ERR! error TS6053: File 'D:/THEIA/theia-xtext/node_modules/@theia/monaco/s
rc/typings/monaco/index.d.ts' not found.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation abou
t this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (D:\THEIA\theia-xtext\node_modules\execa\
index.js:236:11)
lerna ERR!     at <anonymous>
(node:2416) UnhandledPromiseRejectionWarning: Error: Command failed: npm run pre
pare
warning package.json: No license field
warning package.json: No license field
error Command failed with exit code 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean && yarn run b
uild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cache\_logs\2018-11-21T09_00_56
_316Z-debug.log


> @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\theia-xtext\xtext-dsl-extens
ion
> yarn run clean && yarn run build

yarn run v1.12.3
$ rimraf lib
Done in 0.28s.
yarn run v1.12.3
$ tsc && yarn run copy-ls
error TS6053: File 'D:/THEIA/theia-xtext/node_modules/@theia/monaco/src/typings/
monaco/index.d.ts' not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

    at Promise.all.then.arr (D:\THEIA\theia-xtext\node_modules\execa\index.js:23
6:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:2416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 4)
(node:2416) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.

```

**Comment by SharkJ** [comment]
I searched and found the monaco directory in this path (since it was not inside the @theia folder) - `./node_modules/monaco-languageclient/src/typings/monaco/index.d.ts` and changed the `tsconfig` accordingly. I now get this output: -

```

$ yarn install
yarn install v1.12.3
[1/4] Resolving packages...
success Already up-to-date.
$ lerna run prepare
lerna info version 2.4.0
@theia/xtext-dsl-extension: > @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\
theia-xtext\xtext-dsl-extension
@theia/xtext-dsl-extension: > yarn run clean && yarn run build
@theia/xtext-dsl-extension: yarn run v1.12.3
@theia/xtext-dsl-extension: warning package.json: No license field
@theia/xtext-dsl-extension: $ rimraf lib
@theia/xtext-dsl-extension: Done in 0.28s.
@theia/xtext-dsl-extension: yarn run v1.12.3
@theia/xtext-dsl-extension: warning package.json: No license field
@theia/xtext-dsl-extension: $ tsc && yarn run copy-ls
@theia/xtext-dsl-extension: src/browser/language-contribution.ts(30,12): error T
S2339: Property 'languages' does not exist on type 'typeof monaco'.
@theia/xtext-dsl-extension: src/browser/language-contribution.ts(36,12): error T
S2339: Property 'languages' does not exist on type 'typeof monaco'.
@theia/xtext-dsl-extension: src/browser/language-contribution.ts(52,12): error T
S2339: Property 'languages' does not exist on type 'typeof monaco'.
@theia/xtext-dsl-extension: info Visit https://yarnpkg.com/en/docs/cli/run for d
ocumentation about this command.
@theia/xtext-dsl-extension: error Command failed with exit code 2.
@theia/xtext-dsl-extension: npm ERR! code ELIFECYCLE
@theia/xtext-dsl-extension: npm ERR! errno 1
@theia/xtext-dsl-extension: npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `
yarn run clean && yarn run build`
@theia/xtext-dsl-extension: npm ERR! Exit status 1
@theia/xtext-dsl-extension: npm ERR!
@theia/xtext-dsl-extension: npm ERR! Failed at the @theia/xtext-dsl-extension@0.
1.0 prepare script.
@theia/xtext-dsl-extension: npm ERR! This is probably not a problem with npm. Th
ere is likely additional logging output above.
@theia/xtext-dsl-extension: npm ERR! A complete log of this run can be found in:
@theia/xtext-dsl-extension: npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cac
he\_logs\2018-11-21T09_31_50_614Z-debug.log
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm run prepare
lerna ERR! warning package.json: No license field
lerna ERR! warning package.json: No license field
lerna ERR! error Command failed with exit code 2.
lerna ERR! npm ERR! code ELIFECYCLE
lerna ERR! npm ERR! errno 1
lerna ERR! npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean &&
 yarn run build`
lerna ERR! npm ERR! Exit status 1
lerna ERR! npm ERR!
lerna ERR! npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare scrip
t.
lerna ERR! npm ERR! This is probably not a problem with npm. There is likely add
itional logging output above.
lerna ERR!
lerna ERR! npm ERR! A complete log of this run can be found in:
lerna ERR! npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cache\_logs\2018-11-
21T09_31_50_614Z-debug.log
lerna ERR!
lerna ERR!
lerna ERR! > @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\theia-xtext\xtext
-dsl-extension
lerna ERR! > yarn run clean && yarn run build
lerna ERR!
lerna ERR! yarn run v1.12.3
lerna ERR! $ rimraf lib
lerna ERR! Done in 0.28s.
lerna ERR! yarn run v1.12.3
lerna ERR! $ tsc && yarn run copy-ls
lerna ERR! src/browser/language-contribution.ts(30,12): error TS2339: Property '
languages' does not exist on type 'typeof monaco'.
lerna ERR! src/browser/language-contribution.ts(36,12): error TS2339: Property '
languages' does not exist on type 'typeof monaco'.
lerna ERR! src/browser/language-contribution.ts(52,12): error TS2339: Property '
languages' does not exist on type 'typeof monaco'.
lerna ERR! info Visit https://yarnpkg.com/en/docs/cli/run for documentation abou
t this command.
lerna ERR!
lerna ERR!     at Promise.all.then.arr (D:\THEIA\theia-xtext\node_modules\execa\
index.js:236:11)
lerna ERR!     at <anonymous>
(node:5572) UnhandledPromiseRejectionWarning: Error: Command failed: npm run pre
pare
warning package.json: No license field
warning package.json: No license field
error Command failed with exit code 2.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @theia/xtext-dsl-extension@0.1.0 prepare: `yarn run clean && yarn run b
uild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @theia/xtext-dsl-extension@0.1.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\shjslk\AppData\Roaming\npm-cache\_logs\2018-11-21T09_31_50
_614Z-debug.log


> @theia/xtext-dsl-extension@0.1.0 prepare D:\THEIA\theia-xtext\xtext-dsl-extens
ion
> yarn run clean && yarn run build

yarn run v1.12.3
$ rimraf lib
Done in 0.28s.
yarn run v1.12.3
$ tsc && yarn run copy-ls
src/browser/language-contribution.ts(30,12): error TS2339: Property 'languages'
does not exist on type 'typeof monaco'.
src/browser/language-contribution.ts(36,12): error TS2339: Property 'languages'
does not exist on type 'typeof monaco'.
src/browser/language-contribution.ts(52,12): error TS2339: Property 'languages'
does not exist on type 'typeof monaco'.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

    at Promise.all.then.arr (D:\THEIA\theia-xtext\node_modules\execa\index.js:23
6:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
(node:5572) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This
error originated either by throwing inside of an async function without a catch
block, or by rejecting a promise which was not handled with .catch(). (rejection
 id: 4)
(node:5572) [DEP0018] DeprecationWarning: Unhandled promise rejections are depre
cated. In the future, promise rejections that are not handled will terminate the
 Node.js process with a non-zero exit code.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this
command.

```

**Comment by kittaakos** [comment]
Does your `yarn.lock` contain any outgoing changes? If so, please reset to HEAD and try it again.

**Comment by SharkJ** [comment]
I reset the HEAD using `git reset --hard HEAD`, still I get the same error.

**Comment by kittaakos** [comment]
I am out of ideas, you should ask at https://github.com/theia-ide/theia-xtext/issues/8.

**Comment by SharkJ** [comment]
Thank you @kittaakos! 
Closing the issue since it will be continued [here.](https://github.com/theia-ide/theia-xtext/issues/8)
