### ISSUE TITLE
[electron][plugin-ext] No matching bindings found for serviceIdentifier: Symbol(ContributionProvider)

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3651]
I was verifying 369dcff9.
I did:
```
yarn && yarn run rebuild:electron && rm -rf ~/.theia && yarn --cwd ./examples/electron start
```

```
Akoss-MacBook-Pro:theia akos.kitta$ git rev-parse --short HEAD
369dcff9
Akoss-MacBook-Pro:theia akos.kitta$ yarn --cwd ./examples/electron/ start
yarn run v1.12.3
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 11603]
Server worker is ready to accept messages. [ID: 1 | PID: 11603]
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
"3000"
root INFO [nsfw-watcher: 11976] Started watching: /Users/akos.kitta/git/theia/examples/electron/package.json
root ERROR Error: No matching bindings found for serviceIdentifier: Symbol(ContributionProvider)
 Symbol(ContributionProvider) - named: Symbol(extPluginApi) 

    at _validateActiveBindingCount (/Users/akos.kitta/git/theia/node_modules/inversify/lib/planning/planner.js:62:23)
    at _getActiveBindings (/Users/akos.kitta/git/theia/node_modules/inversify/lib/planning/planner.js:48:5)
    at _createSubRequests (/Users/akos.kitta/git/theia/node_modules/inversify/lib/planning/planner.js:91:26)
    at /Users/akos.kitta/git/theia/node_modules/inversify/lib/planning/planner.js:115:17
    at Array.forEach (<anonymous>)
    at /Users/akos.kitta/git/theia/node_modules/inversify/lib/planning/planner.js:114:26
    at Array.forEach (<anonymous>)
    at _createSubRequests (/Users/akos.kitta/git/theia/node_modules/inversify/lib/planning/planner.js:94:20)
    at Object.plan (/Users/akos.kitta/git/theia/node_modules/inversify/lib/planning/planner.js:136:9)
    at /Users/akos.kitta/git/theia/node_modules/inversify/lib/container/container.js:317:37
root ERROR Cannot find a service for the path: /services/hostedPlugin
root ERROR Cannot find a service for the path: /services/plugin-ext

```

Similar: https://github.com/theia-ide/theia/issues/2210.

**Comment by kittaakos** [comment]
@benoitf, does anyone take care of this issue?

**Comment by benoitf** [comment]
@kittaakos I don't think so, all Che developers are using browser version.
