### ISSUE TITLE
Electron rebuild is broken on Windows

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#370]
```
Processing node-pty
C:\projects\theia-02044\node_modules\.bin\electron-rebuild:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\projects\theia-02044\scripts\rebuild.js:32:9)
error Command failed with exit code 1.
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Command exited with code 1

```

**Comment by kittaakos** [comment]
Closed va #381.
