### ISSUE TITLE
[electron] Cannot start the electron application

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#3745]
431d12a5

```
Uncaught (in promise) SyntaxError: Invalid regular expression: /(?<!\!\s*)isInDiffEditor/: Invalid group
    at MonacoKeybindingContribution.push.../../packages/monaco/lib/browser/monaco-keybinding.js.MonacoKeybindingContribution.registerKeybindings (/Users/akos.kitta/Desktop/theia/examples/electron/lib/47.bundle.js:1238)
    at KeybindingRegistry.../../packages/core/lib/browser/keybinding.js.KeybindingRegistry.onStart (bundle.js:75896)
    at FrontendApplication.<anonymous> (bundle.js:75393)
    at step (bundle.js:75048)
    at Object.next (bundle.js:75029)
    at bundle.js:75023
    at Promise (<anonymous>)
    at ../../packages/core/lib/browser/frontend-application.js.__awaiter (bundle.js:75019)
    at FrontendApplication.../../packages/core/lib/browser/frontend-application.js.FrontendApplication.startContributions (bundle.js:75361)
    at FrontendApplication.<anonymous> (bundle.js:75125)
```

**Comment by marechal-p** [comment]
```js
$ npx electron -i
>  /(?<!\!\s*)isInDiffEditor/gm
SyntaxError: Invalid regular expression: /(?<!\!\s*)isInDiffEditor/: Invalid group
    at repl:1:2
    at ContextifyScript.Script.runInContext (vm.js:53:29)
    at REPLServer.defaultEval (repl.js:241:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
    at emitOne (events.js:115:13)
    at REPLServer.emit (events.js:210:7)
    at REPLServer.Interface._onLine (readline.js:278:10)
    at REPLServer.Interface._line (readline.js:625:8)
>
(To exit, press ^C again or type .exit)
>

$ node
>  /(?<!\!\s*)isInDiffEditor/gm
/(?<!\!\s*)isInDiffEditor/gm
>
```

For some reason only Electron has an issue with that regex.

**Comment by kittaakos** [comment]
This item belongs here https://github.com/theia-ide/theia/issues/3730.

We use Node.js `8.2.1` in electron. Same issue if I use `8.2.1` without electron:
```
node --version && node
v8.2.1
> /(?<!\!\s*)isInDiffEditor/gm
SyntaxError: Invalid regular expression: /(?<!\!\s*)isInDiffEditor/: Invalid group

>
```

**Comment by marechal-p** [comment]
I was trying to understand the regex, from what I understand it is trying to see if some string is like `isInDiffEditor xxx` but not `!isInDiffEditor xxx` nor `xxx isInDiffEditor xxx`. I don't really understand.

**Comment by kittaakos** [comment]
Me neither. We have to process these `item.when.serialize()`:

```
textInputFocus
textInputFocus && !editorReadonly
textInputFocus && !editorReadonly
textInputFocus && !editorReadonly
editorFocus
editorTextFocus && !editorReadonly
editorTextFocus && !editorReadonly
editorTextFocus && !editorReadonly
editorTextFocus && !editorReadonly
editorTextFocus && !editorReadonly
textInputFocus && !editorReadonly
isInDiffEditor
isInDiffEditor
editorTextFocus && !editorReadonly
editorHasDefinitionProvider && editorTextFocus && !isInEmbeddedEditor
editorFocus
editorTextFocus && !editorReadonly
editorTextFocus && !editorReadonly
editorTextFocus && !editorReadonly
editorTextFocus
editorTextFocus
editorTextFocus
editorTextFocus && !editorReadonly
editorTextFocus && !editorReadonly
editorTextFocus && !editorReadonly
editorTextFocus
editorFocus && !editorReadonly
editorFocus && !editorReadonly
editorTextFocus && !editorReadonly
editorTextFocus && !editorReadonly
editorFocus
editorFocus
editorFocus
editorTextFocus && !editorReadonly && supportedCodeAction =~ /(\s|^)source\.organizeImports\b/
editorTextFocus && !editorReadonly
editorHasImplementationProvider && editorTextFocus && !isInEmbeddedEditor
editorHasDefinitionProvider && editorTextFocus && !inReferenceSearchEditor && !isInEmbeddedEditor
editorFocus
editorFocus
editorFocus
editorHasCodeActionsProvider && editorTextFocus && !editorReadonly
editorFocus && editorHasDocumentSymbolProvider
editorHasCodeActionsProvider && editorTextFocus && !editorReadonly
editorHasReferenceProvider && editorTextFocus && !inReferenceSearchEditor && !isInEmbeddedEditor
editorHasRenameProvider && editorTextFocus && !editorReadonly
editorFocus
editorFocus
textInputFocus
editorTextFocus
editorTextFocus
textInputFocus && !editorReadonly
editorHasSignatureHelpProvider && editorTextFocus
editorHasCompletionItemProvider && textInputFocus && !editorReadonly
editorTextFocus && hasWordHighlights
editorTextFocus
editorTextFocus
```

**Comment by marechal-p** [comment]
```
textInputFocus false
textInputFocus && !editorReadonly false
textInputFocus && !editorReadonly false
textInputFocus && !editorReadonly false
editorFocus false
editorTextFocus && !editorReadonly false
editorTextFocus && !editorReadonly false
editorTextFocus && !editorReadonly false
editorTextFocus && !editorReadonly false
editorTextFocus && !editorReadonly false
textInputFocus && !editorReadonly false
isInDiffEditor true
isInDiffEditor false
editorTextFocus && !editorReadonly false
editorHasDefinitionProvider && editorTextFocus && !isInEmbeddedEditor false
editorFocus false
editorTextFocus && !editorReadonly false
editorTextFocus && !editorReadonly false
editorTextFocus && !editorReadonly false
editorTextFocus false
editorTextFocus false
editorTextFocus false
editorTextFocus && !editorReadonly false
editorTextFocus && !editorReadonly false
editorTextFocus && !editorReadonly false
editorTextFocus false
editorFocus && !editorReadonly false
editorFocus && !editorReadonly false
editorTextFocus && !editorReadonly false
editorTextFocus && !editorReadonly false
editorFocus false
editorFocus false
editorFocus false
editorTextFocus && !editorReadonly && supportedCodeAction =~ /(s|^)source.organizeImport/ false
editorTextFocus && !editorReadonly false
editorHasImplementationProvider && editorTextFocus && !isInEmbeddedEditor false
editorHasDefinitionProvider && editorTextFocus && !inReferenceSearchEditor && !isInEmbeddedEditor false
editorFocus false
editorFocus false
editorFocus false
editorHasCodeActionsProvider && editorTextFocus && !editorReadonly false
editorFocus && editorHasDocumentSymbolProvider false
editorHasCodeActionsProvider && editorTextFocus && !editorReadonly false
editorHasReferenceProvider && editorTextFocus && !inReferenceSearchEditor && !isInEmbeddedEditor false
editorHasRenameProvider && editorTextFocus && !editorReadonly false
editorFocus false
editorFocus false
textInputFocus false
editorTextFocus false
editorTextFocus false
textInputFocus && !editorReadonly false
editorHasSignatureHelpProvider && editorTextFocus false
editorHasCompletionItemProvider && textInputFocus && !editorReadonly false
editorTextFocus && hasWordHighlights false
editorTextFocus false
editorTextFocus false
```
