### ISSUE TITLE
[ci][windows] TypescriptVersionServiceImpl is often failing the tests

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#3799]
```
TypescriptVersionServiceImpl
    1) resolveBundledVersionInApplicationPath
    2) resolveBundledVersionWithRequire
    √ resolveBundledVersionAsExecutable (1096ms)
    3) getVersions
  typescript package
    √ should support code coverage statistics
  2 passing (1s)
  3 failing
  1) TypescriptVersionServiceImpl resolveBundledVersionInApplicationPath:
     AssertionError [ERR_ASSERTION]: undefined == 'node_modules/typescript/lib'
      at Suite.<anonymous> (src\node\typescript-version-service-impl.spec.ts:43:16)
      at step (src\node\typescript-version-service-impl.spec.ts:47:23)
      at Object.next (src\node\typescript-version-service-impl.spec.ts:28:53)
      at fulfilled (src\node\typescript-version-service-impl.spec.ts:19:58)
      at <anonymous>
  2) TypescriptVersionServiceImpl resolveBundledVersionWithRequire:
     AssertionError [ERR_ASSERTION]: undefined == 'node_modules/typescript/lib'
      at Suite.<anonymous> (src\node\typescript-version-service-impl.spec.ts:48:16)
      at step (src\node\typescript-version-service-impl.spec.ts:47:23)
      at Object.next (src\node\typescript-version-service-impl.spec.ts:28:53)
      at fulfilled (src\node\typescript-version-service-impl.spec.ts:19:58)
      at <anonymous>
  3) TypescriptVersionServiceImpl getVersions:
      AssertionError [ERR_ASSERTION]: 'Bundled: undefined\r\nWorkspace: undefined' == 'Bundled: node_modules/typescript/lib\r\nWorkspace: node_modules/typescript/lib'
      + expected - actual
      -Bundled: undefined
      -Workspace: undefined
      +Bundled: node_modules/typescript/lib
      +Workspace: node_modules/typescript/lib
      
      at Suite.<anonymous> (src\node\typescript-version-service-impl.spec.ts:60:16)
      at step (src\node\typescript-version-service-impl.spec.ts:47:23)
      at Object.next (src\node\typescript-version-service-impl.spec.ts:28:53)
      at fulfilled (src\node\typescript-version-service-impl.spec.ts:19:58)
      at <anonymous>
```

Issue seems to happen a lot of times under windows. Either disable this test for that platform, or fix it :)

**Comment by marechal-p** [comment]
Thanks :)
