### ISSUE TITLE
vscode.languages.registerRenameProvider is not a function

### ISSUE THREAD

**Issue by kaviththiranga** [theia-ide/theia#3921]
I am getting below error when running an existing vscode plugin.

root ERROR [hosted-plugin: 123] (node:123) UnhandledPromiseRejectionWarning: TypeError: vscode_1.languages.registerRenameProvider is not a function
    at RenameFeature.registerLanguageProvider (/tmp/vscode-unpacked/ballerina-vscode-plugin-0.990.2.vsix/extension/node_modules/vscode-languageclient/lib/client.js:1358:35)
    at RenameFeature.register (/tmp/vscode-unpacked/ballerina-vscode-plugin-0.990.2.vsix/extension/node_modules/vscode-languageclient/lib/client.js:682:29)
    at RenameFeature.initialize (/tmp/vscode-unpacked/ballerina-vscode-plugin-0.990.2.vsix/extension/node_modules/vscode-languageclient/lib/client.js:1318:14)
    at ExtendedLangClient.initializeFeatures (/tmp/vscode-unpacked/ballerina-vscode-plugin-0.990.2.vsix/extension/node_modules/vscode-languageclient/lib/client.js:2297:21)
    at connection.initialize.then (/tmp/vscode-unpacked/ballerina-vscode-plugin-0.990.2.vsix/extension/node_modules/vscode-languageclient/lib/client.js:2002:18)
    at <anonymous>

**Comment by kaviththiranga** [comment]
seems this is already tracked in https://github.com/theia-ide/theia/issues/3861
