### ISSUE TITLE
Plugin as sidecar initialization fails when browser is refreshed

### ISSUE THREAD

**Issue by tolusha** [theia-ide/theia#3970]
Plugin (run as side car) initialization fails when browser is refreshed. 

### How to reproduce
* Che 7 workspace with plugin providing command contribution
* Refresh browser
* Observe stack trace in dev console and plugin doesn't work

```
Error: Command C_Cpp.ConfigurationSelect already exist
    at CommandRegistryImpl.registerCommand (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/command-registry.js:33:19)
    at Object.registerCommand (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-context.js:101:40)
    at /home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js:37:29
    at Array.forEach (<anonymous>)
    at Object.exports.doInitialization (/home/theia/node_modules/@theia/plugin-ext-vscode/lib/node/plugin-vscode-init.js:29:30)
    at Function.PluginHostRPC.initialize (/home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js:54:25)
    at Object.init (/home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js:95:43)
    at PluginManagerExtImpl.$init (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:85:35)
    at RPCProtocolImpl.doInvokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:173:23)
    at RPCProtocolImpl.invokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:158:41)
```

**Comment by tolusha** [comment]
`PluginManagerExtImpl.$init()` is invoked every time when browser is refreshed.
https://github.com/theia-ide/theia/blob/master/packages/plugin-ext/src/plugin/plugin-manager.ts#L89

**Comment by tolusha** [comment]
It seems there is no quick fix regarding the root of the issue.
For the time being I propose a workaround:
```js
        if (this.commands.has(command.id)) {
            throw new Error(`Command ${command.id} already exist`);
        }
```
->
```js
       if (this.commands.has(command.id)) {
            this.commands.delete(command.id);
            this.proxy.$unregisterCommand(command.id);
            console.warn(`Command ${command.id} already exist and is overridden.`);
        }
```

**Comment by benoitf** [comment]
AFAIK plug-in is being stopped on refresh as well so cleanup of commands should be done at that time (so when it starts again it's not there)

**Comment by tolusha** [comment]
Make sense, I will check

**Comment by tsmaeder** [comment]
This is more for the IDE2 team. @evidolob Not a clue what the right approach is here.

**Comment by azatsarynnyy** [comment]
There's the same issue with the [Kubernetes Tooling Plugin](https://github.com/eclipse/che-plugin-registry/blob/master/plugins/ms-kubernetes-tools.vscode-kubernetes-tools/0.1.17/meta.yaml).
Running it against Che Theia with Anatoliy's [patch](https://github.com/theia-ide/theia/pull/4008) fixes the problem.

**Comment by benoitf** [comment]
should be fixed now with latest fix https://github.com/theia-ide/theia/pull/4583

**Comment by azatsarynnyy** [comment]
@benoitf I've tested it with the K8s Plugin. Works well. Thank you!
