### ISSUE TITLE
[plugin] status bar message cannot be loaded from nls

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#3992]
<img width="607" alt="screen shot 2019-01-09 at 16 20 38" src="https://user-images.githubusercontent.com/3082655/50908756-a8854900-142a-11e9-823f-22e2fdf3389a.png">

**Comment by akosyakov** [comment]
It turned out to be missing dependencies to nls in the extension. After installing dependencies, it take very long time to display in the status bar anything at all and never proper contribution.

My logs are full of:
```
root ERROR TypeError: Cannot read property 'length' of null
    at LabelParser.../../packages/core/lib/browser/label-parser.js.LabelParser.parse (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:81744:38)
    at StatusBarImpl.../../packages/core/lib/browser/status-bar/status-bar.js.StatusBarImpl.renderElement (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:88960:46)
    at https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:88911:40
    at Array.forEach (<anonymous>)
    at StatusBarImpl.../../packages/core/lib/browser/status-bar/status-bar.js.StatusBarImpl.render (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:88909:18)
    at StatusBarImpl.../../packages/core/lib/browser/widgets/react-widget.js.ReactWidget.onUpdateRequest (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:94298:72)
    at StatusBarImpl.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:23599:22)
    at invokeHandler (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:7585:21)
    at sendMessage (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:7321:13)
    at runMessageLoop (https://3000-ebfc7401-823a-4c74-b07d-77373b5a0661.ws-eu.gitpod.io/bundle.js:7635:17)
```

**Comment by akosyakov** [comment]
Turned out that some VS Code extensions does not set `text` on the status bar and VS Code is capable to tolerate it: https://github.com/Microsoft/vscode/blob/6b71a612e95b090202e58c0e876bc46244814892/extensions/debug-auto-launch/src/extension.ts#L98-L101
