### ISSUE TITLE
[plug-in] Progress bar doesn't work correctly with plugins

### ISSUE THREAD

**Issue by svor** [theia-ide/theia#4027]
Status bar has many instances of progress bar when vscode-java extension was ran as a plugin: 
![screenshot-localhost-3000-2019 01 11-14-29-25](https://user-images.githubusercontent.com/1271546/51034150-68e76a00-15ae-11e9-8020-b0429f50136d.png)

And many console errors like:
```
root ERROR Warning: Encountered two children with the same key, `Building workspace - 0%null1null`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```

**Comment by akosyakov** [comment]
@svor which version of java extension do you use?  with `0.37.0` i cannot get it running at all:
```
root ERROR [hosted-plugin: 21574] (node:21574) UnhandledPromiseRejectionWarning: TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1171:7)
    at Object.t.collectionJavaExtensions (/tmp/vscode-unpacked/redhat.java-0.37.0.vsix/extension/dist/extension.js:1:192841)
    at Promise (/tmp/vscode-unpacked/redhat.java-0.37.0.vsix/extension/dist/extension.js:1:110531)
    at new WrappedPromise (/tmp/vscode-unpacked/vscjava.vscode-java-debug-0.16.0.vsix/extension/node_modules/async-listener/es6-wrapped-promise.js:13:18)
    at a.window.withProgress.n (/tmp/vscode-unpacked/redhat.java-0.37.0.vsix/extension/dist/extension.js:1:109673)
    at StatusBarExtImpl.<anonymous> (/workspace/theia/packages/plugin-ext/lib/plugin/statusBar.js:73:35)
    at step (/workspace/theia/packages/plugin-ext/lib/plugin/statusBar.js:47:23)
    at Object.next (/workspace/theia/packages/plugin-ext/lib/plugin/statusBar.js:28:53)
    at fulfilled (/workspace/theia/packages/plugin-ext/lib/plugin/statusBar.js:19:58)
```

**Comment by akosyakov** [comment]
ok, anyway, from code is clear that a new status  bar entry is created each time when `text` is set
