### ISSUE TITLE
getDrives failure due to using unsupport lsblk flags

### ISSUE THREAD

**Issue by jgbradley1** [theia-ide/theia#4112]
I've built a Theia docker image based on centos 7. After starting the theia backend, error messages begin popping up regarding being unable to list all drives (see below). This cause problems later on when the user is switching workspaces. I found out two flags passed to lsblk (--json and --output-all) do not exist in CentOS. Compare the man pages [here](https://www.unix.com/man-page/centos/8/lsblk/) vs [here](https://manpages.debian.org/testing/util-linux/lsblk.8.en.html).

```
[root@f58e5d926011 theia-app]# yarn theia start --hostname=0.0.0.0 --port=3000 &
[1] 80
yarn run v1.13.0
$ /theia-app/node_modules/.bin/theia start --hostname=0.0.0.0 --port=3000
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 102]
Server worker is ready to accept messages. [ID: 1 | PID: 102]
root INFO Theia app listening on http://0.0.0.0:3000.
Received message which is neither a response nor a notification message:
"3000"
root WARN e.onStart is slow, took: 157.89999999833526 ms
terminal ERROR Couldn't attach - can't find terminal with id: 0
terminal ERROR Error attaching to terminal id 0, the terminal is most likely gone. Starting up a new terminal instead.
root ERROR Request getDrives failed with error: Command "lsblk --bytes --all --json --paths --output-all" exited unexpectedly with "1" Error: Command "lsblk --bytes --all --json --paths --output-all" exited unexpectedly with "1"
    at ChildProcess.childProcess.spawn.on.on (/theia-app/node_modules/drivelist/lib/exec.js:31:26)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
root ERROR Request getDrives failed with error: Command "lsblk --bytes --all --json --paths --output-all" exited unexpectedly with "1" Error: Command "lsblk --bytes --all --json --paths --output-all" exited unexpectedly with "1"
    at ChildProcess.childProcess.spawn.on.on (/theia-app/node_modules/drivelist/lib/exec.js:31:26)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
root ERROR Error when loading drives. Error: Request 'getDrives' failed
    at Proxy.<anonymous> (http://localhost:3000/bundle.js:52:133974)
    at t.<anonymous> (http://localhost:3000/bundle.js:19:222830)
    at http://localhost:3000/bundle.js:19:221371
    at Object.next (http://localhost:3000/bundle.js:19:221476)
    at http://localhost:3000/bundle.js:19:220389
    at new Promise (<anonymous>)
    at s (http://localhost:3000/bundle.js:19:220166)
    at t.drives (http://localhost:3000/bundle.js:19:222695)
    at t.doLoadDrives (http://localhost:3000/bundle.js:79:384244)
    at t.collectLocations (http://localhost:3000/bundle.js:79:384152)
root ERROR Error when loading drives. Error: Request 'getDrives' failed
    at Proxy.<anonymous> (http://localhost:3000/bundle.js:52:133974)
    at t.<anonymous> (http://localhost:3000/bundle.js:19:222830)
    at http://localhost:3000/bundle.js:19:221371
    at Object.next (http://localhost:3000/bundle.js:19:221476)
    at http://localhost:3000/bundle.js:19:220389
    at new Promise (<anonymous>)
    at s (http://localhost:3000/bundle.js:19:220166)
    at t.drives (http://localhost:3000/bundle.js:19:222695)
    at t.doLoadDrives (http://localhost:3000/bundle.js:79:384244)
    at t.collectLocations (http://localhost:3000/bundle.js:79:384152)
root WARN e.onStart is slow, took: 633.6000000010245 ms
root INFO [nsfw-watcher: 166] Started watching: /home
```

**Comment by draco2003** [comment]
Mind sharing your dockerfile for Centos?

**Comment by jgbradley1** [comment]
Sure, check out the `Dockerfile` in [this](https://github.com/jgbradley1/theia-docker-image) repo. I still see this error show up infrequently but don't know how to consistently reproduce the error at this time. It seems to appear when workspaces are closed/opened.

**Comment by fengzilong** [comment]
```bash
lsblk: unrecognized option '--json'
```

+1 for debian 8, I use `buildpack-deps:jessie` as base image

**Comment by tom-shan** [comment]
@jgbradley1 You should try to use drivelist 8.0.6 for this [commit](https://github.com/balena-io-modules/drivelist/commit/621b78febb8ca6b2c4ff8c11a7a1cccc6d7fd0e2) is published after 8.0.0.

**Comment by sgraband** [comment]
`drivelist` ^12.0.2 includes fallback mechanism for Windows drive detection.
