### ISSUE TITLE
theia build error

### ISSUE THREAD

**Issue by frankLife** [theia-ide/theia#4132]
According to [Build your own IDE](https://www.theia-ide.org/doc/composing_applications) ， I always get the error.

```
➜  theia-demo yarn theia build
yarn run v1.13.0
$ /Users/franklife/work/def-base/studio/theia-demo/node_modules/.bin/theia build

<--- Last few GCs --->

[6343:0x103800000]    33626 ms: Mark-sweep 1378.2 (1427.6) -> 1376.6 (1427.6) MB, 762.6 / 0.0 ms  (average mu = 0.122, current mu = 0.010) allocation failure scavenge might not succeed
[6343:0x103800000]    34411 ms: Mark-sweep 1378.7 (1428.1) -> 1377.0 (1428.1) MB, 778.0 / 0.0 ms  (average mu = 0.067, current mu = 0.009) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x3f91cd8dbe3d]
Security context: 0x375dc691e6e1 <JSObject>
    1: /* anonymous */ [0x375dbec93799] [/Users/franklife/work/def-base/studio/theia-demo/node_modules/webpack-sources/node_modules/source-map/lib/source-node.js:~342] [pc=0x3f91ce6654a6](this=0x375de929ad11 <JSGlobal Object>,chunk=0x375d2436d879 <Very long string[137162]>,original=0x375d8a196729 <Object map = 0x375dead83859>)
    2: SourceNode_walk [0x375d2...


FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x10003b125 node::Abort() [/usr/local/bin/node]
 2: 0x10003b32f node::OnFatalError(char const*, char const*) [/usr/local/bin/node]
 3: 0x1001a8e85 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [/usr/local/bin/node]

 4: 0x1005742a2 v8::internal::Heap::FatalProcessOutOfMemory(char const*) [/usr/local/bin/node]

 5: 0x100576d75 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [/usr/local/bin/node]

 6: 0x100572c1f v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [/usr/local/bin/node]

 7: 0x100570df4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [/usr/local/bin/node]

 8: 0x10057d68c v8::internal::Heap::AllocateRawWithLigthRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]

 9: 0x10057d70f v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [/usr/local/bin/node]

10: 0x10054f055 v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [/usr/local/bin/node]

11: 0x1006811a8 v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [/usr/local/bin/node]

12: 0x1008274d8 v8::internal::Runtime_StringCharCodeAt(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
13: 0x3f91cd8dbe3d
14: 0x3f91ce6654a6

Error: webpack exited with an unexpected signal: SIGABRT.
    at ChildProcess.<anonymous> (/Users/franklife/work/def-base/studio/theia-demo/node_modules/@theia/application-manager/lib/application-process.js:59:28)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

How can resolve this ? any option?
@akosyakov

**Comment by akosyakov** [comment]
Hi, could you try to increase memory for node?

`export NODE_OPTIONS=--max_old_space_size=4096`

See https://stackoverflow.com/questions/26094420/fatal-error-call-and-retry-last-allocation-failed-process-out-of-memory/48895989#48895989

**Comment by akosyakov** [comment]
We need to investigate what causing out of memory.
