### ISSUE TITLE
[plugin][windows] The browser example does not start on Windows

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4150]
```
root ERROR Uncaught Exception:  Error: The directory referenced by local-dir:../../plugins does not exist.
root ERROR Error: The directory referenced by local-dir:../../plugins does not exist.
    at LocalDirectoryPluginDeployerResolver.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/main/node/resolvers/plugin-local-dir-resolver.js:84:35)
    at step (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/main/node/resolvers/plugin-local-dir-resolver.js:53:23)
    at Object.next (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/main/node/resolvers/plugin-local-dir-resolver.js:34:53)
    at /Users/akos.kitta/git/theia/packages/plugin-ext/lib/main/node/resolvers/plugin-local-dir-resolver.js:28:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/main/node/resolvers/plugin-local-dir-resolver.js:24:12)
    at LocalDirectoryPluginDeployerResolver.resolve (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/main/node/resolvers/plugin-local-dir-resolver.js:69:16)
    at PluginDeployerImpl.<anonymous> (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/main/node/plugin-deployer-impl.js:274:82)
    at step (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/main/node/plugin-deployer-impl.js:56:23)
    at Object.next (/Users/akos.kitta/git/theia/packages/plugin-ext/lib/main/node/plugin-deployer-impl.js:37:53)
root INFO Theia app listening on http://localhost:3000.
Received message which is neither a response nor a notification message:
```

Furthermore, `export` cannot be used on Windows (with PowerShell and CMD.EXE), we should use [`cross-env`](https://www.npmjs.com/package/cross-env) instead.

See: https://github.com/theia-ide/theia/blob/831ad92788e33da67f67a58926ca848d426d3667/examples/browser/package.json#L62

**Comment by benoitf** [comment]
here is a comment from another PR from @akosyakov 

> Would it be possible to introduce a cli option in addition to ENV variable? then we don't need cross-env, something like theia start --plugins=local-dir:mypluginsdir

it would then avoid a CQ for [`cross-env`](https://www.npmjs.com/package/cross-env)

**Comment by kittaakos** [comment]
> it would then avoid a CQ for [`cross-env`](https://www.npmjs.com/package/cross-env)

Correct. It was there but we removed it this commit: https://github.com/theia-ide/theia/commit/70ecc03957e96100b708c09fcb60fcc1f7aca1a6#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L24.

**Comment by torbgy** [comment]
Hey, I'm struggling with something that might be similar to this...
When trying to run the browser example it provides an error: 
`$ export THEIA_DEFAULT_PLUGINS=local-dir:../../plugins && theia start
'export' is not recognized as an internal or external command, operable program or batch file.
error Command failed with exit code 1.`

Windows: 8.1
yarn: 1.7.0
Python: 2.7.3
node: 8.11.4

**Comment by kittaakos** [comment]
`export` won't work on Windows.

**Comment by kittaakos** [comment]
@torbgy, can you please tell me what are you trying to do? Maybe we can apply a local workaround for this issue.

**Comment by torbgy** [comment]
I'm trying to run the browser example provided by this [page](https://github.com/theia-ide/theia/blob/master/doc/Developing.md#building-on-windows) .
The error occurs when trying to run `yarn run start`

**Comment by kittaakos** [comment]
PR: https://github.com/theia-ide/theia/pull/4376
