### ISSUE TITLE
[Java LS] Download of LS / Offline installation

### ISSUE THREAD

**Issue by alainbernard** [theia-ide/theia#4169]
Hello,

Me again with my corporate, constrained environment :'( I'm trying to install the java extension in my Theia installation. The java extension downloads the JDT LS from Eclipse.org website. 
I've done several experiments for proxy settings: 
- system environment variables 
- npm proxy settings
- yarn proxy settings.
In any case, the download of the LS package fails:

> 
[...]
error /theiaide/node_modules/@theia/java: Command failed.
Exit code: 1
Command: node ./scripts/download-jdt-ls.js
Arguments:
Directory: /theiaide/node_modules/@theia/java
Output:
Error: Failed to download Java LS with code: 503
    at ClientRequest.h.get.response (/theiaide/node_modules/@theia/java/scripts/download-jdt-ls.js:70:28)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient (_http_client.js:558:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    at Socket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:116:13)

Then the question becomes if we can indicate an alternate link without having to recreate our own extension? I've tried to customized the "downloadUrl" property of the provided package.json but as expected it is overwritten when running the `yarn install` command. 
Is it possible to customize this property from the main `package.json` file? (I don't know if there is some kind of "inheritance" between those files)

**Comment by akosyakov** [comment]
The download script uses pure `http/https` Node.js modules to download. They don't respect env variables by default, but there are libraries which do like `request`:https://www.npmjs.com/package/request#controlling-proxy-behaviour-using-environment-variables

PRs are welcomed to improve it.
