### ISSUE TITLE
active debug session is not properly updated

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4176]
`Toggle skipping this file` command from `node-debug` extension does not work because of it https://code.visualstudio.com/docs/nodejs/nodejs-debugging#_skipping-uninteresting-code-node-chrome

**Comment by akosyakov** [comment]
Also custom request is sent with bogus arguments with `command` id as a session id:
```
root ERROR [hosted-plugin: 589] (node:589) UnhandledPromiseRejectionWarning: Error: Debug session 'toggleSkipFileStatus' not found
    at DebugMainImpl.<anonymous> (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-us.gitpod.io/55.bundle.js:5270:23)
    at step (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-us.gitpod.io/55.bundle.js:5064:23)
    at Object.next (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-us.gitpod.io/55.bundle.js:5045:53)
    at https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-us.gitpod.io/55.bundle.js:5039:71
    at new Promise (<anonymous>)
    at push.../../packages/plugin-ext/lib/main/browser/debug/debug-main.js.__awaiter (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-us.gitpod.io/55.bundle.js:5035:12)
    at DebugMainImpl.push.../../packages/plugin-ext/lib/main/browser/debug/debug-main.js.DebugMainImpl.$customRequest (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-us.gitpod.io/55.bundle.js:5263:16)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-us.gitpod.io/55.bundle.js:827:23)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-us.gitpod.io/55.bundle.js:812:41)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.receiveRequest (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-us.gitpod.io/55.bundle.js:776:45)
```
