### ISSUE TITLE
run VS Code api unit tests against Theia

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4224]
There is a VS Code extension to test implementation of VS Code APIs: https://github.com/Microsoft/vscode/tree/master/extensions/vscode-api-tests

It would be cool to run them against Theia as well.

Here launch configurations https://github.com/Microsoft/vscode/blob/98e5b5c0a30591571b5a39aa921cc3f27cea27c9/.vscode/launch.json#L58-L114 to run them.

Here is an issue to support `extensionHost` configuration for VS Code extension development: https://github.com/theia-ide/theia/issues/4016

**Comment by akosyakov** [comment]
On testing VS Code extensions: https://code.visualstudio.com/api/working-with-extensions/testing-extension

**Comment by akosyakov** [comment]
Got them running: 4 passing, 22 falling for `singlefolder-test`.

```
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 21307]
Server worker is ready to accept messages. [ID: 1 | PID: 21307]
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /workspace/theia/plugins/debug-auto-launch
root INFO Resolved "debug-auto-launch" to a VS Code extension "debug-auto-launch@1.0.0" with engines: { vscode: '^1.5.0' }
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /workspace/theia/plugins/ms-vscode.node-debug
root INFO Resolved "ms-vscode.node-debug" to a VS Code extension "node-debug@1.30.4" with engines: { vscode: '^1.29.0', node: '^8.9.3' }
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /workspace/theia/plugins/ms-vscode.node-debug2
root INFO Resolved "ms-vscode.node-debug2" to a VS Code extension "node-debug2@1.30.3" with engines: { vscode: '^1.19.0', node: '>=6.3.0' }
root INFO Theia app listening on http://0.0.0.0:3030.
Received message which is neither a response nor a notification message:
"3030"
root INFO Deploying backend plugin "debug-auto-launch@1.0.0" from "/workspace/theia/plugins/debug-auto-launch/dist/extension"
root INFO Deploying backend plugin "node-debug@1.30.4" from "/workspace/theia/plugins/ms-vscode.node-debug/dist/extension.js"
root INFO Deploying backend plugin "node-debug2@1.30.3" from "/workspace/theia/plugins/ms-vscode.node-debug2/out/src/extension"
root INFO [hosted-plugin: 21344] PLUGIN_HOST(21344) starting instance

root INFO [nsfw-watcher: 21376] Started watching: /workspace/theia/vscode-api-tests/testWorkspace
root INFO [nsfw-watcher: 21376] Started watching: /home/gitpod/.theia
root INFO [nsfw-watcher: 21376] Started watching: /workspace/theia/vscode-api-tests/testWorkspace
root INFO [hosted-plugin: 21539] PLUGIN_HOST(21539) starting instance

root INFO [nsfw-watcher: 21525] Started watching: /workspace/theia/vscode-api-tests/testWorkspace
root INFO [nsfw-watcher: 21525] Started watching: /home/gitpod/.theia
root INFO [nsfw-watcher: 21525] Started watching: /workspace/theia/vscode-api-tests/testWorkspace
root WARN EditorNavigationContribution.onStart is slow, took: 351.90000000875443 ms
root INFO Config file tasks.json does not exist under file:///workspace/theia/vscode-api-tests/testWorkspace
root ERROR Unrecognized key 'F10' in 'F10'
root ERROR Unrecognized key 'F11' in 'F11'
root INFO [hosted-plugin: 21539] PLUGIN_HOST(21539): PluginManagerExtImpl/init()

root INFO [hosted-plugin: 21539] PLUGIN_HOST(21539): initializing(/workspace/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-init.js)

root INFO [hosted-plugin: 21539] PLUGIN_HOST(21539): initializing(/workspace/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-init.js)

root INFO [hosted-plugin: 21539] Debugger contribution has been registered: node

root INFO [hosted-plugin: 21539] PLUGIN_HOST(21539): initializing(/workspace/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-init.js)

root INFO [hosted-plugin: 21539] Debugger contribution has been registered: extensionHost
Debugger contribution has been registered: node2

root INFO [hosted-plugin: 21539] PLUGIN_HOST(21539): PluginManagerExtImpl/loadPlugin(/workspace/theia/plugins/debug-auto-launch/dist/extension)

root INFO [hosted-plugin: 21539] PLUGIN_HOST(21539): PluginManagerExtImpl/loadPlugin(/workspace/theia/plugins/ms-vscode.node-debug/dist/extension.js)

root INFO [hosted-plugin: 21539] Debug configuration provider has been registered: node

root INFO [hosted-plugin: 21539] PLUGIN_HOST(21539): PluginManagerExtImpl/loadPlugin(/workspace/theia/plugins/ms-vscode.node-debug2/out/src/extension)

root ERROR [hosted-plugin: 21539] Could not identify plugin for 'Theia' require call from /workspace/theia/vscode-api-tests/out/singlefolder-tests/commands.test.js

root INFO [hosted-plugin: 21539]

root INFO [hosted-plugin: 21539]

root INFO [hosted-plugin: 21539]   commands namespace tests

root INFO [hosted-plugin: 21539]     1) getCommands

root INFO [hosted-plugin: 21539]     2) command with args

root INFO [hosted-plugin: 21539]     3) editorCommand with extra args

root INFO [hosted-plugin: 21539]     4) api-command: vscode.previewHtml

root INFO [hosted-plugin: 21539]     5) api-command: vscode.diff

root INFO [hosted-plugin: 21539]     6) api-command: vscode.open

root INFO [hosted-plugin: 21539]

root INFO [hosted-plugin: 21539]   Configuration tests

root INFO [hosted-plugin: 21539]     7) configurations, language defaults

root INFO [hosted-plugin: 21539]     8) configuration, defaults

root INFO [hosted-plugin: 21539]     9) configuration, name vs property

root INFO [hosted-plugin: 21539]

root INFO [hosted-plugin: 21539]   editor tests

root INFO [hosted-plugin: 21539]     10) insert snippet

root INFO [hosted-plugin: 21539]     11) "after each" hook: closeAllEditors for "insert snippet"

root INFO [hosted-plugin: 21539]

root INFO [hosted-plugin: 21539]   env-namespace

root INFO [hosted-plugin: 21539]     12) env is set

root INFO [hosted-plugin: 21539]     13) env is readonly

root INFO [hosted-plugin: 21539]
  languages namespace tests

root INFO [hosted-plugin: 21539]     14) setTextDocumentLanguage -> close/open event

root INFO [hosted-plugin: 21539]     ✓ setTextDocumentLanguage -> error when language does not exist (38ms)

root INFO [hosted-plugin: 21539]     ✓ diagnostics, read & event

root INFO [hosted-plugin: 21539]     15) diagnostics & CodeActionProvider

root INFO [hosted-plugin: 21539]     16) completions with document filters

root INFO [hosted-plugin: 21539]
  window namespace tests

root INFO [hosted-plugin: 21539]     QuickInput tests

root INFO [hosted-plugin: 21539]       17) createQuickPick, select second

root INFO [hosted-plugin: 21539]       18) "after each" hook: closeAllEditors for "createQuickPick, select second"

root INFO [hosted-plugin: 21539]

root INFO [hosted-plugin: 21539]   Webview tests

root INFO [hosted-plugin: 21539]     ✓ webviews should be able to send and receive messages (91ms)

root INFO [hosted-plugin: 21539]     19) "after each" hook for "webviews should be able to send and receive messages"

root INFO [hosted-plugin: 21539]

root INFO [hosted-plugin: 21539]   window namespace tests

root INFO [hosted-plugin: 21539]     20) editor, active text editor

root INFO [hosted-plugin: 21539]     21) "after each" hook: closeAllEditors for "editor, active text editor"

root INFO [hosted-plugin: 21539]
  workspace-namespace

root INFO [hosted-plugin: 21539]     ✓ MarkdownString

root INFO [hosted-plugin: 21539]     22) "after each" hook: closeAllEditors for "MarkdownString"

root INFO [hosted-plugin: 21539]

root INFO [hosted-plugin: 21539]

root INFO [hosted-plugin: 21539]   4 passing (1s)
  22 failing

root INFO [hosted-plugin: 21539]

root INFO [hosted-plugin: 21539]   1) commands namespace tests getCommands:
     TypeError: vscode_1.commands.getCommands is not a function
      at Context.<anonymous> (vscode-api-tests/out/singlefolder-tests/commands.test.js:13:36)


root INFO [hosted-plugin: 21539]   2) commands namespace tests command with args:
     Error: The command 't1' cannot be executed. There are no active handlers available for the command. (args: ["start"])
      at CommandRegistry.<anonymous> (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95636:31)
      at step (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95443:23)
      at Object.next (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95424:53)
      at https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95418:71
      at new Promise (<anonymous>)
      at ../../packages/core/lib/common/command.js.__awaiter (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95414:12)
      at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95623:16)
      at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:4626:72)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:827:23)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:812:41)

  3) commands namespace tests editorCommand with extra args:
     Error: Function registerTextEditorCommand is not implemented
      at Object.registerTextEditorCommand (packages/plugin-ext/src/plugin/plugin-context.ts:163:23)
      at Context.<anonymous> (vscode-api-tests/out/singlefolder-tests/commands.test.js:50:46)

  4) commands namespace tests api-command: vscode.previewHtml:
     AssertionError [ERR_ASSERTION]: undefined == true
      at Context.<anonymous> (vscode-api-tests/out/singlefolder-tests/commands.test.js:74:16)
      at <anonymous>

  5) commands namespace tests api-command: vscode.diff:
     Error: The command 'vscode.diff' cannot be executed. There are no active handlers available for the command. (args: [{"$mid":1,"path":"a","scheme":"sc"},{"$mid":1,"path":"b","scheme":"sc"},"DIFF"])
      at CommandRegistry.<anonymous> (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95636:31)
      at step (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95443:23)
      at Object.next (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95424:53)
      at https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95418:71
      at new Promise (<anonymous>)
      at ../../packages/core/lib/common/command.js.__awaiter (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95414:12)
      at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95623:16)
      at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:4626:72)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:827:23)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:812:41)


root INFO [hosted-plugin: 21539]   6) commands namespace tests api-command: vscode.open:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at vscode_1.commands.executeCommand.then (vscode-api-tests/out/singlefolder-tests/commands.test.js:103:83)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)


root INFO [hosted-plugin: 21539]   7) Configuration tests configurations, language defaults:
     AssertionError [ERR_ASSERTION]: undefined deepEqual { 'editor.lineNumbers': 'off', 'editor.tabSize': 2 }
      at Context.<anonymous> (vscode-api-tests/out/singlefolder-tests/configuration.test.js:13:16)


root INFO [hosted-plugin: 21539]   8) Configuration tests configuration, defaults:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at Context.test (vscode-api-tests/out/singlefolder-tests/configuration.test.js:20:16)

  9) Configuration tests configuration, name vs property:

      AssertionError [ERR_ASSERTION]: false == true
      + expected - actual

      -false
      +true

      at Context.test (vscode-api-tests/out/singlefolder-tests/configuration.test.js:33:16)


root INFO [hosted-plugin: 21539]   10) editor tests insert snippet:
     TypeError: Cannot read property 'uri' of undefined
      at Object.<anonymous> (packages/plugin-ext/src/plugin/plugin-context.ts:212:89)
      at step (packages/plugin-ext/lib/plugin/plugin-context.js:32:23)
      at Object.next (packages/plugin-ext/lib/plugin/plugin-context.js:13:53)
      at packages/plugin-ext/lib/plugin/plugin-context.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (packages/plugin-ext/lib/plugin/plugin-context.js:3:12)
      at Object.showTextDocument (packages/plugin-ext/lib/plugin/plugin-context.js:165:24)
      at vscode_1.workspace.openTextDocument.then.doc (vscode-api-tests/out/singlefolder-tests/editor.test.js:15:40)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

  11) editor tests "after each" hook: closeAllEditors for "insert snippet":
     Error: The command 'workbench.action.closeAllEditors' cannot be executed. There are no active handlers available for the command.
      at CommandRegistry.<anonymous> (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95636:31)
      at step (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95443:23)
      at Object.next (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95424:53)
      at https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95418:71
      at new Promise (<anonymous>)
      at ../../packages/core/lib/common/command.js.__awaiter (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95414:12)
      at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95623:16)
      at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:4626:72)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:827:23)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:812:41)

  12) env-namespace env is set:

      AssertionError [ERR_ASSERTION]: 'undefined' == 'string'
      + expected - actual

      -undefined
      +string

      at Context.<anonymous> (vscode-api-tests/out/singlefolder-tests/env.test.js:11:16)


root INFO [hosted-plugin: 21539]   13) env-namespace env is readonly:
     AssertionError [ERR_ASSERTION]: Missing expected exception.
      at Context.<anonymous> (vscode-api-tests/out/singlefolder-tests/env.test.js:18:16)

  14) languages namespace tests setTextDocumentLanguage -> close/open event:
     TypeError: Cannot read property 'languageId' of undefined
      at Context.<anonymous> (vscode-api-tests/out/singlefolder-tests/languages.test.js:15:31)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

  15) languages namespace tests diagnostics & CodeActionProvider:
     Error: The command 'vscode.executeCodeActionProvider' cannot be executed. There are no active handlers available for the command. (args: [{"$mid":1,"path":"path.far","scheme":"ttt"},{"_start":{"_line":0,"_character":0},"_end":{"_line":0,"_character":10}}])
      at CommandRegistry.<anonymous> (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95636:31)
      at step (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95443:23)
      at Object.next (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95424:53)
      at https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95418:71
      at new Promise (<anonymous>)
      at ../../packages/core/lib/common/command.js.__awaiter (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95414:12)
      at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95623:16)
      at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:4626:72)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:827:23)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:812:41)

  16) languages namespace tests completions with document filters:
     Error: The command 'vscode.executeCompletionItemProvider' cannot be executed. There are no active handlers available for the command. (args: [{"$mid":1,"path":"/bower.json","scheme":"file"},{"_line":1,"_character":0}])
      at CommandRegistry.<anonymous> (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95636:31)
      at step (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95443:23)
      at Object.next (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95424:53)
      at https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95418:71
      at new Promise (<anonymous>)
      at ../../packages/core/lib/common/command.js.__awaiter (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95414:12)
      at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95623:16)
      at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:4626:72)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:827:23)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:812:41)

  17) window namespace tests QuickInput tests createQuickPick, select second:
     TypeError: vscode_1.window.createQuickPick is not a function
      at createQuickPick (vscode-api-tests/out/singlefolder-tests/quickInput.test.js:179:39)
      at Context.<anonymous> (vscode-api-tests/out/singlefolder-tests/quickInput.test.js:18:31)

  18) window namespace tests QuickInput tests "after each" hook: closeAllEditors for "createQuickPick, select second":
     Error: The command 'workbench.action.closeAllEditors' cannot be executed. There are no active handlers available for the command.
      at CommandRegistry.<anonymous> (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95636:31)
      at step (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95443:23)
      at Object.next (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95424:53)
      at https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95418:71
      at new Promise (<anonymous>)
      at ../../packages/core/lib/common/command.js.__awaiter (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95414:12)
      at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95623:16)
      at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:4626:72)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:827:23)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:812:41)


root INFO [hosted-plugin: 21539]   19) Webview tests "after each" hook for "webviews should be able to send and receive messages":
     Error: The command 'workbench.action.closeAllEditors' cannot be executed. There are no active handlers available for the command.
      at CommandRegistry.<anonymous> (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95636:31)
      at step (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95443:23)
      at Object.next (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95424:53)
      at https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95418:71
      at new Promise (<anonymous>)
      at ../../packages/core/lib/common/command.js.__awaiter (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95414:12)
      at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95623:16)
      at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:4626:72)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:827:23)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:812:41)

  20) window namespace tests editor, active text editor:
     TypeError: Cannot read property 'uri' of undefined
      at Object.<anonymous> (packages/plugin-ext/src/plugin/plugin-context.ts:212:89)
      at step (packages/plugin-ext/lib/plugin/plugin-context.js:32:23)
      at Object.next (packages/plugin-ext/lib/plugin/plugin-context.js:13:53)
      at packages/plugin-ext/lib/plugin/plugin-context.js:7:71
      at new Promise (<anonymous>)
      at __awaiter (packages/plugin-ext/lib/plugin/plugin-context.js:3:12)
      at Object.showTextDocument (packages/plugin-ext/lib/plugin/plugin-context.js:165:24)
      at Context.test (vscode-api-tests/out/singlefolder-tests/window.test.js:15:31)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:189:7)

  21) window namespace tests "after each" hook: closeAllEditors for "editor, active text editor":
     Error: The command 'workbench.action.closeAllEditors' cannot be executed. There are no active handlers available for the command.
      at CommandRegistry.<anonymous> (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95636:31)
      at step (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95443:23)
      at Object.next (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95424:53)
      at https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95418:71
      at new Promise (<anonymous>)
      at ../../packages/core/lib/common/command.js.__awaiter (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95414:12)
      at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95623:16)
      at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:4626:72)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:827:23)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:812:41)

  22) workspace-namespace "after each" hook: closeAllEditors for "MarkdownString":
     Error: The command 'workbench.action.closeAllEditors' cannot be executed. There are no active handlers available for the command.
      at CommandRegistry.<anonymous> (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95636:31)
      at step (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95443:23)
      at Object.next (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95424:53)
      at https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95418:71
      at new Promise (<anonymous>)
      at ../../packages/core/lib/common/command.js.__awaiter (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95414:12)
      at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/bundle.js:95623:16)
      at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:4626:72)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:827:23)
      at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (https://3030-ba36598e-e862-400e-8c56-7c198d488fa4.ws-eu.gitpod.io/55.bundle.js:812:41)




```

**Comment by akosyakov** [comment]
In order to run:
- install https://github.com/theia-ide/vscode-builtin-extensions
- copy `node-debug` and `node-debug2` VS Code extensions from `vscode-builtin-extensions/extensions` folder into `theia/plugins` folder
  - you need to exclude `@theia/node-js` from the app to use VS Code extensions instead
- copy `vscode-builtin-extensions/vscode/extensions/vscode-api-tests` to `theia/vscode-api-tests`
- add the launch configuration:
```json
{
            "name": "Launch VS Code Tests",
            "type": "node",
            "request": "launch",
            "args": [
                "/workspace/theia/examples/browser/src-gen/backend/main.js",
                "${workspaceFolder}/vscode-api-tests/testWorkspace",
                "--port", "3030",
                "--hostname", "0.0.0.0",
                "--extensionTestsPath=${workspaceFolder}/vscode-api-tests/out/singlefolder-tests"
            ],
            "env": {
                "THEIA_DEFAULT_PLUGINS": "local-dir:${workspaceFolder}/plugins"
            },
            "stopOnEntry": false,
            "sourceMaps": true,
            "outFiles": [
                "${workspaceFolder}/../.js"
            ],
            "console": "integratedTerminal"
        }
```
- start Theia, open `theia` folder and launch the config

**Comment by akosyakov** [comment]
Fixed installation of VS Code apis for test, the result is not much better 😞 

5 passing, 21 failing
