### ISSUE TITLE
[plugin][java] Cannot read property 'hasOwnProperty' of undefined

### ISSUE THREAD

**Issue by svor** [theia-ide/theia#4254]
While trying Java VS Code as a plugin I can see next problem when vscode-java extension is initializing: 
```
root ERROR [hosted-plugin: 28894] (node:28894) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'hasOwnProperty' of undefined
    at /tmp/vscode-unpacked/redhat.java-0.38.0.vsix/extension/dist/extension.js:1:221949
    at i.workspace.workspaceFolders.i.workspace.workspaceFolders.length.i.workspace.workspaceFolders.forEach.e (/tmp/vscode-unpacked/redhat.java-0.38.0.vsix/extension/dist/extension.js:1:222768)
    at Array.forEach (<anonymous>)
    at Object.l [as excludeProjectSettingsFiles] (/tmp/vscode-unpacked/redhat.java-0.38.0.vsix/extension/dist/extension.js:1:221788)
    at w.onReady.then (/tmp/vscode-unpacked/redhat.java-0.38.0.vsix/extension/dist/extension.js:1:117108)
    at <anonymous>
```
Steps to reproduce:
1. Exclude `java-extension` in Theia project;
2. Deploy` vscode-java` extension by id: **vscode:extension/redhat.java**

**Comment by benoitf** [comment]
hello @svor could you say which theia version you're using. master branch ?

**Comment by svor** [comment]
@benoitf master branch

**Comment by tsmaeder** [comment]
Looks a bit like theia is not sending multi-workspace folder initialization requests?
