### ISSUE TITLE
Running hosted Theia with --port parameter failing

### ISSUE THREAD

**Issue by idoprz** [theia-ide/theia#4361]
Running the host Theia with --port XXXX then running hosted Theia fails to parse the port.
For example run Theia:
yarn start --port 3000
then run a hosted plugin fails with this error:

Starting the master backend process without a timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 3392]
Server worker is ready to accept messages. [ID: 1 | PID: 3392]
root ERROR Failed to start the backend application.
root ERROR Error: Invalid listen argument: [ 3000, 3030 ]
    at Server.listen (net.js:1501:9)
    at BackendApplication.<anonymous> (/mnt/c/Users/i040767/repos/theia/packages/core/lib/node/backend-application.js:273:32)
    at step (/mnt/c/Users/i040767/repos/theia/packages/core/lib/node/backend-application.js:59:23)
    at Object.next (/mnt/c/Users/i040767/repos/theia/packages/core/lib/node/backend-application.js:40:53)
    at /mnt/c/Users/i040767/repos/theia/packages/core/lib/node/backend-application.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (/mnt/c/Users/i040767/repos/theia/packages/core/lib/node/backend-application.js:30:12)
    at BackendApplication.start (/mnt/c/Users/i040767/repos/theia/packages/core/lib/node/backend-application.js:217:16)
    at /mnt/c/Users/i040767/repos/theia/examples/browser/src-gen/backend/server.js:34:28
    at <anonymous>

**Comment by akosyakov** [comment]
part of https://github.com/theia-ide/theia/issues/4213

@idoprz Could you have a look please? the starting point: https://github.com/theia-ide/theia/issues/4213#issuecomment-460532325
