### ISSUE TITLE
[ci][git][travis] Browser tests fail on Linux

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#4395]
see 

```
@theia/example-browser: [chrome #0-4] 6 failing
@theia/example-browser: [chrome #0-4]
@theia/example-browser: [chrome #0-4] 1) terminal UI should open a new terminal and then close it:
@theia/example-browser: [chrome #0-4] unknown error: Element <div class="p-MenuBar-itemLabel">...</div> is not clickable at point (357, 14). Other element would receive the click: <p id="notification-text-3-...-|">Could not find Git on the PATH.</p>
@theia/example-browser: [chrome #0-4] Error: An unknown server-side error occurred while processing the command.
@theia/example-browser: [chrome #0-4]     at elementIdClick("0.5138757508818415-9") - click.js:20:22
@theia/example-browser: [chrome #0-4]
@theia/example-browser: [chrome #0-4] 2) call hierarchy view UI call hierarchy view should toggle-on then toggle-off:
@theia/example-browser: [chrome #0-4] unknown error: Element <div class="p-MenuBar-itemLabel">...</div> is not clickable at point (208, 14). Other element would receive the click: <div class="text">...</div>
@theia/example-browser: [chrome #0-4] Error: An unknown server-side error occurred while processing the command.
@theia/example-browser: [chrome #0-4]     at elementIdClick("0.5138757508818415-10") - click.js:20:22
@theia/example-browser: [chrome #0-4]
@theia/example-browser: [chrome #0-4] 3) extensions view UI extensions view should toggle-on then toggle-off:
@theia/example-browser: [chrome #0-4] unknown error: Element <div class="p-MenuBar-itemLabel">...</div> is not clickable at point (208, 14). Other element would receive the click: <div class="text">...</div>
@theia/example-browser: [chrome #0-4] Error: An unknown server-side error occurred while processing the command.
@theia/example-browser: [chrome #0-4]     at elementIdClick("0.5138757508818415-10") - click.js:20:22
@theia/example-browser: [chrome #0-4]
@theia/example-browser: [chrome #0-4] 4) files view UI files view should toggle-on then toggle-off:
@theia/example-browser: [chrome #0-4] unknown error: Element <div class="p-MenuBar-itemLabel">...</div> is not clickable at point (208, 14). Other element would receive the click: <div class="text">...</div>
@theia/example-browser: [chrome #0-4] Error: An unknown server-side error occurred while processing the command.
@theia/example-browser: [chrome #0-4]     at elementIdClick("0.5138757508818415-10") - click.js:20:22
@theia/example-browser: [chrome #0-4]
@theia/example-browser: [chrome #0-4] 5) git view UI git view should toggle-on then toggle-off:
@theia/example-browser: [chrome #0-4] unknown error: Element <div class="p-MenuBar-itemLabel">...</div> is not clickable at point (208, 14). Other element would receive the click: <div class="text">...</div>
@theia/example-browser: [chrome #0-4] Error: An unknown server-side error occurred while processing the command.
@theia/example-browser: [chrome #0-4]     at elementIdClick("0.5138757508818415-10") - click.js:20:22
@theia/example-browser: [chrome #0-4]
@theia/example-browser: [chrome #0-4] 6) search view UI should start with search view visible:
@theia/example-browser: [chrome #0-4] expected false to be true
@theia/example-browser: [chrome #0-4] AssertionError: expected false to be true
@theia/example-browser: [chrome #0-4]     at Context.<anonymous> (/home/travis/build/theia-ide/theia/examples/browser/lib/test/top-panel/top-panel.ui-spec.js:223:65)
@theia/example-browser: [chrome #0-4]     at new Promise (<anonymous>)
@theia/example-browser: [chrome #0-4]     at new F (/home/travis/build/theia-ide/theia/node_modules/core-js/library/modules/_export.js:36:28)
```

from https://api.travis-ci.org/v3/job/496059660/log.txt

it looks like git is not found on the PATH. `git version 2.15.1` should be available, according to system info from logs.

**Comment by marcdumais-work** [comment]
The same or very similar is also happening for Linux: https://travis-ci.org/theia-ide/theia/jobs/496441098#L3095

**Comment by marcdumais-work** [comment]
This error comes-up a few times: 
`@theia/example-browser: root ERROR Cannot use Git from the PATH when the LOCAL_GIT_DIRECTORY or the GIT_EXEC_PATH environment variables are set.`

https://travis-ci.org/theia-ide/theia/jobs/496441098#L3013

**Comment by marcdumais-work** [comment]
Something [else](https://travis-ci.org/theia-ide/theia/jobs/496441098#L1607) potentially suspicious:
```
$ git config --global --unset protocol.version
The command "git config --global --unset protocol.version" exited with 5.
```

**Comment by kittaakos** [comment]
> The command "git config --global --unset protocol.version" exited with 5.

> you try to unset/set an option for which multiple lines match (ret=5), or

Source: https://git-scm.com/docs/git-config#_description

I will look into this later... The build was green by the time I have merged it, I have no idea what causes it.

![screen shot 2019-02-21 at 14 03 52](https://user-images.githubusercontent.com/1405703/53170935-a265b900-35e1-11e9-93b1-76907bbf46f2.jpg)

![screen shot 2019-02-21 at 14 04 02](https://user-images.githubusercontent.com/1405703/53170940-a5f94000-35e1-11e9-9e74-cc1e7606b054.jpg)

**Comment by kittaakos** [comment]
> also happening for Linux

No, it is happening on Linux. Check the log reported by @AlexTugarev, it says:

> Client:
> Version:      17.09.0-ce
> API version:  1.32
> Go version:   go1.8.3
> Git commit:   afdb6d4
> Built:        Tue Sep 26 22:42:38 2017
> OS/Arch:      linux/amd64

I have updated the title to reflect it.

**Comment by kittaakos** [comment]
Nice, according to [this](https://travis-ci.community/t/got-to-fail-carthage-outdated-command-because-of-git-protocol-version/2359/8), the git `protocol.version` change has been reverted by the Travis guys.
