### ISSUE TITLE
When modifying the file, the console reported an error. The error message is as follows

### ISSUE THREAD

**Issue by bj-white** [theia-ide/theia#4402]
logger-protocol.ts:112 root ERROR Error: Request 'setContent' failed
    at Proxy.<anonymous> (http://192.168.153.138:3000/bundle.js:52:133973)
    at e.<anonymous> (http://192.168.153.138:3000/bundle.js:30:148557)
    at http://192.168.153.138:3000/bundle.js:30:146446
    at Object.next (http://192.168.153.138:3000/bundle.js:30:146551)
    at a (http://192.168.153.138:3000/bundle.js:30:145297)

**Comment by kittaakos** [comment]
Same as #4403.
