### ISSUE TITLE
Running the **vscode-mock-debug** failing

### ISSUE THREAD

**Issue by idoprz** [theia-ide/theia#4453]
### Description
Running the **vscode-mock-debug** failing because it's not opening the input box for resolving the ${command:AskForProgramName}

### Reproduction Steps
git clone https://github.com/Microsoft/vscode-mock-debug.git
generate the mock launch config
run the generated configuration

**Diagnostics:** 
root ERROR [hosted-plugin: 18883] (node:19221) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open '/mnt/c/Users/i040767/repos/vscode-mock-debug/${command:AskForProgramName}'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at MockRuntime.loadSource (/mnt/c/Users/i040767/repos/vscode-mock-debug/out/mockRuntime.js:113:38)
    at MockRuntime.start (/mnt/c/Users/i040767/repos/vscode-mock-debug/out/mockRuntime.js:29:14)
    at MockDebugSession.<anonymous> (/mnt/c/Users/i040767/repos/vscode-mock-debug/out/mockDebug.js:93:27)
    at Generator.next (<anonymous>)
    at fulfilled (/mnt/c/Users/i040767/repos/vscode-mock-debug/out/mockDebug.js:7:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
root ERROR [hosted-plugin: 18883] (node:19221) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:19221) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Hosted instance has been terminated

**Comment by benoitf** [comment]
hello, please write on which theia version you're performing the test

**Comment by idoprz** [comment]
> hello, please write on which theia version you're performing the test

I tested it from master

**Comment by sgraband** [comment]
`${command:...}` variable substitution supported in debug configurations.
