### ISSUE TITLE
Cannot start the electron example

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4461]
Failed on both Windows and macOS.

```
git clean -ffqxd && git rev-parse --short HEAD && node --version && python --version && yarn --force && yarn run rebuild:electron && yarn --cwd ./examples/electron/ start
431fa673
v8.14.0
Python 2.7.10
yarn install v1.12.3
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
[3/5] 🚚  Fetching packages...

[...]

lerna success - @theia/example-electron
✨  Done in 189.81s.
yarn run v1.12.3
$ theia check:hoisted -s
🔍  Analyzing hoisted dependencies in the Theia extensions...
📖  Summary:
The following dependency issues were detected in '@theia/core':
 - error: Dependency 'ajv' [6.5.4] was not hoisted to the root 'node_modules' folder. The same dependency already exists with version 6.5.3 at '/Users/akos.kitta/git/theia/node_modules/ajv'.
The following dependency issues were detected in '@theia/keymaps':
 - error: Dependency 'ajv' [6.5.4] was not hoisted to the root 'node_modules' folder. The same dependency already exists with version 6.5.3 at '/Users/akos.kitta/git/theia/node_modules/ajv'.
The following dependency issues were detected in '@theia/workspace':
 - error: Dependency 'ajv' [6.5.4] was not hoisted to the root 'node_modules' folder. The same dependency already exists with version 6.5.3 at '/Users/akos.kitta/git/theia/node_modules/ajv'.
⚠️  This is a reminder to fix the dependency issues.
✨  Done in 0.34s.
✨  Done in 242.45s.
yarn run v1.12.3
$ theia rebuild:electron
Processing node-pty
Processing vscode-nsfw
Processing find-git-repositories
✔ Rebuild Complete
✨  Done in 7.13s.
yarn run v1.12.3
$ theia start
Starting the master backend process with 5000 (ms) timeout.
Starting server worker...
Server worker has been started. [ID: 1 | PID: 6803]
/Users/akos.kitta/git/theia/node_modules/electron-store/index.js:8
		const defaultCwd = (electron.app || electron.remote.app).getPath('userData');
		                                                    ^

TypeError: Cannot read property 'app' of undefined
    at new ElectronStore (/Users/akos.kitta/git/theia/node_modules/electron-store/index.js:8:55)
    at Object.<anonymous> (/Users/akos.kitta/git/theia/examples/electron/src-gen/frontend/electron-main.js:23:23)
    at Object.<anonymous> (/Users/akos.kitta/git/theia/examples/electron/src-gen/frontend/electron-main.js:161:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (module.js:683:10)
    at startup (bootstrap_node.js:196:16)
Server worker has been disconnected. [ID: 1 | PID: 6803]
Server worker failed to start within 5000 milliseconds.
Pass a greater value as '--startup-timeout' option to increase the timeout or a negative to disable.
root INFO Theia app listening on http://localhost:59905.
root INFO Server worker has been stopped. [ID: 1 | PID: 6803]
✨  Done in 5.44s.
```

**Comment by marcdumais-work** [comment]
I can reproduce on Linux too. I tried to go back a few commits, to see if the 0.4.0 release had something to do with this, but I got the same result.

**Comment by kittaakos** [comment]
It works with 45f8993d which is one commit before we introduced the [`electron-store`](https://github.com/theia-ide/theia/pull/4370).

**Note**: it does not necessarily mean that the `electron-store` is the breaking change.
