### ISSUE TITLE
Using Vscode GO extension generate an error when putting focus on a "*.go" file

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#4464]
### Description
I am using the VSCODE-GO version 0.9.2 plugins
When putting focus on a GO file, I get the following error on the console:

root ERROR [hosted-plugin: 7489] { Error: Unknown decoration type key: TextEditorDecorationType1
    at MonacoEditorService.CodeEditorServiceImpl.resolveDecorationOptions (http://localhost:3000/vs/editor/editor.main.js:85341:23)
    at StandaloneEditor.CodeEditorWidget._resolveDecorationOptions (http://localhost:3000/vs/editor/editor.main.js:92924:44)
    at StandaloneEditor.CodeEditorWidget.setDecorationsFast (http://localhost:3000/vs/editor/editor.main.js:92563:78)
    at TextEditorMain.push.../../packages/plugin-ext/lib/main/browser/text-editor-main.js.TextEditorMain.setDecorationsFast (http://localhost:3000/81.bundle.js:12079:34)

**Comment by vince-fugnitto** [comment]
@lmcbout do you still have `bookmarks` plugin installed ?
I think it's coming from the `bookmarks` plugin since it's attempting to add an image
 to the `gutter-path`.

**Comment by vince-fugnitto** [comment]
If you still have `bookmarks` included can you test without it?
 I have the `go` extension working correctly on my end and do not notice the issue you mentioned.

**Comment by lmcbout** [comment]
@vince-fugnitto  you are right, I just remove the "Bookmarks" vscode extension and the error is gone.
Thanks
