### ISSUE TITLE
ERROR error: option `porcelain' takes no value

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#4478]
### Description
latest next build git error

### Reproduction Steps

**OS and Theia version:**

```log
@theia/core 0.5.0-next.e1b5a60f
@theia/output 0.5.0-next.e1b5a60f
@theia/process 0.5.0-next.e1b5a60f
@theia/filesystem 0.5.0-next.e1b5a60f
@theia/variable-resolver 0.5.0-next.e1b5a60f
@theia/workspace 0.5.0-next.e1b5a60f
@theia/languages 0.5.0-next.e1b5a60f
@theia/editor 0.5.0-next.e1b5a60f
@theia/navigator 0.5.0-next.e1b5a60f
@theia/markers 0.5.0-next.e1b5a60f
@theia/outline-view 0.5.0-next.e1b5a60f
@theia/monaco 0.5.0-next.e1b5a60f
@theia/callhierarchy 0.5.0-next.e1b5a60f
@theia/json 0.5.0-next.e1b5a60f
@theia/userstorage 0.5.0-next.e1b5a60f
@theia/preferences 0.5.0-next.e1b5a60f
@theia/terminal 0.5.0-next.e1b5a60f
@theia/task 0.5.0-next.e1b5a60f
@theia/cpp 0.5.0-next.e1b5a60f
@theia/docker 0.2.0-next.771d7851
@theia/editorconfig 0.5.0-next.e1b5a60f
@theia/editor-preview 0.5.0-next.e1b5a60f
@theia/extension-manager 0.5.0-next.e1b5a60f
@theia/file-search 0.5.0-next.e1b5a60f
@theia/git 0.5.0-next.e1b5a60f
@theia/go 0.4.0-next.e3cdab90
@theia/keymaps 0.5.0-next.e1b5a60f
@theia/getting-started 0.5.0-next.e1b5a60f
@theia/java 0.5.0-next.e1b5a60f
@theia/yaml 0.2.0-next.13bf0365
@theia/merge-conflicts 0.5.0-next.e1b5a60f
@theia/messages 0.5.0-next.e1b5a60f
@theia/metrics 0.5.0-next.e1b5a60f
@theia/mini-browser 0.5.0-next.e1b5a60f
@theia/php 0.1.0-next.a7766726
@theia/preview 0.5.0-next.e1b5a60f
@theia/plantuml 0.2.0-next.7fa169ac
@theia/console 0.5.0-next.e1b5a60f
@theia/debug 0.5.0-next.e1b5a60f
@theia/search-in-workspace 0.5.0-next.e1b5a60f
@theia/plugin-ext 0.5.0-next.e1b5a60f
@theia/plugin-ext-vscode 0.5.0-next.e1b5a60f
@theia/python 0.5.0-next.e1b5a60f
@theia/ruby 0.2.0-next.cf5d1fa8
@theia/rust 0.4.0-next.4597546c
@theia/textmate-grammars 0.5.0-next.e1b5a60f
@theia/typescript 0.5.0-next.e1b5a60f
theia-sprotty 0.2.0-next.90d9d8c2
theia-yang-extension 0.2.0-next.d1fb4585
```

**Diagnostics:** 
```log
root ERROR The command `git status --untracked-files=all --branch --porcelain=2 -z` exited with an unexpected code: 129. The caller should either handle this error, or expect that exit code.
root ERROR error: option `porcelain' takes no value
usage: git status [<options>] [--] <pathspec>...

    -v, --verbose         be verbose
    -s, --short           show status concisely
    -b, --branch          show branch information
    --porcelain           machine-readable output
    --long                show status in long format (default)
    -z, --null            terminate entries with NUL
    -u, --untracked-files[=<mode>]
                          show untracked files, optional modes: all, normal, no. (Default: all)
    --ignored             show ignored files
    --ignore-submodules[=<when>]
                          ignore changes to submodules, optional when: all, dirty, untracked. (Default: all)
    --column[=<style>]    list untracked files in columns


root ERROR Error occurred while synchronizing the status of the repository. file:///home/project/JavaWorkSpace/MiaoScript GitError: error: option `porcelain' takes no value
usage: git status [<options>] [--] <pathspec>...

    -v, --verbose         be verbose
    -s, --short           show status concisely
    -b, --branch          show branch information
    --porcelain           machine-readable output
    --long                show status in long format (default)
    -z, --null            terminate entries with NUL
    -u, --untracked-files[=<mode>]
                          show untracked files, optional modes: all, normal, no. (Default: all)
    --ignored             show ignored files
    --ignore-submodules[=<when>]
                          ignore changes to submodules, optional when: all, dirty, untracked. (Default: all)
    --column[=<style>]    list untracked files in columns


    at new GitError (/home/theia/node_modules/dugite-extra/lib/core/git.js:81:28)
    at Object.<anonymous> (/home/theia/node_modules/dugite-extra/lib/core/git.js:256:27)
    at step (/home/theia/node_modules/dugite-extra/lib/core/git.js:50:23)
    at Object.next (/home/theia/node_modules/dugite-extra/lib/core/git.js:31:53)
    at fulfilled (/home/theia/node_modules/dugite-extra/lib/core/git.js:22:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by AlexTugarev** [comment]
@502647092, is this the same as https://github.com/theia-ide/theia/issues/1162? Please check the version of git.

**Comment by 502647092** [comment]
```sh
$ git version
git version 2.7.4
```
Thanks
