### ISSUE TITLE
multi git repo switch error

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#4545]
### Description

multi git repo can't switch
![image](https://user-images.githubusercontent.com/10203793/54264917-27276f80-45af-11e9-93a1-2316dfdce3fd.png)

### Reproduction Steps
update to latest next version
0.5.0-next.fc1edf11

**Diagnostics:** 
```txt
root ERROR Uncaught Exception:  GitError: fatal: ambiguous argument 'HEAD~': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

root ERROR GitError: fatal: ambiguous argument 'HEAD~': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

    at new GitError (/home/theia/node_modules/dugite-extra/lib/core/git.js:81:28)
    at Object.<anonymous> (/home/theia/node_modules/dugite-extra/lib/core/git.js:256:27)
    at step (/home/theia/node_modules/dugite-extra/lib/core/git.js:50:23)
    at Object.next (/home/theia/node_modules/dugite-extra/lib/core/git.js:31:53)
    at fulfilled (/home/theia/node_modules/dugite-extra/lib/core/git.js:22:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by 502647092** [comment]
Maybe it's a strange mistake.
```
root ERROR The command `git --no-optional-locks status --untracked-files=all --branch --porcelain=2 -z` exited with an unexpected code: 128. The caller should either handle this error, or expect that exit code.
root ERROR fatal: bad object HEAD

root ERROR Error occurred while synchronizing the status of the repository. file:///home/project/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/.Trash-0/files/a14e0059-9743-4597-96c3-b0df77f85cf9/JavaWorkSpace/MiaoScript GitError: fatal: bad object HEAD

    at new GitError (/home/theia/node_modules/dugite-extra/lib/core/git.js:81:28)
    at Object.<anonymous> (/home/theia/node_modules/dugite-extra/lib/core/git.js:256:27)
    at step (/home/theia/node_modules/dugite-extra/lib/core/git.js:50:23)
    at Object.next (/home/theia/node_modules/dugite-extra/lib/core/git.js:31:53)
    at fulfilled (/home/theia/node_modules/dugite-extra/lib/core/git.js:22:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```
