### ISSUE TITLE
next version crash: Error: Couldn't find any versions for "@theia/monaco" that matches "0.5.0-next.74d71420"

### ISSUE THREAD

**Issue by dmirc** [theia-ide/theia#4700]
Description

Following your documentation and installation process is not working:
https://www.theia-ide.org/doc/Composing_Applications.html

Breaking at # yarn command

### Reproduction Steps
 

```
[root@ip-192-168-1-199 my-app]# yarn
yarn install v1.13.0
info No lockfile found.
[1/4] Resolving packages...
Couldn't find any versions for "@theia/monaco" that matches "0.5.0-next.74d71420"
? Please choose a version of "@theia/monaco" from this list: (Use arrow keys)

warning @theia/typescript > @theia/core > inversify@4.14.0: Re-Released as 5.0.1
warning @theia/typescript > @theia/filesystem > trash > xdg-trashdir > @sindresorhus/df > execa > cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
warning @theia/typescript > @theia/core > electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
```

```
[root@ip-192-168-1-199 my-app]# cat package.json
{
  "private": true,
  "dependencies": {
    "typescript": "latest",
    "@theia/typescript": "next",
    "@theia/navigator": "next",
    "@theia/terminal": "next",
    "@theia/outline-view": "next",
    "@theia/preferences": "next",
    "@theia/messages": "next",
    "@theia/git": "next",
    "@theia/file-search": "next",
    "@theia/markers": "next",
    "@theia/preview": "next",
    "@theia/callhierarchy": "next",
    "@theia/merge-conflicts": "next",
    "@theia/search-in-workspace": "next",
    "@theia/json": "next",
    "@theia/textmate-grammars": "next",
    "@theia/mini-browser": "next"
  },
  "devDependencies": {
    "@theia/cli": "next"
  }
}
```

```
[root@ip-192-168-1-199 my-app]# yarn --force
yarn install v1.13.0
info No lockfile found.
[1/4] Resolving packages...
warning @theia/typescript > @theia/core > inversify@4.14.0: Re-Released as 5.0.1
warning @theia/typescript > @theia/filesystem > trash > xdg-trashdir > @sindresorhus/df > execa > cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
warning @theia/typescript > @theia/core > electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
warning @theia/navigator > @theia/core > inversify@4.14.0: Re-Released as 5.0.1
warning @theia/cli > @theia/application-manager > webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning @theia/cli > @theia/application-manager > webpack-cli > webpack-addons > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning @theia/cli > @theia/application-manager > webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning @theia/cli > @theia/application-manager > webpack-cli > webpack-addons > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning @theia/cli > @theia/application-manager > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @theia/cli > @theia/application-manager > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @theia/cli > @theia/application-manager > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@theia/monaco/-/monaco-0.5.0-next.74d71420.tgz: Request failed \"404 Not Found\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/centos/my-app/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**OS and Theia version:**
AWS instance Centos 7 latest, Theia version latest i guess from the json file. 

**Diagnostics:** 

[root@ip-192-168-1-199 my-app]# cat /home/centos/my-app/yarn-error.log
Arguments:
  /root/.nvm/versions/node/v8.15.1/bin/node /root/.nvm/versions/node/v8.15.1/bin/yarn --force

PATH:
  /root/.nvm/versions/node/v8.15.1/bin:/sbin:/bin:/usr/sbin:/usr/bin

Yarn version:
  1.13.0

Node version:
  8.15.1

Platform:
  linux x64

Trace:
  Error: https://registry.yarnpkg.com/@theia/monaco/-/monaco-0.5.0-next.74d71420.tgz: Request failed "404 Not Found"
      at ResponseError.ExtendableBuiltin (/root/.nvm/versions/node/v8.15.1/lib/node_modules/yarn/lib/cli.js:702:66)
      at new ResponseError (/root/.nvm/versions/node/v8.15.1/lib/node_modules/yarn/lib/cli.js:808:124)
      at Request.<anonymous> (/root/.nvm/versions/node/v8.15.1/lib/node_modules/yarn/lib/cli.js:66325:16)
      at emitOne (events.js:116:13)
      at Request.emit (events.js:211:7)
      at Request.module.exports.Request.onRequestResponse (/root/.nvm/versions/node/v8.15.1/lib/node_modules/yarn/lib/cli.js:130274:10)
      at emitOne (events.js:116:13)
      at ClientRequest.emit (events.js:211:7)
      at HTTPParser.parserOnIncomingClient (_http_client.js:558:21)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)

**Comment by akosyakov** [comment]
Please clean yarn.lock and try again. yarn had issues today to publish next versions, now it should be good.

**Comment by dmirc** [comment]
Hi,

Works, but there is a lot of warnings during yarn build, not sure if thats normal or you should fix it?
Anyway here is the output:

```
warning @theia/typescript > @theia/core > inversify@4.14.0: Re-Released as 5.0.1
warning @theia/typescript > @theia/filesystem > trash > xdg-trashdir > @sindresorhus/df > execa > cross-spawn-async@2.2.5: cross-spawn no longer requires a build toolchain, use it instead
warning @theia/typescript > @theia/core > electron > electron-download > nugget > progress-stream > through2 > xtend > object-keys@0.4.0:
warning @theia/cli > @theia/application-manager > webpack-cli > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning @theia/cli > @theia/application-manager > webpack-cli > webpack-addons > jscodeshift > babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning @theia/cli > @theia/application-manager > webpack-cli > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning @theia/cli > @theia/application-manager > webpack-cli > webpack-addons > jscodeshift > nomnom@1.8.1: Package no longer supported. Contact support@npmjs.com for more info.
warning @theia/cli > @theia/application-manager > css-loader > cssnano > autoprefixer > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @theia/cli > @theia/application-manager > css-loader > cssnano > postcss-merge-rules > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
warning @theia/cli > @theia/application-manager > css-loader > cssnano > postcss-merge-rules > caniuse-api > browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
[2/4] Fetching packages...
warning monaco-languageclient@0.9.0: The engine "vscode" appears to be invalid.
warning vscode-base-languageclient@4.4.0: The engine "vscode" appears to be invalid.
info fsevents@1.2.7: The platform "linux" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@theia/cli > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "@theia/cli > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
```

**Comment by marcdumais-work** [comment]
@dmirc this looks normal. 

Thanks for confirming the build is now working for you.

**Comment by kittaakos** [comment]
The problem seems to be resolved; I am closing it. Please reopen if required.
