### ISSUE TITLE
Maximum call stack size exceeded during call showOpenDialog from plug-in side

### ISSUE THREAD

**Issue by vzhukovskii** [theia-ide/theia#4752]
### Description
Calling [$showOpenDialog](https://github.com/theia-ide/theia/blob/master/packages/plugin-ext/src/main/browser/dialogs-main.ts#L66) causes error with message:
```
ERROR RangeError: Maximum call stack size exceeded
```
and stack trace:
```
ERROR RangeError: Maximum call stack size exceeded
    at <anonymous>
    at new Promise (<anonymous>)
    at Logger.../../packages/core/lib/common/logger.js.Logger.ifEnabled (http://localhost:3000/bundle.js:97885:16)
    at Logger.../../packages/core/lib/common/logger.js.Logger.getLog (http://localhost:3000/bundle.js:97910:21)
    at Logger.../../packages/core/lib/common/logger.js.Logger.log (http://localhost:3000/bundle.js:97898:21)
    at log (http://localhost:3000/bundle.js:97820:35)
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (http://localhost:3000/bundle.js:97318:29)
    at Emitter.../../packages/core/lib/common/event.js.Emitter.fire (http://localhost:3000/bundle.js:97403:29)
    at FileDialogModel.push.../../packages/filesystem/lib/browser/file-dialog/file-dialog-model.js.FileDialogModel.doOpenNode (http://localhost:3000/2.bundle.js:144:39)
    at FileDialogModel.../../packages/core/lib/browser/tree/tree-model.js.TreeModelImpl.openNode (http://localhost:3000/bundle.js:92636:18)
```

The same code, but used in dedicate extension in theia doesn't cause such exception.

### Reproduction Steps
Use Kubernetes vscode plugin in theia and call `Add Configuration File` menu action.

**OS and Theia version:**

**Diagnostics:**

**Comment by vzhukovskii** [comment]
During investigation, what was found:

sample code to reproduce the problem:
```typescript
import { CommandContribution } from '@theia/core';
import { injectable, inject } from 'inversify';
import { CommandRegistry } from '@theia/core/lib/common/command';
import { LabelProvider } from '@theia/core/lib/browser';
import { DirNode } from './file-tree';
import URI from '@theia/core/lib/common/uri';
import { OpenFileDialogProps, OpenFileDialogFactory } from './file-dialog';
import { FileStat, FileSystem } from '../common/filesystem';
import { WorkspaceService } from '@theia/workspace/lib/browser';
import { UriSelection } from '@theia/core/lib/common/selection';

export namespace FILE_DIALOG_COMMANDS {
    export const TEST = {
        id: 'file.dialog.test',
        label: 'Get file paths'
    };
}

@injectable()
export class FileDialogTest implements CommandContribution {

    @inject(LabelProvider) protected readonly labelProvider: LabelProvider;
    @inject(FileSystem) protected readonly fileSystem: FileSystem;
    @inject(WorkspaceService) protected readonly workspaceService: WorkspaceService;
    @inject(OpenFileDialogFactory) protected readonly openFileDialogFactory: OpenFileDialogFactory;

    registerCommands(commands: CommandRegistry): void {
        commands.registerCommand(FILE_DIALOG_COMMANDS.TEST, {
            execute: async () => {
                const paths = await this.showOpenDialog({canSelectFiles: true, canSelectFolders: false} as OpenFileDialogProps);
                console.log(paths);
            },
            isEnabled: () => true,
            isVisible: () => true
        });
    }

    protected async getRootUri(defaultUri: string | undefined): Promise<FileStat | undefined> {
        let rootStat;

        // Try to use default URI as root
        if (defaultUri) {
            rootStat = await this.fileSystem.getFileStat(defaultUri);
        }

        // Try to use workspace service root if there is no preconfigured URI
        if (!rootStat) {
            rootStat = (await this.workspaceService.roots)[0];
        }

        // Try to use current user home if root folder is still not taken
        if (!rootStat) {
            rootStat = await this.fileSystem.getCurrentUserHome();
        }

        return rootStat;
    }

    async showOpenDialog(options: OpenFileDialogProps): Promise<string[] | undefined> {
        const rootStat = await this.getRootUri(undefined);

        if (!rootStat) {
            throw new Error('Unable to find the rootStat');
        }

        const rootUri = new URI(rootStat.uri);
        const name = this.labelProvider.getName(rootUri);
        const icon = await this.labelProvider.getIcon(rootUri);
        const rootNode = DirNode.createRoot(rootStat, name, icon);

        const dialog = this.openFileDialogFactory(options);
        dialog.model.navigateTo(rootNode);
        const result = await dialog.open();

        return UriSelection.getUris(result).map(uri => uri.path.toString());
    }
}
```

The problem reproduces only when configuration is passed:
```
{canSelectFiles: true, canSelectFolders: false} as OpenFileDialogProps
```

But when this one is passed in dialog options:
```
{canSelectFiles: true} as OpenFileDialogProps
```
issue disappear and dialog works as well.

Trying to find best solution to check, whether selected item in tree is non-leaf item.

**Comment by vzhukovskii** [comment]
Possible workaround at this moment is to set `canSelectFolders` to `undefined` if it doesn't need to be set.
