### ISSUE TITLE
debug-nodeejs build error

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#4779]
### Description
```
[4/4] Building fresh packages...
error /home/theia/node_modules/@theia/debug-nodejs: Command failed.
Exit code: 1
Command: download-debug-adapters
Arguments:
Directory: /home/theia/node_modules/@theia/debug-nodejs
Output:
node-debug: downloading from https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/node-debug/1.29.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
node-debug2: downloading from https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/node-debug2/1.29.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage
internal/streams/legacy.js:59
throw er; // Unhandled stream error in pipe.
^
Error: Not a valid zip file
at UnzipStream.processDataChunk (/home/theia/node_modules/unzip-stream/lib/unzip-stream.js:155:40)
at UnzipStream._parseOrOutput (/home/theia/node_modules/unzip-stream/lib/unzip-stream.js:651:28)
at UnzipStream._transform (/home/theia/node_modules/unzip-stream/lib/unzip-stream.js:718:10)
at UnzipStream.Transform._read (_stream_transform.js:186:10)
at UnzipStream.Transform._write (_stream_transform.js:174:12)
at doWrite (_stream_writable.js:396:12)
at writeOrBuffer (_stream_writable.js:382:5)
at UnzipStream.Writable.write (_stream_writable.js:290:11)
at Extract._transform (/home/theia/node_modules/unzip-stream/lib/extract.js:30:22)
at Extract.Transform._read (_stream_transform.js:186:10)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Reproduction Steps
**OS and Theia version:**
latest next

**Comment by 502647092** [comment]
![image](https://user-images.githubusercontent.com/10203793/55398338-dafe9800-557a-11e9-9844-e55bd370c691.png)
emm....
