### ISSUE TITLE
"Error: Request 'updateContent' failed" in docker output when there is a validation error on a Camel file

### ISSUE THREAD

**Issue by apupier** [theia-ide/theia#4857]
### Description
```
root ERROR Error: Request 'updateContent' failed
    at Proxy.<anonymous> (http://localhost:3000/bundle.js:52:133471)
    at e.<anonymous> (http://localhost:3000/bundle.js:30:152054)
    at http://localhost:3000/bundle.js:30:149611
    at Object.next (http://localhost:3000/bundle.js:30:149716)
    at http://localhost:3000/bundle.js:30:148629
    at new Promise (<anonymous>)
    at a (http://localhost:3000/bundle.js:30:148406)
    at e.saveContentChanges (http://localhost:3000/bundle.js:30:151863)
    at http://localhost:3000/bundle.js:19:781217
    at http://localhost:3000/bundle.js:19:780596
Caused by: Error: 'file:///home/project/camelagainagain.xml' is out of sync.
    at FileSystemNode.createOutOfSyncError (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:295:45)
    at FileSystemNode.<anonymous> (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:231:40)
    at step (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:59:23)
    at Object.next (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:40:53)
    at fulfilled (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:31:58)
    at <anonymous>
```

### Reproduction Steps
docker run -it -p 3000:3000 -v "C:/Users/Aurelien Pupier/theiatmp:/home/project:cached" theiaide/theia-full:latest

use deploy plugin by id command:
vscode:extension/camel-tooling.vscode-apache-camel
vscode:extension/redhat.vscode-xml

create an xml file with content:
```
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="        http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd        http://camel.apache.org/schema/spring http://camel.apache.org/schema/spring/camel-spring.xsd">
    <camelContext id="cbr-example-context" xmlns="http://camel.apache.org/schema/spring">
        <route id="cbr-route">
            <from id="_from1" uri="timer:timerName?delay=1000"/>
            <log id="_log1" message="Receiving order ${file:name}"/>
            <choice id="_choice1">
                <when id="_when1">
                    <xpath id="_xpath1">/order/customer/country = 'UK'</xpath>
                    <log id="_log2" message="Sending order ${file:name} to the UK"/>
                    <to id="_to1" uri="file:work/cbr/output/uk"/>
                </when>
                <when id="_when2">
                    <xpath id="_xpath2">/order/customer/country = 'US'</xpath>
                    <log id="_log3" message="Sending order ${file:name} to the US"/>
                    <to id="_to2" uri="file:work/cbr/output/us"/>
                </when>
                <otherwise id="_otherwise1">
                    <log id="_log4" message="Sending order ${file:name} to another country"/>
                    <to id="_to3" uri="file:work/cbr/output/others"/>
                </otherwise>
            </choice>
            <log id="_log5" message="Done processing ${file:name}"/>
        </route>
    </camelContext>
</beans>
```
change timer:timerName?delay=1000 by timer:timerName?delay=1000xx

observe stack in docker output

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
@apupier And you don't get a dialog asking do you want to override the state on fs?

The error indicates that fs state is more up-to-date then an opened document. Maybe Docker does something to a file after we open in. Need more investigation.

**Comment by apupier** [comment]
> And you don't get a dialog asking do you want to override the state on fs?

no, I noticed nothing in UI

**Comment by tolusha** [comment]
@apupier 
I can't reproduce this issue. Is it still relevant?  Could you check it again pls.

**Comment by apupier** [comment]
> I can't reproduce this issue. Is it still relevant? Could you check it again pls.

I cannot check.
I cannot launch theia-full with latest pulled image:

```
docker run -it -p 3000:3000 -v "C:/Users/Aurelien Pupier/theiatmp:/home/project:cached" theiaide/theia-full:latest
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"yarn\": executable file not found in $PATH": unknown.
```

**Comment by tolusha** [comment]
Have you pulled the latest image ?

**Comment by apupier** [comment]
> Have you pulled the latest image ?

yes I called `docker pull theiaide/theia-full:latest` before trying to start the docker image

i noticed that a new version was available this morning. this new one is starting. So will try to reproduce

**Comment by apupier** [comment]
I cannot reproduce anymore.

Thanks for having tried to reproduce.
