### ISSUE TITLE
[rust][vscode] no adapter found on completions

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4859]
```
root ERROR [hosted-plugin: 17155] (node:17155) UnhandledPromiseRejectionWarning: Error: no adapter found
    at LanguagesExtImpl.withAdapter (/workspace/theia/packages/plugin-ext/lib/plugin/languages.js:109:35)
    at LanguagesExtImpl.$releaseCompletionItems (/workspace/theia/packages/plugin-ext/lib/plugin/languages.js:145:14)
    at RPCProtocolImpl.doInvokeHandler (/workspace/theia/packages/plugin-ext/lib/api/rpc-protocol.js:175:23)
    at RPCProtocolImpl.invokeHandler (/workspace/theia/packages/plugin-ext/lib/api/rpc-protocol.js:160:41)
    at RPCProtocolImpl.receiveRequest (/workspace/theia/packages/plugin-ext/lib/api/rpc-protocol.js:124:45)
    at RPCProtocolImpl.receiveOneMessage (/workspace/theia/packages/plugin-ext/lib/api/rpc-protocol.js:110:22)
    at /workspace/theia/packages/plugin-ext/lib/api/rpc-protocol.js:53:89
    at /workspace/theia/packages/plugin-ext/lib/api/rpc-protocol.js:201:17
    at /workspace/theia/packages/core/lib/common/event.js:161:33
    at CallbackList.invoke (/workspace/theia/packages/core/lib/common/event.js:176:39)
```

**Comment by akosyakov** [comment]
rust LS log errors:
```
ERROR 2019-04-15T06:43:56Z: rls::server: dispatch error: Error { code: InvalidParams, message: "invalid type: map, expected a string", data: None }, message: `{"jsonrpc":"2.0","id":21,"method":"completionItem/resolve","params":[{"label":"cgroups_fs","detail":"/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/cgroups-fs-1.0.1/src/lib.rs","documentation":{"kind":"markdown","value":"Cgroup-fs is a minimal wrapper around Linux Control Groups (cgroups) filesystem (usually\nmounted as `/sys/fs/cgroup`).\n\n# Examples\n\n## Get memory usage from root cgroup\n\n```rust\nlet root_cgroup = cgroups_fs::CgroupName::new(\"\");\nlet root_memory_cgroup = cgroups_fs::Cgroup::new(&root_cgroup, \"memory\");\nprintln!(\n    \"Current memory usage is {} bytes\",\n    root_memory_cgroup.get_value::<u64>(\"memory.usage_in_bytes\").unwrap()\n);\n```\n\n## Measure memory usage of a child process\n\nRead [the `CgroupsCommandExt` documentation].\n\n[the `CgroupsCommandExt` documentation]: trait.CgroupsCommandExt.html#impl-CgroupsCommandExt"},"insertTextFormat":2,"insertText":"cgroups_fs","kind":9},null]}`
[Error - 6:43:56 AM] Request completionItem/resolve failed.
  Message: invalid type: map, expected a string
  Code: -32602 
[Info  - 6:43:56 AM] Connection to server got closed. Server will restart.
ERROR 2019-04-15T06:43:57Z: rls::server: dispatch error: Error { code: InvalidParams, message: "invalid type: map, expected a string", data: None }, message: `{"jsonrpc":"2.0","id":4,"method":"completionItem/resolve","params":[{"label":"cgroups_fs","detail":"/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/cgroups-fs-1.0.1/src/lib.rs","documentation":{"kind":"markdown","value":"Cgroup-fs is a minimal wrapper around Linux Control Groups (cgroups) filesystem (usually\nmounted as `/sys/fs/cgroup`).\n\n# Examples\n\n## Get memory usage from root cgroup\n\n```rust\nlet root_cgroup = cgroups_fs::CgroupName::new(\"\");\nlet root_memory_cgroup = cgroups_fs::Cgroup::new(&root_cgroup, \"memory\");\nprintln!(\n    \"Current memory usage is {} bytes\",\n    root_memory_cgroup.get_value::<u64>(\"memory.usage_in_bytes\").unwrap()\n);\n```\n\n## Measure memory usage of a child process\n\nRead [the `CgroupsCommandExt` documentation].\n\n[the `CgroupsCommandExt` documentation]: trait.CgroupsCommandExt.html#impl-CgroupsCommandExt"},"insertTextFormat":2,"insertText":"cgroups_fs","kind":9},null]}`
[Error - 6:43:57 AM] Request completionItem/resolve failed.
  Message: invalid type: map, expected a string
  Code: -32602 
[Info  - 6:43:57 AM] Connection to server got closed. Server will restart.
ERROR 2019-04-15T06:43:58Z: rls::server: dispatch error: Error { code: InvalidParams, message: "invalid type: map, expected a string", data: None }, message: `{"jsonrpc":"2.0","id":4,"method":"completionItem/resolve","params":[{"label":"cgroups_fs","detail":"/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/cgroups-fs-1.0.1/src/lib.rs","documentation":{"kind":"markdown","value":"Cgroup-fs is a minimal wrapper around Linux Control Groups (cgroups) filesystem (usually\nmounted as `/sys/fs/cgroup`).\n\n# Examples\n\n## Get memory usage from root cgroup\n\n```rust\nlet root_cgroup = cgroups_fs::CgroupName::new(\"\");\nlet root_memory_cgroup = cgroups_fs::Cgroup::new(&root_cgroup, \"memory\");\nprintln!(\n    \"Current memory usage is {} bytes\",\n    root_memory_cgroup.get_value::<u64>(\"memory.usage_in_bytes\").unwrap()\n);\n```\n\n## Measure memory usage of a child process\n\nRead [the `CgroupsCommandExt` documentation].\n\n[the `CgroupsCommandExt` documentation]: trait.CgroupsCommandExt.html#impl-CgroupsCommandExt"},"insertTextFormat":2,"insertText":"cgroups_fs","kind":9},null]}`
[Error - 6:43:58 AM] Request completionItem/resolve failed.
  Message: invalid type: map, expected a string
  Code: -32602 
[Info  - 6:43:58 AM] Connection to server got closed. Server will restart.
ERROR 2019-04-15T06:43:59Z: rls::server: dispatch error: Error { code: InvalidParams, message: "invalid type: map, expected a string", data: None }, message: `{"jsonrpc":"2.0","id":4,"method":"completionItem/resolve","params":[{"label":"cgroups_fs","detail":"/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/cgroups-fs-1.0.1/src/lib.rs","documentation":{"kind":"markdown","value":"Cgroup-fs is a minimal wrapper around Linux Control Groups (cgroups) filesystem (usually\nmounted as `/sys/fs/cgroup`).\n\n# Examples\n\n## Get memory usage from root cgroup\n\n```rust\nlet root_cgroup = cgroups_fs::CgroupName::new(\"\");\nlet root_memory_cgroup = cgroups_fs::Cgroup::new(&root_cgroup, \"memory\");\nprintln!(\n    \"Current memory usage is {} bytes\",\n    root_memory_cgroup.get_value::<u64>(\"memory.usage_in_bytes\").unwrap()\n);\n```\n\n## Measure memory usage of a child process\n\nRead [the `CgroupsCommandExt` documentation].\n\n[the `CgroupsCommandExt` documentation]: trait.CgroupsCommandExt.html#impl-CgroupsCommandExt"},"insertTextFormat":2,"insertText":"cgroups_fs","kind":9},null]}`
[Error - 6:43:59 AM] Request completionItem/resolve failed.
  Message: invalid type: map, expected a string
  Code: -32602 
[Info  - 6:43:59 AM] Connection to server got closed. Server will restart.
ERROR 2019-04-15T06:43:59Z: rls::server: dispatch error: Error { code: InvalidParams, message: "invalid type: map, expected a string", data: None }, message: `{"jsonrpc":"2.0","id":4,"method":"completionItem/resolve","params":[{"label":"cgroups_fs","detail":"/home/gitpod/.cargo/registry/src/github.com-1ecc6299db9ec823/cgroups-fs-1.0.1/src/lib.rs","documentation":{"kind":"markdown","value":"Cgroup-fs is a minimal wrapper around Linux Control Groups (cgroups) filesystem (usually\nmounted as `/sys/fs/cgroup`).\n\n# Examples\n\n## Get memory usage from root cgroup\n\n```rust\nlet root_cgroup = cgroups_fs::CgroupName::new(\"\");\nlet root_memory_cgroup = cgroups_fs::Cgroup::new(&root_cgroup, \"memory\");\nprintln!(\n    \"Current memory usage is {} bytes\",\n    root_memory_cgroup.get_value::<u64>(\"memory.usage_in_bytes\").unwrap()\n);\n```\n\n## Measure memory usage of a child process\n\nRead [the `CgroupsCommandExt` documentation].\n\n[the `CgroupsCommandExt` documentation]: trait.CgroupsCommandExt.html#impl-CgroupsCommandExt"},"insertTextFormat":2,"insertText":"cgroups_fs","kind":9},null]}`
[Error - 6:43:59 AM] Request completionItem/resolve failed.
  Message: invalid type: map, expected a string
  Code: -32602 
[Error - 6:43:59 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by akosyakov** [comment]
Monaco get in the weird state because cancellation tokens are not respected and continue spamming with resolved requests.
