### ISSUE TITLE
Terminal is leaking

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#4894]
Open 4 Terminal widgets. Close them. Take a heap snapshot:

![Screen Shot 2019-04-12 at 14 46 56](https://user-images.githubusercontent.com/914497/56038512-7093e780-5d32-11e9-9c42-b93e79e2c80e.png)

Repeat with 3 more widgets (just in case)

![Screen Shot 2019-04-12 at 14 47 56](https://user-images.githubusercontent.com/914497/56038557-8f927980-5d32-11e9-9152-ba99d15494e4.png)

Then open 2 other terminals and create some output, e.g. `cat yarn.lock` or `top`. Compare the retainers by size with a previous snapshot.

![Screen Shot 2019-04-12 at 14 50 06](https://user-images.githubusercontent.com/914497/56038631-b18bfc00-5d32-11e9-835a-c415389b12b0.png)
![Screen Shot 2019-04-12 at 14 50 09](https://user-images.githubusercontent.com/914497/56038632-b18bfc00-5d32-11e9-9046-15d3d764c247.png)

This is pretty bad: the ArrayBuffers from xterm remain in memory.

**Comment by AlexTugarev** [comment]
BTW this was the original hint to this issue:

```
root WARN Error: Possible Emitter memory leak detected. 30 exit listeners added. Use event.maxListeners to increase limit
    at Emitter.../../packages/core/lib/common/event.js.Emitter.checkMaxListeners (http://localhost:3000/bundle.js:98360:26)
    at PreferenceServiceImpl._event.Object.assign.maxListeners [as onPreferenceChanged] (http://localhost:3000/bundle.js:98327:27)
    at Object.createPreferenceProxy (http://localhost:3000/bundle.js:84292:32)
    at createTerminalPreferences (http://localhost:3000/32.bundle.js:139:22)
    at Binding.dynamicValue (http://localhost:3000/32.bundle.js:145:16)
    at http://localhost:3000/bundle.js:35993:118
    at invokeFactory (http://localhost:3000/bundle.js:35940:16)
    at http://localhost:3000/bundle.js:35993:26
    at Array.map (<anonymous>)
    at _injectProperties (http://localhost:3000/bundle.js:35879:57)
```

**Comment by akosyakov** [comment]
@AlexTugarev Can you reproduce with latest xtermjs? Which code retains ArrayBuffers? xtermjs?
