### ISSUE TITLE
plugins jebbs.plantuml not support

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#4899]
### Description
![image](https://user-images.githubusercontent.com/10203793/56090990-96a8bb80-5edb-11e9-88f8-ad9c14afd6a8.png)
 

### Reproduction Steps
download plugin and start theia
https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml

**OS and Theia version:**
next version

**Diagnostics:** 
```
TypeError: Cannot read property 'execute' of undefined
    at executeCatch (/home/theia/plugins/jebbs.plantuml/extension/out/src/commands/common.js:16:27)
    at /home/theia/node_modules/@theia/plugin-ext/lib/plugin/command-registry.js:113:28
    at CommandRegistryImpl.executeLocalCommand (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/command-registry.js:165:44)
    at CommandRegistryImpl.$executeCommand (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/command-registry.js:130:45)
    at RPCProtocolImpl.doInvokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:175:23)
    at RPCProtocolImpl.invokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:160:41)
    at RPCProtocolImpl.receiveRequest (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:124:45)
    at RPCProtocolImpl.receiveOneMessage (/home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:110:22)
    at /home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:53:89
    at /home/theia/node_modules/@theia/plugin-ext/lib/api/rpc-protocol.js:201:17
```

**Comment by akosyakov** [comment]
It's a bug in plugin-system, it seems we don't preserve the original command object somehow.

**Comment by benoitf** [comment]
https://github.com/theia-ide/theia/pull/4946 is solving the reported issue but there are other errors after with this extension

**Comment by benoitf** [comment]
It will require https://github.com/theia-ide/theia/pull/4743 as well

as workaround, you can define 
```json
{
   "plantuml.diagramsRoot": "."
}
```

in your preferences

and then you can export stuff
![plantuml](https://user-images.githubusercontent.com/436777/56352320-47aaa100-61cf-11e9-953d-88d99d838651.gif)

**Comment by 502647092** [comment]
@benoitf 
![image](https://user-images.githubusercontent.com/10203793/56434041-9a867480-6305-11e9-8863-9365e8981278.png)
chinese language not support ?

**Comment by 502647092** [comment]
![temp](https://user-images.githubusercontent.com/10203793/56434200-33b58b00-6306-11e9-8bdc-5190368dc71f.gif)
emm I don't know if you can understand it.
It means that when I start dragging the preview window, the mouse will enter the preview window and cannot be lowered.

**Comment by akosyakov** [comment]
should be fixed by https://github.com/theia-ide/theia/pull/4947

@502647092 please reopen if you still cannot export
