### ISSUE TITLE
download-debug-adapters not support vscode market download url

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#4900]
### Description
can't use vscode market download url
https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/Go/0.9.2/vspackage
must replace to
https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/Go/0.9.2/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

But I compared the downloaded files and found that the content was the same.
![image](https://user-images.githubusercontent.com/10203793/56091824-51d65200-5ee6-11e9-8470-050936d3a3e0.png)

![image](https://user-images.githubusercontent.com/10203793/56091831-76322e80-5ee6-11e9-9bdb-6e93a223e3ae.png)

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:** 
package.json
```
{
    "private": true,
    "dependencies": {
        "@theia/plugin-ext-vscode": "next",
        "@theia/preview": "next",
        "@theia/editor-preview": "next",
        "@theia/getting-started": "next",
        "@theia/json": "next",
        "@theia/textmate-grammars": "next",
        "@theia/git": "next",
        "@theia/keymaps": "next",
        "@theia/merge-conflicts": "next",
        "@theia/task": "next",
        "@theia/terminal": "next",
        "@theia/workspace": "next"
    },
    "devDependencies": {
        "@theia/cli": "next",
        "@theia/debug": "next"
    },
    "scripts": {
        "postinstall": "download-debug-adapters"
    },
    "adapterDir": "plugins",
    "adapters": {
        "vscode-go": "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/Go/0.9.2/vspackage",
        "redhat.java": "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/redhat/vsextensions/java/0.42.1/vspackage",
        "octref.vetur": "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/octref/vsextensions/vetur/0.18.1/vspackage",
        "jebbs.plantuml": "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/jebbs/vsextensions/plantuml/2.10.9/vspackage",
        "vscode-lombok": "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/GabrielBB/vsextensions/vscode-lombok/0.9.7/vspackage",
        "vscode-docker": "https://marketplace.visualstudio.com/_apis/public/gallery/publishers/PeterJausovec/vsextensions/vscode-docker/0.6.1/vspackage"
    }
}
```

```
$ download-debug-adapters
vscode-go: downloading from https://marketplace.visualstudio.com/_apis/public/gallery/publishers/ms-vscode/vsextensions/Go/0.9.2/vspackage
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: Not a valid zip file
    at UnzipStream.processDataChunk (/home/theia/node_modules/unzip-stream/lib/unzip-stream.js:155:40)
    at UnzipStream._parseOrOutput (/home/theia/node_modules/unzip-stream/lib/unzip-stream.js:651:28)
    at UnzipStream._transform (/home/theia/node_modules/unzip-stream/lib/unzip-stream.js:718:10)
    at UnzipStream.Transform._read (_stream_transform.js:190:10)
    at UnzipStream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at UnzipStream.Writable.write (_stream_writable.js:294:11)
    at Extract._transform (/home/theia/node_modules/unzip-stream/lib/extract.js:30:22)
    at Extract.Transform._read (_stream_transform.js:190:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
The command '/bin/sh -c yarn --pure-lockfile &&     NODE_OPTIONS="--max_old_space_size=4096" yarn theia build' returned a non-zero code: 1
```

**Comment by akosyakov** [comment]
Please use the following template for a marketplace URL:
https://ms-vscode.gallery.vsassets.io/_apis/public/gallery/publisher/ms-vscode/extension/csharp/1.3.0/assetbyname/Microsoft.VisualStudio.Services.VSIXPackage

It's a direct url.
