### ISSUE TITLE
[Java] Hyperlinks to source code in hovers don't work

### ISSUE THREAD

**Issue by BoykoAlex** [theia-ide/theia#4938]
Regression. This used to work well before (a month ago)

Launch Theia with Java extension
Open a Java file in a Maven project for example
Hover on `java.util.List` occurrence in a Java file (or any other that has hover content with hyper links)
Scroll to the bottom of the hover where most of the time "See Also" links are located
Click on `Collection` or any other hyperlinks
Nothing happens.
You might see this in the Output view:
```
[Error - 11:04:17 PM] Request textDocument/hover failed.
Error: The request (id: 3, method: 'textDocument/hover') has been cancelled
    at new ResponseError (http://localhost:3000/bundle.js:111038:28)
    at handleResponse (http://localhost:3000/bundle.js:110019:48)
    at processMessageQueue (http://localhost:3000/bundle.js:109847:17)
    at http://localhost:3000/bundle.js:109831:13
    at run (http://localhost:3000/bundle.js:106836:13)
    at runIfPresent (http://localhost:3000/bundle.js:106865:21)
    at onGlobalMessage (http://localhost:3000/bundle.js:106905:17)
```

Expected:
Clicking on such link opens java.util.Collection class source

OSX
Theia 0.5.0

**Comment by akosyakov** [comment]
Probably https://github.com/TypeFox/monaco-languageclient/issues/142
