### ISSUE TITLE
On Windows, the VS Code plugins in development might not deploy due to wrong version detected

### ISSUE THREAD

**Issue by apupier** [theia-ide/theia#4952]
### Description

on Windows, the Theia version is seen instead for the vscode one

### Reproduction Steps

follow https://github.com/theia-ide/theia/wiki/Testing-VS-Code-extensions

as vsix, you can use https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml

**OS and Theia version:**

Windows 10
Theia master

**Diagnostics:** 

```
root ERROR [hosted-plugin: 16000] (node:16000) UnhandledPromiseRejectionWarning: Error: The language client requires VS Code version ^1.26 but received version 0.5.0
    at LanguageClient.checkVersion (C:\Users\AURELI~1\AppData\Local\Temp\vscode-unpacked\redhat.vscode-xml-0.5.1.vsix\extension\node_modules\vscode-languageclient\lib\main.js:118:19)
    at new LanguageClient (C:\Users\AURELI~1\AppData\Local\Temp\vscode-unpacked\redhat.vscode-xml-0.5.1.vsix\extension\node_modules\vscode-languageclient\lib\main.js:99:18)
    at requirements.resolveRequirements.catch.then.requirements (C:\Users\AURELI~1\AppData\Local\Temp\vscode-unpacked\redhat.vscode-xml-0.5.1.vsix\extension\out\src\extension.js:70:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

note: using docker run -it --rm -p 3000:3000 -p 3030:3030  -v C:/git/theia/plugins:/plugins -e THEIA_PLUGINS=local-dir:///plugins theiaide/theia-full:next is working (but don't have the debug anymore, at least out of the box)

**Comment by sgraband** [comment]
VS Code API version properly set and configurable via CLI/env variable.
