### ISSUE TITLE
root ERROR Error: Request 'watchFileChanges' failed

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#5006]
### Description
![temp](https://user-images.githubusercontent.com/10203793/56791897-d60bcc00-683a-11e9-9840-e30cbeeb329c.gif)

### Reproduction Steps
docker pull miaowoo/theia:next
open any file

**OS and Theia version:**
latest docker version
theia next

**Diagnostics:** 
```
root ERROR Request watchFileChanges failed with error: Connection is closed. Error: Connection is closed.
    at new ConnectionError (/home/theia/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/home/theia/node_modules/vscode-jsonrpc/lib/main.js:613:19)
    at Object.sendRequest (/home/theia/node_modules/vscode-jsonrpc/lib/main.js:715:13)
    at /home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:310:72
    at new Promise (<anonymous>)
    at /home/theia/node_modules/@theia/core/lib/common/messaging/proxy-factory.js:303:24
    at <anonymous>
root ERROR Error: Request 'watchFileChanges' failed
    at Proxy.<anonymous> (https://theia.yumc.pw/bundle.js:19:847539)
    at e.doWatchFileChanges (https://theia.yumc.pw/bundle.js:19:378430)
    at e.watchFileChanges (https://theia.yumc.pw/bundle.js:19:378327)
    at https://theia.yumc.pw/bundle.js:12:52382
```

**Comment by akosyakov** [comment]
Seems like a connection to fs watching process get closed. Or fs watching process got killed? could be issue with your OS configuration in docker. Can you reproduce it on master without your image?

**Comment by akosyakov** [comment]
You can try to pass `--no-cluster` mode option to run in single threaded mode, maybe you will see more errors why nsfw is collapsing.

**Comment by 502647092** [comment]
I Can't reproduce it on master
Although there is an error, it does not seem to affect the use.
