### ISSUE TITLE
The PluginHot crash in latest master for SQL-Tools VSCode extension

### ISSUE THREAD

**Issue by ariel-bentu** [theia-ide/theia#5078]
### Description
VSCode extension SQL-Tools crashes the pluginHosts. It worked about two weeks ago on master, and now on master it does not.

### Reproduction Steps
Download the vsix: https://marketplace.visualstudio.com/_apis/public/gallery/publishers/mtxr/vsextensions/sqltools/0.17.18/vspackage

Copy it to the plugins folder
Start Theia server
Access theia from browser - wait untill fully loaded, and observe server output: 

**OS and Theia version:**
master, MAC-OS
 
**Diagnostics:** 
Logs look like this:
Before loading the browser (only start server):
```
yarn run v1.13.0
$ theia start --plugins=local-dir:../../plugins
Failed to resolve module: getmac
root INFO Theia app listening on http://localhost:3000.
root INFO unzipping the plugin ProxyPluginDeployerEntry {
  deployer:
   PluginVsCodeFileHandler {
     unpackedFolder:
      '/private/var/folders/hm/zvsqr3ns2d98t7__1v64hk580000gn/T/vscode-unpacked' },
  delegate:
   PluginDeployerEntryImpl {
     originId: 'local-dir:../../plugins',
     pluginId: 'mtxr.sqltools-0.17.18.vsix',
     map: Map {},
     changes: [],
     acceptedTypes: [],
     currentPath:
      '/Users/i022021/dev/node/theia/plugins/mtxr.sqltools-0.17.18.vsix',
     initPath:
      '/Users/i022021/dev/node/theia/plugins/mtxr.sqltools-0.17.18.vsix',
     resolved: true,
     resolvedByName: 'LocalDirectoryPluginDeployerResolver' },
  deployerName: 'PluginVsCodeFileHandler' }
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /Users/i022021/dev/node/theia/plugins/.DS_Store
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /private/var/folders/hm/zvsqr3ns2d98t7__1v64hk580000gn/T/vscode-unpacked/mtxr.sqltools-0.17.18.vsix
root INFO Resolved "mtxr.sqltools-0.17.18.vsix" to a VS Code extension "sqltools@0.17.18" with engines: { vscode: '^1.30.0' }
root INFO Deploying backend plugin "sqltools@0.17.18" from "/private/var/folders/hm/zvsqr3ns2d98t7__1v64hk580000gn/T/vscode-unpacked/mtxr.sqltools-0.17.18.vsix/extension/extension.js"
```

After loading browser
```
root INFO Using Git [2.15.0] from the PATH. (/usr/local/bin/git)
root INFO Detected keyboard layout: US (Mac)
root WARN LanguagesFrontendContribution.onStart is slow, took: 266.00000000325963 ms
root INFO [nsfw-watcher: 81231] Started watching: /Users/i022021/.theia
root INFO [nsfw-watcher: 81231] Started watching: /Users/i022021/dev/node/dist
root WARN EditorNavigationContribution.onStart is slow, took: 628.2950000022538 ms
root INFO [nsfw-watcher: 81231] Started watching: /Users/i022021/dev/node/dist
Started watching: /Users/i022021/dev/node/dist
root WARN Couldn't restore widget state for debug-console. Error: TypeError: Cannot read property 'getControl' of undefined
root WARN "sqltools.connections" preference is not supported
root ERROR [hosted-plugin: 81235] internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module 'getmac'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/i022021/dev/node/theia/packages/plugin-ext/lib/plugin/node/env-node-ext.js:33:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

root ERROR Error: schema is invalid: data.properties['sqltools.autoConnectTo'].required should be array
    at Ajv.validateSchema (http://localhost:3000/bundle.js:102759:16)
    at Ajv._addSchema (http://localhost:3000/bundle.js:102888:10)
    at Ajv.compile (http://localhost:3000/bundle.js:102688:24)
    at PreferenceSchemaProvider.../../packages/core/lib/browser/preferences/preference-contribution.js.PreferenceSchemaProvider.updateValidate (http://localhost:3000/bundle.js:84275:43)
    at http://localhost:3000/bundle.js:84133:65
    at http://localhost:3000/bundle.js:98771:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (http://localhost:3000/bundle.js:98786:39)
    at Emitter.../../packages/core/lib/common/event.js.Emitter.fire (http://localhost:3000/bundle.js:98874:29)
    at PreferenceSchemaProvider.../../packages/core/lib/browser/preferences/preference-provider.js.PreferenceProvider.emitPreferencesChangedEvent (http://localhost:3000/bundle.js:84532:49)
    at PreferenceSchemaProvider.../../packages/core/lib/browser/preferences/preference-contribution.js.PreferenceSchemaProvider.setSchema (http://localhost:3000/bundle.js:84298:14)
root WARN Error: a registered grammar provider for 'source.sql' scope is overridden
    at TextmateRegistry.push.../../packages/monaco/lib/browser/textmate/textmate-registry.js.TextmateRegistry.registerTextmateGrammarScope (http://localhost:3000/22.bundle.js:814:26)
    at _loop_1 (http://localhost:3000/82.bundle.js:9129:41)
    at PluginContributionHandler.push.../../packages/plugin-ext/lib/main/browser/plugin-contribution-handler.js.PluginContributionHandler.handleContributions (http://localhost:3000/82.bundle.js:9157:21)
    at HostedPluginSupport.push.../../packages/plugin-ext/lib/hosted/browser/hosted-plugin.js.HostedPluginSupport.initContributions (http://localhost:3000/82.bundle.js:3206:46)
    at HostedPluginSupport.push.../../packages/plugin-ext/lib/hosted/browser/hosted-plugin.js.HostedPluginSupport.loadPlugins (http://localhost:3000/82.bundle.js:3134:30)
    at http://localhost:3000/82.bundle.js:3120:19
root WARN Error: 'sql' language is remapped from 'source.sql' to 'source.sql' scope
    at TextmateRegistry.push.../../packages/monaco/lib/browser/textmate/textmate-registry.js.TextmateRegistry.mapLanguageIdToTextmateGrammar (http://localhost:3000/22.bundle.js:824:26)
    at _loop_1 (http://localhost:3000/82.bundle.js:9145:45)
    at PluginContributionHandler.push.../../packages/plugin-ext/lib/main/browser/plugin-contribution-handler.js.PluginContributionHandler.handleContributions (http://localhost:3000/82.bundle.js:9157:21)
    at HostedPluginSupport.push.../../packages/plugin-ext/lib/hosted/browser/hosted-plugin.js.HostedPluginSupport.initContributions (http://localhost:3000/82.bundle.js:3206:46)
    at HostedPluginSupport.push.../../packages/plugin-ext/lib/hosted/browser/hosted-plugin.js.HostedPluginSupport.loadPlugins (http://localhost:3000/82.bundle.js:3134:30)
    at http://localhost:3000/82.bundle.js:3120:19
root WARN Plugin contributes items to a menu with invalid identifier: view/title
root INFO Config file tasks.json does not exist under file:///Users/i022021/dev/node/dist
root ERROR Uncaught Exception:  Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
root ERROR Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at ChildProcess.target.send (internal/child_process.js:636:16)
    at HostedPluginProcess.onMessage (/Users/i022021/dev/node/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin-process.js:105:31)
    at HostedPluginSupport.onMessage (/Users/i022021/dev/node/theia/packages/plugin-ext/lib/hosted/node/hosted-plugin.js:104:38)
    at HostedPluginServerImpl.onMessage (/Users/i022021/dev/node/theia/packages/plugin-ext/lib/hosted/node/plugin-service.js:168:27)
    at JsonRpcProxyFactory.onNotification (/Users/i022021/dev/node/theia/packages/core/lib/common/messaging/proxy-factory.js:246:36)
    at /Users/i022021/dev/node/theia/packages/core/lib/common/messaging/proxy-factory.js:181:53
    at handleNotification (/Users/i022021/dev/node/theia/node_modules/vscode-jsonrpc/lib/main.js:483:43)
    at processMessageQueue (/Users/i022021/dev/node/theia/node_modules/vscode-jsonrpc/lib/main.js:255:17)
    at Immediate.<anonymous> (/Users/i022021/dev/node/theia/node_modules/vscode-jsonrpc/lib/main.js:242:13)
    at runCallback (timers.js:705:18)
root INFO [nsfw-watcher: 81231] Started watching: /Users/i022021/dev/node/dist/extension.js
```

the last part  of Uncaught exception is repeating many times.

**Comment by akosyakov** [comment]
```
Error: Cannot find module 'getmac'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/i022021/dev/node/theia/packages/plugin-ext/lib/plugin/node/env-node-ext.js:33:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
```

Looks like a real error. cc @benoitf does it ring a bell?

**Comment by ariel-bentu** [comment]
seems to not happen any more.

**Comment by benoitf** [comment]
I missed the CC notification. AFAIK we could hit the issue if we have some missing modules (getmac) so I would say probably that dependencies have not been updated. I introduced getmac module to grab mac address to generate a platform ID used by VS Code API. I would suspect that the module was not there.
