### ISSUE TITLE
[plug-in] Implement 'workbench.action.debug.restart` (vscode-java-debug) command

### ISSUE THREAD

**Issue by vrubezhny** [theia-ide/theia#5102]
### Description
 'workbench.action.debug.restart` VS Code API command is missing from Language Support Plugins used in Che 7 GA.  

https://github.com/Microsoft/vscode-docs/blob/master/docs/editor/debugging.md#debug-actions

### Reproduction Steps

Found by the code coverage tool, see: https://github.com/eclipse/che/issues/13007

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
It's a matter of renaming an existing command: https://github.com/theia-ide/theia/blob/e147cf39c7f484374b7ec0cd0d04958c3ef00bca/packages/debug/src/browser/debug-frontend-application-contribution.ts#L75

Please add a breaking note in CHANGELOG.

**Comment by vrubezhny** [comment]
> It's a matter of renaming an existing command:
> 
> https://github.com/theia-ide/theia/blob/e147cf39c7f484374b7ec0cd0d04958c3ef00bca/packages/debug/src/browser/debug-frontend-application-contribution.ts#L75
> 
> Please add a breaking note in CHANGELOG.

I also think so, but will the only renaming be enough?

**Comment by akosyakov** [comment]
@vrubezhny you should for sure check with your extension whether it is enough and put a comment on the PR that other double check it during review. yes `0.7.0` is next release

**Comment by vrubezhny** [comment]
Having the command renamed from `debug.restart` to `workbench.action.debug.restart` in order to make it consistent with VSCode and running the following versions of VSCode extensions on theia:
*  redhat.java-0.44.0.vsix
* vscode-java-debug-0.16.0.vsix

I was able to reproduce the following error:
```
root ERROR [hosted-plugin: 24978] (node:24978) UnhandledPromiseRejectionWarning: Error: The command 'workbench.action.debug.restart' cannot be executed. There are no active handlers available for the command.
    at CommandRegistry.<anonymous> (http://localhost:3000/bundle.js:98782:31)
    at step (http://localhost:3000/bundle.js:98570:23)
    at Object.next (http://localhost:3000/bundle.js:98551:53)
    at http://localhost:3000/bundle.js:98545:71
    at new Promise (<anonymous>)
    at ../../packages/core/lib/common/command.js.__awaiter (http://localhost:3000/bundle.js:98541:12)
    at CommandRegistry.../../packages/core/lib/common/command.js.CommandRegistry.executeCommand (http://localhost:3000/bundle.js:98765:16)
    at CommandRegistryMainImpl.push.../../packages/plugin-ext/lib/main/browser/command-registry-main.js.CommandRegistryMainImpl.$executeCommand (http://localhost:3000/86.bundle.js:3301:72)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.doInvokeHandler (http://localhost:3000/44.bundle.js:498:23)
    at RPCProtocolImpl.push.../../packages/plugin-ext/lib/api/rpc-protocol.js.RPCProtocolImpl.invokeHandler (http://localhost:3000/44.bundle.js:483:41)

root ERROR [hosted-plugin: 24978] (node:24978) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 7)
```
For some reasons in most cases HotCodeReplace was silently failing without any error indications logged with this version of `vscode-java-debug` as well as with version `0.15.0`.
