### ISSUE TITLE
Cannot start electron example on windows10 with error spawn UNKNOWN

### ISSUE THREAD

**Issue by wheelBL** [theia-ide/theia#5116]
### Description
clone theia and follow the quick start. A spawn UNKNOW error occurs when starting electron example.

### Reproduction Steps
execute the following instructions
```
git clone https://github.com/theia-ide/theia \
&& cd theia \
&& yarn \
&& yarn run rebuild:electron \
&& cd examples/electron \
&& yarn run start
```

**OS and Theia version:**
OS: Windows Server 2016 Standard and Windows 10 Pro 1703
Theia: fe6ea99291c177a1ba9278b99c1918611f624bbf

**Diagnostics:** 
```
PS D:\code\theia\examples\electron> yarn run start
yarn run v1.16.0
$ theia start --plugins=local-dir:../../plugins
command D:\code\theia\node_modules\electron\cli.js
args D:\code\theia\examples\electron\src-gen\frontend\electron-main.js,--plugins=local-dir:../../plugins
options [object Object]
{ Error: spawn UNKNOWN
    at ChildProcess.spawn (internal/child_process.js:366:11)
    at Object.spawn (child_process.js:538:9)
    at ApplicationProcess.spawn (D:\code\theia\dev-packages\application-manager\lib\application-process.js:34:19)
    at ApplicationPackageManager.<anonymous> (D:\code\theia\dev-packages\application-manager\lib\application-package-man
ager.js:197:30)
    at step (D:\code\theia\dev-packages\application-manager\lib\application-package-manager.js:58:23)
    at Object.next (D:\code\theia\dev-packages\application-manager\lib\application-package-manager.js:39:53)
    at D:\code\theia\dev-packages\application-manager\lib\application-package-manager.js:33:71
    at new Promise (<anonymous>)
    at __awaiter (D:\code\theia\dev-packages\application-manager\lib\application-package-manager.js:29:12)
    at ApplicationPackageManager.startElectron (D:\code\theia\dev-packages\application-manager\lib\application-package-m
anager.js:193:16) errno: 'UNKNOWN', code: 'UNKNOWN', syscall: 'spawn' }
error Command failed with exit code 1.
```

**Comment by akosyakov** [comment]
Which version of node? cc @kittaakos maybe you have ideas what goes wrong?

**Comment by kittaakos** [comment]
I have tried it, I could reproduce the issue.

Currently, I am checking what's going on; I am not sure yet but perhaps we cannot spawn the electron process outside of the user's folder.

**Comment by kittaakos** [comment]
> I am not sure yet but perhaps we cannot spawn the electron process outside of the user's folder

No, it does not work either when I start it from the user's home.

**Comment by kittaakos** [comment]
> maybe you have ideas what goes wrong?

We cannot use `node_modules/electron/cli.js` on Windows. The original `node_modules/.bin/electron` on UNIX is:
```
#!/usr/bin/env node

var electron = require('./')

var proc = require('child_process')

var child = proc.spawn(electron, process.argv.slice(2), {stdio: 'inherit', windowsHide: false})
child.on('close', function (code) {
  process.exit(code)
})

const handleTerminationSignal = function (signal) {
  process.on(signal, function signalHandler () {
    if (!child.killed) {
      child.kill(signal)
    }
  })
}

handleTerminationSignal('SIGINT')
handleTerminationSignal('SIGTERM')
```

And on Windows it is:
```
#!/bin/sh
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")

case `uname` in
    *CYGWIN*) basedir=`cygpath -w "$basedir"`;;
esac

if [ -x "$basedir/node" ]; then
  "$basedir/node"  "$basedir/../electron/cli.js" "$@"
  ret=$?
else 
  node  "$basedir/../electron/cli.js" "$@"
  ret=$?
fi
exit $ret
```

As I see, we cannot `require` the `cli.js` module but we have to spawn the binary as we did before https://github.com/theia-ide/theia/commit/4dc74a522c0e353b0573c0e69f4f8d6ed71d1633#diff-99e0a5729f2015f136002eec7ba112c1. At least, the current way does not work on Windows.

**Comment by kittaakos** [comment]
@wheelBL, can you please try with https://github.com/theia-ide/theia/pull/5127?
