### ISSUE TITLE
Building Theia with Node 12.2.0 doesn;t work

### ISSUE THREAD

**Issue by akhiljay** [theia-ide/theia#5117]
### Description
I tried installing the dependencies for Theia IDE based on the instructions provided here https://www.theia-ide.org/doc/Composing_Applications.html 

### Reproduction Steps
I just typed in Yarn to install the packages but it errors out at "node_modules/node-pty - Command failed". This happens if you have node 12.2.0 released on May 7 th 2019
https://nodejs.org/en/download/releases/

**Comment by kittaakos** [comment]
Upstream change: https://github.com/fsevents/fsevents/pull/274
```
30 warnings and 14 errors generated.
make: *** [Release/obj.target/fse/fsevents.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/akos.kitta/git/theia/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:257:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command \"/Users/akos.kitta/.nvm/versions/node/v12.2.0/bin/node\" \"/Users/akos.kitta/git/theia/node_modules/node-gyp/bin/node-gyp.js\" \"build\" \"--fallback-to-build\" \"--module=/Users/akos.kitta/git/theia/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node\" \"--module_name=fse\" \"--module_path=/Users/akos.kitta/git/theia/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64\" \"--napi_version=4\" \"--node_abi_napi=napi\"
gyp ERR! cwd /Users/akos.kitta/git/theia/node_modules/fsevents
gyp ERR! node -v v12.2.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/Users/akos.kitta/.nvm/versions/node/v12.2.0/bin/node /Users/akos.kitta/git/theia/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/akos.kitta/git/theia/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/akos.kitta/git/theia/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/akos.kitta/git/theia/node_modules/fsevents/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1011:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:268:5)
node-pre-gyp ERR! System Darwin 18.5.0
node-pre-gyp ERR! command \"/Users/akos.kitta/.nvm/versions/node/v12.2.0/bin/node\" \"/Users/akos.kitta/git/theia/node_modules/fsevents/node_modules/node-pre-gyp/bin/node-pre-gyp\" \"install\" \"--fallback-to-build\"
node-pre-gyp ERR! cwd /Users/akos.kitta/git/theia/node_modules/fsevents
node-pre-gyp ERR! node -v v12.2.0
node-pre-gyp ERR! node-pre-gyp -v v0.10.0
node-pre-gyp ERR! not ok 
Failed to execute '/Users/akos.kitta/.nvm/versions/node/v12.2.0/bin/node /Users/akos.kitta/git/theia/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/Users/akos.kitta/git/theia/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64/fse.node --module_name=fse --module_path=/Users/akos.kitta/git/theia/node_modules/fsevents/lib/binding/Release/node-v72-darwin-x64 --napi_version=4 --node_abi_napi=napi' (1)"
info This module is OPTIONAL, you can safely ignore this error
```

```
$ yarn why fsevents
yarn why v1.15.2
[1/4] 🤔  Why do we have the module "fsevents"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "fsevents@1.2.4"
info Reasons this module exists
   - "_project_#@theia#application-manager#webpack#watchpack#chokidar" depends on it
   - Hoisted from "_project_#@theia#application-manager#webpack#watchpack#chokidar#fsevents"
✨  Done in 0.90s.
```

**Comment by abalter** [comment]
According to [this](https://github.com/theia-ide/theia/issues/5123#issuecomment-491795426) it will only build under 10. But as you can see, I couldn't get it to build with 10 either.

**Comment by abalter** [comment]
According to [this](https://github.com/theia-ide/theia/issues/5123#issuecomment-491795426) it will only build under 10. But as you can see, I couldn't get it to build with 10 either.
