### ISSUE TITLE
Error building @theia/node-pty

### ISSUE THREAD

**Issue by jankeromnes** [theia-ide/theia#5168]
### Description
Installing Theia dependencies is broken in Gitpod, and in particular building `@theia/node-pty`.

### Reproduction Steps

1. Open [Theia in Gitpod](https://gitpod.io/#https://github.com/theia-ide/theia)
2. See the errors in the automated build log

**OS and Theia version:**

Linux 4.15.0-1028-gcp / trunk

**Diagnostics:** 

This is the full log when `yarn` is run:

```
yarn install v1.16.0
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning monaco-languageclient@0.9.0: The engine "vscode" appears to be invalid.
warning vscode-base-languageclient@4.4.0: The engine "vscode" appears to be invalid.
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
warning "workspace-aggregator-64b51a41-eda4-45b4-92c7-b94c817f5662 > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-64b51a41-eda4-45b4-92c7-b94c817f5662 > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-64b51a41-eda4-45b4-92c7-b94c817f5662 > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
[5/5] Building fresh packages...
[6/14] ⢀ @theia/node-pty
[2/14] ⢀ dtrace-provider
[3/14] ⢀ electron
[4/14] ⢀ native-keymap
error /workspace/theia/node_modules/@theia/node-pty: Command failed.
Exit code: 1
Command: node scripts/install.js
Arguments:
Directory: /workspace/theia/node_modules/@theia/node-pty
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | linux | x64
gyp http GET https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
gyp info spawn /usr/bin/python
gyp info spawn args [ '/workspace/theia/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/workspace/theia/node_modules/@theia/node-pty/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/workspace/theia/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/gitpod/.node-gyp/10.15.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/gitpod/.node-gyp/10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=/workspace/theia/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/gitpod/.node-gyp/10.15.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/workspace/theia/node_modules/@theia/node-pty',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: Entering directory '/workspace/theia/node_modules/@theia/node-pty/build'
  CXX(target) Release/obj.target/pty/src/unix/pty.o
In file included from ../../../nan/nan.h:50,
                 from ../src/unix/pty.cc:20:
/home/gitpod/.node-gyp/10.15.3/include/node/uv.h:24: error: unterminated #ifndef
 #ifndef UV_H

In file included from ../../../nan/nan.h:50,
                 from ../src/unix/pty.cc:20:
/home/gitpod/.node-gyp/10.15.3/include/node/uv.h:1468:69: error: ‘size’ has not been declared
 UV_EXTERN int uv_ip4_name(const struct sockaddr_in* src, char* dst, size
                                                                     ^~~~
In file included from /usr/include/c++/8/bits/stl_algobase.h:59,
                 from /usr/include/c++/8/memory:62,
                 from /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:21,
                 from /home/gitpod/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/usr/include/x86_64-linux-gnu/c++/8/bits/c++config.h:236:1: error: expected ‘,’ or ‘...’ before ‘namespace’
 namespace std
 ^~~~~~~~~
In file included from /usr/include/c++/8/new:40,
                 from /usr/include/c++/8/ext/new_allocator.h:33,
                 from /usr/include/x86_64-linux-gnu/c++/8/bits/c++allocator.h:33,
                 from /usr/include/c++/8/bits/allocator.h:46,
                 from /usr/include/c++/8/memory:63,
                 from /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:21,
                 from /home/gitpod/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/usr/include/c++/8/exception:35:37: error: expected ‘)’ before end of line
 #pragma GCC visibility push(default)
                                     ^
                                     )
In file included from ../../../nan/nan.h:50,
                 from ../src/unix/pty.cc:20:
/home/gitpod/.node-gyp/10.15.3/include/node/uv.h:1468:26: note: to match this ‘(’
 UV_EXTERN int uv_ip4_name(const struct sockaddr_in* src, char* dst, size
                          ^
In file included from /usr/include/c++/8/new:40,
                 from /usr/include/c++/8/ext/new_allocator.h:33,
                 from /usr/include/x86_64-linux-gnu/c++/8/bits/c++allocator.h:33,
                 from /usr/include/c++/8/bits/allocator.h:46,
                 from /usr/include/c++/8/memory:63,
                 from /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:21,
                 from /home/gitpod/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/usr/include/c++/8/exception:35:37: error: expected initializer before end of line
 #pragma GCC visibility push(default)
                                     ^
/usr/include/c++/8/exception:35:37: error: expected ‘}’ before end of line
In file included from ../../../nan/nan.h:50,
                 from ../src/unix/pty.cc:20:
/home/gitpod/.node-gyp/10.15.3/include/node/uv.h:27:12: note: to match this ‘{’
 extern "C" {
            ^
In file included from /usr/include/c++/8/new:40,
                 from /usr/include/c++/8/ext/new_allocator.h:33,
                 from /usr/include/x86_64-linux-gnu/c++/8/bits/c++allocator.h:33,
                 from /usr/include/c++/8/bits/allocator.h:46,
                 from /usr/include/c++/8/memory:63,
                 from /home/gitpod/.node-gyp/10.15.3/include/node/v8.h:21,
                 from /home/gitpod/.node-gyp/10.15.3/include/node/node.h:63,
                 from ../../../nan/nan.h:51,
                 from ../src/unix/pty.cc:20:
/usr/include/c++/8/exception:35:37: error: expected declaration before end of line
 #pragma GCC visibility push(default)
                                     ^
make: *** [pty.target.mk:101: Release/obj.target/pty/src/unix/pty.o] Error 1
make: Leaving directory '/workspace/theia/node_modules/@theia/node-pty/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/workspace/theia/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 4.15.0-1028-gcp
gyp ERR! command "/home/gitpod/.nvm/versions/node/v10.15.3/bin/node" "/workspace/theia/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /workspace/theia/node_modules/@theia/node-pty
```

**Comment by jankeromnes** [comment]
Could this be related to the use of Node 10?

The build errors have some similarities with https://github.com/microsoft/node-pty/issues/279.

**Comment by jankeromnes** [comment]
Strangely, when you retry a fresh dependencies install (with `THEIA_ELECTRON_SKIP_REPLACE_FFMPEG=1 yarn` because of https://github.com/theia-ide/theia/pull/5055#issuecomment-491186650), it seems to work fine.

I'm not sure what's different between the two runs.

**Comment by AlexTugarev** [comment]
@jankeromnes, please try again. Sometimes there is are hiccups with node-gyp builds.

e.g. from logs you can read such info:
> /home/gitpod/.node-gyp/10.15.3/include/node/uv.h:24: error: unterminated #ifndef

so, node-gyp tried to download some headers, but they're likely broken.
`rm -rf ./node_modules && rm -rm ~/.node-gyp && yarn` should do a clean build in such cases.

**Comment by jankeromnes** [comment]
This issue seems to have fixed itself. Closing for now.
