### ISSUE TITLE
Error reported on the console after a task is completed and we re-select the terminal 

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#5328]
### Description
After executing a task which open a terminal and the task terminates, selecting another view in the bottom panel and back to the terminal, it generate the following error on the server console.

```
root ERROR Request getCwdURI failed with error: terminal "13" does not exist Error: terminal "13" does not exist
    at ShellTerminalServer.<anonymous> (/home/lmcbout/theia/theia/packages/terminal/lib/node/base-terminal-server.js:117:27)
    at step (/home/lmcbout/theia/theia/packages/terminal/lib/node/base-terminal-server.js:59:23)
    at Object.next (/home/lmcbout/theia/theia/packages/terminal/lib/node/base-terminal-server.js:40:53)
    at /home/lmcbout/theia/theia/packages/terminal/lib/node/base-terminal-server.js:34:71
    at new Promise (<anonymous>)
    at __awaiter (/home/lmcbout/theia/theia/packages/terminal/lib/node/base-terminal-server.js:30:12)
    at ShellTerminalServer.BaseTerminalServer.getCwdURI (/home/lmcbout/theia/theia/packages/terminal/lib/node/base-terminal-server.js:112:16)
    at JsonRpcProxyFactory.<anonymous> (/home/lmcbout/theia/theia/packages/core/lib/common/messaging/proxy-factory.js:217:73)
    at step (/home/lmcbout/theia/theia/packages/core/lib/common/messaging/proxy-factory.js:47:23)
    at Object.next (/home/lmcbout/theia/theia/packages/core/lib/common/messaging/proxy-factory.js:28:53)
```

### Reproduction Steps
Open the browser with Theia as a workspace
Open the problem or output view in the bottom panel
Select Run Task -> npm: test browser
Wait the task finish (A popup message will tell you when the task is completed

 ==> Select the output view then re--select the terminal view, the error should show on the server console log

**OS and Theia version:**
Theia version : 0.7.0
OS: Ubuntu 16.04
Browser: Chrome

**Diagnostics:**

**Comment by lmcbout** [comment]
Another way to  test, you can use the packages/task/test-resources as a workspace. Modify the task-long-running, replace 300 by 5, so it is enough. Add a return statement at the end, The error will be reported when completed the task. 
Another way, use the following in the tasks.json and put focus on another view in the bottom panel and come back, the error is created again.
--> It looks like when the task is completed, it removes the terminal from the potential views even if it is still visible on the screen  and when we put the focus back, the error is generated.
In tasks.json, replace<theia folder> by your environment
    {
      "label": "list all files in Theia packages",
      "type": "shell",
      "cwd": "${workspaceFolder}",
      "command": "ls",
      "args": [
        "-alR",
        "$<theia folder>/packages"
      ]
    },

**Comment by vince-fugnitto** [comment]
I haven't been able to reproduce with either of the methods you provided, perhaps it has something to do with your environment ? Itd be good to confirm, maybe @elaihau you can try ?

**Comment by lmcbout** [comment]
After re basing With the latest commit (commit 741876b3ecba8a96) this morning, I noticed an issue that was fixed a week ago
"root ERROR Request getCwdURI failed with error: "

**Comment by lmcbout** [comment]
To reproduce
- Start a task, after completion, start again -> generate a second terminal
- Kill one of the two created terminal and start the task again
--> result: "root ERROR Request getCwdURI failed with error: "

**Comment by vince-fugnitto** [comment]
@lmcbout are you sure the issue still exists?
I am unable to reproduce the error following your procedure.

**Comment by elaihau** [comment]
> @lmcbout are you sure the issue still exists?
> I am unable to reproduce the error following your procedure.

I still see it happen from my local env.

**Comment by sgraband** [comment]
Fixed: `getCwdURI` now has `.catch(() => this.lastCwd)` fallback.
