### ISSUE TITLE
[0.7.1] Upcoming bugfix release

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#5336]
### Description
This is so people are aware and can (quickly) propose content. We have the following so far:  
- commit: https://github.com/theia-ide/theia/pull/5322/commits/adccdd0cd7efd1ee07aa5b0568a3c6eb7213cbaf (issue: https://github.com/theia-ide/theia/issues/5308)

We will probably not wait very long before proceeding.

**Comment by akosyakov** [comment]
including https://github.com/theia-ide/theia/commit/26492e7d6af261be800be6c91d43be39256d59f8 would be good as well

**Comment by marcdumais-work** [comment]
@akosyakov can you triage https://github.com/theia-ide/theia/issues/5338; I wonder if it's only cosmetic or a real, must-fix issue that could/should be included as well.

**Comment by marcdumais-work** [comment]
I created the `0.7.1` branch from the `0.6.0` release commit, and added the 2 commits/fixes above on top.

**Comment by marcdumais-work** [comment]
I have built and published the `0.7.1` branch to a local NPM registry and build an application like the browser example, using the locally published packages. The app starts well, so it looks like the vscode-uri fix works. Not sure how to validate the other fix. 

I have however issues with the git unit tests not passing (timeout). Will retry in case it's a fluke.

**Comment by marcdumais-work** [comment]
```
@theia/git:   83 passing (1m)
@theia/git:   1 failing
@theia/git:   1) git-slow diff-slow diff with rename/move:
@theia/git:      Error: Timeout of 50000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
@theia/git:   
@theia/git: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
@theia/git: error Command failed with exit code 1.
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: yarn run test
lerna ERR! Warning: React depends on requestAnimationFrame. Make sure that you load a polyfill in older browsers. https://fb.me/react-polyfills
lerna ERR! (node:2513) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dispose' of undefined
lerna ERR!     at DisposableCollection.push (/opt/ericsson-dev/theia/packages/core/lib/common/disposable.js:80:42)
lerna ERR!     at GitRepositoryProvider.<anonymous> (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:142:44)
lerna ERR!     at step (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:70:23)
lerna ERR!     at Object.next (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:51:53)
lerna ERR!     at fulfilled (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:42:58)
lerna ERR! (node:2513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
lerna ERR! (node:2513) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
lerna ERR! (node:2513) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dispose' of undefined
lerna ERR!     at DisposableCollection.push (/opt/ericsson-dev/theia/packages/core/lib/common/disposable.js:80:42)
lerna ERR!     at GitRepositoryProvider.<anonymous> (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:142:44)
lerna ERR!     at step (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:70:23)
lerna ERR!     at Object.next (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:51:53)
lerna ERR!     at fulfilled (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:42:58)
lerna ERR! (node:2513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
lerna ERR! (node:2513) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dispose' of undefined
lerna ERR!     at DisposableCollection.push (/opt/ericsson-dev/theia/packages/core/lib/common/disposable.js:80:42)
lerna ERR!     at GitRepositoryProvider.<anonymous> (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:142:44)
lerna ERR!     at step (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:70:23)
lerna ERR!     at Object.next (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:51:53)
lerna ERR!     at fulfilled (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:42:58)
lerna ERR! (node:2513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
lerna ERR! (node:2513) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'dispose' of undefined
lerna ERR!     at DisposableCollection.push (/opt/ericsson-dev/theia/packages/core/lib/common/disposable.js:80:42)
lerna ERR!     at GitRepositoryProvider.<anonymous> (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:142:44)
lerna ERR!     at step (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:70:23)
lerna ERR!     at Object.next (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:51:53)
lerna ERR!     at fulfilled (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:42:58)
lerna ERR! (node:2513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)
lerna ERR! (node:2513) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
lerna ERR!     at __values (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:76:46)
lerna ERR!     at GitRepositoryProvider.<anonymous> (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:268:30)
lerna ERR!     at step (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:70:23)
lerna ERR!     at Object.next (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:51:53)
lerna ERR!     at fulfilled (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:42:58)
lerna ERR! (node:2513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 5)
lerna ERR! (node:2513) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
lerna ERR!     at __values (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:76:46)
lerna ERR!     at GitRepositoryProvider.<anonymous> (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:268:30)
lerna ERR!     at step (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:70:23)
lerna ERR!     at Object.next (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:51:53)
lerna ERR!     at fulfilled (/opt/ericsson-dev/theia/packages/git/lib/browser/git-repository-provider.js:42:58)
lerna ERR! (node:2513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 6)
lerna ERR! The command `git clone --recursive --progress -- https://github.com/kittaakos/eclipse.jdt.ls.git /tmp/diff-slow-rename11953-2513-1l8iubw.wcw8` exited with an unexpected code: 128. The caller should either handle this error, or expect that exit code.
lerna ERR! Cloning into '/tmp/diff-slow-rename11953-2513-1l8iubw.wcw8'...
lerna ERR! remote: Enumerating objects: 16063, done.        
remote: Total 16063 (delta 0), reused 0 (delta 0), pack-reused 16063        
Receiving objects: 100% (16063/16063), 7.12 MiB | 150.00 KiB/s, done.iB/s   
lerna ERR! fatal: unable to open /tmp/diff-slow-rename11953-2513-1l8iubw.wcw8/.git/objects/pack/tmp_pack_aJzZ3U: No such file or directory
lerna ERR! fatal: index-pack failed

```

**Comment by marcdumais-work** [comment]
This failure does not happen on master, as far as I know. Maybe I am missing a fix for it?

**Comment by marcdumais-work** [comment]
I tried on another machine and the git unit tests now pass. 

I'll include 8516a5257f106f61eb73244d02a4799e48743b2e as well (https://github.com/theia-ide/theia/pull/5340)

**Comment by marcdumais-work** [comment]
`0.7.1` published
