### ISSUE TITLE
[preview] [MarkDown] Theia README preview broken in theia app built from npm

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#5337]
### Description
The Markdown rendering is broken in `next`, when used from application built from packages. Not all `.md` files are affected. I noticed that our main `README.md` is affected. 

This issue is not present in the browser example, containing the same extensions, but built from sources.

### Reproduction Steps
``` 
cd <theia repo>/examples/browser
mkdir a && cd a
cp ../package.json .
# edit package.json: replace all theia package version (e.g.:"0.7.0") with "next"
yarn
yarn  theia build
yarn theia start --port=3333 ../../    # open point browser to "localhost:3333"
try to open README.md from root: right-click -> open with -> preview
```

**OS and Theia version:**
ubuntu 16.04, version: most recent `next` as of about an hour ago

**Diagnostics:** 
Front-tend log: this one happens every time I try to preview our project's README.md. 
```
Uncaught (in promise) TypeError: h is not a function
    at e.getEngine (markdown-preview-handler.ts:295)
    at e.renderContent (markdown-preview-handler.ts:48)
    at n.<anonymous> (preview-widget.ts:201)
    at types.ts:53
    at Object.next (types.ts:53)
    at types.ts:53
    at new Promise (<anonymous>)
    at c (types.ts:53)
    at n.render (preview-widget.ts:197)
    at n.<anonymous> (preview-widget.ts:183)
```

backend log: this happens soon after backend starts / workspace is set - it and may or may not be related to the cause of this issue
```
root INFO Using Git [2.21.0] from the PATH. (/usr/bin/git)
root ERROR TypeError: Cannot read property 'forEach' of undefined
    at http://localhost:3333/bundle.js:106:1276577
    at http://localhost:3333/bundle.js:1:68500
    at e.invoke (http://localhost:3333/bundle.js:1:68718)
    at e.fire (http://localhost:3333/bundle.js:1:70043)
    at e.set [as selectedRepository] (http://localhost:3333/bundle.js:8:82643)
    at e.set [as selectedRepository] (http://localhost:3333/bundle.js:1:321356)
    at e.<anonymous> (http://localhost:3333/bundle.js:1:323379)
    at http://localhost:3333/bundle.js:1:319070
    at Object.next (http://localhost:3333/bundle.js:1:319175)
    at a (http://localhost:3333/bundle.js:1:317921)
```

**Comment by AlexTugarev** [comment]
They switched exports in the `markdown-it-anchor` library. cf. [commit](https://github.com/valeriangalliat/markdown-it-anchor/commit/e0bdda02c0e4f8d9725a2a552dffa4a3f432da96)

Besides that, I don't see any useful feature added. Going to create a PR to pin the version for now.

Also, that is a very nice example of how things can go south and we are not aware of it. If our `yarn.lock` would be update more frequently, we'd see this kind of errors earlier.
