### ISSUE TITLE
[plugins] error thrown 'hosted plugin instance is not running'

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5358]
**Description**

An error is thrown whenever the frontend-application is closed, while the backend is still alive.

```
root ERROR Error: Hosted plugin instance is not running.
    at NodeHostedPluginRunner.AbstractHostedInstanceManager.terminate (/workspace/theia/packages/plugin-dev/lib/node/hosted-instance-manager.js:196:19)
    at HostedPluginServerImpl.dispose (/workspace/theia/packages/plugin-dev/lib/node/hosted-plugin-service.js:72:36)
    at /workspace/theia/packages/plugin-dev/lib/node/plugin-dev-backend-module.js:36:65
    at /workspace/theia/packages/core/lib/common/event.js:161:33
    at CallbackList.invoke (/workspace/theia/packages/core/lib/common/event.js:176:39)
    at Emitter.fire (/workspace/theia/packages/core/lib/common/event.js:264:29)
    at /workspace/theia/packages/core/lib/common/messaging/proxy-factory.js:153:58
    at CallbackList.invoke (/workspace/theia/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/workspace/theia/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at closeHandler (/workspace/theia/node_modules/vscode-jsonrpc/lib/main.js:221:26)
```

**Steps to Reproduce:**
1. Start the application (at the moment of testing, no plugins were present)
2. Open the frontend in a browser
3. Close the frontend
4. Notice the error thrown on the backend

**Additional Info**
- Master as of 92cfe9a
- OS Version: `MacOS 10.14`
- No plugins present

**Comment by kittaakos** [comment]
Happens with the electron example too. Start the electron application and refresh the browser window:
```
root ERROR Error: Hosted plugin instance is not running.
    at ElectronNodeHostedPluginRunner.AbstractHostedInstanceManager.terminate (/Users/akos.kitta/git/theia/packages/plugin-dev/lib/node/hosted-instance-manager.js:196:19)
    at HostedPluginServerImpl.dispose (/Users/akos.kitta/git/theia/packages/plugin-dev/lib/node/hosted-plugin-service.js:72:36)
    at /Users/akos.kitta/git/theia/packages/plugin-dev/lib/node/plugin-dev-backend-module.js:36:65
    at /Users/akos.kitta/git/theia/packages/core/lib/common/event.js:161:33
    at CallbackList.invoke (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:176:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/packages/core/lib/common/event.js:264:29)
    at /Users/akos.kitta/git/theia/packages/core/lib/common/messaging/proxy-factory.js:153:58
    at CallbackList.invoke (/Users/akos.kitta/git/theia/node_modules/vscode-jsonrpc/lib/events.js:71:39)
    at Emitter.fire (/Users/akos.kitta/git/theia/node_modules/vscode-jsonrpc/lib/events.js:135:36)
    at closeHandler (/Users/akos.kitta/git/theia/node_modules/vscode-jsonrpc/lib/main.js:221:26)
```
