### ISSUE TITLE
[scm] error cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5363]
**Description**

There is an error thrown by the `scm` package:

```
root ERROR TypeError: Cannot read property 'forEach' of undefined
    at http://localhost:3000/81.bundle.js:437:41
    at http://localhost:3000/bundle.js:99413:33
    at CallbackList.../../packages/core/lib/common/event.js.CallbackList.invoke (http://localhost:3000/bundle.js:99428:39)
    at Emitter.../../packages/core/lib/common/event.js.Emitter.fire (http://localhost:3000/bundle.js:99516:29)
    at ScmService.set [as selectedRepository] (http://localhost:3000/36.bundle.js:1316:57)
    at GitRepositoryProvider.set [as selectedRepository] (http://localhost:3000/82.bundle.js:6890:52)
    at GitRepositoryProvider.<anonymous> (http://localhost:3000/82.bundle.js:6994:53)
    at step (http://localhost:3000/82.bundle.js:6757:23)
    at Object.next (http://localhost:3000/82.bundle.js:6738:53)
    at fulfilled (http://localhost:3000/82.bundle.js:6729:58)
```

**Steps to Reproduce:**
1. Start the application without a workspace.
2. Notice the error thrown on the backend.

**Comment by benoitf** [comment]
I noticed it as well  :+1:
