### ISSUE TITLE
[git] Error when the git repository was wiped from the FS between two server sessions

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#5437]
Found when testing #5416.

Wipe the git repository from the FS between two backend sessions. The reconnecting client will trigger a Git refresh (`status`?) and will cause the following error:

```
root INFO Using Git [2.20.1] from the PATH. (/usr/local/bin/git)
root INFO [nsfw-watcher: 1184] Started watching: /Users/akos.kitta/.theia
root INFO [nsfw-watcher: 1184] Started watching: /Users/akos.kitta/Desktop/git-tmp
root INFO [nsfw-watcher: 1184] Started watching: /Users/akos.kitta/Desktop/git-tmp
root WARN EditorNavigationContribution.onStart is slow, took: 877.3999999975786 ms
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO Config file tasks.json does not exist under file:///Users/akos.kitta/Desktop/git-tmp
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.20.1'.
root ERROR Request status failed with error: Unable to find path to repository on disk. Error: Unable to find path to repository on disk.
    at /Users/akos.kitta/git/theia/node_modules/dugite-no-gpl/build/lib/git-process.js:87:39
    at exithandler (child_process.js:301:5)
    at ChildProcess.errorhandler (child_process.js:313:5)
    at ChildProcess.emit (events.js:189:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
root WARN Couldn't restore widget for code-editor-opener. Error: Error: 'file:///Users/akos.kitta/Desktop/git-tmp/mocha-eperm/package.json' has not been found. 
```

The frontend error:
```
Uncaught (in promise) Error: Request 'status' failed
    at Proxy.<anonymous> (bundle.js:109424)
    at GitRepositoryTracker.<anonymous> (:3000/80.bundle.js:5649)
    at step (:3000/80.bundle.js:5613)
    at Object.next (:3000/80.bundle.js:5594)
    at :3000/80.bundle.js:5588
    at new Promise (<anonymous>)
    at push.../../packages/git/lib/browser/git-repository-tracker.js.__awaiter (:3000/80.bundle.js:5584)
    at GitRepositoryTracker.<anonymous> (:3000/80.bundle.js:5637)
    at invokeFunc (bundle.js:44889)
    at trailingEdge (bundle.js:44936)
```

The code ends up here (no idea what's wrong with the source maps):
```js
this.toDispose.dispose();
                        tokenSource = new core_1.CancellationTokenSource();
                        this.toDispose.push(core_1.Disposable.create(function () { return tokenSource.cancel(); }));
                        token = tokenSource.token;
                        source = this.selectedRepository;
                        if (!source) return [3 /*break*/, 3];
                        return [4 /*yield*/, this.git.status(source)];
```

**Comment by sgraband** [comment]
`@theia/git` is officially deprecated per README.
