### ISSUE TITLE
An extension application developer has to explicitly depend on @theia/monaco

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#544]
Otherwise, the generated webpack configuration breaks as the `monaco` dependencies are not in the `node_modules` folder.

Ideally, an extension should be able to contribute to the webpack generation phase, and the monaco part should not be hardcoded.

**Comment by kittaakos** [comment]
Another problem is that I have to explicitly depend on workspace, otherwise, the application does not start:

```
index.js:35 Error: A command with id 'file:open' does not exist.
    at ActionMenuNode.get [as label] (file:///Users/akos.kitta/Desktop/theia-electron-app/lib/bundle.js:15630:23)
    at ActionMenuNode.get [as sortString] (file:///Users/akos.kitta/Desktop/theia-electron-app/lib/bundle.js:15646:45)
    at file:///Users/akos.kitta/Desktop/theia-electron-app/lib/bundle.js:15575:19
    at Array.sort (native)
    at CompositeMenuNode.addNode (file:///Users/akos.kitta/Desktop/theia-electron-app/lib/bundle.js:15574:24)
    at MenuModelRegistry.findSubMenu (file:///Users/akos.kitta/Desktop/theia-electron-app/lib/bundle.js:15539:17)
    at MenuModelRegistry.registerSubmenu (file:///Users/akos.kitta/Desktop/theia-electron-app/lib/bundle.js:15497:30)
    at NavigatorMenuContribution.registerMenus (file:///Users/akos.kitta/Desktop/theia-electron-app/lib/bundle.js:27044:18)
    at MenuModelRegistry.onStart (file:///Users/akos.kitta/Desktop/theia-electron-app/lib/bundle.js:15478:25)
    at FrontendApplication.startContributions (file:///Users/akos.kitta/Desktop/theia-electron-app/lib/bundle.js:14803:20)
module.exports.Promise.resolve.then.then.then.then.then.then.catch.reason @ index.js:35
```

**Comment by kittaakos** [comment]
@akosyakov, I think you have updated the extension manager to handle the transitive dependencies correctly. If so, could you please confirm and close this? Thank you!

**Comment by akosyakov** [comment]
Yes, it is backed-in the webpack config generator. Ideally, each extension could contribute to the generation process.
