### ISSUE TITLE
Cannot set property exports of #<Module> which has only a getter

### ISSUE THREAD

**Issue by sstone1** [theia-ide/theia#5514]
### Description
I am trying to use an existing VSCode extension with Theia, but it fails when reloading the browser window with the following error:

```
PLUGIN_HOST(18): PluginManagerExtImpl/loadPlugin(/tmp/vscode-unpacked/ibm.blockchain-platform.latest.tswkwskifz.ibm-blockchain-platform-1.0.3.vsix/extension/out/src/extension)
TypeError: Cannot set property exports of #<Module> which has only a getter
    at /home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js:135:50
    at Array.forEach (<anonymous>)
    at Object.loadPlugin (/home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/plugin-host-rpc.js:127:48)
    at PluginManagerExtImpl.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:174:48)
    at step (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:47:23)
    at Object.next (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:28:53)
    at /home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:22:71
    at new Promise (<anonymous>)
    at __awaiter (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:18:12)
    at PluginManagerExtImpl.$init (/home/theia/node_modules/@theia/plugin-ext/lib/plugin/plugin-manager.js:121:16)
Unable to load a plugin from "/tmp/vscode-unpacked/ibm.blockchain-platform.latest.tswkwskifz.ibm-blockchain-platform-1.0.3.vsix/extension/out/src/extension"
```

### Reproduction Steps
Some node modules, such as `ansi-styles`, define the exports in an immutable manner: https://github.com/chalk/ansi-styles/blob/master/index.js#L159

This line:
https://github.com/theia-ide/theia/blob/master/packages/plugin-ext/src/hosted/node/plugin-host-rpc.ts#L110

... causes this error when trying to assign to the exports property which only has a getter:
```
/Users/sstone1/Desktop/test.js:6
module.children[0].exports = {};
                           ^

TypeError: Cannot assign to read only property 'exports' of object '#<Module>'
```

**OS and Theia version:**

**Diagnostics:**

**Comment by akosyakov** [comment]
@sstone1 you are welcomed to have a look if it is critical for you.
