### ISSUE TITLE
[vscode] unable to run extension sample (diagnostic-related-information-sample)

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#5773]
**Description**

I am unable to run the extension sample from https://github.com/microsoft/vscode-extension-samples/tree/master/diagnostic-related-information-sample which provides diagnostics for test purposes. Originally I wanted to use the extension to test my PR for https://github.com/theia-ide/theia/pull/5763.

**How to test**

1. close the repository (https://github.com/microsoft/vscode-extension-samples)
2. `cd diagnostic-related-information-sample` and build (`npm install`)
3. copy the directory `diagnostic-related-information-sample` into the `plugins` folder in Theia
4. start the Theia application
5. open the directory `diagnostic-related-information-sample` as a workspace
6. open the file `sample-demo.rs`
7. no problem markers are contributed, an error is displayed in the console

**Error**

```bash
$ theia start --plugins=local-dir:../../plugins -p=8989
root INFO Theia app listening on http://localhost:8989.
root INFO PluginTheiaDirectoryHandler: accepting plugin with path /home/evinfug/theia-workspace/theia/plugins/diagnostic-related-information-sample
root INFO Resolved "diagnostic-related-information-sample" to a VS Code extension "diagnostic-related-information-sample@0.0.1" with engines: { vscode: '^1.32.0' }
root INFO Deploying backend plugin "diagnostic-related-information-sample@0.0.1" from "/home/evinfug/theia-workspace/theia/plugins/diagnostic-related-information-sample/out/extension.js"
root INFO Using Git [2.21.0] from the PATH. (/usr/bin/git)
root WARN LanguagesFrontendContribution.onStart is slow, took: 157.7500000003056 ms
root WARN EditorNavigationContribution.onStart is slow, took: 225.62500000003638 ms
root INFO [nsfw-watcher: 7607] Started watching: /home/evinfug/.theia
root INFO [hosted-plugin: 7626] PLUGIN_HOST(7626) starting instance
root INFO [hosted-plugin: 7626] PLUGIN_HOST(7626): PluginManagerExtImpl/init()
PLUGIN_HOST(7626): initializing(diagnostic-related-information-sample@0.0.1 with /home/evinfug/theia-workspace/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-init.js)
root INFO [hosted-plugin: 7626] PLUGIN_HOST(7626): PluginManagerExtImpl/loadPlugin(/home/evinfug/theia-workspace/theia/plugins/diagnostic-related-information-sample/out/extension.js)
root ERROR [hosted-plugin: 7626] { Error: Cannot find module '/home/evinfug/theia-workspace/theia/plugins/diagnostic-related-information-sample/out/extension.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Function.module._load (/home/evinfug/theia-workspace/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-init.js:98:33)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.loadPlugin (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/hosted/node/plugin-host-rpc.js:156:28)
    at PluginManagerExtImpl.<anonymous> (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:301:60)
    at step (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:47:23)
    at Object.next (/home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:28:53)
    at /home/evinfug/theia-workspace/theia/packages/plugin-ext/lib/plugin/plugin-manager.js:22:71 code: 'MODULE_NOT_FOUND' }
root ERROR [hosted-plugin: 7626] Unable to load a plugin from "/home/evinfug/theia-workspace/theia/plugins/diagnostic-related-information-sample/out/extension.js"


```

**Comment by kittaakos** [comment]
Works for me without a problem:

![Screen Shot 2019-07-22 at 16 18 30](https://user-images.githubusercontent.com/1405703/61639764-64f27e00-ac9c-11e9-8850-3141bebf5beb.jpg)

Checks this wiki page on running/testing VS Code extensions: https://github.com/theia-ide/theia/wiki/Testing-VS-Code-Extensions

**Comment by vince-fugnitto** [comment]
> Works for me without a problem
> Checks this wiki page on running/testing VS Code extensions: https://github.com/theia-ide/theia/wiki/Testing-VS-Code-Extensions

Thank you @kittaakos, I'll see the link you provided.

**Comment by vince-fugnitto** [comment]
Thank you @kittaakos :)
