### ISSUE TITLE
LaTeX-Ubuntu

### ISSUE THREAD

**Issue by maxcordivani** [theia-ide/theia#5813]
### Description
 on Ubuntu I have a problem, LaTeX View (Widget) is empty. 

### Reproduction Steps

See image.
![Annotazione 2019-07-29](https://user-images.githubusercontent.com/26182750/62064522-53c1e800-b22d-11e9-9114-3a6ee6351ad3.jpg)

**OS and Theia version:**
OS VMware: ubuntu ubuntu 4.18.0-25-generic
Theia version: v0.9.0

**Diagnostics:** 

```
@ubuntu:/home/massimo/theia# yarn
yarn install v1.17.3
$ node-gyp install
gyp info it worked if it ends with ok
gyp info using node-gyp@4.0.0
gyp info using node@10.15.3 | linux | x64
gyp http GET https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v10.15.3/node-v10.15.3-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v10.15.3/SHASUMS256.txt
10.15.3
gyp info ok 
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning monaco-languageclient@0.9.0: The engine "vscode" appears to be invalid.
warning vscode-base-languageclient@4.4.0: The engine "vscode" appears to be invalid.
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > istanbul-instrumenter-loader@3.0.1" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
warning " > tslint-language-service@0.9.9" has incorrect peer dependency "typescript@>= 2.3.1 < 3".
warning "workspace-aggregator-5c212cb3-0371-41ed-a57e-f1768ed6b9bb > @theia/application-manager > font-awesome-webpack@0.0.5-beta.2" has unmet peer dependency "font-awesome@>=4.3.0".
warning "workspace-aggregator-5c212cb3-0371-41ed-a57e-f1768ed6b9bb > @theia/debug > requestretry@3.1.0" has unmet peer dependency "request@2.*.*".
warning "workspace-aggregator-5c212cb3-0371-41ed-a57e-f1768ed6b9bb > @theia/application-manager > font-awesome-webpack > less-loader@2.2.3" has incorrect peer dependency "less@^2.3.1".
[5/5] Building fresh packages...
[12/16] ⠠ @theia/electron
[9/16] ⠠ drivelist
[7/16] ⠐ nsfw
[11/16] ⠐ vscode-ripgrep
error /home/massimo/theia/node_modules/@theia/electron: Command failed.
Exit code: 127
Command: node scripts/post-install.js
Arguments: 
Directory: /home/massimo/theia/node_modules/@theia/electron
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.3 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/home/massimo/theia/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/massimo/theia/dev-packages/electron/native/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/massimo/theia/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/root/.node-gyp/10.15.3/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/root/.node-gyp/10.15.3',
gyp info spawn args   '-Dnode_gyp_dir=/home/massimo/theia/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/root/.node-gyp/10.15.3/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/massimo/theia/dev-packages/electron/native',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: ingresso nella directory "/home/massimo/theia/dev-packages/electron/native/build"
  CC(target) Release/obj.target/ffmpeg/src/ffmpeg.o
  CC(target) Release/obj.target/ffmpeg/src/linux-ffmpeg.o
  SOLINK_MODULE(target) Release/obj.target/ffmpeg.node
  COPY Release/ffmpeg.node
make: uscita dalla directory "/home/massimo/theia/dev-packages/electron/native/build"
gyp info ok 
Found cached ffmpeg library.
Hashes are equal, not replacing the ffmpeg library.
Error: 2 bad / 18 found
> h264 detected (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
> aac detected (AAC (Advanced Audio Coding))
    at main (/home/massimo/theia/dev-packages/electron/electron-codecs-test.js:64:15)
    at Object.<anonymous> (/home/massimo/theia/dev-packages/electron/electron-codecs-test.js:70:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Error: "electron-codecs-test.js" exited with 127
    at ChildProcess.subprocess.once (/home/massimo/theia/dev-packages/electron/scripts/post-install.js:36:40)




root@ubuntu:/home/massimo/theia# cd examples/browser/
root@ubuntu:/home/massimo/theia/examples/browser# yarn run start
yarn run v1.17.3
$ theia start --plugins=local-dir:../../plugins
root WARN The directory referenced by local-dir:../../plugins does not exist.
root INFO Theia app listening on http://localhost:3000.
root INFO Detected keyboard layout from pressed keys: Italian (PC)
root WARN Collided keybinding is ignored;  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}  collided with  {"command":"file.saveAs","keybinding":"ctrl+shift+s"}
root WARN Could not register keybinding:
  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}
Error: "ctrlcmd+shift+s" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"}
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
root WARN LanguagesFrontendContribution.onStart is slow, took: 147 ms
root INFO Using Git [2.17.1] from the PATH. (/usr/bin/git)
root INFO [nsfw-watcher: 4429] Started watching: /root/.theia
root WARN EditorNavigationContribution.onStart is slow, took: 1421 ms
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
terminal ERROR Couldn't attach - can't find terminal with id: 0 
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.17.1'.
terminal ERROR Error attaching to terminal id 0, the terminal is most likely gone. Starting up a new terminal instead.
root INFO Config file tasks.json does not exist under file:///home/massimo/theia
root INFO [nsfw-watcher: 4429] Started watching: /home/massimo/theia/.theia/settings.json
root INFO [nsfw-watcher: 4429] Started watching: /home/massimo/theia/.vscode/launch.json
root INFO [nsfw-watcher: 4429] Started watching: /home/massimo/theia/.vscode/settings.json
root INFO [nsfw-watcher: 4429] Started watching: /home/massimo/theia
root INFO [nsfw-watcher: 4429] Started watching: /home/massimo/theia
root ERROR [nsfw-watcher: 4429] Failed to watch "/home/massimo/theia": Inotify limit reached
root INFO [nsfw-watcher: 4429] Stopped watching: /home/massimo/theia
root INFO Started watching the git repository: file:///home/massimo/theia
root INFO [nsfw-watcher: 4429] Started watching: /home/massimo/theia/latex/sample.tex
root INFO [nsfw-watcher: 4429] Started watching: /home/massimo/theia/examples/browser/package.json
root INFO [nsfw-watcher: 4429] Stopped watching: /home/massimo/theia/examples/browser/package.json
root INFO [nsfw-watcher: 4429] Started watching: /home/massimo/theia/examples/browser/compile.tsconfig.json
root INFO [nsfw-watcher: 4429] Stopped watching: /home/massimo/theia/examples/browser/compile.tsconfig.json
root INFO [nsfw-watcher: 4429] Started watching: /home/massimo/theia/examples/browser/coverage-webpack.config.js
root WARN Invalid embedded language found at scope meta.tag.js: <<null>>
root WARN Invalid embedded language found at scope meta.tag.without-attributes.js: <<null>>
root INFO [nsfw-watcher: 4429] Stopped watching: /home/massimo/theia/examples/browser/coverage-webpack.config.js
root INFO [nsfw-watcher: 4429] Started watching: /home/massimo/theia/examples/browser/wdio.conf.js
root INFO [nsfw-watcher: 4429] Stopped watching: /home/massimo/theia/examples/browser/wdio.conf.js
root INFO [nsfw-watcher: 4429] Started watching: /home/massimo/theia/examples/browser/Dockerfile
root INFO [nsfw-watcher: 4429] Stopped watching: /home/massimo/theia/examples/browser/Dockerfile
root INFO [nsfw-watcher: 4429] Started watching: /home/massimo/theia/LaTeX-Workshop/viewer/viewer.css
root INFO [nsfw-watcher: 4429] Stopped watching: /home/massimo/theia/LaTeX-Workshop/viewer/viewer.css
root INFO [nsfw-watcher: 4429] Started watching: /home/massimo/theia/.theia/settings.json
root INFO [nsfw-watcher: 4429] Stopped watching: /home/massimo/theia/.theia/settings.json
root INFO Stopped watching the git repository: file:///home/massimo/theia
root ERROR Uncaught Exception:  Error: Connection is disposed.
root ERROR Error: Connection is disposed.
    at new ConnectionError (/home/massimo/theia/node_modules/vscode-jsonrpc/lib/main.js:138:28)
    at throwIfClosedOrDisposed (/home/massimo/theia/node_modules/vscode-jsonrpc/lib/main.js:616:19)
    at Object.sendRequest (/home/massimo/theia/node_modules/vscode-jsonrpc/lib/main.js:715:13)
    at /home/massimo/theia/packages/core/lib/common/messaging/proxy-factory.js:311:72
    at new Promise (<anonymous>)
    at /home/massimo/theia/packages/core/lib/common/messaging/proxy-factory.js:304:24
    at process._tickCallback (internal/process/next_tick.js:68:7)
root INFO Detected keyboard layout from pressed keys: Italian (PC)
root WARN Collided keybinding is ignored;  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}  collided with  {"command":"file.saveAs","keybinding":"ctrl+shift+s"}
root WARN Could not register keybinding:
  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}
Error: "ctrlcmd+shift+s" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"}
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
root WARN LanguagesFrontendContribution.onStart is slow, took: 142 ms
root INFO Using Git [2.17.1] from the PATH. (/usr/bin/git)
root WARN EditorNavigationContribution.onStart is slow, took: 297 ms
root INFO [nsfw-watcher: 5917] Started watching: /root/.theia
root INFO Detected keyboard layout from pressed keys: Italian (PC)
root WARN Collided keybinding is ignored;  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}  collided with  {"command":"file.saveAs","keybinding":"ctrl+shift+s"}
root WARN Could not register keybinding:
  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}
Error: "ctrlcmd+shift+s" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"}
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
root WARN LanguagesFrontendContribution.onStart is slow, took: 136 ms
root INFO Using Git [2.17.1] from the PATH. (/usr/bin/git)
root INFO [nsfw-watcher: 5945] Started watching: /root/.theia
root INFO [nsfw-watcher: 5945] Started watching: /home/massimo/theia/Plugins
root INFO [nsfw-watcher: 5945] Started watching: /home/massimo/theia/Plugins
root WARN EditorNavigationContribution.onStart is slow, took: 1246 ms
root INFO Config file tasks.json does not exist under file:///home/massimo/theia/Plugins
root INFO Started watching the git repository: file:///home/massimo/theia
root INFO [nsfw-watcher: 5945] Started watching: /home/massimo/theia/Plugins/James-Yu.latex-workshop-7.2.0.vsix
root INFO [nsfw-watcher: 5945] Stopped watching: /home/massimo/theia/Plugins/James-Yu.latex-workshop-7.2.0.vsix
root INFO [nsfw-watcher: 5945] Started watching: /home/massimo/theia/Plugins/sample.tex
root INFO Stopped watching the git repository: file:///home/massimo/theia
root INFO Using Git [2.17.1] from the PATH. (/usr/bin/git)
root INFO Detected keyboard layout from pressed keys: Italian (PC)
root WARN Collided keybinding is ignored;  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}  collided with  {"command":"file.saveAs","keybinding":"ctrl+shift+s"}
root WARN Could not register keybinding:
  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}
Error: "ctrlcmd+shift+s" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"}
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
root WARN LanguagesFrontendContribution.onStart is slow, took: 158 ms
root WARN EditorNavigationContribution.onStart is slow, took: 5929 ms
root INFO [nsfw-watcher: 6159] Started watching: /root/.theia
root INFO Using Git [2.17.1] from the PATH. (/usr/bin/git)
root INFO [nsfw-watcher: 6182] Started watching: /root/.theia
root INFO [nsfw-watcher: 6182] Started watching: /home/massimo/theia/latex
root INFO Detected keyboard layout from pressed keys: Italian (PC)
root WARN Collided keybinding is ignored;  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}  collided with  {"command":"file.saveAs","keybinding":"ctrl+shift+s"}
root WARN Could not register keybinding:
  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}
Error: "ctrlcmd+shift+s" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"}
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
root WARN LanguagesFrontendContribution.onStart is slow, took: 140 ms
root INFO [nsfw-watcher: 6182] Started watching: /home/massimo/theia/latex
root WARN EditorNavigationContribution.onStart is slow, took: 1318 ms
root INFO Config file tasks.json does not exist under file:///home/massimo/theia/latex
root INFO Started watching the git repository: file:///home/massimo/theia
root INFO [nsfw-watcher: 6182] Started watching: /home/massimo/theia/latex/sample.tex
root INFO Stopped watching the git repository: file:///home/massimo/theia
root INFO Using Git [2.17.1] from the PATH. (/usr/bin/git)
root INFO Detected keyboard layout from pressed keys: Italian (PC)
root WARN Collided keybinding is ignored;  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}  collided with  {"command":"file.saveAs","keybinding":"ctrl+shift+s"}
root WARN Could not register keybinding:
  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}
Error: "ctrlcmd+shift+s" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"}
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
root WARN LanguagesFrontendContribution.onStart is slow, took: 149 ms
root WARN EditorNavigationContribution.onStart is slow, took: 264 ms
root INFO [nsfw-watcher: 6292] Started watching: /root/.theia
root INFO Detected keyboard layout from pressed keys: Italian (PC)
root WARN Collided keybinding is ignored;  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}  collided with  {"command":"file.saveAs","keybinding":"ctrl+shift+s"}
root WARN Could not register keybinding:
  {"command":"outlineView:toggle","keybinding":"ctrlcmd+shift+s"}
Error: "ctrlcmd+shift+s" is in collision with something else [scope:0]
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"}
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
root WARN LanguagesFrontendContribution.onStart is slow, took: 139 ms
root INFO Using Git [2.17.1] from the PATH. (/usr/bin/git)
root INFO [nsfw-watcher: 6316] Started watching: /root/.theia
root INFO [nsfw-watcher: 6316] Started watching: /home/massimo/theia
root WARN EditorNavigationContribution.onStart is slow, took: 7156 ms
root INFO [nsfw-watcher: 6316] Started watching: /home/massimo/theia
root ERROR [nsfw-watcher: 6316] Failed to watch "/home/massimo/theia": Inotify limit reached
root INFO [nsfw-watcher: 6316] Stopped watching: /home/massimo/theia
root INFO Config file tasks.json does not exist under file:///home/massimo/theia
root INFO [nsfw-watcher: 6316] Started watching: /home/massimo/theia/.theia/settings.json
root INFO Started watching the git repository: file:///home/massimo/theia
root INFO [nsfw-watcher: 6316] Started watching: /home/massimo/theia/.vscode/launch.json
root INFO [nsfw-watcher: 6316] Started watching: /home/massimo/theia/.vscode/settings.json
root INFO [nsfw-watcher: 6316] Started watching: /home/massimo/theia/latex/sample.tex
root INFO [nsfw-watcher: 6316] Started watching: /home/massimo/theia/.theia/settings.json
root INFO [nsfw-watcher: 6316] Stopped watching: /home/massimo/theia/.theia/settings.json
root ERROR [nsfw-watcher: 6316] Failed to watch "/home/massimo/theia": Inotify limit reached
root INFO [nsfw-watcher: 6316] Stopped watching: /home/massimo/theia
root INFO [nsfw-watcher: 6316] Started watching: /root/.npm/_logs/2019-07-29T23_24_49_960Z-debug.log


root INFO [nsfw-watcher: 6316] Started watching: /home/massimo/theia/package.json
root INFO [nsfw-watcher: 6316] Started watching: /home/massimo/theia/.editorconfig
root INFO [nsfw-watcher: 6316] Stopped watching: /home/massimo/theia/package.json
root INFO [nsfw-watcher: 6316] Stopped watching: /root/.npm/_logs/2019-07-29T23_24_49_960Z-debug.log
root INFO [nsfw-watcher: 6316] Stopped watching: /home/massimo/theia/.editorconfig
root INFO [nsfw-watcher: 6316] Started watching: /home/massimo/theia/webpack.config.js
root WARN Invalid embedded language found at scope meta.tag.js: <<null>>
root WARN Invalid embedded language found at scope meta.tag.without-attributes.js: <<null>>
root INFO [nsfw-watcher: 6316] Stopped watching: /home/massimo/theia/webpack.config.js
```

thanks

**Comment by kittaakos** [comment]
```
Hashes are equal, not replacing the ffmpeg library.
Error: 2 bad / 18 found
> h264 detected (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
> aac detected (AAC (Advanced Audio Coding))
    at main (/home/massimo/theia/dev-packages/electron/electron-codecs-test.js:64:15)
    at Object.<anonymous> (/home/massimo/theia/dev-packages/electron/electron-codecs-test.js:70:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
Error: "electron-codecs-test.js" exited with 127
    at ChildProcess.subprocess.once (/home/massimo/theia/dev-packages/electron/scripts/post-install.js:36:40)
```
This thread can help: https://github.com/marechal-p


```
root ERROR [nsfw-watcher: 6316] Failed to watch "/home/massimo/theia": Inotify limit reached
```
See this section in the doc: https://github.com/theia-ide/theia/blob/master/doc/Developing.md#linux

Are there any errors in the browser's console?

**Comment by akosyakov** [comment]
@maxcordivani please fix inotify limit as @kittaakos suggested and try again

if it does not help then it is a bug

**Comment by maxcordivani** [comment]
I have seen and followed your instructions.
Now works. I attach picture.
![Annotazione 2019-07-30](https://user-images.githubusercontent.com/26182750/62115980-ab0d9a00-b2b9-11e9-97e7-1afde492fef6.jpg)

Thanks for the great support.

**Comment by akosyakov** [comment]
thanks for reporting back
