### ISSUE TITLE
Cannot read property 'maxResults' of undefined     at SearchInWorkspaceWidget

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#5833]
It started today, seems to be a regression by some recent changes:
```
bundle.js:110209 root ERROR TypeError: Cannot read property 'maxResults' of undefined
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderNotification (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/88.bundle.js:2356:112)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderSearchField (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/88.bundle.js:2380:33)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderSearchAndReplace (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/88.bundle.js:2330:32)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderSearchHeader (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/88.bundle.js:2322:46)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.onAfterAttach (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/88.bundle.js:2280:18)
    at SearchInWorkspaceWidget.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/bundle.js:23662:22)
    at invokeHandler (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/bundle.js:7614:21)
    at Object.sendMessage (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/bundle.js:7350:13)
    at DockLayout.../../node_modules/@phosphor/widgets/lib/docklayout.js.DockLayout.attachWidget (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/bundle.js:12043:37)
    at DockLayout.../../node_modules/@phosphor/widgets/lib/docklayout.js.DockLayout.addWidget (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/bundle.js:11938:14)
log @ bundle.js:110209
2bundle.js:110209 root ERROR TypeError: Cannot read property 'maxResults' of undefined
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderNotification (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/88.bundle.js:2356:112)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderSearchField (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/88.bundle.js:2380:33)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderSearchAndReplace (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/88.bundle.js:2330:32)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.renderSearchHeader (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/88.bundle.js:2322:46)
    at SearchInWorkspaceWidget.push.../../packages/search-in-workspace/lib/browser/search-in-workspace-widget.js.SearchInWorkspaceWidget.onUpdateRequest (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/88.bundle.js:2292:22)
    at SearchInWorkspaceWidget.../../node_modules/@phosphor/widgets/lib/widget.js.Widget.processMessage (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/bundle.js:23628:22)
    at invokeHandler (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/bundle.js:7614:21)
    at sendMessage (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/bundle.js:7350:13)
    at runMessageLoop (https://3000-e7a860c1-828e-4f16-ad7b-634c59a7ec29.ws-eu0.gitpod.io/bundle.js:7664:17)
log @ bundle.js:110209
bundle.js:110209 
```

@vince-fugnitto @fangnx Could you have a look?

**Comment by kittaakos** [comment]
> It started today

It was logged already [here](https://github.com/theia-ide/theia/pull/5665#issuecomment-513770484) days ago.
I think they're the same.

**Comment by vince-fugnitto** [comment]
Yes I previously noticed it also when switching from `master` and the `view containers integration` branch. It was fixed when resetting the workbench layout so I didn't think more of it.

**Comment by akosyakov** [comment]
I see i was trying to preserve old layout in this branch in the morning and was switching between master and this branch, so maybe it was caused the issue. Anyway i've give up on this approach, since was not able to make any meaningful progress and will just go with completely resetting layout.
