### ISSUE TITLE
can't copy multi file in explorer

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#5856]
### Description
select multi file can't paste  

### Reproduction Steps
select multi file
press `Ctrl + C`
select target folder
press `Ctrl + V`

**OS and Theia version:**
latest next version
Windows 10
Chrome 75

**Diagnostics:** 
```
application-error.ts:61 Uncaught (in promise) Error: Request 'copy' failed
    at Proxy.<anonymous> (https://theia.miaowoo.cc/bundle.js:8:1048671)
    at t.copy (https://theia.miaowoo.cc/bundle.js:8:464654)
    at n.handlePaste (https://theia.miaowoo.cc/bundle.js:8:53438)
    at HTMLDivElement.<anonymous> (https://theia.miaowoo.cc/bundle.js:8:53027)
    at HTMLDocument.r (https://theia.miaowoo.cc/bundle.js:1:514380)
Caused by: Error: 'file:///home/project/TXTWorkSpace/kind/config.yml%0Afile%3A///home/project/TXTWorkSpace/kind/kind.sh' has not been found.
    at FileSystemNode.<anonymous> (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:409:64)
    at step (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:59:23)
    at Object.next (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:40:53)
    at fulfilled (/home/theia/node_modules/@theia/filesystem/lib/node/node-filesystem.js:31:58)
```

**Comment by akosyakov** [comment]
A dup of https://github.com/theia-ide/theia/issues/4872
