### ISSUE TITLE
Plugin API: Theia IDE doesn't support 'telemetry` property of  'workspace/configuration'

### ISSUE THREAD

**Issue by vrubezhny** [theia-ide/theia#5944]
### Description
PHP Intelephense extension fails to start due to lack of support of workspace configuration by Theia which is required in following call examples (https://github.com/bmewburn/vscode-intelephense/blob/master/src/middleware.ts#L278):
```
        v.telemetry.enabled = workspace.getConfiguration('telemetry').get('enableTelemetry');
```

### Reproduction Steps
Download PHP Intelephense extension v.1.1.5 (https://github.com/bmewburn/vscode-intelephense/releases) and save it to Theia 'plugins' folder, start Theia IDE browser example and try to edit/hover over/get content assist on a PHP file.
See errors listed above in the Output View.

**OS and Theia version:**
The issue is reproducible on Theia 'master' and 'che-7.0.0' branches

**Diagnostics:** 
Errors from the Output view:
```
[Trace - 1:28:37 PM] Received request 'workspace/configuration - (1)'.
Params: {
    "items": [
        {
            "section": "intelephense"
        },
        {
            "section": "intelephense",
            "scopeUri": "file:///home/jeremy/projects/che/phptest"
        }
    ]
}
[Trace - 1:28:37 PM] Sending response 'workspace/configuration - (1)'. Processing request took 16ms
Result: [
    null,
    null
]
(node:32300) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'telemetry' of null
    at Object.t.getDeepObjectValue (/tmp/vscode-unpacked/bmewburn.vscode-intelephense-client-1.1.5.vsix/extension/node_modules/intelephense/lib/intelephense.js:40:53770)
    at G (/tmp/vscode-unpacked/bmewburn.vscode-intelephense-client-1.1.5.vsix/extension/node_modules/intelephense/lib/intelephense.js:53:23488)
    at D (/tmp/vscode-unpacked/bmewburn.vscode-intelephense-client-1.1.5.vsix/extension/node_modules/intelephense/lib/intelephense.js:53:21568)
    at Object.<anonymous> (/tmp/vscode-unpacked/bmewburn.vscode-intelephense-client-1.1.5.vsix/extension/node_modules/intelephense/lib/intelephense.js:53:26668)
    at Generator.next (<anonymous>)
    at o (/tmp/vscode-unpacked/bmewburn.vscode-intelephense-client-1.1.5.vsix/extension/node_modules/intelephense/lib/intelephense.js:53:20564)
(node:32300) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)

```

**Comment by akosyakov** [comment]
@vrubezhny Is not it a dup of https://github.com/theia-ide/theia/issues/5945? an error is identical, please close if so

**Comment by tsmaeder** [comment]
yes, this is a duplicate: closing
