### ISSUE TITLE
vscode java dependency plugin error when expand class node

### ISSUE THREAD

**Issue by yeweiasia** [theia-ide/theia#5967]
### Description
 
vscode java dependency plugin throw errors when expand class node in 
javaDependencyExplorer

### Reproduction Steps

![javadependencyerror](https://user-images.githubusercontent.com/16164849/63205203-f6a2af00-c0d3-11e9-9b6c-101ce63268f7.gif)

**OS and Theia version:**
ubuntu 18.04
theia 0.9.0

**Diagnostics:** 

backend log:
```
root ERROR Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/home/yewei/Workspace/theia/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/yewei/Workspace/theia/node_modules/express/lib/response.js:170:12)
    at /home/yewei/Workspace/theia/packages/plugin-ext/lib/hosted/node/plugin-reader.js:112:37
    at /home/yewei/Workspace/theia/node_modules/express/lib/response.js:430:22
    at SendStream.onend (/home/yewei/Workspace/theia/node_modules/express/lib/response.js:1047:5)
    at SendStream.emit (events.js:189:13)
    at ReadStream.onend (/home/yewei/Workspace/theia/node_modules/send/index.js:822:10)
    at ReadStream.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
root ERROR Uncaught Exception:  Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
root ERROR Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/home/yewei/Workspace/theia/node_modules/express/lib/response.js:767:10)
    at ServerResponse.send (/home/yewei/Workspace/theia/node_modules/express/lib/response.js:170:12)
    at /home/yewei/Workspace/theia/packages/plugin-ext/lib/hosted/node/plugin-reader.js:112:37
    at /home/yewei/Workspace/theia/node_modules/express/lib/response.js:430:22
    at SendStream.onend (/home/yewei/Workspace/theia/node_modules/express/lib/response.js:1047:5)
    at SendStream.emit (events.js:189:13)
    at ReadStream.onend (/home/yewei/Workspace/theia/node_modules/send/index.js:822:10)
    at ReadStream.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
root ERROR Failed to fetch children for 'javaDependencyExplorer' Error: The command 'vscode.executeDocumentSymbolProvider' cannot be executed. There are no active handlers available for the command. (args: [{"$mid":1,"path":"/home/yewei/Workspace/demo/src/main/java/com/example/demo/Apple.java","scheme":"file"}])
    at CommandRegistry. (http://192.168.31.211:3000/bundle.js:109511:31)
    at step (http://192.168.31.211:3000/bundle.js:109287:23)
    at Object.next (http://192.168.31.211:3000/bundle.js:109268:53)
    at fulfilled (http://192.168.31.211:3000/bundle.js:109259:58)
root ERROR Failed to fetch children for 'javaDependencyExplorer' Error: The command 'vscode.executeDocumentSymbolProvider' cannot be executed. There are no active handlers available for the command. (args: [{"$mid":1,"path":"/home/yewei/Workspace/demo/src/main/java/com/example/demo/Apple.java","scheme":"file"}])
    at CommandRegistry. (http://192.168.31.211:3000/bundle.js:109511:31)
    at step (http://192.168.31.211:3000/bundle.js:109287:23)
    at Object.next (http://192.168.31.211:3000/bundle.js:109268:53)
    at fulfilled (http://192.168.31.211:3000/bundle.js:109259:58)
```
web browser console log:
<img width="1071" alt="Capture" src="https://user-images.githubusercontent.com/16164849/63205308-15ee0c00-c0d5-11e9-90d8-08ea5eb859c5.PNG">

**Comment by akosyakov** [comment]
It's caused by https://github.com/theia-ide/theia/issues/4048

**Comment by akosyakov** [comment]
@yeweiasia Could you check again please? The missing command was implemented already.

**Comment by yeweiasia** [comment]
> @yeweiasia Could you check again please? The missing command was implemented already.
the errors seems to be fixed ,but the function of jumping to the position works a bit weird.
![dependency_jump](https://user-images.githubusercontent.com/16164849/70763022-a390ee00-1d8d-11ea-953c-30b178eb38f8.gif)
