### ISSUE TITLE
Error when try to start Theia with eclipse-cdt plugin

### ISSUE THREAD

**Issue by tolusha** [theia-ide/theia#5993]
### Description
Error when try to start Theia with eclipse-cdt plugin

### Reference issue
https://github.com/eclipse/che/issues/14290

### Reproduction Steps
1. Put extension [1] in the `plugin` folder.
2. Start Theia
3. Observe the error below

**OS and Theia version:**
Linux, Theia latest 

**Diagnostics:** 
Stack tracke
```
root ERROR Uncaught Exception:  TypeError: Cannot read property 'versions' of undefined
root ERROR TypeError: Cannot read property 'versions' of undefined
    at Request._callback (/home/tolusha/projects/theia-ide/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-resolver.js:129:55)
    at Request.self.callback (/home/tolusha/projects/theia-ide/theia/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/home/tolusha/projects/theia-ide/theia/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/home/tolusha/projects/theia-ide/theia/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
root ERROR Uncaught Exception:  Error: No extension
root ERROR Error: No extension
    at Request._callback (/home/tolusha/projects/theia-ide/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-resolver.js:120:44)
    at Request.self.callback (/home/tolusha/projects/theia-ide/theia/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/home/tolusha/projects/theia-ide/theia/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/home/tolusha/projects/theia-ide/theia/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

[1] https://github.com/che-incubator/che-cpptools/releases/download/v1.0/cdt-vscode-0.0.7.vsix

**Comment by tsmaeder** [comment]
@tolusha "latest" meaing the latest release version or master? Also, does the CDT plugin work with the 7.0.0 branch?

**Comment by tolusha** [comment]
"latest" means master.
And they worked fine with 7.0.0 branch

**Comment by vinokurig** [comment]
Now the Error is:
```
root ERROR Failed to resolve plugins from 'vscode:extension/eclipse-cdt.cdt-gdb-vscode' Error: No extension
    at Request._callback (/home/ivinokur/projects/theia/packages/plugin-ext-vscode/lib/node/plugin-vscode-resolver.js:121:44)
    at Request.init.self.callback (/home/ivinokur/projects/theia/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.<anonymous> (/home/ivinokur/projects/theia/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:198:13)
    at IncomingMessage.<anonymous> (/home/ivinokur/projects/theia/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:286:20)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```
Witch is expected because there is no `eclipse-cdt.cdt-gdb-vscode` extension in the vscode marketplace.
If all necessary plugins are installed manually the extension should be successfully installed as well @tolusha Could you please check it  with the latest changes?

**Comment by tolusha** [comment]
I can't reproduce this issue anymore
