### ISSUE TITLE
[vscode][plugin] Hosted Plugin can't load plugin

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#6003]
### Description

today I test a plugin
but plugin-dev can't load it
before last month it's ok

### Reproduction Steps

**OS and Theia version:**

**Diagnostics:** 
https://github.com/theia-ide/theia/blob/f46ebf4e0b01c3fe58212ca8927537aff0ddb3a0/packages/plugin-dev/src/browser/hosted-plugin-controller.ts#L105-L107

```
ERROR Need to load plugin miaowoo.@dayu/vscode

e.log	@	logger-protocol.ts:112
(anonymous)	@	logger-frontend-module.ts:41
(anonymous)	@	logger.ts:312
(anonymous)	@	logger.ts:304
Promise.then (async)		
e.log	@	logger.ts:299
n	@	logger.ts:45
r	@	backend.js:6
(anonymous)	@	hosted-plugin-controller.ts:106
Promise.then (async)		
e.initialize	@	hosted-plugin-controller.ts:75
(anonymous)	@	frontend-application.ts:268
(anonymous)	@	bundle.js:1
(anonymous)	@	bundle.js:1
(anonymous)	@	bundle.js:1
a	@	bundle.js:1
e.startContributions	@	bundle.js:1
(anonymous)	@	frontend-application.ts:123
(anonymous)	@	bundle.js:1
(anonymous)	@	bundle.js:1
(anonymous)	@	bundle.js:1
a	@	bundle.js:1
e.start	@	bundle.js:1
(anonymous)	@	index.js:32
Promise.then (async)		
(anonymous)	@	index.js:75
n	@	bootstrap:19
(anonymous)	@	bootstrap:83
(anonymous)	@	bundle.js:1
```

**Comment by akosyakov** [comment]
@502647092 Could you mention which plugin and maybe you have not obfuscated stack traces?

**Comment by 502647092** [comment]
```
root ERROR [hosted-plugin: 345] Promise rejection not handled in one second: Error: Unknown actor CommandRegistryMain
root ERROR [hosted-plugin: 345] With stack trace: Error: Unknown actor CommandRegistryMain
    at RPCProtocolImpl.doInvokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:200:19)
    at RPCProtocolImpl.invokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:192:41)
    at RPCProtocolImpl.receiveRequest (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:154:45)
    at RPCProtocolImpl.receiveOneMessage (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:123:22)
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:55:89
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:233:17
    at /home/theia/node_modules/@theia/core/lib/common/event.js:162:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:177:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:265:29)
    at ChildProcess.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:145:21)
Promise rejection not handled in one second: Error: Unknown actor CommandRegistryMain
With stack trace: Error: Unknown actor CommandRegistryMain
    at RPCProtocolImpl.doInvokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:200:19)
    at RPCProtocolImpl.invokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:192:41)
    at RPCProtocolImpl.receiveRequest (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:154:45)
    at RPCProtocolImpl.receiveOneMessage (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:123:22)
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:55:89
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:233:17
    at /home/theia/node_modules/@theia/core/lib/common/event.js:162:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:177:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:265:29)
    at ChildProcess.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:145:21)
Promise rejection not handled in one second: Error: Unknown actor StatusBarMessageRegistryMain
With stack trace: Error: Unknown actor StatusBarMessageRegistryMain
    at RPCProtocolImpl.doInvokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:200:19)
    at RPCProtocolImpl.invokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:192:41)
    at RPCProtocolImpl.receiveRequest (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:154:45)
    at RPCProtocolImpl.receiveOneMessage (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:123:22)
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:55:89
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:233:17
    at /home/theia/node_modules/@theia/core/lib/common/event.js:162:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:177:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:265:29)
    at ChildProcess.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:145:21)
root ERROR [hosted-plugin: 345] Promise rejection not handled in one second: Error: Unknown actor StatusBarMessageRegistryMain
With stack trace: Error: Unknown actor StatusBarMessageRegistryMain
    at RPCProtocolImpl.doInvokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:200:19)
    at RPCProtocolImpl.invokeHandler (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:192:41)
    at RPCProtocolImpl.receiveRequest (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:154:45)
    at RPCProtocolImpl.receiveOneMessage (/home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:123:22)
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:55:89
    at /home/theia/node_modules/@theia/plugin-ext/lib/common/rpc-protocol.js:233:17
    at /home/theia/node_modules/@theia/core/lib/common/event.js:162:33
    at CallbackList.invoke (/home/theia/node_modules/@theia/core/lib/common/event.js:177:39)
    at Emitter.fire (/home/theia/node_modules/@theia/core/lib/common/event.js:265:29)
    at ChildProcess.<anonymous> (/home/theia/node_modules/@theia/plugin-ext/lib/hosted/node/hosted-plugin-process.js:145:21)
```

**Comment by 502647092** [comment]
I create a test plugin
follow https://www.theia-ide.org/doc/authoring_plugins
`src/theia-hello-world-plugin-backend-plugin.ts`
```
import * as theia from '@theia/plugin';

export function start() {
    const informationMessageTestCommand = {
        id: 'hello-world-example-generated',
        label: "Hello World"
    };
    theia.commands.registerCommand(informationMessageTestCommand, (...args: any[]) => {
        theia.window.showInformationMessage('Hello World!');
    });

}

export function stop() {

}
```
package.json
```
{
    "name": "theia-hello-world-plugin",
    "publisher": "theia",
    "keywords": [
        "theia-plugin"
    ],
    "version": "0.0.1",
    "files": [
        "src"
    ],
    "devDependencies": {
        "@theia/plugin": "latest",
        "rimraf": "^2.6.2",
        "typescript": "^2.9.2"
    },
    "scripts": {
        "prepare": "yarn run clean && yarn run build",
        "clean": "rimraf lib",
        "build": "tsc"
    },
    "engines": {
        "theiaPlugin": "latest"
    },
    "theiaPlugin": {
        "backend": "dist/theia-hello-world-plugin-backend-plugin.js"
    }
}
```
tsconfig.json
```
{
    "compilerOptions": {
        "baseUrl": "src",
        "outDir": "dist",
        "target": "es6",
        "module": "commonjs",
        "sourceMap": true,
        "declaration": true,
        "noImplicitAny": true,
        "allowUnreachableCode": true,
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true
    }
}
```
start instance
```
root WARN The directory referenced by local-dir:../../plugins does not exist.
root INFO Theia app listening on http://localhost:3030.
root INFO Deploying backend plugin "theia-hello-world-plugin@0.0.1" from "/workspace/theia/examples/dist/theia-hello-world-plugin-backend-plugin.js"
Plugin in file:///workspace/theia/examples doesn't have watch script
root INFO Using Git [2.19.1] from the PATH. (/usr/bin/git)
root INFO Detected keyboard layout from browser API: US (PC)
root WARN Collided keybinding is ignored;  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}  collided with  {"command":"terminal:clear","keybinding":"ctrlcmd+k","context":"terminalActive"}
root WARN Could not register keybinding:
  {"command":"passthrough","keybinding":"ctrl+k","context":"terminalActive"}
Error: "ctrl+k" is in collision with something else [scope:0]
root WARN LanguagesFrontendContribution.onStart is slow, took: 243.24999999953434 ms
root INFO [hosted-plugin: 3968] PLUGIN_HOST(3968) starting instance
root INFO [nsfw-watcher: 3947] Started watching: /home/gitpod/.theia
root ERROR Need to load plugin theia.theia-hello-world-plugin
root WARN EditorNavigationContribution.onStart is slow, took: 2338.824999984354 ms
root INFO [nsfw-watcher: 3947] Started watching: /workspace/theia
root INFO Checking whether '--no-optional-locks' can be used with the current Git executable. Minimum required version is '2.15.0'.
root INFO '--no-optional-locks' is a valid Git option for the current Git version: '2.19.1'.
root INFO [nsfw-watcher: 3947] Started watching: /workspace/theia
root INFO Config file tasks.json does not exist under file:///workspace/theia
root INFO [nsfw-watcher: 3947] Started watching: /workspace/theia/.theia/settings.json
root INFO [nsfw-watcher: 3947] Started watching: /workspace/theia/.vscode/launch.json
root INFO Started watching the git repository: file:///workspace/theia
root INFO [nsfw-watcher: 3947] Started watching: /workspace/theia/.vscode/settings.json
root INFO [hosted-plugin: 3968] PLUGIN_HOST(3968): PluginManagerExtImpl/init()
root INFO [hosted-plugin: 3968] PLUGIN_HOST(3968): initializing(theia-hello-world-plugin@0.0.1 with /workspace/theia/packages/plugin-ext/lib/hosted/node/scanners/backend-init-theia.js)
```

**Comment by 502647092** [comment]
![image](https://user-images.githubusercontent.com/10203793/63734819-578a6e00-c8b0-11e9-8601-928cb0f6deb7.png)
when I start Development Host
WebSocket will recover many packet id is 21 and every packet have 1~2M
@akosyakov Do you know what problem

**Comment by akosyakov** [comment]
@502647092 I'm not using hosted plugin sorry, i hope someone from @theia-ide/plugin-system can help

**Comment by 502647092** [comment]
maybe before theia not support activationEvents
and i not config this
after add this config ext is correct
