### ISSUE TITLE
webpack errors do not fail the build

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#644]
For example (from my dev branch):

```
@theia/example-browser: ERROR in ./src-gen/frontend/index.js
@theia/example-browser: Module not found: Error: Can't resolve '@theia/debug/lib/browser/debug-frontend-module' in '/home/eantotr/sync/work/theia/examples/browser/src-gen/frontend'
@theia/example-browser:  @ ./src-gen/frontend/index.js 43:47-104
@theia/example-browser: Uncaught Exception:  Error: webpack failed with the exit code 2
@theia/example-browser: Error: webpack failed with the exit code 2\n    at ChildProcess.<anonymous> (/home/eantotr/sync/work/theia/dev-packages/application-package/lib/application-process.js:59:28)\n    at emitTwo (events.js:125:13)\n    at ChildProcess.emit (events.js:213:7)\n    at maybeClose (internal/child_process.js:927:16)\n    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
lerna success run Ran npm script 'prepare' in packages:
lerna success - @theia/application-package
lerna success - @theia/cli
lerna success - @theia/ext-scripts
lerna success - @theia/core
lerna success - @theia/cpp
lerna success - @theia/debug
lerna success - @theia/editor
lerna success - @theia/extension-manager
lerna success - @theia/filesystem
lerna success - @theia/gdb
lerna success - @theia/git
lerna success - @theia/go
lerna success - @theia/java
lerna success - @theia/languages
lerna success - @theia/markers
lerna success - @theia/monaco
lerna success - @theia/navigator
lerna success - @theia/preferences-api
lerna success - @theia/preferences
lerna success - @theia/process
lerna success - @theia/python
lerna success - @theia/terminal
lerna success - @theia/typescript
lerna success - @theia/workspace
lerna success - @theia/example-browser
lerna success - @theia/example-electron
Done in 149.63s.
Done in 151.67s.
```

**Comment by epatpol** [comment]
Yes that bothered me a lot when testing the other day, maybe we should add the [bail](https://webpack.github.io/docs/configuration.html#bail) option to webpack? Let me test it locally.

**Comment by hexa00** [comment]
It is reported as a hard error already... we just don't act on it upstream.
