### ISSUE TITLE
[git] Loop when selecting the Git Fetch form a non-git folder

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#681]
Scenario: I have a workspace in THEIA, but there is no ".git" folder 
I selected the git-> git Fetch command
The following error shows on the console and is looping foreever

[2017-10-19T13:44:49.252Z] ERROR: Theia/11862 on elxa8z6zp12:
    TypeError: Cannot read property 'localUri' of null
        at DugiteGit.getFsPath (/home/lmcbout/theia/theia/packages/git/lib/node/dugite-git.js:509:75)
        at DugiteGit.<anonymous> (/home/lmcbout/theia/theia/packages/git/lib/node/dugite-git.js:136:47)
        at step (/home/lmcbout/theia/theia/packages/git/lib/node/dugite-git.js:52:23)
        at Object.next (/home/lmcbout/theia/theia/packages/git/lib/node/dugite-git.js:33:53)
        at /home/lmcbout/theia/theia/packages/git/lib/node/dugite-git.js:27:71
        at Promise (<anonymous>)
        at __awaiter (/home/lmcbout/theia/theia/packages/git/lib/node/dugite-git.js:23:12)
        at DugiteGit.status (/home/lmcbout/theia/theia/packages/git/lib/node/dugite-git.js:131:16)
        at DugiteGitWatcherServer.<anonymous> (/home/lmcbout/theia/theia/packages/git/lib/node/dugite-git-watcher.js:101:67)
        at step (/home/lmcbout/theia/theia/packages/git/lib/node/dugite-git-watcher.js:50:23) []

**Comment by lmcbout** [comment]
Missing the first few lines of the debug trace:
[2017-10-19T13:44:49.252Z] ERROR: Theia/11862 on elxa8z6zp12: Uncaught Exception:  [ 'TypeError: Cannot read property \'localUri\' of null' ]

**Comment by lmcbout** [comment]
If I restart the browser (yarn start), close and re-create a new web browser  on (localhost:3000), open a new workspace with no git folder, the server start logging the same error on the console. In fact, since I restarted a new application, the debug traces should not be there anymore ???

**Comment by kittaakos** [comment]
Could be the same as https://github.com/theia-ide/theia/issues/638#issuecomment-336957591.
We need to verify this again after integrating the changes from #650 to the master.

**Comment by kittaakos** [comment]
> I selected the git-> git Fetch command

This problem should not happen anymore: the Git command handlers are disabled when no repositories have been selected by the user.

> the server start logging the same error on the console.

Backend disposes any stale listeners on non-existing repositories.

**Comment by svenefftinge** [comment]
@kittaakos is there still something to do here?

**Comment by kittaakos** [comment]
Fixed with https://github.com/theia-ide/theia/pull/650. I am closing this.
