### ISSUE TITLE
[terminal] Error when building electron application from published packages

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#737]
`package.json`:
```
{
  "name": "theia-electron-app-example",
  "version": "1.0.0",
  "description": "An electron-based packaged Theia application example",
  "main": "src-gen/frontend/electron-main.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/theia-ide/theia-electron-app-example.git"
  },
  "theia": {
    "target": "electron"
  },
  "scripts": {
    "generate": "theia generate",
    "compile": "webpack && shx cp ./src-gen/frontend/index.html ./lib",
    "electron-rebuild": "electron-rebuild",
    "package": "build -m --x64 --dir",
    "start": "open ./dist/mac/theia-electron-app-example.app",
    "postinstall": "npm run generate && npm run electron-rebuild && npm run compile && npm run package"
  },
  "keywords": [],
  "author": "typefox <npm@typefox.io>",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/theia-ide/theia-electron-app-example/issues"
  },
  "homepage": "https://github.com/theia-ide/theia-electron-app-example#readme",
  "dependencies": {
    "@theia/cli": "0.2.0",
    "@theia/core": "0.2.0",
    "@theia/editor": "0.2.0",
    "@theia/filesystem": "0.2.0",
    "@theia/monaco": "0.2.0",
    "@theia/navigator": "0.2.0",
    "@theia/preferences": "0.2.0",
    "@theia/preferences-api": "0.2.0",
    "@theia/process": "0.2.0",
    "@theia/terminal": "0.2.0",
    "@theia/workspace": "0.2.0"
  },
  "devDependencies": {
    "electron-builder": "^19.30.2",
    "shx": "^0.2.0"
  }
}

```

Error:
```
npm WARN prefer global node-gyp@3.6.2 should be installed with -g

> rabin-bindings@1.7.3 install /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/rabin-bindings
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds/rabin-bindings-v1.7.3-node-v57-darwin-x64.tar.gz
prebuild-install info found local prebuild
prebuild-install info unpacking @ prebuilds/rabin-bindings-v1.7.3-node-v57-darwin-x64.tar.gz
prebuild-install info unpack resolved to /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/rabin-bindings/build/Release/rabin-bindings.node
prebuild-install info unpack required /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/rabin-bindings/build/Release/rabin-bindings.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> node-pty@0.7.1 install /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/node-pty
> node scripts/install.js

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  CXX(target) Release/obj.target/pty/src/unix/pty.o
  SOLINK_MODULE(target) Release/pty.node

> fsevents@1.1.2 install /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/fsevents
> node install

[fsevents] Success: "/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/fsevents/lib/binding/Release/node-v57-darwin-x64/fse.node" already installed
Pass --update-binary to reinstall or --build-from-source to recompile

> dtrace-provider@0.8.5 install /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/dtrace-provider
> node scripts/install.js


> node-pty@0.7.1 postinstall /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/node-pty
> node scripts/post-install.js


> electron@1.7.6 postinstall /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron
> node install.js


> theia-electron-app-example@1.0.0 postinstall /Users/akos.kitta/Desktop/electron/theia-electron-app-example
> npm run generate && npm run electron-rebuild && npm run compile && npm run package


> theia-electron-app-example@1.0.0 generate /Users/akos.kitta/Desktop/electron/theia-electron-app-example
> theia generate

Uncaught Exception:  Error: Cannot find module 'xterm/package.json'
Error: Cannot find module 'xterm/package.json'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.resolve (internal/module.js:18:19)
    at ExtensionPackageCollector.module.exports.modulePath [as resolveModule] (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/.application-module-loader.js:1:102)
    at ExtensionPackageCollector.collectPackage (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/@theia/application-package/lib/extension-package-collector.js:44:32)
    at ExtensionPackageCollector.collectPackages (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/@theia/application-package/lib/extension-package-collector.js:30:18)
    at ExtensionPackageCollector.collectPackagesWithParent (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/@theia/application-package/lib/extension-package-collector.js:36:14)
    at ExtensionPackageCollector.collectPackage (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/@theia/application-package/lib/extension-package-collector.js:53:18)
    at ExtensionPackageCollector.collectPackages (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/@theia/application-package/lib/extension-package-collector.js:30:18)
    at ExtensionPackageCollector.collect (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/@theia/application-package/lib/extension-package-collector.js:20:14)
    at ApplicationPackage.get [as extensionPackages] (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/@theia/application-package/lib/application-package.js:167:53)

> theia-electron-app-example@1.0.0 electron-rebuild /Users/akos.kitta/Desktop/electron/theia-electron-app-example
> electron-rebuild

✔ Rebuild Complete

> theia-electron-app-example@1.0.0 compile /Users/akos.kitta/Desktop/electron/theia-electron-app-example
> webpack && shx cp ./src-gen/frontend/index.html ./lib

Hash: 8a884485bcc2e9989c6f
Version: webpack 2.7.0
Time: 3372ms
                                                         Asset     Size  Chunks                    Chunk Names
                              vs/basic-languages/src/fsharp.js  3.15 kB          [emitted]
                        e19892df121e7f85c61754c54bbb7951.woff2  49.8 kB          [emitted]
                        af7ae505a9eed503f8b8e6982036873e.woff2  77.2 kB          [emitted]
                        0a32a80243e05284a5d741c5dc093f31.woff2  24.4 kB          [emitted]
                        de59a97248b44599e6747a27a943f738.woff2  20.2 kB          [emitted]
                         fee66e712a8a08eef5805a46892932ad.woff    98 kB          [emitted]
                          674f50d287a8c48dc19ba404d20fe713.eot   166 kB          [emitted]
                          912ec66d7572ff821749319396470bde.svg   444 kB          [emitted]  [big]
                          b06871f281fee6b241d60582ae9369b9.ttf   166 kB          [emitted]
                          cf2aabacdc2b3a5768b03545cb1d8330.svg  21.5 kB          [emitted]
                                                   0.bundle.js   203 kB       0  [emitted]
                                                     bundle.js  2.38 MB       1  [emitted]  [big]  main
                                               0.bundle.js.map   281 kB       0  [emitted]
                                                 bundle.js.map  2.93 MB       1  [emitted]         main
                                  vs/base/worker/workerMain.js   152 kB          [emitted]
vs/editor/contrib/suggest/browser/media/String_inverse_16x.svg  4.74 kB          [emitted]
        vs/editor/contrib/suggest/browser/media/String_16x.svg  4.74 kB          [emitted]
                               vs/editor/editor.main.nls.de.js  28.1 kB          [emitted]
                               vs/editor/editor.main.nls.es.js    29 kB          [emitted]
                               vs/editor/editor.main.nls.hu.js  31.1 kB          [emitted]
                               vs/editor/editor.main.nls.fr.js  31.2 kB          [emitted]
                                     vs/editor/editor.main.css   172 kB          [emitted]
                               vs/editor/editor.main.nls.it.js    30 kB          [emitted]
                                  vs/editor/editor.main.nls.js  24.3 kB          [emitted]
                               vs/editor/editor.main.nls.ja.js  31.8 kB          [emitted]
                               vs/editor/editor.main.nls.ko.js  28.6 kB          [emitted]
                            vs/editor/editor.main.nls.pt-br.js  27.8 kB          [emitted]
                               vs/editor/editor.main.nls.ru.js    44 kB          [emitted]
                               vs/editor/editor.main.nls.tr.js    28 kB          [emitted]
                            vs/editor/editor.main.nls.zh-cn.js  22.6 kB          [emitted]
      vs/editor/standalone/browser/quickOpen/symbol-sprite.svg  20.7 kB          [emitted]
                            vs/editor/editor.main.nls.zh-tw.js  23.1 kB          [emitted]
                                                  vs/loader.js  28.9 kB          [emitted]
                                      vs/editor/editor.main.js  1.81 MB          [emitted]  [big]
                                 vs/basic-languages/src/bat.js  2.11 kB          [emitted]
                              vs/basic-languages/src/coffee.js  3.88 kB          [emitted]
                                 vs/basic-languages/src/cpp.js  4.69 kB          [emitted]
                              vs/basic-languages/src/csharp.js  4.83 kB          [emitted]
                                 vs/basic-languages/src/css.js  4.73 kB          [emitted]
                          vs/basic-languages/src/dockerfile.js  2.37 kB          [emitted]
                        11d1a2390613abf202bfd2ebbd5c4500.woff2  90.7 kB          [emitted]
                          vs/basic-languages/src/handlebars.js  6.52 kB          [emitted]
                                  vs/basic-languages/src/go.js  3.04 kB          [emitted]
                                vs/basic-languages/src/html.js   4.8 kB          [emitted]
                                vs/basic-languages/src/java.js  3.19 kB          [emitted]
                                 vs/basic-languages/src/ini.js  1.48 kB          [emitted]
                                vs/basic-languages/src/less.js  4.14 kB          [emitted]
                                 vs/basic-languages/src/lua.js   2.5 kB          [emitted]
                            vs/basic-languages/src/markdown.js  3.58 kB          [emitted]
                 vs/basic-languages/src/monaco.contribution.js  4.97 kB          [emitted]
                               vs/basic-languages/src/msdax.js  5.29 kB          [emitted]
                         vs/basic-languages/src/objective-c.js  2.79 kB          [emitted]
                                 vs/basic-languages/src/php.js  8.31 kB          [emitted]
                            vs/basic-languages/src/postiats.js  8.24 kB          [emitted]
                          vs/basic-languages/src/powershell.js  3.56 kB          [emitted]
                                 vs/basic-languages/src/pug.js  5.19 kB          [emitted]
                              vs/basic-languages/src/python.js   3.3 kB          [emitted]
                                   vs/basic-languages/src/r.js  3.21 kB          [emitted]
                               vs/basic-languages/src/razor.js  8.84 kB          [emitted]
                                vs/basic-languages/src/ruby.js   8.5 kB          [emitted]
                                  vs/basic-languages/src/sb.js  2.21 kB          [emitted]
                                vs/basic-languages/src/scss.js  6.65 kB          [emitted]
                            vs/basic-languages/src/solidity.js    19 kB          [emitted]
                                 vs/basic-languages/src/sql.js  18.6 kB          [emitted]
                               vs/basic-languages/src/swift.js  4.51 kB          [emitted]
                                  vs/basic-languages/src/vb.js  5.98 kB          [emitted]
                                 vs/basic-languages/src/xml.js  2.12 kB          [emitted]
                                vs/basic-languages/src/yaml.js  3.87 kB          [emitted]
                                    vs/language/css/cssMode.js    21 kB          [emitted]
                        vs/language/css/monaco.contribution.js  2.31 kB          [emitted]
                                   vs/language/css/monaco.d.ts  1.98 kB          [emitted]
                                  vs/language/css/cssWorker.js   477 kB          [emitted]  [big]
                                  vs/language/json/jsonMode.js  36.5 kB          [emitted]
                       vs/language/json/monaco.contribution.js  1.82 kB          [emitted]
                                  vs/language/json/monaco.d.ts  1.71 kB          [emitted]
                                vs/language/json/jsonWorker.js    93 kB          [emitted]
                                  vs/language/html/htmlMode.js  19.3 kB          [emitted]
                                  vs/language/html/monaco.d.ts  1.83 kB          [emitted]
                       vs/language/html/monaco.contribution.js  2.35 kB          [emitted]
                                vs/language/html/htmlWorker.js   113 kB          [emitted]
   [0] ./~/inversify/lib/inversify.js 1.93 kB {1} [built]
   [2] ./~/@theia/core/lib/browser/index.js 969 bytes {1} [built]
  [93] ./~/@theia/workspace/lib/browser/workspace-frontend-module.js 2.96 kB {1} [built]
 [124] ./~/@theia/editor/lib/browser/editor-frontend-module.js 1.8 kB {1} [built]
 [172] ./~/@theia/core/lib/browser/frontend-application-module.js 4.91 kB {1} [built]
 [173] ./~/@theia/core/lib/browser/logger-frontend-module.js 1.95 kB {1} [built]
 [174] ./~/@theia/core/lib/browser/messaging/messaging-frontend-module.js 599 bytes {1} [built]
 [175] ./~/@theia/core/lib/electron-browser/menu/electron-menu-module.js 2.19 kB {1} [built]
 [176] ./~/@theia/filesystem/lib/browser/filesystem-frontend-module.js 1.77 kB {1} [built]
 [177] ./~/@theia/languages/lib/browser/languages-frontend-module.js 1.3 kB {1} [built]
 [178] ./~/@theia/markers/lib/browser/problem/problem-frontend-module.js 2.42 kB {1} [built]
 [179] ./~/@theia/monaco/lib/electron-browser/monaco-electron-module.js 1.15 kB {1} [built]
 [180] ./~/@theia/navigator/lib/browser/navigator-frontend-module.js 1.62 kB {1} [built]
 [181] ./~/@theia/outline-view/lib/browser/outline-view-frontend-module.js 1.59 kB {1} [built]
 [365] ./src-gen/frontend/index.js 2.47 kB {1} [built]
    + 415 hidden modules

ERROR in ./~/@theia/terminal/lib/browser/terminal-frontend-module.js
Module not found: Error: Can't resolve 'xterm/lib/xterm.css' in '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/@theia/terminal/lib/browser'
 @ ./~/@theia/terminal/lib/browser/terminal-frontend-module.js 38:0-30
 @ ./src-gen/frontend/index.js

ERROR in ./~/@theia/terminal/lib/browser/terminal-widget.js
Module not found: Error: Can't resolve 'xterm' in '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/@theia/terminal/lib/browser'
 @ ./~/@theia/terminal/lib/browser/terminal-widget.js 73:12-28
 @ ./~/@theia/terminal/lib/browser/terminal-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./~/@theia/terminal/lib/browser/terminal-widget.js
Module not found: Error: Can't resolve 'xterm/lib/addons/attach/attach' in '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/@theia/terminal/lib/browser'
 @ ./~/@theia/terminal/lib/browser/terminal-widget.js 75:0-41
 @ ./~/@theia/terminal/lib/browser/terminal-frontend-module.js
 @ ./src-gen/frontend/index.js

ERROR in ./~/@theia/terminal/lib/browser/terminal-widget.js
Module not found: Error: Can't resolve 'xterm/lib/addons/fit/fit' in '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/@theia/terminal/lib/browser'
 @ ./~/@theia/terminal/lib/browser/terminal-widget.js 74:0-35
 @ ./~/@theia/terminal/lib/browser/terminal-frontend-module.js
 @ ./src-gen/frontend/index.js
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! theia-electron-app-example@1.0.0 compile: `webpack && shx cp ./src-gen/frontend/index.html ./lib`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the theia-electron-app-example@1.0.0 compile script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akos.kitta/.npm/_logs/2017-10-25T08_16_54_124Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! theia-electron-app-example@1.0.0 postinstall: `npm run generate && npm run electron-rebuild && npm run compile && npm run package`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the theia-electron-app-example@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/akos.kitta/.npm/_logs/2017-10-25T08_16_54_187Z-debug.log
```

**Comment by kittaakos** [comment]
Building it from the source works as expected.

**Comment by kittaakos** [comment]
According to [npmjs.org](https://www.npmjs.com/package/@theia/terminal), `@theia/terminal` depends on `xterm` but it does not get pulled into the `node_modules`.

**Comment by kittaakos** [comment]
Blocks #346.

**Comment by akosyakov** [comment]
Could it be because of https://github.com/theia-ide/theia/commit/af29995c1dc3f95e6a45ecc88a864704dad8df0a#diff-41bfa10c8e35c718f31ed7856660cb95R11?

**Comment by kittaakos** [comment]
Yeah, it could be. But with the workaround, one can build the application. So I leave as is now. Thanks anyway!

**Comment by hexa00** [comment]
I tried the application yesterday and it seemed like it ran the v3 branch... since I had the problem with the empty space on the right.

So I guess the workaround was to declare the dependency not because of the v3 branch?

**Comment by kittaakos** [comment]
The reason why we have a xterm.js v3 fork: https://gitter.im/theia-ide/theia?at=5a293b4f87680e6230e16d8d

**Comment by hexa00** [comment]
Rested and this is fixed since xterm v3 was released.
