### ISSUE TITLE
Bundled electron application does not start

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#738]
The application is using published npm packages. It starts in debug mode from VSCode, also starting as an individual node process work. Fails when starting as an application.

I did some "debugging" and it turned out, that the connection is `undefined` when we are creating the proxy workers. Both the message reader and writer looks OK.

```
reader WorkerMessageReader {
  errorEmitter: 
   Emitter {
     _options: undefined,
     _event: [Function],
     _callbacks: CallbackList { _callbacks: [Object], _contexts: [Object] } },
  closeEmitter: 
   Emitter {
     _options: undefined,
     _event: [Function],
     _callbacks: CallbackList { _callbacks: [Object], _contexts: [Object] } },
  partialMessageEmitter: Emitter { _options: undefined },
  worker: 
   Worker {
     domain: null,
     _events: { message: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     exitedAfterDisconnect: undefined,
     suicide: [Getter/Setter],
     state: 'none',
     id: 1,
     process: 
      ChildProcess {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        _closesNeeded: 2,
        _closesGot: 0,
        connected: true,
        signalCode: null,
        exitCode: null,
        killed: false,
        spawnfile: '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/dist/mac/theia-electron-app-example.app/Contents/Frameworks/theia-electron-app-example Helper.app/Contents/MacOS/theia-electron-app-example Helper',
        _handle: [Object],
        spawnargs: [Object],
        pid: 13433,
        stdin: null,
        stdout: null,
        stderr: null,
        stdio: [Object],
        channel: [Object],
        _channel: [Getter/Setter],
        _handleQueue: null,
        _pendingHandle: null,
        send: [Function],
        _send: [Function],
        disconnect: [Function],
        _disconnect: [Function] } } }


writer WorkerMessageWriter {
  errorEmitter: 
   Emitter {
     _options: undefined,
     _event: [Function],
     _callbacks: CallbackList { _callbacks: [Object], _contexts: [Object] } },
  closeEmitter: 
   Emitter {
     _options: undefined,
     _event: [Function],
     _callbacks: CallbackList { _callbacks: [Object], _contexts: [Object] } },
  worker: 
   Worker {
     domain: null,
     _events: { message: [Function] },
     _eventsCount: 1,
     _maxListeners: undefined,
     exitedAfterDisconnect: undefined,
     suicide: [Getter/Setter],
     state: 'none',
     id: 1,
     process: 
      ChildProcess {
        domain: null,
        _events: [Object],
        _eventsCount: 5,
        _maxListeners: undefined,
        _closesNeeded: 2,
        _closesGot: 0,
        connected: true,
        signalCode: null,
        exitCode: null,
        killed: false,
        spawnfile: '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/dist/mac/theia-electron-app-example.app/Contents/Frameworks/theia-electron-app-example Helper.app/Contents/MacOS/theia-electron-app-example Helper',
        _handle: [Object],
        spawnargs: [Object],
        pid: 13433,
        stdin: null,
        stdout: null,
        stderr: null,
        stdio: [Object],
        channel: [Object],
        _channel: [Getter/Setter],
        _handleQueue: null,
        _pendingHandle: null,
        send: [Function],
        _send: [Function],
        disconnect: [Function],
        _disconnect: [Function] } } }


inspect
connection undefined
```

The resulting error is the following:
```
module.js:472
    throw err;
    ^

Error: Cannot find module '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/dist/mac/theia-electron-app-example.app/Contents/MacOS/undefined'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)
    at bootstrap_node.js:551:3

```

CC: @akosyakov

**Comment by kittaakos** [comment]
When I log the `connection` in the `vscode-jsonrpc/lib/main.js` module:
```
console.log('VSCode JSON-RPC => connection', connection, connection === undefined, connection === void 0, JSON.stringify(connection));
```

I get the following output:
```
VSCode JSON-RPC => connection undefined false false {}
```

**Comment by kittaakos** [comment]
This `undefined` connection seems to be correct, at least I have the same when logging it to the console from VSCode. The reader and the writer are slightly different:
```
WorkerMessageReader {
  errorEmitter: 
   Emitter {
     _options: undefined,
     _event: [Function],
     _callbacks: CallbackList { _callbacks: [Object], _contexts: [Object] } },
  closeEmitter: 
   Emitter {
     _options: undefined,
     _event: [Function],
     _callbacks: CallbackList { _callbacks: [Object], _contexts: [Object] } },
  partialMessageEmitter: Emitter { _options: undefined },
  worker: 
   Worker {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     exitedAfterDisconnect: undefined,
     suicide: [Getter/Setter],
     state: 'online',
     id: 1,
     process: 
      process {
        title: '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper',
        version: 'v7.9.0',
        moduleLoadList: [Object],
        versions: 
         { http_parser: '2.7.0',
           node: '7.9.0',
           v8: '5.8.283.38',
           uv: '1.11.0',
           zlib: '1.2.11',
           ares: '1.10.1-DEV',
           modules: '54',
           openssl: '1.0.2k' },
        arch: 'x64',
        platform: 'darwin',
        release: [Object],
        argv: [Object],
        execArgv: [Object],
        env: [Object],
        pid: 24096,
        features: [Object],
        _needImmediateCallback: false,
        execPath: '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper',
        debugPort: 31863,
        _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
        _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
        _getActiveRequests: [Function: _getActiveRequests],
        _getActiveHandles: [Function: _getActiveHandles],
        reallyExit: [Function: reallyExit],
        abort: [Function: abort],
        chdir: [Function],
        cwd: [Function],
        umask: [Function: umask],
        getuid: [Function: getuid],
        geteuid: [Function: geteuid],
        setuid: [Function: setuid],
        seteuid: [Function: seteuid],
        setgid: [Function: setgid],
        setegid: [Function: setegid],
        getgid: [Function: getgid],
        getegid: [Function: getegid],
        getgroups: [Function: getgroups],
        setgroups: [Function: setgroups],
        initgroups: [Function: initgroups],
        _kill: [Function: _kill],
        _debugProcess: [Function: _debugProcess],
        _debugPause: [Function: _debugPause],
        _debugEnd: [Function: _debugEnd],
        hrtime: [Function: hrtime],
        cpuUsage: [Function: cpuUsage],
        dlopen: [Function],
        uptime: [Function: uptime],
        memoryUsage: [Function: memoryUsage],
        binding: [Function: binding],
        _linkedBinding: [Function: _linkedBinding],
        _setupDomainUse: [Function: _setupDomainUse],
        _events: [Object],
        crash: [Function],
        crashReporter: [Object],
        _rawDebug: [Function],
        _eventsCount: 10,
        domain: null,
        _maxListeners: undefined,
        NativeModule: [Object],
        _fatalException: [Function],
        _exiting: false,
        assert: [Function],
        config: [Object],
        emitWarning: [Function],
        nextTick: [Function: nextTick],
        _tickCallback: [Function: _tickCallback],
        _tickDomainCallback: [Function: _tickDomainCallback],
        stdout: [Getter],
        stderr: [Getter],
        stdin: [Getter],
        openStdin: [Function],
        exit: [Function],
        kill: [Function],
        channel: [Object],
        _channel: [Getter/Setter],
        _handleQueue: null,
        _pendingHandle: null,
        send: [Function],
        _send: [Function],
        connected: true,
        disconnect: [Function],
        _disconnect: [Function],
        argv0: '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper',
        mainModule: [Object],
        __signal_exit_emitter__: [Object] } } }


WorkerMessageWriter {
  errorEmitter: 
   Emitter {
     _options: undefined,
     _event: [Function],
     _callbacks: CallbackList { _callbacks: [Object], _contexts: [Object] } },
  closeEmitter: 
   Emitter {
     _options: undefined,
     _event: [Function],
     _callbacks: CallbackList { _callbacks: [Object], _contexts: [Object] } },
  worker: 
   Worker {
     domain: null,
     _events: {},
     _eventsCount: 0,
     _maxListeners: undefined,
     exitedAfterDisconnect: undefined,
     suicide: [Getter/Setter],
     state: 'online',
     id: 1,
     process: 
      process {
        title: '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper',
        version: 'v7.9.0',
        moduleLoadList: [Object],
        versions: 
         { http_parser: '2.7.0',
           node: '7.9.0',
           v8: '5.8.283.38',
           uv: '1.11.0',
           zlib: '1.2.11',
           ares: '1.10.1-DEV',
           modules: '54',
           openssl: '1.0.2k' },
        arch: 'x64',
        platform: 'darwin',
        release: [Object],
        argv: [Object],
        execArgv: [Object],
        env: [Object],
        pid: 24096,
        features: [Object],
        _needImmediateCallback: false,
        execPath: '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper',
        debugPort: 31863,
        _startProfilerIdleNotifier: [Function: _startProfilerIdleNotifier],
        _stopProfilerIdleNotifier: [Function: _stopProfilerIdleNotifier],
        _getActiveRequests: [Function: _getActiveRequests],
        _getActiveHandles: [Function: _getActiveHandles],
        reallyExit: [Function: reallyExit],
        abort: [Function: abort],
        chdir: [Function],
        cwd: [Function],
        umask: [Function: umask],
        getuid: [Function: getuid],
        geteuid: [Function: geteuid],
        setuid: [Function: setuid],
        seteuid: [Function: seteuid],
        setgid: [Function: setgid],
        setegid: [Function: setegid],
        getgid: [Function: getgid],
        getegid: [Function: getegid],
        getgroups: [Function: getgroups],
        setgroups: [Function: setgroups],
        initgroups: [Function: initgroups],
        _kill: [Function: _kill],
        _debugProcess: [Function: _debugProcess],
        _debugPause: [Function: _debugPause],
        _debugEnd: [Function: _debugEnd],
        hrtime: [Function: hrtime],
        cpuUsage: [Function: cpuUsage],
        dlopen: [Function],
        uptime: [Function: uptime],
        memoryUsage: [Function: memoryUsage],
        binding: [Function: binding],
        _linkedBinding: [Function: _linkedBinding],
        _setupDomainUse: [Function: _setupDomainUse],
        _events: [Object],
        crash: [Function],
        crashReporter: [Object],
        _rawDebug: [Function],
        _eventsCount: 10,
        domain: null,
        _maxListeners: undefined,
        NativeModule: [Object],
        _fatalException: [Function],
        _exiting: false,
        assert: [Function],
        config: [Object],
        emitWarning: [Function],
        nextTick: [Function: nextTick],
        _tickCallback: [Function: _tickCallback],
        _tickDomainCallback: [Function: _tickDomainCallback],
        stdout: [Getter],
        stderr: [Getter],
        stdin: [Getter],
        openStdin: [Function],
        exit: [Function],
        kill: [Function],
        channel: [Object],
        _channel: [Getter/Setter],
        _handleQueue: null,
        _pendingHandle: null,
        send: [Function],
        _send: [Function],
        connected: true,
        disconnect: [Function],
        _disconnect: [Function],
        argv0: '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper',
        mainModule: [Object],
        __signal_exit_emitter__: [Object] } } }


inspect
undefined
```

**Comment by kittaakos** [comment]
https://github.com/electron/electron/issues/6337

**Comment by kittaakos** [comment]
`electron-main.js`:
```js
// @ts-check
const cluster = require('cluster');
if (cluster.isMaster) {
    // Workaround for https://github.com/electron/electron/issues/9225. Chrome has an issue where
    // in certain locales (e.g. PL), image metrics are wrongly computed. We explicitly set the
    // LC_NUMERIC to prevent this from happening (selects the numeric formatting category of the
    // C locale, http://en.cppreference.com/w/cpp/locale/LC_categories).
    if (process.env.LC_ALL) {
        process.env.LC_ALL = 'C';
    }
    process.env.LC_NUMERIC = 'C';
    const electron = require('electron');
    const path = require('path');
    electron.app.on('window-all-closed', function () {
        if (process.platform !== 'darwin') {
            electron.app.quit();
        }
    });
    electron.app.on('ready', function () {
        const mainWindow = new electron.BrowserWindow({ width: 1024, height: 728 });
        mainWindow.webContents.toggleDevTools();
        const { fork }  = require('child_process');
        // TODO calculate the location of the backend's main.
        const cp = fork("../../Contents/Resources/app/src-gen/backend/main.js", process.argv, {
            stdio: [0, 'pipe', 'pipe', 'ipc']
        });
        cp.once('message', function (message) {
            mainWindow.loadURL(`file://${path.join(__dirname, '../../lib/index.html')}?port=${message.port}`);
        });
        cp.on('error', function (error) {
            console.error(error);
            electron.app.exit(1);
        });
        mainWindow.on('closed', function () {
            electron.app.exit(0);
        });
    });
} else {
    require("../backend/main");
}
```

`main.js`:
```js
// @ts-check
const serverPath = require('path').resolve(__dirname, 'server');
module.exports = require('@theia/core/lib/node/cluster/main').default(serverPath).then(function (address) {
    process.send({ port: address.port });
});
```

**Comment by kittaakos** [comment]
PR: https://github.com/theia-ide/theia/pull/746
