### ISSUE TITLE
[git][electron] Cannot bundle git executable into the application

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#753]
```
Unhandled rejection Error: ENOENT: no such file or directory, symlink 'git' -> '/Users/akos.kitta/Desktop/electron/theia-electron-app-example/dist/mac/Electron.app/Contents/Resources/app/node_modules/dugite/git/libexec/git-core/git-pack-refs'
    at /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/src/util/appFileCopier.ts:70:38
From previous event:
    at /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/src/util/appFileCopier.ts:70:21
    at Generator.next (<anonymous>)
    at xfs.mkdir.er (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/fs-extra/lib/mkdirs/mkdirs.js:37:14)
    at FSReqWrap.oncomplete (fs.js:137:15)
From previous event:
    at copyAppFiles (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/out/util/appFileCopier.js:62:21)
    at taskManager.addTask.default.each.it (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/src/platformPackager.ts:238:86)
From previous event:
    at MacPackager.copyAppFiles (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/src/platformPackager.ts:238:43)
    at /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/src/platformPackager.ts:186:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at MacPackager.doPack (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/out/platformPackager.js:267:11)
    at /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/src/macPackager.ts:87:71
    at Generator.next (<anonymous>)
From previous event:
    at MacPackager.pack (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/out/macPackager.js:183:11)
    at /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/src/packager.ts:260:24
From previous event:
    at Packager.doBuild (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/out/packager.js:332:11)
    at /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/src/packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/out/packager.js:261:11)
    at /Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/src/builder.ts:283:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/out/builder.js:63:21)
    at then (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Object.args [as handler] (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/src/cli/cli.ts:49:4)
    at Object.runCommand (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/node_modules/yargs/lib/command.js:228:22)
    at Object.parseArgs [as _parseArgs] (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/node_modules/yargs/yargs.js:1041:24)
    at Object.get [as argv] (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/node_modules/yargs/yargs.js:957:21)
    at Object.<anonymous> (/Users/akos.kitta/Desktop/electron/theia-electron-app-example/node_modules/electron-builder/src/cli/cli.ts:43:15)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
    at Function.Module.runMain (module.js:653:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

Blocks #346.

**Comment by kittaakos** [comment]
It does not happen anymore with `electron-builder version=19.56.2`.
