### ISSUE TITLE
[windows] Electron application does not start after installing it

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#754]
After #738 I get this when I start the electron application after the installation
```
Failed to start the backend application.
Error: %1 is not a valid Win32 application.
\\?\C:\Users\kittaakos\AppData\Local\Programs\theia-electron-app-example\resources\app\node_modules\node-pty\build\Release\pty.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\kittaakos\AppData\Local\Programs\theia-electron-app-example\resources\app\node_modules\node-pty\lib\windowsPtyAgent.js:9:11)
    at Object.<anonymous> (C:\Users\kittaakos\AppData\Local\Programs\theia-electron-app-example\resources\app\node_modules\node-pty\lib\windowsPtyAgent.js:160:3)
C:\Users\kittaakos\AppData\Local\Programs\theia-electron-app-example\resources\app\node_modules\@theia\core\lib\node\cluster\main.js:41
    throw reason;
    ^

Error: %1 is not a valid Win32 application.
\\?\C:\Users\kittaakos\AppData\Local\Programs\theia-electron-app-example\resources\app\node_modules\node-pty\build\Release\pty.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\kittaakos\AppData\Local\Programs\theia-electron-app-example\resources\app\node_modules\node-pty\lib\windowsPtyAgent.js:9:11)
    at Object.<anonymous> (C:\Users\kittaakos\AppData\Local\Programs\theia-electron-app-example\resources\app\node_modules\node-pty\lib\windowsPtyAgent.js:160:3)
The express server worker 1 has been disconnected.
The express server worker 1 has been stopped.
```

**Comment by kittaakos** [comment]
As a workaround, one can build it on Windows and then it starts. Later, it fails with something else.

**Comment by kittaakos** [comment]
For some reason, editor.main module is not included:
```
loader.js:7 Loading "vs/editor/editor.main" failed
function.r.onError.r.onError @ loader.js:7
r.onError @ loader.js:7
s._onLoadError @ loader.js:7
s @ loader.js:7
(anonymous) @ loader.js:7
e.triggerErrorback @ loader.js:7
(anonymous) @ loader.js:7
(anonymous) @ loader.js:7
readFileAfterOpen @ fs.js:359
loader.js:7 Detail:  Error: ENOENT: no such file or directory, open 'c:\Users\kittaakos\dev\theia-electron-app-example\dist\win-unpacked\c%3A\Users\kittaakos\dev\theia-electron-app-example\dist\win-unpacked\resources\app\lib\vs\editor\editor.main.js'
function.r.onError.r.onError @ loader.js:7
r.onError @ loader.js:7
s._onLoadError @ loader.js:7
s @ loader.js:7
(anonymous) @ loader.js:7
e.triggerErrorback @ loader.js:7
(anonymous) @ loader.js:7
(anonymous) @ loader.js:7
readFileAfterOpen @ fs.js:359
loader.js:7 Error: ENOENT: no such file or directory, open 'c:\Users\kittaakos\dev\theia-electron-app-example\dist\win-unpacked\c%3A\Users\kittaakos\dev\theia-electron-app-example\dist\win-unpacked\resources\app\lib\vs\editor\editor.main.js'
function.r.onError.r.onError @ loader.js:7
r.onError @ loader.js:7
s._onLoadError @ loader.js:7
s @ loader.js:7
(anonymous) @ loader.js:7
e.triggerErrorback @ loader.js:7
(anonymous) @ loader.js:7
(anonymous) @ loader.js:7
readFileAfterOpen @ fs.js:359
loader.js:7 Here are the modules that depend on it:
function.r.onError.r.onError @ loader.js:7
r.onError @ loader.js:7
s._onLoadError @ loader.js:7
s @ loader.js:7
(anonymous) @ loader.js:7
e.triggerErrorback @ loader.js:7
(anonymous) @ loader.js:7
(anonymous) @ loader.js:7
readFileAfterOpen @ fs.js:359
loader.js:7 ["===anonymous1==="]0: "===anonymous1==="length: 1__proto__: Array(0)
function.r.onError.r.onError @ loader.js:7
r.onError @ loader.js:7
s._onLoadError @ loader.js:7
s @ loader.js:7
(anonymous) @ loader.js:7
e.triggerErrorback @ loader.js:7
(anonymous) @ loader.js:7
(anonymous) @ loader.js:7
readFileAfterOpen @ fs.js:359

```

**Comment by marcdumais-work** [comment]
@kittaakos I get the same error on my Windows 10 installation, using latest master.

**Comment by marcdumais-work** [comment]
```typescript
/C:/Users/Marc/theia/examples/electron/lib/vs/loader.js:7 Detail:  Error: ENOENT: no such file or directory, open 'C:\Users\Marc\theia\examples\electron\c%3A\Users\Marc\theia\examples\electron\lib\vs\editor\editor.main.js'
function.r.onError.r.onError @ /C:/Users/Marc/theia/examples/electron/lib/vs/loader.js:7
/C:/Users/Marc/theia/examples/electron/lib/vs/loader.js:7 Error: ENOENT: no such file or directory, open 'C:\Users\Marc\theia\examples\electron\c%3A\Users\Marc\theia\examples\electron\lib\vs\editor\editor.main.js'
function.r.onError.r.onError @ /C:/Users/Marc/theia/examples/electron/lib/vs/loader.js:7
/C:/Users/Marc/theia/examples/electron/lib/vs/loader.js:7 Here are the modules that depend on it:
function.r.onError.r.onError @ /C:/Users/Marc/theia/examples/electron/lib/vs/loader.js:7
/C:/Users/Marc/theia/examples/electron/lib/vs/loader.js:7 Array(1)
function.r.onError.r.onError @ /C:/Users/Marc/theia/examples/electron/lib/vs/loader.js:7
```

**Comment by UdoW** [comment]
For me it gives me the follwoing error: 

`no such file or directory, open 'M:\projects\theia_20171030\theia\examples\electron\m%3A\projects\theia_20171030\theia\examples\electron\lib\vs\editor\editor.main.js'`

Somehow the path is twice: first in with "M:\.." then in the middle with "\m%3A\..." again. I suppose the for building the absolute path the path comparison is not working correctly.

**Comment by kittaakos** [comment]
Still just a blind guess, but I think the problem is here: https://github.com/theia-ide/theia/blob/116222a7551917c59107a9288991a1e7e7cbe403/packages/monaco/src/electron-browser/monaco-electron-module.ts#L18

We cannot just convert the URI to string and load it as a module.

**Comment by kittaakos** [comment]
The `editor` folder folder seems to be missing from `vs`:

`OS X`:
<img width="220" alt="screen shot 2017-10-30 at 13 26 27" src="https://user-images.githubusercontent.com/1405703/32170734-1269c312-bd76-11e7-863b-54b380aaa5dd.png">

`Windows`:
<img width="224" alt="screen shot 2017-10-30 at 13 26 13" src="https://user-images.githubusercontent.com/1405703/32170728-0c8ff8da-bd76-11e7-911d-4644becd7202.png">

**Comment by kittaakos** [comment]
The problem is in the `AMDLoader.Utilities.fileUriToFilePath`. It will convert the `file:///c%3A/Users/kittaakos/dev/theia-electron-app-example/lib/vs/editor/editor.main.js` URI  into a `c%3A/Users/kittaakos/dev/theia-electron-app-example/lib/vs/editor/editor.main.js` FS path.

**Comment by kittaakos** [comment]
The `decoreURI` leaves the `file:///c%3A/Users/kittaakos/dev/theia-electron-app-example/lib/vs/editor/editor.main.js` as is.

**Comment by kittaakos** [comment]
OK, so I believe this is a bug, VSCode's AMD loader cannot decode URIs with `file` scheme, so the FS path is incorrect. The module loading fails. Here is a very simple script that demonstrates the problem on Windows:
```
const Uri = require('vscode-uri').default;
const os = require('os');
const fs = require('fs');

const homeUri = Uri.parse(os.homedir());
console.log(homeUri.toString());
console.log(decodeURI(homeUri.toString()));
console.log('exists', fs.existsSync(decodeURI(homeUri.toString())));

const homeFileUri = Uri.file(os.homedir());
console.log(homeFileUri.toString());
console.log(decodeURI(homeFileUri.toString()));
console.log('exists', fs.existsSync(decodeURI(homeFileUri.toString())));
```

```
C:%5CUsers%5Ckittaakos
C:\Users\kittaakos
exists true
file:///c%3A/Users/kittaakos
file:///c%3A/Users/kittaakos
exists false
```

CC: @akosyakov

**Comment by akosyakov** [comment]
[baseUrl](http://requirejs.org/docs/api.html#config-baseUrl) seems to be a path, could you try `const baseUrl = __dirname;`.

Decoding/encoding is encapsulated by vscode-uri, one should not do it again.

**Comment by kittaakos** [comment]
It works with the approach from the very first commit: https://github.com/theia-ide/theia/blob/f0b1896f1b926839533a5874619d1442e6515cad/examples/browser/src/electron/index.html.

I try with the FS path too.

**Comment by kittaakos** [comment]
> const baseUrl = __dirname;.

It does not work, it expects a URI.

**Comment by kittaakos** [comment]
PR: https://github.com/theia-ide/theia/pull/761
