### ISSUE TITLE
[Windows] Building an electron application fails on Windows but succeeds on  OS X

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#756]
Building the following `package.json` fails on Windows while it is green on OS X. `ExtensionPackageCollector` fails with missing `markers` dependency:

```
Uncaught Exception:  Error: Cannot find module '@theia/markers/package.json'
Error: Cannot find module '@theia/markers/package.json'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.resolve (internal/module.js:18:19)
    at ExtensionPackageCollector.module.exports.modulePath [as resolveModule] (C:\Users\kittaakos\dev\theia-electron-app-example\.application-module-loader.js:1:102)
```

`package.json`: 
```json
{
  "name": "theia-electron-app-example",
  "version": "1.0.0",
  "description": "A boilerplate Theia application",
  "main": "src-gen/frontend/electron-main.js",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/theia-ide/theia-electron-app-example.git"
  },
  "theia": {
    "target": "electron"
  },
  "scripts": {
    "generate": "theia generate",
    "compile": "npm dedupe && webpack && shx cp ./src-gen/frontend/index.html ./lib",
    "electron-rebuild": "electron-rebuild",
    "package": "build",
    "package:all": "build -mwl --x64",
    "postinstall": "npm run generate && npm run package",
    "dist": "npm run electron-rebuild && npm run compile && npm run package",
    "clean": "rimraf ./src-gen && rimraf ./lib && rimraf ./dist && rimraf ./node_modules"
  },
  "keywords": [],
  "author": "typefox <npm@typefox.io>",
  "license": "ISC",
  "bugs": {
    "url": "https://github.com/theia-ide/theia-electron-app-example/issues"
  },
  "homepage": "https://github.com/theia-ide/theia-electron-app-example#readme",
  "//": [
    "explicit xterm dependency: https://github.com/theia-ide/theia/issues/737",
    "npm dedupe is called before webpack: https://github.com/theia-ide/theia/issues/752"
  ],
  "dependencies": {
    "@theia/cli": "next",
    "@theia/core": "next",
    "@theia/editor": "next",
    "@theia/filesystem": "next",
    "@theia/git": "next",
    "@theia/languages": "next",
    "@theia/monaco": "next",
    "@theia/navigator": "next",
    "@theia/outline-view": "next",
    "@theia/preferences": "next",
    "@theia/preferences-api": "next",
    "@theia/process": "next",
    "@theia/terminal": "next",
    "@theia/workspace": "next",
    "xterm": "^2.9.2"
  },
  "devDependencies": {
    "electron-builder": "^19.30.2",
    "rimraf": "^2.6.2",
    "shx": "^0.2.2"
  }
}
```

Console log on Windows:
```

kittaakos@DESKTOP-VJRAMKC MINGW64 ~/dev/theia-electron-app-example (master)
$ git pull
Already up-to-date.

kittaakos@DESKTOP-VJRAMKC MINGW64 ~/dev/theia-electron-app-example (master)
$ clear

kittaakos@DESKTOP-VJRAMKC MINGW64 ~/dev/theia-electron-app-example (master)
$ npm i

> dtrace-provider@0.8.5 install C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\dtrace-provider
> node scripts/install.js


> node-pty@0.7.1 install C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty
> node scripts/install.js


C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Agent.cc
  AgentCreateDesktop.cc
  ConsoleFont.cc
  ConsoleInput.cc
..\..\..\..\deps\winpty\src\agent\ConsoleInput.cc(121): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
..\..\..\..\deps\winpty\src\agent\ConsoleInput.cc(137): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
..\..\..\..\deps\winpty\src\agent\ConsoleInput.cc(155): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
..\..\..\..\deps\winpty\src\agent\ConsoleInput.cc(172): warning C4244: 'return': conversion from '__int64' to 'int', possible loss of data [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
  ConsoleInputReencoding.cc
  ConsoleLine.cc
  DebugShowInput.cc
  DefaultInputMap.cc
..\..\..\..\deps\winpty\src\agent\DefaultInputMap.cc(291): warning C4244: 'argument': conversion from '__int64' to 'int', possible loss of data [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
  EventLoop.cc
  InputMap.cc
  LargeConsoleRead.cc
  NamedPipe.cc
  Scraper.cc
  Terminal.cc
..\..\..\..\deps\winpty\src\agent\Scraper.cc(561): warning C4244: 'argument': conversion from 'int64_t' to 'const int', possible loss of data [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
..\..\..\..\deps\winpty\src\agent\Scraper.cc(623): warning C4244: 'argument': conversion from 'int64_t' to 'int', possible loss of data [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
  Win32Console.cc
  Win32ConsoleBuffer.cc
  main.cc
  BackgroundDesktop.cc
  Buffer.cc
  DebugClient.cc
  GenRandom.cc
  OwnedHandle.cc
  StringUtil.cc
  WindowsSecurity.cc
  WindowsVersion.cc
  WinptyAssert.cc
  WinptyException.cc
  WinptyVersion.cc
  win_delay_load_hook.cc
  Generating code
c:\users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\deps\winpty\src\agent\agent.cc(231): warning C4722: 'Agent::~Agent': destructor never returns, potential memory leak [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\deps\winpty\src\winpty-agent.vcxproj]
  Finished generating code
  winpty-agent.vcxproj -> C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\Release\\winpty-agent.exe
  winpty-agent.vcxproj -> C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\Release\winpty-agent.pdb (Full PDB)
  AgentLocation.cc
  winpty.cc
  BackgroundDesktop.cc
  Buffer.cc
  DebugClient.cc
  GenRandom.cc
  OwnedHandle.cc
  StringUtil.cc
  WindowsSecurity.cc
  WindowsVersion.cc
  WinptyAssert.cc
  WinptyException.cc
  WinptyVersion.cc
  win_delay_load_hook.cc
     Creating library C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\Release\winpty.lib and object C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\Release\winpty.exp
  Generating code
  Finished generating code
  winpty.vcxproj -> C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\Release\\winpty.dll
  winpty.vcxproj -> C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\Release\winpty.pdb (Full PDB)
  pty.cc
  path_util.cc
..\src\win\pty.cc(42): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int' [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(42): warning C4302: 'type cast': truncation from 'HANDLE' to 'int' [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(53): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int' [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(53): warning C4302: 'type cast': truncation from 'HANDLE' to 'int' [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(104): warning C4018: '<': signed/unsigned mismatch [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(215): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int' [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(215): warning C4302: 'type cast': truncation from 'HANDLE' to 'int' [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(216): warning C4311: 'type cast': pointer truncation from 'HANDLE' to 'int' [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(216): warning C4302: 'type cast': truncation from 'HANDLE' to 'int' [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\pty.vcxproj]
..\src\win\pty.cc(233): warning C4533: initialization of 'marshal' is skipped by 'goto cleanup' [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\pty.vcxproj]
  ..\src\win\pty.cc(213): note: see declaration of 'marshal'
  ..\src\win\pty.cc(233): note: see declaration of 'cleanup'
..\src\win\pty.cc(280): warning C4312: 'type cast': conversion from 'int32_t' to 'HANDLE' of greater size [C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\pty.vcxproj]
  win_delay_load_hook.cc
     Creating library C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\Release\pty.lib and object C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\Release\pty.exp
  Generating code
  Finished generating code
  pty.vcxproj -> C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\Release\\pty.node
  pty.vcxproj -> C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty\build\Release\pty.pdb (Full PDB)

> rabin-bindings@1.7.3 install C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\rabin-bindings
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.3.0
prebuild-install info looking for local prebuild @ prebuilds\rabin-bindings-v1.7.3-node-v57-win32-x64.tar.gz
prebuild-install info found local prebuild
prebuild-install info unpacking @ prebuilds\rabin-bindings-v1.7.3-node-v57-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\rabin-bindings\build\Release\rabin-bindings.node
prebuild-install info unpack required C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\rabin-bindings\build\Release\rabin-bindings.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> node-pty@0.7.1 postinstall C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\node-pty
> node scripts/post-install.js


> dugite@1.42.0 postinstall C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\dugite
> node ./script/download-git.js


> electron@1.7.6 postinstall C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron
> node install.js


> theia-electron-app-example@1.0.0 postinstall C:\Users\kittaakos\dev\theia-electron-app-example
> npm run generate && npm run package


> theia-electron-app-example@1.0.0 generate C:\Users\kittaakos\dev\theia-electron-app-example
> theia generate

Uncaught Exception:  Error: Cannot find module '@theia/markers/package.json'
Error: Cannot find module '@theia/markers/package.json'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.resolve (internal/module.js:18:19)
    at ExtensionPackageCollector.module.exports.modulePath [as resolveModule] (C:\Users\kittaakos\dev\theia-electron-app-example\.application-module-loader.js:1:102)
    at ExtensionPackageCollector.collectPackage (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\@theia\cli\node_modules\@theia\application-package\lib\extension-package-collector.js:44:32)
    at ExtensionPackageCollector.collectPackages (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\@theia\cli\node_modules\@theia\application-package\lib\extension-package-collector.js:30:18)
    at ExtensionPackageCollector.collectPackagesWithParent (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\@theia\cli\node_modules\@theia\application-package\lib\extension-package-collector.js:36:14)
    at ExtensionPackageCollector.collectPackage (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\@theia\cli\node_modules\@theia\application-package\lib\extension-package-collector.js:53:18)
    at ExtensionPackageCollector.collectPackages (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\@theia\cli\node_modules\@theia\application-package\lib\extension-package-collector.js:30:18)
    at ExtensionPackageCollector.collect (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\@theia\cli\node_modules\@theia\application-package\lib\extension-package-collector.js:20:14)
    at ApplicationPackage.get [as extensionPackages] (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\@theia\cli\node_modules\@theia\application-package\lib\application-package.js:167:53)

> theia-electron-app-example@1.0.0 package C:\Users\kittaakos\dev\theia-electron-app-example
> build

electron-builder 19.42.1
Using electron-builder.yml configuration file
Rebuilding native production dependencies for win32:x64
Warning: Packaging using asar archive is disabled — it is strongly not recommended.
Please enable asar and use asarUnpack to unpack files that must be externally available.
Packaging for win32 x64 using electron 1.7.6 to dist\win-unpacked
Error: Application entry file "src-gen\frontend\electron-main.js" does not exist. Seems like a wrong configuration.
    at C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\src\platformPackager.ts:340:15
From previous event:
    at WinPackager.checkFileInPackage (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\out\platformPackager.js:389:11)
    at C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\src\platformPackager.ts:364:16
    at Generator.next (<anonymous>)
    at C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\graceful-fs\polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:154:5)
From previous event:
    at WinPackager.sanityCheckPackage (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\out\platformPackager.js:407:11)
    at C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\src\platformPackager.ts:208:16
    at Generator.next (<anonymous>)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at WinPackager.doPack (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\out\platformPackager.js:267:11)
    at C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\src\platformPackager.ts:115:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\out\platformPackager.js:190:11)
    at C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\src\packager.ts:260:24
From previous event:
    at Packager.doBuild (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\out\packager.js:332:11)
    at C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\src\packager.ts:186:52
    at Generator.next (<anonymous>)
From previous event:
    at Packager.build (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\out\packager.js:261:11)
    at C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\src\builder.ts:283:40
    at Generator.next (<anonymous>)
From previous event:
    at build (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\out\builder.js:63:21)
    at then (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at runCallback (timers.js:785:20)
    at tryOnImmediate (timers.js:747:5)
    at processImmediate [as _immediateCallback] (timers.js:718:5)
From previous event:
    at Object.args [as handler] (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\src\cli\cli.ts:49:4)
    at Object.runCommand (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\node_modules\yargs\lib\command.js:228:22)
    at Object.parseArgs [as _parseArgs] (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\node_modules\yargs\yargs.js:1041:24)
    at Object.get [as argv] (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\node_modules\yargs\yargs.js:957:21)
    at Object.<anonymous> (C:\Users\kittaakos\dev\theia-electron-app-example\node_modules\electron-builder\src\cli\cli.ts:43:15)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! theia-electron-app-example@1.0.0 package: `build`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the theia-electron-app-example@1.0.0 package script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kittaakos\AppData\Roaming\npm-cache\_logs\2017-10-30T08_21_26_666Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! theia-electron-app-example@1.0.0 postinstall: `npm run generate && npm run package`
npm ERR! Exit status 4294967295
npm ERR!
npm ERR! Failed at the theia-electron-app-example@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kittaakos\AppData\Roaming\npm-cache\_logs\2017-10-30T08_21_26_761Z-debug.log

kittaakos@DESKTOP-VJRAMKC MINGW64 ~/dev/theia-electron-app-example (master)
$

```

**Comment by akosyakov** [comment]
It means that there is no `node_modules/@theia/markers/package.json`.

**Comment by kittaakos** [comment]
The dependency does not get pulled on Windows. That should not be the case, I am more or less positive, I've messed up something. I need to double check before raising a false alarm.

`Windows:`
<img width="261" alt="screen shot 2017-10-30 at 09 37 35" src="https://user-images.githubusercontent.com/1405703/32161512-1f81ece8-bd56-11e7-8b83-ce660a7c9215.png">

`OS X:`
<img width="238" alt="screen shot 2017-10-30 at 09 37 53" src="https://user-images.githubusercontent.com/1405703/32161525-29566fdc-bd56-11e7-9faf-fafa12d6e289.png">

**Comment by kittaakos** [comment]
I do not have a better idea; I need to set up a CI for them.

**Comment by kittaakos** [comment]
It does not fail on the CIs. I am closing this ticket.

**Comment by kittaakos** [comment]
Building it from a fresh clone on Windows solved the issue too.
