### ISSUE TITLE
File sub-menu "Save" generates an error when there is no workspace set

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#829]
In the THEIA configuration as of Nov 13, the "File" sub-menu as some elements and if you select "Save" or "Save All" without any workspace set , it reports the following errors:

Exception has occurred: Error
Error: Received a 503 from couch
    at ChangesStream._onResponse (/home/lmcbout/theia/theia/node_modules/changes-stream/index.js:179:15)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:120:20)
    at ClientRequest.emit (events.js:210:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:23)
    at TLSSocket.socketOnData (_http_client.js:454:20)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at addChunk (_stream_readable.js:266:12)

**Comment by akosyakov** [comment]
It is not related to Save. The error says that npm registry cannot connect to npm web hooks:
https://github.com/theia-ide/theia/blob/ed7f86f858df257e703a76939b30d77a00d6291d/dev-packages/application-package/src/npm-registry.ts#L126-L128

We can improve the error message though. A user don't need to do anything it will try reconnect again latter.
