### ISSUE TITLE
Not enough fs watches should be handled

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#90]
From a fresh git clone

Running the install steps in the readme when I get to:
npm run cold:start:electron

I get a seemingly infinite number of exceptions like these:
```
Uncaught Exception:  Error: watch /home/eantotr/src/Theia/examples/node_modules/tslint-loader/.idea/inspectionProfiles ENOSPC
Error: watch /home/eantotr/src/Theia/examples/node_modules/tslint-loader/.idea/inspectionProfiles ENOSPC
    at exports._errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1316:19)
    at Object.fs.watch (fs.js:1341:11)
    at createFsWatchInstance (/home/eantotr/src/Theia/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/eantotr/src/Theia/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/eantotr/src/Theia/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleDir (/home/eantotr/src/Theia/node_modules/chokidar/lib/nodefs-handler.js:407:19)
    at FSWatcher.<anonymous> (/home/eantotr/src/Theia/node_modules/chokidar/lib/nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (/home/eantotr/src/Theia/node_modules/chokidar/lib/nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:112:15)
```

**Comment by hexa00** [comment]
It's now in the doc
