### ISSUE TITLE
Cannot build electron application from Theia 0.2.3

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#914]
No menus are present when starting the application. See: https://github.com/theia-ide/yangster-electron/issues/23

I have found this in the log (after changing the generated source again to be able to see the dev tools window):
```
preference-proxy.ts:72 Uncaught (in promise) Error: unexpected property: toJSON
    at Object.get (file:///C:/Program%20Files/typefox/Yangster/resources/app/lib/bundle.js:69979:19)
    at JSON.stringify (<anonymous>)
    at KeybindingRegistry.registerKeybinding (file:///C:/Program%20Files/typefox/Yangster/resources/app/lib/bundle.js:65234:75)
    at file:///C:/Program%20Files/typefox/Yangster/resources/app/lib/bundle.js:51816:22
    at Array.forEach (native)
    at DiagramKeybindingContribution.registerKeybindings (file:///C:/Program%20Files/typefox/Yangster/resources/app/lib/bundle.js:51815:11)
    at KeybindingRegistry.onStart (file:///C:/Program%20Files/typefox/Yangster/resources/app/lib/bundle.js:65192:30)
    at FrontendApplication.<anonymous> (file:///C:/Program%20Files/typefox/Yangster/resources/app/lib/bundle.js:18112:42)
    at step (file:///C:/Program%20Files/typefox/Yangster/resources/app/lib/bundle.js:17992:23)
    at Object.next (file:///C:/Program%20Files/typefox/Yangster/resources/app/lib/bundle.js:17973:53)
get @ preference-proxy.ts:72
KeybindingRegistry.registerKeybinding @ keybinding.ts:131
(anonymous) @ diagram-keybinding.ts:72
DiagramKeybindingContribution.registerKeybindings @ diagram-keybinding.ts:71
KeybindingRegistry.onStart @ keybinding.ts:111
(anonymous) @ frontend-application.ts:119
step @ frontend-application.ts:6
(anonymous) @ frontend-application.ts:6
(anonymous) @ frontend-application.ts:6
__awaiter @ frontend-application.ts:6
FrontendApplication.startContributions @ frontend-application.ts:101
(anonymous) @ frontend-application.ts:74
step @ frontend-application.ts:6
(anonymous) @ frontend-application.ts:6
(anonymous) @ frontend-application.ts:6
__awaiter @ frontend-application.ts:6
FrontendApplication.start @ frontend-application.ts:73
start @ index.js:22
messages.js:46 Uncaught (in promise) Error: Unhandled method toJSON
    at new ResponseError (messages.js:46)
    at handleResponse (main.js:430)
    at processMessageQueue (main.js:258)
    at Immediate.<anonymous> (main.js:242)
    at runCallback (timers.js:672)
    at tryOnImmediate (timers.js:645)
    at processImmediate [as _immediateCallback] (timers.js:617)
ResponseError @ messages.js:46
handleResponse @ main.js:430
processMessageQueue @ main.js:258
(anonymous) @ main.js:242
runCallback @ timers.js:672
tryOnImmediate @ timers.js:645
processImmediate @ timers.js:617
messages.js:46 Uncaught (in promise) Error: Unhandled method toJSON
    at new ResponseError (messages.js:46)
    at handleResponse (main.js:430)
    at processMessageQueue (main.js:258)
    at Immediate.<anonymous> (main.js:242)
    at runCallback (timers.js:672)
    at tryOnImmediate (timers.js:645)
    at processImmediate [as _immediateCallback] (timers.js:617)
ResponseError @ messages.js:46
handleResponse @ main.js:430
processMessageQueue @ main.js:258
(anonymous) @ main.js:242
runCallback @ timers.js:672
tryOnImmediate @ timers.js:645
processImmediate @ timers.js:617
messages.js:46 Uncaught (in promise) Error: Unhandled method toJSON
    at new ResponseError (messages.js:46)
    at handleResponse (main.js:430)
    at processMessageQueue (main.js:258)
    at Immediate.<anonymous> (main.js:242)
    at runCallback (timers.js:672)
    at tryOnImmediate (timers.js:645)
    at processImmediate [as _immediateCallback] (timers.js:617)
ResponseError @ messages.js:46
handleResponse @ main.js:430
processMessageQueue @ main.js:258
(anonymous) @ main.js:242
runCallback @ timers.js:672
tryOnImmediate @ timers.js:645
processImmediate @ timers.js:617
messages.js:46 Uncaught (in promise) Error: Unhandled method toJSON
    at new ResponseError (messages.js:46)
    at handleResponse (main.js:430)
    at processMessageQueue (main.js:258)
    at Immediate.<anonymous> (main.js:242)
    at runCallback (timers.js:672)
    at tryOnImmediate (timers.js:645)
    at processImmediate [as _immediateCallback] (timers.js:617)
ResponseError @ messages.js:46
handleResponse @ main.js:430
processMessageQueue @ main.js:258
(anonymous) @ main.js:242
runCallback @ timers.js:672
tryOnImmediate @ timers.js:645
processImmediate @ timers.js:617

```

I have the feeling we are trying to serialize an ES6 Map. I have seen some very similar before.

**Comment by kittaakos** [comment]
Figured it out, it is because of the logging. So when keybindings collide, we try to log it nicely, which fails. This issue does not occur without Theia extensions. I will take care of it.

**Comment by kittaakos** [comment]
Happens when we have a proxy: `preference-proxy#createPreferenceProxy`.
