### ISSUE TITLE
Document how to run tests in watch mode.

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#924]
I could do something like this on OS X. It is an OKish workaroud.
```
cd packages/filesystem && yarn --ignore-scripts && ./node_modules/.bin/mocha -w --opts ../../configs/mocha.opts src/**/*.spec.ts
```

It does not work on Windows either from `GitBash` or `cygwin`. Obviously fails from `cmd.exe` too. (Did no try from PS).

From GitBash:
```
$ cd packages/filesystem && yarn --ignore-scripts && ./node_modules/.bin/mocha -w --opts ../../configs/mocha.opts src/**/*.spec.ts
yarn install v1.2.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.87s.

Error: The specified module could not be found.
\\?\C:\Users\kittaakos\dev\theia\node_modules\nsfw\build\Release\nsfw.node
    at Object.Module._extensions..node (module.js:653:18)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\kittaakos\dev\theia\node_modules\nsfw\lib\src\index.js:3:16)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\kittaakos\dev\theia\packages\filesystem\src\node\nsfw-watcher\nsfw-filesystem-watcher.ts:9:1)
    at Module._compile (module.js:624:30)
    at Module.m._compile (C:\Users\kittaakos\dev\theia\node_modules\ts-node\src\index.ts:392:23)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\kittaakos\dev\theia\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\kittaakos\dev\theia\packages\filesystem\src\node\node-filesystem.spec.ts:20:1)
    at Module._compile (module.js:624:30)
    at Module.m._compile (C:\Users\kittaakos\dev\theia\node_modules\ts-node\src\index.ts:392:23)
    at Module._extensions..js (module.js:635:10)
    at Object.require.extensions.(anonymous function) [as .ts] (C:\Users\kittaakos\dev\theia\node_modules\ts-node\src\index.ts:395:12)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at C:\Users\kittaakos\dev\theia\node_modules\mocha\lib\mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\kittaakos\dev\theia\node_modules\mocha\lib\mocha.js:228:14)
    at Mocha.run (C:\Users\kittaakos\dev\theia\node_modules\mocha\lib\mocha.js:514:10)
    at loadAndRun (C:\Users\kittaakos\dev\theia\node_modules\mocha\bin\_mocha:437:22)
    at Object.<anonymous> (C:\Users\kittaakos\dev\theia\node_modules\mocha\bin\_mocha:454:3)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Function.Module.runMain (module.js:665:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
```

**Comment by akosyakov** [comment]
have you tried `npx run test:watch @theia/filesystem` from the root?

**Comment by kittaakos** [comment]
I go this:
```
$ npx run test:watch @theia/filesystem
npx: installed 1 in 1.359s
Path must be a string. Received undefined
null
```

**Comment by kittaakos** [comment]
The `Run Mocha Test` is also broken on Windows. Works cool on OS X.

**Comment by akosyakov** [comment]
You should add `"test:watch": "theiaext test:watch"` in package.json of `@theia/filesystem`.

**Comment by kittaakos** [comment]
I did that, received the same error. Do I have to do anything before trying to execute the `npx` script?

**Comment by akosyakov** [comment]
you should run `yarn` once to link `theiaext`, nothing more

**Comment by kittaakos** [comment]
Nailed it! I will update the documentation and close this.
