### ISSUE TITLE
[ci][git] Occasional Git test failure on Windows

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#962]
There is a problem with the Git tests on Windows. Occasionally, the `after all` test hook fails on Appvayor when trying to clean up the repository from the temp folder. Either the Git watcher or the Git process itself locks the repository.

```
git "after all" hook:
lerna ERR! execute      Error: EBUSY: resource busy or locked, unlink 'C:\Users\appveyor\AppData\Local\Temp\1\exec-foo117118-2164-1at7b18.tom0f'
lerna ERR! execute       at Object.fs.unlinkSync (fs.js:1061:18)
lerna ERR! execute       at rimrafSync (C:\projects\theia\node_modules\temp\node_modules\rimraf\rimraf.js:211:13)
lerna ERR! execute       at cleanupDirsSync (C:\projects\theia\node_modules\temp\lib\temp.js:143:5)
lerna ERR! execute       at Object.cleanupSync (C:\projects\theia\node_modules\temp\lib\temp.js:196:19)
lerna ERR! execute       at Suite.<anonymous> (src\node\dugite-git.spec.ts:31:15)
lerna ERR! execute       at step (src\node\dugite-git.spec.ts:38:23)
lerna ERR! execute       at Object.next (src\node\dugite-git.spec.ts:19:53)
lerna ERR! execute       at src\node\dugite-git.spec.ts:13:71
lerna ERR! execute       at new Promise (<anonymous>)
lerna ERR! execute       at __awaiter (src\node\dugite-git.spec.ts:9:12)
lerna ERR! execute       at Context.<anonymous> (src\node\dugite-git.spec.ts:30:11)
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute 
lerna ERR! execute     at Promise.all.then.arr (C:\projects\theia\node_modules\execa\index.js:236:11)
lerna ERR! execute     at <anonymous>
lerna ERR! execute     at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by marcdumais-work** [comment]
I just got this error on appveyor: https://ci.appveyor.com/project/kittaakos/theia/build/1.0.1642

**Comment by marcdumais-work** [comment]
Trying locally on the Windows VM, the git tests seem to pass (at least that once). But the electron tests failed afterwards.

**Comment by kittaakos** [comment]
Please put the electron test failures aside. I already have some changes that will simplify the Git tests. I will submit the PR soon. Bear with me.
